### ISSUE TITLE
Unholy dk Outbreak

### ISSUE THREAD

**Issue by Zankom** [Hekili/hekili#102]
Sometimes when i use outbreak, the addon suggests i use it again on the same target right after i just used it.

**Comment by Thordros** [comment]
This happens if Army of the Dead isn't on cooldown. The Unholy APL is written in such a way that all of their primary abilities are expressed as some fraction of GCD's remaining in AotD's cooldown. If it isn't on cooldown, nothing will fire—except for Outbreak, which is defined before the action lists.

There isn't a lot Hekili can do about this unless the Unholy APL is rewritten.

**Comment by Hekili** [comment]
Please post a snapshot from when this occurs. 

Have you modified your priority at all? Enabled or disabled abilities?

**Comment by Zankom** [comment]
> Please post a snapshot from when this occurs.
> 
> Have you modified your priority at all? Enabled or disabled abilities?

I usually disable cooldowns when im not fighting a boss, so army isint used that often, and i took apocalypse off of the cooldowns category so its suggested all the time.

**Comment by Zankom** [comment]
> This happens if Army of the Dead isn't on cooldown. The Unholy APL is written in such a way that all of their primary abilities are expressed as some fraction of GCD's remaining in AotD's cooldown. If it isn't on cooldown, nothing will fire—except for Outbreak, which is defined before the action lists.
> 
> There isn't a lot Hekili can do about this unless the Unholy APL is rewritten.

This still happens when army of the dead is on cooldown

**Comment by Hekili** [comment]
Still need a proper ticket and snapshot from when you're seeing this.
