### ISSUE TITLE
Frost mage: add range check for Frost Nova (like you already do for Arcane Explosion)

### ISSUE THREAD

**Issue by brucek2** [Hekili/hekili#1030]
Frost Nova is similar to Arcane Explosion in that while the game engine does not enforce a range requirement for it (or even require that there be a targeted enemy at all), the spell is only useful if there is an enemy within the its area of effect.

I noticed that arcane mage already includes this line for arcane_explosion:
```
usable = function () return not state.spec.arcane or target.distance < 10, "target out of range" end,
```

I've been playing with a manually inserted similar line for Frost mage's Frost Nova (12 yard range) and find it an important improvement when the Grisly Icicle legendary is equipped. Otherwise, Frost Nova will frequently be suggested even when it will have no effect due to no enemy being in range of the nova.

**Comment by Livvvvvvven** [comment]
Please also add similar judgments to several range spells of warriors and paladins. Thank you very much.

**Comment by Hekili** [comment]
> the spell is only useful if there is an enemy within the its area of effect.

This isn't exactly true, unfortunately.  Disciplinary Command, for example, is based on casting spells, not whether they do damage.

If you're playing Frost Mage, though, you don't need Frost Nova for proccing Disciplinary Command (since you're using other Frost spells), so I suppose I can build in the same basic exception as Arcane Explosion.  Then again, Grisly Icicle really does rely on being in range of adds to freeze them and get the benefit.

Ultimately, I'll go ahead and make Frost Nova similar to Arcane Explosion for Frost Mage only.

@Livvvvvvven, if there are specific Warrior or Paladin abilities you're concerned with, please submit a separate ticket for those (you can bundle your Warrior requests in one ticket and your Paladin requests in a separate ticket).  Thanks!
