### ISSUE TITLE
Elemental Shaman rotation bug report / request for clarification

### ISSUE THREAD

**Issue by yoheines** [Hekili/hekili#1032]
While learning the Elemental shaman spec, I noticed some behaviour that I can't quite explain:

Character data: https://pastebin.com/8HM3PFwZ

1. Hekili will recommend two Lava Bursts in a row with the "Master of the Elements" talent: https://pastebin.com/Vna6y1f8. Expected behaviour: With Master of the Elements up, prioritize a nature or frost spell.

2. While Lava Burst is casting as an opener, Hekili will recommend another Lava Burst as a followup, and then change this recommendation to Flame Shock after the cast is through: https://pastebin.com/rqbR7s0J. Expected behavior: Recommendation should not change after the cast. My guess is that this is caused by a special "opener" handling. In combat, Flame Shock has the highest priority, but out of combat, Hekili recommends pre-casting Lava Burst as an opener. Is there a way to disable this? In M+, there's usually no time to precast anyway, and in the raid it's easy to remember a fixed opener rotation.

3. In AoE situations, Hekili will recommend extending the Flame Shock dot way before it expires: https://pastebin.com/6WZLrZ9B. Expected behaviour: Refresh Flame Shock at most 5 seconds before it expires. My guess is it wants me to change targets to apply more dots. It would be nice if it only recommended Flame Shock after I've actually changed the target. Interestingly, the "recommend target swaps" setting  doesn't seem to affect this behavior.

4. Another issue where I couldn't come up with a snapshot, but suspect it's more of an enhancement anyway: Hekili seems to recommend extending the Flame Shock dot on targets that are about to die. Is there a time-to-die calculation that's taken into account? Maybe there's also a connection to number 3) above.

**Comment by yoheines** [comment]
I found out how to configure 2) and 3) - by disabling the respective lines in the action list. I now understand why it recommends Flame Shock even when it's not close to expiring - it actually does want me to swap targets. The problem is that when this icon shows up, it's too late, and I don't want to waste several 100 ms to switch to a different target. Also, in M+, spreading Flame Shock on multiple targets is often inefficient because mobs die too fast. Maybe I'll have to create a weakaura to keep track of the number of Flame Shock dots myself.

**Comment by yoheines** [comment]
I "fixed" 1) by removing the stormkeeper conditional in this line of the APL:

actions.single_target+=/lightning_bolt,if=(buff.stormkeeper.remains<1.1*gcd*buff.stormkeeper.stack|buff.stormkeeper.up&buff.master_of_the_elements.up)

I guess this then turns into a question why the official SimC APL wants to prioritize Lightning Bolt with Master of the Elements ONLY when I have Stormkeeper stacks.

Update: Elemental shaman discord agrees that sometimes lava burst -> lava burst is the right way to play.

**Comment by Hekili** [comment]
For 1, compare to sim behavior.  I didn't see an issue there.

For 2, there is a *precombat* entry for Lava Burst.  And then, you're not in combat until something hits, so you could potentially LvB twice there.  I'll block it but it's not something that matters at all.  The recommendation changing is purely a function of the LvB impacting (travel time) or you/your party otherwise starting combat.  It's intended to function that way.

For 3, the snapshot you provided does not refresh Flame Shock at all.  You do have target cycling enabled, and the addon doesn't tell you "hey change your target" and then "now cast X" -- it tells you to cast X on another target.

For 4, you could certainly write the priority to stop refreshing Flame Shock if a target is about to die.  But you'll fine situations where that is risky as well.  It's totally okay to use your better judgment if you don't want to refresh dots on something that is going to die.  But if anything else happens, the target survives longer, and you start pumping LvBs into a target without Flame Shock, you might be unhappy about it.
