### ISSUE TITLE
Drop fps in combat

### ISSUE THREAD

**Issue by Myro2** [Hekili/hekili#1035]
Good day.

 I have a mensi problem with adon during combat. when combat or fait in M+ drops fps and it start mowing. Is there anything to look at...? drop fps is from 80fps to 40fps. You can't play with it then

**Comment by MrSmurfy** [comment]
Play around with the performance settings;
https://i.imgur.com/W6c1Pyk.png

**Comment by Smudgiee** [comment]
Also try changing your display icons to maybe 2 or 1 if you can play that way. I think that is the biggest impact. I use 1 display and I dont think I ever notice lag, apart from the lag I would already have because bad engine and cpu.
But if you're using the Fire Mage then sadly you will get lag no matter what due tohow complex it is with Hekili.

**Comment by Myro2** [comment]
I'm sorry I tried, and it's not working. driv didn't do it, but after the last 2 updates of the adon it did

**Comment by Myro2** [comment]
I only play 2 windows ato on single and aoe. otherwise cpu is Ryzen 5 2600 and gpu gtx 1070

**Comment by Smudgiee** [comment]
You mean it didn't happen before? before the last two updates that were pushed? If that is the case maybe fill out the ticket correctly through every step with snapshots and information so Hekili will even bother with this ticket

**Comment by Myro2** [comment]
yes it's so it's only after the update and I've been looking at it

**Comment by Hekili** [comment]
I'm going to close this ticket for not following ticket instructions.  If you want to submit a ticket, please follow the directions so I have at least a little bit of the information I'd need to help investigate your issue.  Thanks.
