### ISSUE TITLE
New malefic rapture logic.

### ISSUE THREAD

**Issue by F074** [Hekili/hekili#1038]
I just installed the latest beta fixing the corruption bug for aff lock, but I noticed a change with malefic rapture. Specifically if you attempt to hold PS and Soul rot, the rotation will no longer pool shards and just waste them. I'm guessing the new logic just assumes it's pointless to pool if PS/SR don't exist if I disable them through toggles.

The reason I disabled them before the beta was to use them when I wanted on specific trash packs or aoe heave parts of a fight. Not just every minute on the minute like the new logic does.(Which is correct given a constant single target situation)

Anyway, the old logic allowed you to pool shards even when PS/SR were disabled is that still possible with this latest update?
 
Here is a pastebin:

https://pastebin.com/bXK8UidA

**Comment by Smudgiee** [comment]
I think it's entry 36 of default that changed, that causes this. You can just edit it back to how it was, which is what I've done. Or you could technically just add rupture to a toggle also and just pressing it when u want without addon recommending it until turned back on with PS etc

**Comment by F074** [comment]
This here?  How do I tweak it? Not sure how to find the old action list.

# Burn soul shards if fight is almost over
actions+=/malefic_rapture,if=boss&fight_remains<execute_time*soul_shard&dot.unstable_affliction.ticking

**Comment by Smudgiee** [comment]
No that's not the one. 
I'll wait until Hekili responds and see what he says before giving any information, don't want people to make edits and mess stuff up

**Comment by F074** [comment]
oh you meant this right? either way I have no idea how to change it.

talent.phantom_singularity.enabled & ( dot.phantom_singularity.ticking | cooldown.phantom_singularity.remains > 25 | fight_remains < cooldown.phantom_singularity.remains )

**Comment by Hekili** [comment]
Smudgiee's comments are basically right.

If you're wanting to be able to toggle MR off to save Shards, you could add it to whichever toggle you'd like it to be on (Cooldowns, I assume).

When PS is toggled off, it's treated as though it's fully on cooldown.  The newer desynchronizing logic for that entry is intentional, but I've been making efforts lately to adjust priorities when they have "burn CDs before the fight ends" logic in them.  That sort of thing should really only apply to boss scenarios, because going pack to pack in M+ burning all your CDs at the end is not a positive thing.

Changing `cooldown.phantom_singularity.remains > 25` to `cooldown.phantom_singularity.true_remains > 25` will bypass that "full CD when toggled off" logic, but remember that when I update priorities, any edits you make will be obliterated.  Refer to the FAQ about that.
