### ISSUE TITLE
Warrior Down Time

### ISSUE THREAD

**Issue by FullSol** [Hekili/hekili#1049]
**BEFORE SUBMITTING AN ISSUE:**

1.  Version: 9.0.5-1.0.6

2.  Didn't see one for Devastate., I see the one for Revenge which I also don't see a lot of usage on.

**Describe the Bug/Issue**
It appears that Devastate (and revenge) are not properly being suggested and it is causing dead time in the rotation.

**To Reproduce**
Normal usage with defenses/cooldown on or off

**Expected behavior**
Don't expect as much down-time

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/L6f5YuT9

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/N1KhUJjR

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**Comment by Hekili** [comment]
The sim profile will not use Devastate in AOE situations.  Have you done any sim testing to see if it's better DPS or mitigation to allow it?

The culprit is:
`actions+=/run_action_list,name=aoe,if=spell_targets.thunder_clap>=3`

If there are 3+ targets, it will always run the AOE action list (and stop at the end) which will cause it not to reach the default `generic` list.

**Comment by FullSol** [comment]
With that in mind I did some pulls and that is exactly what is happening. Devastate always shows with a single target and in aoe it vanishes.

Thanks

**Comment by Hekili** [comment]
A quick sim test suggests falling back to the single-target priority (without Devastator talented) will do more DPS/mitigation/etc.  I'll make a change in the addon as well.

https://www.raidbots.com/simbot/report/vXVipKmj9xaSTJrVxZj66A

**Comment by mati3464** [comment]
About the revenge, main problem is that in .lua file there is one line: 
line 736 "if toggle.defensives and buff.ignore_pain.down then return false, "don't spend on revenge if ignore_pain is down" end"

So in situation were you tanking with no dmg incoming that will trigger ignore pain, example trees tanking or other tank already tanking boss, hekili will not recommend use revenge even with 100 rage already, because that line in lua blocking it. 
I personally each update remove that line from warriorprot.lua each update. 

I using my personal profile for prot warrior and here are example how it recommendations are going on boss fight:

https://i.imgur.com/epUNsRk.png


Here you have detailed problem on topic 


https://github.com/Hekili/hekili/issues/1007

**Comment by Hekili** [comment]
For Revenge, I'm loosening up the condition you noted so it only applies if you've taken a significant (10% max health) amount of damage in the past 5 seconds.  So if you're off-tanking or not getting hit at all, Revenge will be available even with Ignore Pain down.

I'll also have that APL change included in the next release.
