### ISSUE TITLE
Epidemic bug Unholy

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#1057]
Dear developer, you are generally wrong. This bug is clearly visible on the Sire Denathrius boss where many additional targets appear. In the first phase, when it appears there is UH, but for the rest I already check many, many times, and I see that I have runes for an outbreak, but the addon wants to first press an epidemic a bunch of times and only after that it presses outbreak. I ask you to check the addon again. For you have a mistake there. And you can test it yourself on the boss Sire Denathrius

**Comment by Hekili** [comment]
You can still respond in the other thread, even with it closed.  You are welcome to provide another snapshot that shows what you're describing, but the reason why Epidemic was recommended in your snapshot was because you had no runes to use Outbreak.

If you have an example of it not using Outbreak, while you have runes, and there are multiple targets that need Plague, then provide that.

> Dear developer, you are generally wrong.

That kind of behavior and attitude is generally unwelcome.  Follow ticket instructions and be polite.  Thanks.

**Comment by geraint425** [comment]
Well, here's a screenshot I attach with what is happening, there is a buff on the main target, there is no on others, and the addon suggests using an epidemic, not an outbreak. https://imgur.com/a/ts4Lqp0 
and here's another bug with what the addon suggests to use. https://pastebin.com/yS7e2vtu
