### ISSUE TITLE
In game status report panel

### ISSUE THREAD

**Issue by quetzalsly** [Hekili/hekili#1082]
I love hekili but it is always such a mystery on how things work behind the scenes.
I have no idea which spec is working well, which spec has bugs, I end up searching github issues and seeing random problems.

* How does hekili work? am I supposed to be updating the simc templates to new ones or editing them as the simc repo is updated or something? this repo seems to have older simc templates so I am confused.

* How do the tank specs work? for example blood dk, does it try its best to actually tank or is it only based on simc dps output? I tried a low level blood dk and I cant tell if its being intelligent with death strike or not, it sometimes keeps on saying to heartstrike even when my hp is low.

For my actual suggestion I was thinking in the main hekili window to have like a little table for each spec:
For example: Low level compatable, Pre raid (non covenant) compatable, Raid/Mythic+ min max compatable.
Each table entry would have ticks or crosses, this would be in a separate file and people on github could state their experience if the spec works optimally or not. There could also be a 'known limitations' next to each spec which describes what is wrong.

There could also be an update log and a notice encouraging people to post suggestions on github.

**Comment by Hekili** [comment]
No, you don't need to update from SimC (and you'd probably end up with a broken result). No spec's profile is significantly behind SimC; if you're looking at file dates, keep in mind that most updates to a SimC profile aren't priority related. 

Any spec being "low level compatible" is pure chance and I have no intent to actively support that. The addon tells you that every time you log in with a low level character. 

Covenants, conduits, legendaries, etc. are all supported for all specs within the addon. The tar trap/flare legendary is a notable exception because you can't detect that a snare-immune boss is inside a tar trap.

The priority for Blood is visible in-game, so if you're well-versed in sims, everything you need to know why recommendations are what they are is available to you.  The general philosophy with tanking is that any maintenance buff type mechanics are maintained and you avoid overspending resources that you'd need to react to big combat events. You will still exercise your own judgment with regard to fight mechanics if you want to be successful.

You don't need a big table of reviews to decide if the addon helps you play better in a particular spec. It helps you or it doesn't. If it does, use it. If it doesn't, don't. Don't overthink it.
