### ISSUE TITLE
Havoc priority issue

### ISSUE THREAD

**Issue by Illuminat442** [Hekili/hekili#1084]
So I have updated to the latest version.  I am having an issue as a Havoc dh that Hekili is telling me to use an ability expecting that I have certin talents selected.  I am not using Unbound Chaos at all and not using any abilities or talents that would buff my Fel Rush ability but Hekili keeps telling me to use Fel Rush for dps.

**Comment by IIeTpoc** [comment]
Hey there is an answer for your ticket. https://github.com/Hekili/hekili/issues/975

**Comment by Hekili** [comment]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by ijoihlhnn** [comment]
there is a toggle to disable the use of fel rush if you dont use Unbound Chaos.
CHeck the options before creating incomplete tickets. :)

**Comment by Hekili** [comment]
@ijoihlhnn is correct that you can turn that off using a toggle (or specialization option).
