### ISSUE TITLE
Unholy DK - Primary display only recommends outbreak when close to a second or multiple targets.

### ISSUE THREAD

**Issue by yungwern** [Hekili/hekili#1090]
**BEFORE SUBMITTING AN ISSUE:**

**Describe the Bug/Issue**
When I get close to another target the primary display only recommends outbreak. The cooldowns display will show as normal, and only until I use all my recommended cooldowns will the primary display show normally again. 

![Normal Hekili](https://user-images.githubusercontent.com/83782648/117358727-58d4b200-ae6b-11eb-820d-3c62ca1d88e6.PNG)
This is what my display normally looks like.

![2 target hekili](https://user-images.githubusercontent.com/83782648/117358765-61c58380-ae6b-11eb-9061-e31ed759909c.PNG)
This is what it looks like when I get close to another target.

**WHEN SUBMITTING AN ISSUE:**
**PUT ISSUE REPORT LINK HERE:  https://pastebin.com/PcKa3Vr1

**Comment by Hekili** [comment]
That snapshot doesn't look like it was taken when you were having the problem.

**Comment by yungwern** [comment]
https://pastebin.com/yaJ10NSt

**Comment by yungwern** [comment]
Let me know if that one works, im not too sure what im doing when it comes to these snapshots. Also I dont need to be in combat for it to happen. When I stand next to two training dummies and switch targets between the two it shows as the second screenshot I provided.

**Comment by Hekili** [comment]
Have you done any special customizing in your options?  Your Death and Decay cooldown was 30s (max CD), which leads me to believe you have added it to a toggle (Cooldowns, maybe?).  The logic for Unholy DK to switch between setting up AOE vs. dropping DnD and doing AOE damage relies on the cooldown for Death and Decay.  

Since abilities are treated as though they are on their max CD when toggled off, that is probably causing this behavior.

If you want to control Death and Decay with a toggle, you'll need to come up with a priority that isn't dependent on DnD's CD.

Also, it looks like perhaps you've edited (possibly accidentally?) your priority.  Because your second-to-last entry in your Unholy > default action list has been changed to Unholy Blight, when it would normally be a Run Action List entry for the `generic_aoe` priority.  You may want to reset your priority so you have the default behavior restored.

**Comment by yungwern** [comment]
Ok thank you very much for the detailed response. It appears that somehow I did accidentally edit my priority. I reset it to default and everything is working fine now. Also I don't seem to have many problems with DnD when its in my cooldowns toggle, but creating a new priority for it would probably work a lot better. Thanks again for your help, I really appreciate it.
