### ISSUE TITLE
DH enhancement 

### ISSUE THREAD

**Issue by somedhclass** [Hekili/hekili#1095]
im looking to maybe have Fel rush show up on priotry 1 second before hunt or eyebeam off cd ... and having a fel rush avaible when i use immo i used the box to for movement but it using it off cd so i dont have my buff going into a eye beam or immo or hunt 

build: v9.0.5-1.0.8
level: 60 (60)
class: DEMONHUNTER
spec: havoc

talents: demon_blades
    essence_break
    felblade
    master_of_the_glaive
    momentum
    soul_rending
    unbound_chaos

**Comment by somedhclass** [comment]
this is what im told to do " but dont seem to line up 

"The apl changed.
I'd say the class is more on a prio list than a rotation
So basically you wanna pair momentum buff wiht immo or eyebeam or hunt but you never wanna overcap either
And then you wanna vengeful as much as possible"

**Comment by Hekili** [comment]
I'll respond to the points in your second post and ask you to clean up and clarify your other thoughts before I respond to them.

> The apl changed.

Priorities are always changing.  I keep up with them.  There's nothing missing.

> I'd say the class is more on a prio list than a rotation

Every class uses a priority.

> So basically you wanna pair momentum buff wiht immo or eyebeam or hunt

Your sim priority already syncs Eye Beam and The Hunt with Momentum.  It doesn't for Immolation Aura, but you'd need to show that it's worthwhile to hold Immolation Aura.  That the ability benefits from Momentum does not mean it's worth getting fewer Immolation Auras over the course of a fight because you waited to use it.

> but you never wanna overcap either

You don't *want* to overcap, but you inevitably will.  Your sim profile is fury capped an average of 7.37% of the time (as much as 12.92% of the time).

![image](https://user-images.githubusercontent.com/9438134/118012722-5a94ee80-b31f-11eb-9a3c-33359a4a8d43.png)

This happens because the opportunity cost of avoiding capping -- delaying important abilities that you want to use as often as possible -- is often higher than the benefit of avoiding resource waste.

> And then you wanna vengeful as much as possible

If you've set your spec options accordingly, this already happens.

> im looking to maybe have Fel rush show up on priotry 1 second before hunt or eyebeam off cd ... and having a fel rush avaible when i use immo i used the box to for movement but it using it off cd so i dont have my buff going into a eye beam or immo or hunt

I can't do anything with this request as stated.  You should try testing your own changes in SimulationCraft and report back if you find something that is a DPS increase.
