### ISSUE TITLE
Merge custom action pack with latest updated pack

### ISSUE THREAD

**Issue by vicwac** [Hekili/hekili#1125]
Is there a possibility to merge our customized action packs with the latest Hekili updates so we can enjoy the latest priorities while still having our custom inputs?

For example on my BM hunter I have customized recommendations for Exhilaration when health.pct<=50 and Spirit Mend when health.pct<=60, and I'd like to merge that with every update instead of having to manually type it out again.

Please let me know if this is possible, and if this feature is already available, please advise on how to do so, many thanks!

**Comment by Hekili** [comment]
Nope.

Default priorities get overwritten when updated.

**Comment by vicwac** [comment]
Yes I understand that, but could we at least have a function to import and merge our custom defensive cooldowns into every new update so we don't have to type them out again? From my rudimentary understanding of how Hekili is designed, it's possible to cut and paste lines from one action pack to another, correct me if I'm wrong? Just a consideration to implement that would be greatly appreciated.

**Comment by Hekili** [comment]
No, that's not something I'll invest time into.  I get it.  But defaults are meant to be updated, that's why they're distinguished as blue.  This is also explained in the wiki.

If you want to preserve your changes and merge them into the updated defaults, you should be making a copy of the defaults and putting your edits into the copy.

**Comment by vicwac** [comment]
Yes of course I do make a copy when I add my custom defensives, but if there's an update to the rotation or whatnot then I won't be able to benefit from both that as well as my custom defensives unless I make another copy and re-add all my customs manually. What I'm trying to say is if there's a way for me to cut and paste all my edits into the new copy of the most recently updated priorities, that would be great.

I'm sure all moderately serious players would want to have a convenient way of customizing the action pack according to their playstyle, and that is no insult towards the effectiveness of the default priorities, it's just personal preference.

But ok since you've made it clear you won't consider implementing that at this time, although hopefully you will think about it for the future. Thanks.

**Comment by Hekili** [comment]
Correct, I won't implement what you've asked for in the way you've asked for it.  I have ideas about other ways to allow some customization.  But no promises and no ETA on those.  You'll want to just manually copy your changes over.

The best advice I can give is to make your changes in text form on the Profile tab and then import.  If you go that route, it's easy to copy and paste your changes going forward instead of building them by hand in the UI.

**Comment by vicwac** [comment]
Yes that's basically what would work, although if there was a UI function to quickly mass copy over custom edits from one priority pack to another, that would be the sweet spot.

For now I'll just try doing that from the profile tab, thanks for the suggestion, and look forward to your ideas on future customization.
