### ISSUE TITLE
Add a learning mode

### ISSUE THREAD

**Issue by izomiac** [Hekili/hekili#1129]
A nice feature would be to do post-combat analysis of time spent doing nothing, how many times the player used an ability other than what was recommended, how much that decision affected overall DPS for the fight, and why Hekili recommended something different.  That way one can see their potential "mistakes" and learn from them immediately.  I'm envisioning a small window that shows itself after combat ends, if there's anything to critique.

**Comment by Hekili** [comment]
This is something I've considered, but honestly, would ultimately be much lower value than one might expect.  There are lots of good reasons to push something else than what the addon is recommending due to fight mechanics and you're raid's choreography.

I'd recommend using the addon while playing then using a tool like wowanalyzer for the postmortem analysis.
