### ISSUE TITLE
Unholy DK rotation snapshotting

### ISSUE THREAD

**Issue by imarkvisser** [Hekili/hekili#1131]
Hi Hekili,

I am using the latest version of the addon and Unholy DK is having issues making suggestions in aoe fights.
 
SNAPSHOT LINK:
https://pastebin.com/XUTdFqiL

Let me know if you need any more info.

**Comment by Hekili** [comment]
This may be resolved in the latest (1.0.3) release.  Please let me know either way.

**Comment by imarkvisser** [comment]
Solved! Thanks man!

**Comment by imarkvisser** [comment]
Ahola, it still seems to happen randomly. A lot less though;
Snapshot: https://pastebin.com/qNvY2xhR

**Comment by Hekili** [comment]
FWIW, it's not random.  Auto-snapshots are made when the action list, as written, doesn't result in a recommendation.

The way the Unholy APL is written is really sensitive to timing issues.  I'll look at the scenario and try to sort that out.  Thanks for forwarding the snapshot, because otherwise this is impossible to review.

**Comment by Hekili** [comment]
Hey, this actually did catch a bug.  Basically, the addon tries to conserve CPU by narrowing the period of time where recommendations are valid.  However, this didn't reset immediately after a `wait` action, so basically the addon waited and then was not able to recommend anything immediately after.

I have to do some additional testing, but I think this will be sorted in the next release.

**Comment by Hekili** [comment]
I believe this is fixed.
