### ISSUE TITLE
Enh shaman profile during ascendance

### ISSUE THREAD

**Issue by Greencatinglasses** [Hekili/hekili#1132]
THIS IS NOT A BUG BUT AN IMPROVEMENT SUGGESTION.

I frequently notice that during ascendance Hekili addon rotation feels sluggish mainly for the following reason:
After windstrike there is some another cast (LL or something else, it is not important) and after this cast the next cast is not immediately windstrike but some other cast. And only after half of gcd or something like it the cast shown in the addon window becomes windstrike. It can be frustrating sometimes and lead to the situation when the rotation becomes ws - cast - cast - ws instead of ws-cast-ws. This is very important if the character has a good chuck of haste stat.

It would be great if ascendance situation was hardcoded in such a way that after some cast that is not ws the next cast could be only windstrike.

About snapshot: it is hard to capture this behavior since it occurs at 0.5s or less time scale. And exactly at this moment I should press the pause button. 

UP I have done it, after windstrike casted LB and then got crush lighntning in the addon window. 
Snapshot:

https://pastebin.com/jmVezCxF -- moved to pastebin per instructions

**Comment by Hekili** [comment]
Please follow the ticket instructions.

**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Greencatinglasses** [comment]
Please, change ``incompelete'' label or point out what info I should also provide.

**Comment by Hekili** [comment]
> THIS IS NOT A BUG BUT AN IMPROVEMENT SUGGESTION.

It's perceived as a bug because this is literally what the Pad Windstrike option is for.

Use Pastebin to link your snapshot, because you didn't paste the complete snapshot.

**Comment by Greencatinglasses** [comment]
Is is right? https://pastebin.com/1dyt53L2

**Comment by Hekili** [comment]
If that's the entire snapshot, yes.  But it looks like it's cropped short.  I'll investigate.

The snapshot would be more useful if you had more than 1 icon showing.  So I can see that Ascendance is up and it's recommending more than 1 ability between Windstrikes.

**Comment by Hekili** [comment]
I'm still not able to see this issue.

![image](https://user-images.githubusercontent.com/9438134/124362457-f990e500-dc02-11eb-9777-909a7032c0dd.png)

![image](https://user-images.githubusercontent.com/9438134/124362510-4ffe2380-dc03-11eb-9b9a-679b9f7904f4.png)

**Comment by Greencatinglasses** [comment]
Could it be the problem when only one icon is showing? Maybe I should provide a movie or?
