### ISSUE TITLE
Frost DK BoS Rotation Bug?

### ISSUE THREAD

**Issue by ghost** [Hekili/hekili#115]
**Describe the Bug/Issue**

The Frost DK rotation doesn't suggest Empower Rune Weapon OR Pillar of Frost when using Breath of Sindragosa. 

When using Obliteration instead of Breath of Sindragosa, ERW + Pillar are recommended as normal.

**To Reproduce**

Start doing your rotation as told, and when it gets done capping Runic Power, use Breath of Sindragosa like it says. 

ERW + Pillar are never recommended, even once BoS is off cooldown again.

**Expected behavior**

ERW + Pillar to be recommended during the burst.
 
**PUT SNAPSHOT LINK HERE:**

https://pastebin.com/nSmLvfer

**Comment by Hekili** [comment]
```
[ 17]  Checking empower_rune_weapon (Frost DK - cooldowns - 11 )...
empower_rune_weapon is known and enabled.
The action (empower_rune_weapon) is usable at (0.00 + 0.00).
 - the action is ready before the current recommendation (at +0.00 vs. +60.00).
List ( cooldowns ) called from ( Frost DK:default:5 ) would PASS at 0.00.
 - NONE
 - this entry's criteria FAILS: ( cooldown.pillar_of_frost.ready[true] | target.time_to_die[181.00] < 20 ) & talent.breath_of_sindragosa.enabled[true] & rune.current[0.00] >= 3 & runic_power.current[27.00] > 60
There are 1 recheck events.
List ( cooldowns ) called from ( Frost DK:default:5 ) would PASS at 2.62.
 - NONE
Recheck #1 ( +2.62 ) NOT MET: ( cooldown.pillar_of_frost.ready[true] | target.time_to_die[178.38] < 20 ) & talent.breath_of_sindragosa.enabled[true] & rune.current[3.00] >= 3 & runic_power.current[12.00] > 60
```

Yeah, this isn't a bug but rather a misunderstanding about the Frost DK APL; as written, you will not have cast Breath of Sindragosa without having used PoF and ERW *first* -- they're part of the pre-BoS setup.

The addon will have recommended ERW -> PoF -> BoF if we're going purely on addon recommendations.  However, when you've manually hit BoS, it would probably make sense to implement a fallback to make sure those CDs are used.  I'll look into it.

**Comment by Hekili** [comment]
Try 8.1.5-13-alpha1 when it comes up and see if that suffices.

**Comment by ghost** [comment]
I just went through the rotation very slowly while not pressing Breath of Sindragosa even when it was recommended.

Breath looks like it gets recommended at about 50 Runic Power, way before HRW / Pillar are ever recommended. Once you get around 70 RP, HRW is recommended finally. After HRW is recommended, it suggested Breath, then suggested Howling Blast, and then finally Pillar.

Does this sound like I broke the rotation messing with settings or something?


-- just saw your new reply while I was writing this, I'll try it and let you know asap

**Comment by Hekili** [comment]
If you changed something, then getting different results shouldn't be surprising.  Gotta evaluate tweaks in the context of the whole priority.

`actions.cooldowns+=/breath_of_sindragosa,use_off_gcd=1,if=cooldown.empower_rune_weapon.remains&cooldown.pillar_of_frost.remains`

That's the only entry for Breath of Sindragosa in the default Frost DK kit.  It requires that ERW and PoF are both on cooldown, so if you're seeing BoS recommended without ERW and PoF on cooldown, something has been changed.

`actions.cooldowns+=/pillar_of_frost,if=cooldown.empower_rune_weapon.remains`

That is the only PoF entry; it requires that ERW is on cooldown.  (Note, this will work both immediately after using ERW and for the whole period that ERW is on cooldown.)

There are two entries for ERW, one is with BoS talented and one without.  We'll look only at the BoS talented one:

`actions.cooldowns+=/empower_rune_weapon,if=(cooldown.pillar_of_frost.ready|target.time_to_die<20)&talent.breath_of_sindragosa.enabled&rune>=3&runic_power>60`

ERW is recommended when PoF is ready (or the target is dying in less than 20 seconds, this perhaps should be adjusted to when the *encounter* is ending in less than 20) and you have 3+ runes and runic power is over 60.

This logic is why you'll generally see an opener that looks like Oblit -> Oblit -> Oblit -> Oblit -> wait for runes to reach 3, pop ERW, pop PoF, pop BoS.  The opener changes as you get procs for Rime, but all that setup is to put leave you with runes recharging and a fair pool of RP before you start BoS.

Other caveats:  If you change the toggle assignments for abilities, when they are toggled off, they are treated as being on-cooldown.  This shouldn't actually impact your situation, because BoS is a cooldown ability and not recommended with CDs toggled off.  Same with ERW.  So with default settings and cooldowns disabled, you'll still get PoF recommendations but not ERW or PoF.

**Comment by ghost** [comment]
I just reset everything and it's working perfectly. I have no idea what I changed to break that but sorry for wasting your time.

I appreciate you taking the time to help me, thank you.

**Comment by Hekili** [comment]
You identified a couple of areas to tune up the addon, anyway.  I posted a 8.1.5-13-alpha2 which will avoid burning CDs on trash that are dying as well.  I'll close the ticket, but appreciate the feedback you provided.  Thanks!
