### ISSUE TITLE
[Bug] Boomkin - Celestial Alignment not suggested with Darkmoon Card trinket

### ISSUE THREAD

**Issue by jozef3d** [Hekili/hekili#1155]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an existing, open ticket for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I have cooldowns to show up separately, and it seems that Celestial alignment doesn't display consistently, but the Darnkmoon trinket pops up each time its off cooldown.

### How to Reproduce

Go boomkin, make sure to have a Darkmoon trinket.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Hekili** [comment]
Please take a snapshot (alt-shift-p) and put in on pastebin and then link here. Thanks.

**Comment by imarkvisser** [comment]
Ahola Hekili, I'll do it for him. I was having the same issue. When I am not wearing the darkmoon trinket the cooldowns are being used properly, otherwise not.

Character data;
https://pastebin.com/w2jcMABL

Snapshot;
https://pastebin.com/ptc5rGp3

The snapshot is before starting combat. Let me know if I need to provide a snapshot for after casting the Darkmoon trinket

**Comment by Hekili** [comment]
Thanks for the report.  I *think* 1.0.9 solves this, but I thought 1.0.8 did, too.  I basically revised my translation of the SimC priority's `on_use_trinket` variable.  Other trinkets might be affected as well, so I'll leave this open for more feedback.

Please let me know if 1.0.9 resolves this for the Darkmoon trinket.

**Comment by imarkvisser** [comment]
That seems to solve it. Cheers mate.

**Comment by imarkvisser** [comment]
Hmm today I am having the same issue again, I don't really understand why;
https://pastebin.com/i79MasL6

It won't recommened anything but the on_use_trinket trinket. If I cast Celestial Alignment myself then the other CD's start being recommended.

**Comment by imarkvisser** [comment]
Here is another snapshot from right after using the on_use_trinket;
https://pastebin.com/QXB0sUNQ

**Comment by Hekili** [comment]
From what I can see in these snapshots, the issue is not related to trinkets.

In these cases, the logic that's blocked is re: burning CDs at the last second of a fight.  The cooldown entries that normally would've been used were based on burning CDs as a fight ends, which I treat as bossfight logic.  (You don't want to pop all CDs right before you pull a boss.)  Otherwise, it looks like you were just shy of the AP needed for the addon to recommend CDs.

**Comment by imarkvisser** [comment]
Hi Hekili,

If I have all CD's available and target a full health rare boss it won't recommend any CD's except for the darkmoon trinket;
https://pastebin.com/HP8XYjwv

**Comment by Hekili** [comment]
This snapshot looks like it was done before pulling, so there's not a lot of useful information in it.  I'll remove some boss-related checks.

**Comment by Hekili** [comment]
Try v9.1.0-1.0.11-beta1 when it comes online in a moment.

**Comment by imarkvisser** [comment]
Working great now as usual. Thanks mate.

**Comment by Hekili** [comment]
Thanks for the quick response.

One thing I'm going to have to keep in mind is that the Balance priority is another one that is not very friendly to testing on target dummies (which was not the issue you were having).  But time-to-die calculations get very wonky on target dummies since they won't actually die.

I'll leave this open for now because I anticipate there still might be some weird cases.

**Also**, because of how the Balance APL has some densely-constructed variables used in decision-making, you may find it to be a little smoother to enable Enhanced Recheck in `/hekili` > Balance > Performance.  I may enable it by default going forward.

**Comment by imarkvisser** [comment]
Thanks for the advice, I'll enable Enhanced Recheck, if I spot anything weird with it I'll report back. :)

**Comment by jozef3d** [comment]
confirmed working now.  Thanks.
