### ISSUE TITLE
[REC] Elemental Shaman - Frost Shock during movement

### ISSUE THREAD

**Issue by larskeizer** [Hekili/hekili#1159]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For elemental shamans, the addon correctly advises Spiritwalker's Grace during movement. There are however times that there is movement and no spells able to be cast (too low maelstrom, nothing to renew.) - At these moments it would be grant if the addon recommends Frost Shock to be used as a filler. It doesn't do much damage, but on heavy movement fights it definitely adds up.

### How to Reproduce

1. Make sure Spiritwalker's Grace is ON cooldown
2. Run around and do some casts, when there is nothing to cast, there is quite a lot of downtime and instead frost shock could and should be used as a filler

### Snapshot (Link)

https://pastebin.com/NuMGS6y3

### Contact Information

Lars#8888

**Comment by Hekili** [comment]
This is not an uncommon request.  The problem is, do you want the addon to tell you the best thing to do or just what you can do while you're moving?  The addon has no way of knowing if you can/will stop moving imminently or not, and you already know that you can always hit Frost Shock, so do you need the addon to call that out?

Generally speaking, your optimal DPS decision is to stop moving and get your hardcasts in.

**Comment by larskeizer** [comment]
Hmmm, you do make a great point. In that case, potentially, might it be possible to have a new separete button in hekili that can be turned on or off? Like a "filler button" that lights up when you're moving and isn't replacing the other recommendations. During the normal rotation it would be greyed out. Naturally I have no idea how this would work coding wise as you're all doing the hard work, and it's already incredible.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Hekili** [comment]
It's possible, but possibly not incredibly valuable.  In this case, it would simply be telling you to Frost Shock as you move (if SWG is not up and on CD).

You can already accomplish most of this with your own custom priority, but that has its own caveat that you'll have to manually make updates if/when I update the defaults.  See https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions.

Here's a quick look at the Elemental priority with the `default` action list Entry dropdown expanded.

![image](https://user-images.githubusercontent.com/9438134/125197717-d5e62400-e22c-11eb-83cf-fc6d5699fefb.png)

If you look at the entry for Spiritwalker's Grace and then check `Show Modifiers` you can see that it's set up to check for movement.

![image](https://user-images.githubusercontent.com/9438134/125197767-fca45a80-e22c-11eb-994e-1fe09cfcc48e.png)

We can set up a Frost Shock entry basically the same way.

Click the green plus, check Enabled, select Frost Shock, and we'll use the condition `buff.spiritwalkers_grace.down` which means we do *not* have SWG active.  I'll set up the same movement check as SWG, too.

![image](https://user-images.githubusercontent.com/9438134/125197818-2c536280-e22d-11eb-9b10-68f6ebe05287.png)

The last piece is knowing where this belongs in the priority.  I'm genuinely not doing sim testing to prove anything, we're just going to do it since we know this is what you want.  If we look at the first screenshot, we can assume that any of these high-priority instants that we'd be able to cast while moving, should still be cast at a higher priority than this Frost Shock.  Fae Transfusion is the first in the list with a cast time (and you may not even have that, if you're not a Night Fae) so we'll position it above Fae Transfusion.  That leaves us with no hardcasts higher in priority than our Frost Shock.  Use the `Up` triangle to move this entry to position 16.

![image](https://user-images.githubusercontent.com/9438134/125197912-a4218d00-e22d-11eb-839a-c36e4bfa1a2b.png)

Stationary:  
![image](https://user-images.githubusercontent.com/9438134/125197948-cb785a00-e22d-11eb-8769-38dd1a504c0b.png)

Moving:  
![image](https://user-images.githubusercontent.com/9438134/125197959-d59a5880-e22d-11eb-9964-2bbed4db3589.png)

Read that Wiki entry so you catch the part about making a *copy* of the default priority so your changes aren't obliterated when I update the default, and then keep an eye out for default updates so you can manually reimplement your changes if/when needed.

**Comment by larskeizer** [comment]
Hey,

Thank you very much for taking the time to write this thorough guide/custom priority!

Much appreciated!
________________________________
Van: Hekili ***@***.***>
Verzonden: zondag 11 juli 2021 15:54
Aan: Hekili/hekili ***@***.***>
CC: larskeizer ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Hekili/hekili] [REC] Elemental Shaman - Frost Shock during movement (#1159)


It's possible, but possibly not incredibly valuable. In this case, it would simply be telling you to Frost Shock as you move (if SWG is not up and on CD).

You can already accomplish most of this with your own custom priority, but that has its own caveat that you'll have to manually make updates if/when I update the defaults. See https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions.

Here's a quick look at the Elemental priority with the default action list Entry dropdown expanded.

[image]<https://user-images.githubusercontent.com/9438134/125197717-d5e62400-e22c-11eb-83cf-fc6d5699fefb.png>

If you look at the entry for Spiritwalker's Grace and then check Show Modifiers you can see that it's set up to check for movement.

[image]<https://user-images.githubusercontent.com/9438134/125197767-fca45a80-e22c-11eb-994e-1fe09cfcc48e.png>

We can set up a Frost Shock entry basically the same way.

Click the green plus, check Enabled, select Frost Shock, and we'll use the condition buff.spiritwalkers_grace.down which means we do not have SWG active. I'll set up the same movement check as SWG, too.

[image]<https://user-images.githubusercontent.com/9438134/125197818-2c536280-e22d-11eb-9b10-68f6ebe05287.png>

The last piece is knowing where this belongs in the priority. I'm genuinely not doing sim testing to prove anything, we're just going to do it since we know this is what you want. If we look at the first screenshot, we can assume that any of these high-priority instants that we'd be able to cast while moving, should still be cast at a higher priority than this Frost Shock. Fae Transfusion is the first in the list with a cast time (and you may not even have that, if you're not a Night Fae) so we'll position it above Fae Transfusion. That leaves us with no hardcasts higher in priority than our Frost Shock. Use the Up triangle to move this entry to position 16.

[image]<https://user-images.githubusercontent.com/9438134/125197912-a4218d00-e22d-11eb-839a-c36e4bfa1a2b.png>

Stationary:
[image]<https://user-images.githubusercontent.com/9438134/125197948-cb785a00-e22d-11eb-8769-38dd1a504c0b.png>

Moving:
[image]<https://user-images.githubusercontent.com/9438134/125197959-d59a5880-e22d-11eb-9964-2bbed4db3589.png>

Read that Wiki entry so you catch the part about making a copy of the default priority so your changes aren't obliterated when I update the default, and then keep an eye out for default updates so you can manually reimplement your changes if/when needed.
