### ISSUE TITLE
Concentration spell defaults to keybind 1 instead of current keybinding when I use 1 stack

### ISSUE THREAD

**Issue by topazz94** [Hekili/hekili#1179]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

My first concentration stack gives me my normal keybind recommendation, aka Shift Mousebutton 2. Soon as I use one stack, and wait 2 seconds, it reappears as the first spell recommended, but only now, is has the keybind 1 in it, which is my Crusader Strike normally I think it somehow is overlapping or a visual bug maybe? Its only Hekili whch has this overlapping problem, so I'm thinking it might be a setting, but as far as I'm aware, I couldn't find anything wrong with my setup really.

Even after getting full 2 stacks again, the first concentration still has the keybind 1. Funny thing is, soon as I swap talents for my first row, aka Holy shield to Blessed Hammer, the first concentration becomes Shift MB2 again but the 2nd is till bugged.

![Knipsel](https://user-images.githubusercontent.com/32469255/126903270-d2a8ec86-c568-46af-8910-e35675c14ff4.PNG)
![Knipsel2](https://user-images.githubusercontent.com/32469255/126903288-48adc036-e70a-4716-923f-5679cc376021.PNG)
![Knipsel3](https://user-images.githubusercontent.com/32469255/126903390-634ec571-7d82-45de-9d75-55ae50520ab6.PNG)
![Knipsel4](https://user-images.githubusercontent.com/32469255/126903457-712426f0-ef3a-430d-b351-5252ad2aa760.PNG)

### How to Reproduce

1 Using normal keybind for Concentration
2 Wait a bit untill Concentration gets recommended again
3 Keybind Concentration has changed till 1/default key?

Relaoding/relogging didnt do anything for me

### Player Information (Link)

https://pastebin.com/BeTdVQ8s

### Error Messages (Link)

Not available

### Additional Information

Just want to thank you for your work really, great addon

**Comment by Hekili** [comment]
I have no idea what you mean by concentration stack. Not how it relates to keybindings. Can you explain in a few short bullet points?

**Comment by Hekili** [comment]
To get some debugging information, when you see the right bindings, type `/dump Hekili.KeybindInfo` and do the same again when you see the wrong keybind.

Paste the results of both into Pastebin and provide the link here.

**Comment by topazz94** [comment]
> 
> 
> I have no idea what you mean by concentration stack. Not how it relates to keybindings. Can you explain in a few short bullet points?

I have 2 stacks of concentration as protection Paladin, aka I can have one in reserve if that makes sense? When I havent used one, it shows the correct keybinding in Hekili, but when I use my first one and wait till it shows up in rotation again, it shows a different keybinding then it is on,

**Comment by topazz94** [comment]
> /dump Hekili.KeybindInfo

Correct one
https://pastebin.com/sx3m04jV   

Wrong one
https://pastebin.com/tYvYnF2S

**Comment by Hekili** [comment]
Concentration is an aura, Consecration is an ability that doesn't have stacks (charges, I assume) that I'm aware of, and maybe you're talking about Blessed Hammer's charges?  I'm very confused.

The keybinding text you're concerned with appears to be on the Consecration ability.  I see it's `Shift-Mouse4` on your action bars, but later shows up as `1`.

If Consecration is the concern, let's redo those Pastebins because they are missing what we need.

Type `/dump Hekili.KeybindInfo.consecration` when you see the *right* binding, put that on Pastebin and link it.  Do the same thing again when you see the *wrong* binding.

This is very likely going to be related to how your action bars are set up and ordered (and/or which bar mod you use).  Other stuff that can trick it is if you have any bars set up to swap based on holding modifier keys.

The simple solution is to manually set your keybind via /hekili > Abilities > Consecration > Override Keybind Text -- just type what you want it to show.  That's going to be less effort than reorganizing your action bars to work more nicely with my addon's keybinding detection.

**Comment by topazz94** [comment]
Aah my bad for the misunderstanding, I was talking about the Consecration abilty, which doesnt really have stacks, but you can sorta overlap it.


Correct one
https://pastebin.com/QxTANMin

Wrong one
https://pastebin.com/rrEHpYV8

I will try your solution, seems a lot easier to solve the hassle yeah, but just wanted to let you know what the issue was. Its most likely a problem on my settings then, but I only use elvui really, so I might have a deeper look into it

**Comment by Hekili** [comment]
In both cases, it is pulling the keybind from bar 8.  Is your Consecration macro'd on bar 8?  Can you confirm that bar 8 is the bar # that Consecration is actually on?

If you check the following:
/ec > ActionBars > Player Bars > Bar 8, is there any text in Action Paging?  What's there?

![image](https://user-images.githubusercontent.com/9438134/126914514-1bcb971a-a19b-4ec2-b52d-d27104fe2780.png)
