### ISSUE TITLE
[REC] Balance Druid Low DPS

### ISSUE THREAD

**Issue by howdeh** [Hekili/hekili#1192]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello, this may seem rather picky as I am new to playing Balance and trying to get around Hekili itself for DPS. I found the addon out of the box really good for my MM Hunter as it drastically improved my DPS. I understand that getting 'better' at my class is an alternative but I'm finding it hard to understand why my DPS is falling to lower than 4k (dropping to 3.7k after 2 convokes and Incarnation) after several minutes despite raidbots simming me at 4.3k.

https://www.raidbots.com/simbot/report/8omVs89NBoJV2t9Jb4gc97

I'm finding that Hekili is not casting convoke the spirits when off CD (I guess the addon recommends that it gets casted with Incarnation) however this is not being recommended by raidbots so I'm curious as to why the addon is recommending this? What is also odd is that Hekili almost tries to recommend convoke at around 22s left CD on Incarnation so I'm not sure what's happening. 

Raidbots is also recommending the use of starfall in ST output. I'm not sure where else it is deviating. Am I just bad at pressing buttons (it doesn't feel like I am missing anything here) or is there something not right about the balance rotation? I must admit I feel like I am pressing the buttons very quick and a recommendation may change which may have been missed? I'm not sure how to combat that though as I was going by the initial recommendation.

I realise starfall is casted by convoke but it doesn't look like that is being triggered by convoke in the spell output list on raidbots. Even with the removal of starfall I'd be expecting to hit a higher DPS as I know it is not a recommended spell in ST combat.

Edit: further look into my details vs raidbots, it looks like my Primordial Arcanic Pulsar uptime is 31% vs 98% - is it me miss pressing spells to stop having that kept up? Please bear in mind the DPS is extended by DoTs and I had stopped casting by this point but i highly doubt that it would drop from 98% to 31% in the space of <10s?

Edit: Added a second pastebin for 2nd snapshot. The opener this time recommended starfire rather than wrath x2. It also recommended convoke for a split second when it came off CD but then waited until Incarnation was off CD but it got used. Details is showing a 77% uptime on PAP and 62% on Redirected anima which is better. Maybe better at pressing buttons the second time round, but still capping at 3.7k DPS following the addon. I did notice that moonfire/sunfire are not at 100% uptime too.

### How to Reproduce

1. Enter game as Balance Druid
2. Fight dummy using recommended spells

### Snapshot (Link)

https://pastebin.com/GdGgELCJ
https://pastebin.com/UZtaRVYy

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/8omVs89NBoJV2t9Jb4gc97

**Comment by Hekili** [comment]
You'll have to narrow down each difference you're concerned about and match it with a snapshot.  I can't really do much of anything with a broader philosophical analysis. Specific deviations from the sim, with snapshots to match, that's what I need to assess and change.

**Comment by howdeh** [comment]
In both snapshots convoke the spirits is available but not used. It is recommended when the cooldown ends but quickly vanishes from the recommendation. It is then not recommended again until Incarnation is off CD. 

Without more knowledge of the class I can't pinpoint where the issue may be. It does feel like the addon is changing its mind in several places, maybe causing less uptime on moonfire and sunfire, but definitely conflicting when throwing out your next ability which had already been pressed which then changes the next action. I will have another go at some targets later to see what is being recommended towards the end of PAP buff. 

I now understand that I need to keep 100% uptime of PAP and grove invigoration for maximum damage output. The addon is at least not capping on astral power. 

Should I be using a different profile for an opener with wrath x2? In the second snapshot it recommended starfire for the opener. I don't think this is correct.

**Comment by howdeh** [comment]
Going to close this until I have more info so I do not waste your time! Clearly i need to read up on the class to understand damage output. Raidbots seems to want to cast convoke as soon as it is off CD. Incarn/CA is only casted when convoke is off CD.

Is there a way to have this triggered? Also what about the opener?

**Comment by Hekili** [comment]
So, lots of questions here.  Things to keep in mind:

1. If there is a bug or if the priority is not matching SimulationCraft, it's important to find the *first* thing, resolve that, and see what else gets resolved by fixing that.
2. Keep in mind, every sim is starting out with the same default circumstances, so as you go pack to pack in M+ or clearing trash in raids, you won't be starting with the same circumstances as your sim.  For example, Wrath, Wrath, Starfire as an opener doesn't make a ton of sense if you aren't going to proc Lunar Eclipse from those Wrath casts.  Your first pull after a wipe will closely match SimC, though.
3. Wrath, Wrath, Starfire was (until recently) very reliant on your max distance positioning from your target, so that your Wrath had time to travel before the boss actually pulls and combat starts.  This should be resolved now, regardless.

> I understand that getting 'better' at my class is an alternative but I'm finding it hard to understand why my DPS is falling to lower than 4k (dropping to 3.7k after 2 convokes and Incarnation) after several minutes despite raidbots simming me at 4.3k.

What amount of time are you testing yourself for when you attack a dummy?  Your sim is running 180 seconds +/- 20%.  Averaging pulls that lasts 216 seconds into your DPS calculations might distort what you see when you look at a single sample in-game.

> I'm finding that Hekili is not casting convoke the spirits when off CD (I guess the addon recommends that it gets casted with Incarnation) however this is not being recommended by raidbots so I'm curious as to why the addon is recommending this? 

Genuinely not sure what you're saying here.  Convoke is synced up with Incarnation (or Celestial Alignment) mostly.  You can look at the priority to see what the conditions are.  I'll show you, below.

> What is also odd is that Hekili almost tries to recommend convoke at around 22s left CD on Incarnation so I'm not sure what's happening.

Probably related to the logic around when to desync Convoke, which has a lot to do with fight length.

Convoke desync logic, from SimC:
```
variable,name=convoke_desync,value=ceil((fight_remains-15-cooldown.ca_inc.remains)%180)=ceil((fight_remains-15-cooldown.convoke_the_spirits.duration-cooldown.convoke_the_spirits.remains)%180)&!raid_event.adds.exists|cooldown.ca_inc.remains>interpolated_fight_remains|cooldown.convoke_the_spirits.remains>interpolated_fight_remains-10|!covenant.night_fae
# Calculates whether using Convoke now will allow you to still cast the same amount of Convoke+CA/Inc casts
```

Convoke logic, which includes variable.convoke_desync above:
```
convoke_the_spirits,if=!druid.no_cds&((variable.convoke_desync&!cooldown.ca_inc.ready&!runeforge.primordial_arcanic_pulsar|buff.ca_inc.up)&astral_power<=40&(buff.eclipse_lunar.remains>10|buff.eclipse_solar.remains>10)|fight_remains<10&!cooldown.ca_inc.ready)
# Uses Convoke if CA/Inc is up or you are desyncing CA/Inc with Convoke and you are below 40 AsP
```

> Raidbots is also recommending the use of starfall in ST output. I'm not sure where else it is deviating.

Your sim profile has this entry for Starfall, which is used on average 2.48 per iteration of your sim:

![image](https://user-images.githubusercontent.com/9438134/127652138-1ac44a98-eb2b-4956-b081-4df73dd3e253.png)

The same exists in the addon:

```
# Use Starfall with Stellar Drift and no Starlord, when no Starfall is up, you are in Lunar Eclipse for 8+secs or to proc Pulsar when above 90 AsP or adpative swarm has 8+secs remaining or is in flight. Note that under the same conditions it's dps neutral to Starfall during Ravenous Frenzy, when you'd still end up with 90+asp for the last globals.
actions.st+=/starfall,if=talent.stellar_drift.enabled&!talent.starlord.enabled&buff.starfall.refreshable&(buff.eclipse_lunar.remains>8&eclipse.in_lunar&buff.primordial_arcanic_pulsar.value<250|buff.primordial_arcanic_pulsar.value>=250&astral_power>90|dot.adaptive_swarm_damage.remains>8|action.adaptive_swarm_damage.in_flight)&cooldown.ca_inc.remains>10
```

If you're at a point when it seems like this should be getting recommended in single-target -- you don't have anything higher priority to push -- then snapshot and I can tell you why you got a different recommendation.  It could be a bug.  It could be that 2.48 casts in a 3 minute average fight is pretty rare, and that if you delay anything even a small amount, those tiny windows for ST Starfalls close up.

> Am I just bad at pressing buttons (it doesn't feel like I am missing anything here) or is there something not right about the balance rotation?

I have no way of knowing what you're pushing, but I'd assume you can push the right button when shown the icon of the spell to cast, so you're probably doing fine.

> further look into my details vs raidbots, it looks like my Primordial Arcanic Pulsar uptime is 31% vs 98% - is it me miss pressing spells to stop having that kept up? 

This might be distorted by Details in-game, based on having the Primordial Arcanic Pulsar up before combat begins.  *Maybe*.  Genuinely uncertain.  But unless you somehow go very long periods of time where you just overcap Astral Power relentlessly, Primordial Arcanic Pulsar should basically always be up.  See if you find yourself hitting AsP generators and not AsP spenders when you have high AsP.  That'd be an issue to solve.

It will help me a lot if you keep your snapshot links and your "why I'm giving you this snapshot link" explanation close together (think bulletpoints) so I don't have to worry about linking the right sim to whichever part.

* https://pastebin.com/GdGgELCJ
> further look into my details vs raidbots, it looks like my Primordial Arcanic Pulsar uptime is 31% vs 98% - is it me miss pressing spells to stop having that kept up? Please bear in mind the DPS is extended by DoTs and I had stopped casting by this point but i highly doubt that it would drop from 98% to 31% in the space of <10s?

If you have Primordial Arcanic Pulsar up 30% of a 3 minute pull, that's 54 seconds.  If the sim has it up for 98%, that's 176.4 seconds.  Much more than a 10 second difference, of course.  What kind of % uptime of the aura do you see on competitive logs?

Are you just in combat for a very long time when you're testing on dummies or something?

Sometimes SimC implements buffs slightly differently from the live game, so that there is greater visibility.  But that uptime difference is quite interesting.

Anyway, reviewing this specific snapshot:  You're in combat but not targeting anything.  Your next eclipse will be Lunar.  You need 2 Wrath casts to trigger it, but you're already in-combat so the opener (which is only a thing for the first few seconds of the fight) is secondary to getting your dots up at this point.  You have Primordial Arcanic Pulsar up with 10 stacks.

Keep your enemies targeted while snapshotting.  And while DPSing in general, of course.  This snapshot doesn't really tell us much else.

* https://pastebin.com/UZtaRVYy
> The opener this time recommended Starfire rather than wrath x2. It also recommended convoke for a split second when it came off CD but then waited until Incarnation was off CD but it got used. Details is showing a 77% uptime on PAP and 62% on Redirected anima which is better. Maybe better at pressing buttons the second time round, but still capping at 3.7k DPS following the addon. I did notice that moonfire/sunfire are not at 100% uptime too.

Snapshot won't tell me what *was* recommended, it tells me what *is* recommended, so the context is helpful but if you want to be told why it's showing Starfire, you have to supply a snapshot when that's happening.

Again, you're in combat and you have no target.  No dots are applied (because you have no target).  Your next Eclipse can be either.  Both Wrath and Starfire need 2 casts to trigger the next Eclipse.

Recommendations are Moonfire, Sunfire, Starfire, Starfire.  Which is about what one would expectd when you're in combat, so opener is over, and you don't have a target.

So, given that you have 2 snapshots with nothing targeted, how are you triggering your snapshots?  Why do you have no target when you're snapshotting?  Are you clicking off and trying to do something manual in menus to make a snapshot?  Use your toggle button.  *When* you snapshot matters.

Think of it like a photograph.  If you take a picture the day after a concert, the band isn't going to be on stage in your photo.  Snapshot the moment when you think something should be recommended but it isn't.  Tell me what you think you should see next to the link you provide.  Keep in mind, having your basic dots applied is pretty high up in priority so if you don't have a target or you're looking at a target with no dots applied, the addon is probably going to tell you to apply dots.

Feel free to read through the priority to see what the sim builds out.  Priority lists are about priority.  If something is higher up in the priority list and is ready to go (resources are available, not on cooldown, conditions are met), then it's going to be recommended over anything lower in the priority.

**Comment by Hekili** [comment]
Closing.  You can post new ticket(s) as needed and provide specific cases as discussed above, if you'd like.
