### ISSUE TITLE
[FDK] Chains of Ice is not always displayed correctly if you move Pillar of Frost to another window like defensives or interpputs.

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#1195]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello. Here I noticed one feature that was not there before, or rather did not pay attention until today. When playing FDK, I usually moved abilities such as (Pillar of Frost, Abomination Limb, Empower Rune Weapon, Frostwyrm's Fury, Breath of Sindragosa) into one of the slots, it could be defensives or interpputs. It seemed to suit me, I myself could control the process using a macro like this:
#showtooltip Breath of Sindragosa
/ cast Pillar of Frost
/ cast Empower Rune Weapon
/ cast Abomination Limb
/ cast! Breath of Sindragosa
/ cast Raise Dead
/ use 14
But I saw one inconsistency between Chains of Ice and Pillar of Frost. It turns out that until the moment when Pillar of Frost was ready, the addon offered to immediately use Chains of Ice without Pillar of Frost. This happens only when we have Pillar of Frost ready and Chains of Ice has stacks. Is it possible to simply make the addon recommend Chains of Ice only during Pillar of Frost? On rotation, I saw that during gcd Pillar of Frost, we must press Chains of Ice. But how can I do that please, so that the addon does not make much difference where I move the icons? In fact, I don't touch the rotation, I just removed them in one place, it's so convenient for me. But this only moment just doesn't want to work correctly. I tried with your new Show Separately function, but as soon as I put these icons there it still uses Chains of Ice anyway. Is it possible to somehow get out of this situation? or even so it is necessary that the addon states that Pillar of Frost belongs to the Default (none) category, then I should leave it there and not touch it because it breaks the rotation.

### How to Reproduce

1. Pillar of Frost 10 seconds to readiness.
2. Suggest using Chains of Ice when there is Pillar of Frost right away.

### Snapshot (Link)

https://pastebin.com/ZpCGiteU

### Additional Information

Here's if that Snapshots Defensives https://pastebin.com/8Ndpb4M0

**Comment by Hekili** [comment]
If an ability is set to Show Separately (i.e., carved out to Cooldowns), it is treated as though it is on CD in the other displays.  For the most part, it's a necessary compromise so that priorities don't just break down entirely when your abilities aren't on cooldown but the addon isn't allowed to recommend them.

The Chains of Ice entry that was used was:

```
! talent.obliteration.enabled[false] & death_knight.runeforge.fallen_crusader[true] & ! buff.pillar_of_frost.up[false] & cooldown.pillar_of_frost.remains[60.00] > 15 & ( buff.cold_heart.stack[11.00] >= 10 & buff.unholy_strength.up[true] | buff.cold_heart.stack[11.00] >= 13 )
```

If you want Pillar of Frost's real CD to be considered in that entry, you can change that Pillar of Frost reference to `cooldown.pillar_of_frost.true_remains` but you'll likely need to make more, similar changes elsewhere, and I don't help write/revise custom priorities in general.

> Is it possible to simply make the addon recommend Chains of Ice only during Pillar of Frost?

Sure, you can write a custom priority that does that, if you want.

> Here's if that Snapshots Defensives pastebin.com/8Ndpb4M0

Sorry, what is this snapshot for?  Why are you showing me this one?  Thanks.
