### ISSUE TITLE
[FEATURE] Import / Export custom changes. 

### ISSUE THREAD

**Issue by MrWizard516** [Hekili/hekili#1197]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

It would be nice if you could add in the option to be able to export all of our custom changes and be able to re-import them when new versions are released so that we don't have the keep going back and setting them up all over again.

### Contact Information

Discord: MrWizard#8972

**Comment by Hekili** [comment]
Can you be more specific?

If you're talking about Priorities, the FAQ already provides you a way to create your own copy of Priorities so that your changes aren't overwritten.  There's no real feasible way to automatically merge any changes you've made with any changes I've made.

If you're not talking about Priorities, which settings are you concerned with?
