### ISSUE TITLE
Discipline Priest Basic Rotation

### ISSUE THREAD

**Issue by Bastyani** [Hekili/hekili#122]
Hey! Any chance to throw in discipline priest basic dps rotation? Like SW: Pain, Smite, Penance, Schism...

**Comment by c2lknt** [comment]
Seconding this request.  It's a simple rotation but there's just so much to pay attention to as a disc priest that being able to *not* think about the rotation would be a great help.

**Comment by Hekili** [comment]
Thinking about it.  Don't know how basic/suboptimal I want to allow in the addon.  If it's supported, it should be good.

**Comment by c2lknt** [comment]
It doesn't have to be suboptimal.  The issue with Disc is its just "use everything on CD" (with the possible exception of using penance on a friendly target) - and there are only like 4 spells, and no procs/interactions, so that's what I (and I think OP) mean by "basic".  It's a really simple rotation, it "should be easy" and you "shouldn't need" something like Hekili, but there's just so much for a disc priest to pay attention to.

The strength of Hekili is in 1) getting to know new specs and 2) having a benchmark to go by when learning new content, so your rotation isn't another thing you have to think about when trying to figure out how to optimally handle new mechanics.  It's perfect for disc because healers have so much to think about in all contexts, both in new and familiar content - not just mechanics but watching for idiot dps standing in fire, butt pulling, emergency CC, extra mechanics that are "healer jobs", etc - and being able to look in just one place to get a sense for how best to optimize your dps (and therefore healing), and not have to look at your penance/pw:solace CDs, or the debuff timer(s) on sw:p, would be so helpful.  

In M+, disc already does worse dps than resto druid, so there's no way to stop the sadness (and worse healing and 100% fewer battle rezzes), but I'd love to give disc a try in lower keys, and having the confidence of a tool like Hekili might help me (and others) get in there and do it.
