### ISSUE TITLE
Have different buttons on Hekili panel and on the Blizzard panel

### ISSUE THREAD

**Issue by sergeyvolkov-tech** [Hekili/hekili#1231]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Have different buttons on Hekili panel and on the Blizzard panel

### How to Reproduce

1. Enter game as a Balance Druid. 
2. Activate moonkin form
3. Hit 1 or 2 skills from Hekili Panel
4. Compare which buttons you must press on Hekili panel and blizzard panel, Moonfire on blizzard panel has button "1" and on Hekili panel it is "Q"
And Starsurge on blizzard panel is "Q" and on Hekili panel is "F"
![123](https://user-images.githubusercontent.com/43564452/132985727-9a147a57-9a98-41f8-8877-5a4a705cf82a.png)

### Player Information (Link)

https://pastebin.com/NFxiNJ7V

### Error Messages (Link)

1

**Comment by Hekili** [comment]
Keybind detection is sensitive to how you've organized your bars for your multiple forms, because of action bar paging.  You probably have those abilities in different slots on different action bar pages.

You can try reorganizing your bars, or you can just set the keybind manually in /hekili > Actions > Override Keybind Text.

**Comment by sergeyvolkov-tech** [comment]
@Hekili  "You probably have those abilities in different slots on different action bar pages." i check this, but no, skills that i show on screenshot there is only on 1 panel, and for example "Moonfire" in normal form will be "1" and in moonkin form will be "q".
That problem only with druid class and only with moonkin form, other forms have text "1". I have 1 druid with this problem (He is on screenshot), i delete this character, and create new one. He has very same problem. 

And about this "You can try reorganizing your bars, or you can just set the keybind manually in /hekili > Actions > Override Keybind Text." I look in ingame menu, but cant find "Actions", and look in AddOns, cant find too...

**Comment by Hekili** [comment]
I should've said /hekili > Abilities, not Actions.  You can manually set the keybinding there.

That said, I'd still bet money you have those abilities on a different action bar page, one that isn't visible at the moment.  If you have your action bar pages in a weird order, it will interfere with keybind detection because the same slots are recycled between multiple bar pages.

If you want to provide more information, you can paste the output from the following:
 * `/dump Hekili.KeybindInfo.starfire`
 * `/dump Hekili.KeybindInfo.moonfire`
 * `/dump Hekili.KeybindInfo.starsurge`

**Comment by sergeyvolkov-tech** [comment]
@Hekili Man you are right, it was panel №10...
It is kind of interesting thing... 
When i pick bear form my panel 1 transform in panel 7, with bear skills
When i pick cat form my panel 1 transform in panel 9, with cat skills
At this moment all fine with keybinding.
And when i pick moonkin form my panel 1 is not transform at all, i dont know why, and i start look at all my panels. And i see panel 10 full of skills, and Hekili take buttons from panel 10 i dont know why...

When i clean panel 10, Hekili start take buttons from panel 1, it is pretty strange for me)
Anyway thank you for help!

**Comment by Hekili** [comment]
It's because of what I explained.  The addon pulls from action bars in pages.  Action bar 1 is what you see when you're not in any form.  In your various forms, the default pages for each form are as follows...

Cat Form:  7
Cat Form (prowling):  8
Bear Form:  9
Moonkin Form:  10

If you decide to turn off paging (so you just use bar 1 in Moonkin Form), you'd want to clear the spells out of page 10 since that's where the addon will look first for the binding.  Then it looks at lower bar numbers from there.
