### ISSUE TITLE
[HUNTER]  kill command make a distance check

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#1242]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Please see how you can implement
kill command when pets are far from the target, or get stuck elsewhere. I would like to
The kill command was with a check for a distance, and a check for a pet.

**Comment by Larsy93** [comment]
This would be awesome, it causes issues every now and then.

**Comment by Hekili** [comment]
It would likely rely on having Pet-Based Target Detection enabled (i.e., having a pet ability on your own action bars).

**Comment by Larsy93** [comment]
> It would likely rely on having Pet-Based Target Detection enabled (i.e., having a pet ability on your own action bars).

Not a problem for me, playing a BM hunter u should probably have that enabled either way imo since it performs better that way.

**Comment by Hekili** [comment]
This should work in 9.1.5.

**Comment by harsjo** [comment]
@Hekili This function seems to check whether or not the pet is in melee range of the target. If it's possible I think it would be better to check if the pet is within 50 yards, since that is what decides if you get an error message for the spell or not, i.e. "Your pet is out of range of the target".
I actually want to prioritize using Kill Command if my pet is not in melee range, but within 50 yards, since it makes the pet sprint to the target and actually do damage to it.
On that note, is there any syntax for checking my pet's distance to my target? Or a boolean like target.pet_bite.in_range?

**Comment by Hekili** [comment]
1.  This is a very old, closed ticket.

2.  You can simply disable "Check Pet Range for Kill Command" in your Beast Mastery options.

![image](https://user-images.githubusercontent.com/9438134/215498148-bc14ae1a-094d-48ad-b015-43004c61d49a.png)

> I actually want to prioritize using Kill Command if my pet is not in melee range, but within 50 yards, since it makes the pet sprint to the target and actually do damage to it.

Yeah, this appears to have changed a bit (in game) over time.  The reason it was changed in the first place is that when your pet was out of range before, you could have Kill Command stuck blocking the queue until the pet got in range for Kill Command to work.

> On that note, is there any syntax for checking my pet's distance to my target? Or a boolean like target.pet_bite.in_range?

Nope.
