### ISSUE TITLE
[REC] Feral druid, Brutal Slash recommended with Clearcasting instead of Shred

### ISSUE THREAD

**Issue by luizzitol** [Hekili/hekili#1252]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my feral druid, when having clearcasting proc, the addon is recommending Brutal Slash instead of Shred. As Brutal Slash only have 1 charge available (not maximum 3), and rake and thrash are up, the clearcasting would be better used as a Shred.

It is also better to keep 2 Brutal Slash charges to use inside the Tiger's Fury, and the addon is not keeping any.

### How to Reproduce

Not much to say here, Just follow druid rotation as shown and you will find that many clearcasting are used on Brutal Slash, and Brutal Slash always take priority versus Shred saving none for Tiger's Fury.

### Snapshot (Link)

https://pastebin.com/PHj2dLnR

**Comment by Hekili** [comment]
The priority is specifically written to compare Brutal Slash damage to Shred damage in that scenario and Brutal Slash comes out on top, regardless of the charges.  Do you have any sims that demonstrate your recommendations?

**Comment by luizzitol** [comment]
Thank you for the prompt response. I love this addon and I am fascinated to
see how much goes into it.

On that snapshot I sent it use Brutal Slash with clear casting and the next
spell it uses is shred.

If only it did it the other way around, you would have 15 energy on top, as
Brutal Slash is 25 energy compared to 40 Shred.

On the same note, while in Tiger's fury, Brutal Slash has way better value
than Shred, therefore it would be very beneficial to try and keep charges
to be used during those 10 secs -obviously without sitting at 3 charges.

Unfortunately I don't know how to sim something like that at the moment,
but I can have a look and see if I can figure it out.

Many thanks
Luis

**Comment by Hekili** [comment]
I completely understand the logic you throw out.  One of the big challenges in priority design is that a lot of things that seem like they're more optimal are really a wash -- or a DPS loss -- in aggregate.  Opportunity cost always looms over these micro-optimizations.

If you save Brutal Slash for Tiger's Fury (keeping the last charge regenerating only), and your fight length doesn't support that last Brutal Slash, you probably lose DPS.  You can account for that as well in a priority, and dump BrS when the fight is ending, but then when you put those combinations of factors together, do you wind up ahead or back where you started?

That's why sims are so important.  We get really confident about common sense assertions in our priority but often times, the optimization doesn't pay off as much as we'd expect, even if you do end up with 15 more energy afterward.

It's definitely something that can be sim tested, though.

**Comment by luizzitol** [comment]
I have been tinkering with the priorities for a couple of hours and added
the following.

+Shred if clearcast and not in tigers fury
+Brutal slash if more than 2 charges
+Shred if not in tigers fury
+The default brutal slash calculation.

I feel satisfied about this change but yeah, now I wonder if me being
satisfied implies a dps loss...

I wish I knew how to sim this as I have been hitting the dummy for hours
hahaha, any "tutorial" you can point me to?

many thanks
Luis

**Comment by Hekili** [comment]
Dummy testing doesn't really count except for finding mechanical issues.  If you go to SimulationCraft's site, their wiki is the only reference for modifying priorities for testing purposes.
