### ISSUE TITLE
Fire mage getting 'Critical mass' icon with a red X (Sun King's Blessing leggo)

### ISSUE THREAD

**Issue by uzzwow** [Hekili/hekili#1275]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I'm getting the `Critical mass` icon with an x on the right side of the icon, as a fire mage, with the Sun King's Blessing leggendary

### How to Reproduce

fire mage, with the Sun King's Blessing leggendary

### Snapshot (Link)

https://pastebin.com/jAR1pr74

**Comment by Hekili** [comment]
The entry you're referring to is recommending removal of Sun King's Blessing before Combustion.  The explanation from the sim is here:

`If Sun King's Blessing stacks are high, cancel them before Combustion so that the Sun King's Blessing proc can be safely delayed until after Combustion without risk of expiration.`

The specific conditions leading that entry to show:

`buff.combustion.down&buff.sun_kings_blessing.stack>2&talent.rune_of_power&cooldown.rune_of_power.remains<20`

In your snapshot, that was:

`buff.combustion.down[true] & buff.sun_kings_blessing.stack[3.00] > 2 & talent.rune_of_power.enabled[true] & cooldown.rune_of_power.remains[0.00] < 20`

That seems to match the sim behavior.  Does that help?

You can make a macro to `/cancelaura` the buff, too.

If you were to ignore the `cancel_buff`, it looks like a ~1.4% DPS loss.

![image](https://user-images.githubusercontent.com/9438134/141653969-47ea1b93-fd46-4d33-be63-9149cffd4afb.png)

https://www.raidbots.com/simbot/report/4WwkZsm3nhY39mr1iufpKd

Would you prefer a spec option to disable that entry?  You can also turn it off by going to /hekili > Priorities > Fire > Action Lists > combustion_phase > 5 and uncheck Enabled.
