### ISSUE TITLE
Hekili stops displaying often in raid fights

### ISSUE THREAD

**Issue by Zankom** [Hekili/hekili#128]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version. I am using the latest version

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports. 
 
**Describe the Bug/Issue**
A clear and concise description of what the bug is. The ability icon bar disappears randomly on a bossfight, and sometimes on adds

**To Reproduce**
Steps to reproduce the behavior: Only has happened on a raid boss in my experience
- Go to '....'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
A clear and concise description of what you expected to happen. I expected the addon to display the rotation as always, but it refused to display

**Screenshots**
If applicable, add screenshots to help explain your problem. The icons simply disappear, so a screenshot isint needed

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here. build: v8.1.5-14

level: 120
class: ROGUE
spec: assassination

talents: cheat_death
    elaborate_planning
    iron_wire
    poison_bomb
    subterfuge
    toxic_blade
    vigor

traits: azerite_empowered=3
    double_dose=2
    earthlink=1
    echoing_blades=1
    gutripper=2
    lying_in_wait=2
    scent_of_blood=1
    shrouded_mantle=1
    shrouded_suffocation=1
    twist_the_knife=1

sets/legendaries/artifacts: none

gear:     first_mates_spyglass=1
    spark_dampening_footpads=1
    heartpiercing_stalactite=1
    gloves_of_spiritual_grace=1
    grongpelt_vest=1
    ritual_binders_ring=1
    heart_of_azeroth=1
    zocalo_stabber=1
    deathstalkers_bindings=1
    orgrimmar_tabard=1
    ornate_elundris_ring=1
    forest_lords_razorleaf=1
    stretched_sinew_waistcord=1
    crown_of_aakuls_dark_reign=1
    mestrahs_singing_spaulders=1
    common_white_shirt=1
    deathguards_greatcloak=1
    honorbound_outriders_pants=1

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
Please fill out the ticket so I know what to even look at.

**Comment by Hekili** [comment]
WHEN SUBMITTING AN ISSUE:

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

PUT ISSUE REPORT LINK HERE:

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
PUT SNAPSHOT LINK HERE:

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**Comment by Hekili** [comment]
Closed; no info.
