### ISSUE TITLE
[BUG] HekiliDisplayPrimary.Recommendations[1].wait doesn't update frequently without Throttle Updates

### ISSUE THREAD

**Issue by Snoogey** [Hekili/hekili#1282]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

HekiliDisplayPrimary.Recommendations[1].wait doesn't seem to update frequently when Throttle Updates is Unchecked.
I can see that the value is changing, but it's not changing in a reliable/fast manner.
However, when turning on Throttle Updates and setting it to the absolute "smallest" throttling, i.e. 20. it appears to be accurately updating the wait value again.
Turning off Throttle Updates after this once again produces the original result - a very "slow" wait value.
This started since the "9.1.5" update of Hekili.

### How to Reproduce

Create a WeakAura returning HekiliDisplayPrimary.Recommendations[1].wait.
Spam the recommended abilities as fast as you can.
See how the wait value doesn't match the "GCD dial" on the ability.
Turn on Throttle Updates, set it to 20.
Do the above again.
See how the wait value matches with the "GCD dial" more closely.

### Player Information (Link)

https://pastebin.com/MHeKe86C

### Error Messages (Link)

N/A

**Comment by Hekili** [comment]
Yes, the best way for the addon to reduce CPU usage is to update less frequently, if it hasn't seen anything happen in combat that would confirm an update is needed.

The `wait` value for an icon is probably not the value you want to build a WeakAura around, because the `wait` is simply the amount of time between when recommendations were generated and the recommended ability should be used.  (For queued icons, `wait` is the time since the last action.)

I believe the value you'd actually want to work off of is the `exact_time` that the recommendation is meant to be used.  You can look in UI.lua for `Display_RefreshCooldowns` (line 1307) to see how the addon combines GCD information, ability/item cooldown information, and `exact_time` to update its own displayed CD spiral.
