### ISSUE TITLE
[BUG] LAG SPIKES DURING RECOMMENDATION CALUCATIONS [DRUID][FERAL]

### ISSUE THREAD

**Issue by ChrisKader** [Hekili/hekili#1298]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I am currently unable to determine exactly WHEN the spike would start but if I hit a dummy for around 5 minutes, I can generally reproduce the issue at least once. Below is a video recording of what I am talking about.

### How to Reproduce

1. Cycle through the Feral rotation for around 5 minutes or so.

### Player Information (Link)

https://pastebin.com/vczHjBSP

### Additional Information

Snapshot: https://pastebin.com/ujJ5dq4Q
Additional Snapshot: https://pastebin.com/kLn7XgUN

### Contact Information

Onlyne#0001

**Comment by Hekili** [comment]
Sorry, this ticket sums up to "a lag spike happens sometimes" without anything that would help me investigate it. I'm working on some stuff that may improve it, so watch for the next release and see if it's any better at that point.

**Comment by ChrisKader** [comment]
I also have a video clip of when its happening that also shows the number of recommendations drop down from 4 to 1 while CPU usage increases and FPS drops. Link starts at the 4:10 mark with the FPS drop happening as I cast convoke at the 4:20 mark.

https://drive.google.com/file/d/1pfGOimXByIDfhKkv4aKNjPeqcTCKK_Hw/view?t=250

**Comment by ChrisKader** [comment]
Drive is still processing the video so its at 360p. Should be at 1080p soon.

**Comment by Hekili** [comment]
The video isn't accessible.  Looking at the snapshot, the addon's respecting your settings regarding throttling.  Like I mentioned, I'm working on things that may impact this but there's nothing I can really pull from the video that will help me to do any additional replication.  The changes I'm already making will impact this significantly.

> pastebin.com/ujJ5dq4Q

This looks truncated.

> pastebin.com/kLn7XgUN

This throttles intentionally (based on your settings), but there seems to be some oddness in the snapshot.  For some reason, checking Tiger's Fury entries take longer to process.  But this can be distorted a bit, because generating a snapshot itself adds a ton of CPU time (building huge strings of conditions data takes more CPU than actually generating the recommendations).

Anyway, best thing is to wait and see, since this is all directly affected by changes that I'm working on already.

**Comment by ChrisKader** [comment]
Should be accessible now. Regardless, I will wait for the next release.

**Comment by Hekili** [comment]
If you wanna do anything experimental, you can go into Events.lua and remove:

```
RegisterEvent( "CURRENT_SPELL_CAST_CHANGED", function( event, cancelled )
    Hekili:ForceUpdate( event, true )
end )
```

You can comment it out with `--` or `--[[ ]]` or just delete it.  That event is causing extra updates that don't seem to be needed.

**Comment by geraint425** [comment]
I checked everything ok on my feral. Does not lag, does not slow down. And the person in the video clearly shows that he uses the program for hekilli to read the rotation. This can be seen by clicking on the bars. Since he instantly presses them to even GCD. That's his whole problem. I can record a video from my feral where everything works fine without lags. And the person clearly uses software.

**Comment by ChrisKader** [comment]
I use a Razor Naga mouse that has 12 buttons on the side to which I bind my abilities to. You can clearly see in the video that most of my abilities are linked to NUMPAD binds.

**Comment by ChrisKader** [comment]
Razor Naga lets me set buttons to repeat when I hold them down. Shred, for example, is on NUMPAD3. If I hold that button down on the mouse, it will keep pressing NUMPAD3. This results in me using shred right when I need to (the moment I have enough energy to do so). Same goes for Rake, Swipe and others.

**Comment by ChrisKader** [comment]
![image](https://user-images.githubusercontent.com/633360/144177064-cf2bf464-261b-4d1b-b1d2-5076c4d06955.png)

**Comment by ChrisKader** [comment]
> If you wanna do anything experimental, you can go into Events.lua and remove:
> 
> ```
> RegisterEvent( "CURRENT_SPELL_CAST_CHANGED", function( event, cancelled )
>     Hekili:ForceUpdate( event, true )
> end )
> ```
> 
> You can comment it out with `--` or `--[[ ]]` or just delete it. That event is causing extra updates that don't seem to be needed.

I tested for about 30 mins on a dummy then did a key with zero issue after commenting out that event register. After the key, I uncommented it and within a few minutes I experienced the same issue.

Thanks for the help!
