### ISSUE TITLE
Ret TV on 2 Target without RV

### ISSUE THREAD

**Issue by killer1209** [Hekili/hekili#130]
For RET sometimes it is recommending to use TV as a finisher with 2 Targets and not using Righteous Verdict Talent.

https://pastebin.com/AvG79mKX

**Comment by Hekili** [comment]
Can you take a snapshot when it's recommending TV and you think it shouldn't?  This snapshot is recommending Hammer of Wrath.

**Comment by killer1209** [comment]
i edited the original post let me know if that capture it.

**Comment by Hekili** [comment]
That helps.  Thanks.  Investigating.

**Comment by killer1209** [comment]
so it looks likes its also happens on more then 2 targets.

not sure if its different but here is another snapshot of it at 4 targets.

https://pastebin.com/BVGzizia

not sure if its my settings or something. but it is set to auto and the add on is detecting the 4 mobs

**Comment by Hekili** [comment]
Thanks for investigating, too.

The issue comes from the Retribution APL's layout and the updates I've made to the variable system (see variable.ds_castable).  The variable system would cache a default value for variable.ds_castable when the finishers list was checked the first time.  When the finishers list was checked a second time, the default (0) would be used and this would be interpreted to mean that Divine Storm shouldn't be used.

I believe I have a solution, which I'm posting as v8.1.5-16-beta1.  It should be online in ~10 minutes or so, so please try it and let me know if things seem resolved.

This should also improve performance a fair amount.

**Comment by Hekili** [comment]
I'm posting -16 as release since that bug really needs to be resolved for all users.  If you still find issues, please reopen this ticket or submit a new one with updated information.
