### ISSUE TITLE
2 problems currently seen, same profile in use. Windwalker: Icons show, do not 'walk off' when used.  SinRogue: Doesn't show up at all.

### ISSUE THREAD

**Issue by Barleduq** [Hekili/hekili#1301]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Windwalker: With latest version, 9.1.5-1.0.4-alpha8, installed by CurseBreaker from wowinterface.com. I have 4 queue icons showing.  The addon icons show up but instead of each one going away when I use it and being replaced by the next, they mostly just sit there with the cooldown sweep showing. This is particularly a problem for windwalker because in order to get my mastery boost I can't use the same ability/spell twice in a row.  I had, around hte third week in November, tried tweaking some of the settings - mostly adding one icon, and playing with the alpha.  I put all of those back, and it still doesn't work correctly.  I uninstalled, removed the saved variables, and reinstalled, and it didn't change anything.

SinRogue: I moved to this character. Hekili doesn't show up at all. It is enabled, I'm using the same profile over all my characters.  This time, I tried tracking down a previous version - Curseforge shows 9.1.5-1.0.3. I manually installed it, and it still doesn't show up.  

I use swatter as my bug collection tool. It shows no errors for Hekili. I have disabled all the addons it was complaining about, except for Blizzard_QuestSuperTracker, and Blizzard_Deprecated (!) and I don't know where to find them to turn them off.

Here is a screenshot of it failing to move the icons off and showing them with cooldown sweeps. 

![WoWScrnShot_120521_235332](https://user-images.githubusercontent.com/20568287/144822616-97c99f79-8627-45e8-820c-1d508ee5c708.jpg)
  
When I logged back in to my monk, Hekili (the installation from curseforge, 9.1.5-1.0.3) doesn't show up at all. 

### How to Reproduce

Log in to any character. 
Observe Hekili there, or not there, 
    if there, observe the icons not behaving as they had been while in combat

I honestly don't know how to reproduce.  I don't know what I did to make it happen in the first place. 

### Player Information (Link)

windwalker: https://pastebin.com/t0qBSRSm    sinrogue: https://pastebin.com/wRXezEix

### Error Messages (Link)

No error messages show up. 

### Contact Information

I do check my github email.  However, my Discord is Barleduq#2721 and my battlenet is WillowBirman#1606

**Comment by Hekili** [comment]
First, thanks for alpha testing.  Keep in mind, alpha versions are _not_ latest releases, and are test versions that are likely to have bugs.

Second, it is *really hard* to follow the multiple issues in your ticket and figure out which pieces might be related and which pieces are unrelated.  If there are distinct issues, it's better to put the issues in separate tickets.  If there are issues that are closely interconnected, putting them in one ticket makes sense.

Last, can you give me some info about your PC?  CPU, GPU?  What is your typical framerate?  If you get relatively low FPS, I can imagine some ways the new alpha might not work well for you.

**Issue 1:  WW recommendations are slow to update in alpha8**

I've had another report of this, or what I think might be this, from someone playing Survival Hunter.  I'm investigating it.

It would be helpful to have a snapshot, which you can create by pausing the addon (`ALT-SHIFT-P` by default) and then retrieving it from the Snapshots section of /hekili.  Put it on Pastebin and provide a link here.

> I uninstalled, removed the saved variables, and reinstalled, and it didn't change anything.

It would not likely change anything.  It's an issue with the current alpha, though I don't seem to have the same issue.  You can revert to 1.0.3 in the meantime.

> When I logged back in to my monk, Hekili (the installation from curseforge, 9.1.5-1.0.3) doesn't show up at all.

Have you been importing priorities yourself?  You may need to tell the addon to reload the 1.0.3 priority (though if you deleted SavedVariables, it should have no memory).  Go to /hekili > Priorities > Windwalker, and click the "circle-arrow" button next to Priority Name to reload the priority.  You should be fine at that point.

**Issue 2:  Assassination doesn't show the addon at all**

I'm not able to replicate this on my computer, with same talents/settings as you.  A snapshot might help here, as it can force the addon to make recommendations.  You might try doing the same priority reload as I mentioned above.

Otherwise, try a clean install (delete addon, delete addon's SavedVariables, reinstall 1.0.3) again and confirm whether you're still having issues.  At that point, it would not be an alpha issue, but a 1.0.3 issue.
