### ISSUE TITLE
Frost Mage problem with proc uses

### ISSUE THREAD

**Issue by Amortalist** [Hekili/hekili#1309]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I'm having some troubles with the frost mage rotation, I don't have a legendary yet, playing NF and gearing that char but Hekili seems to be inconsistent at using the procs. Sometimes by purely following the ST rotation (cooldown & covenants activated) it sometimes let the procs end while it's still advising me to spam frostbolt, even with Fingers of Frost stacks or Brain Freeze (Free instant Flurry).

It will often wait for either 2 charges of FoF to advise to cast ice lance, or not at all.

### How to Reproduce

Play frost mage without legendaries, Night fae covenant
Talent build is classic mono 2 - 2 - 3 - 2 - 3 - 2 - 1 
Normal rotation on night fae dummy (Raider's Training Dummy)

### Snapshot (Link)

https://pastebin.com/GKy8eTf5

### Contact Information

Nibana#6011

**Comment by Hekili** [comment]
What were you expecting to be recommended at the time you took the snapshot?

**Comment by Amortalist** [comment]
Most likely 2 Ice Lance (To clear FoF stacks) then Flurry (using the Brain Freeze proc for 2 Winter Chill on Target) then 2 more Ice Lance

**Comment by Hekili** [comment]
Why "most likely"? What else might you expect at that moment?

**Comment by Amortalist** [comment]
Nothing else, I'm just saying that according to Wowhead / Icy Veins rotation advices but I'm not a Frost Mage pro is why I say most likely

**Comment by Amortalist** [comment]
My ilvl is very low btw, 180 ish. It feels like it's often locked trying to make me spam frostbolt for no apparent reasons when I have procs available. Trying it in 15s atm. Not sure if that's related but Hekili has been quite buggy ever since I did mage tower on different chars.

**Comment by Hekili** [comment]
"Quite buggy" doesn't mean anything useful. You can report specific bugs with details and snapshots, though. I'll review what you already provided.

**Comment by Hekili** [comment]
Okay, so in your snapshot, Rune of Power was recommended first.

```
11.  rune_of_power ( cds - 5 )
The action (rune_of_power) is usable at (0.00 + 0.00).
 - the action is ready before the current recommendation (at +0.00 vs. +10.00).
List ( cds ) called from ( Frost Mage:default:2 ) would PASS at 0.00.
NONE
 - this entry's criteria PASSES: cooldown.icy_veins.remains[180.00] > 12 & buff.rune_of_power.down[true]
Action chosen:  rune_of_power at 0.00!
Returned from list (cds), current recommendation is rune_of_power (+0.00).
- cds
The recommended action (rune_of_power) is ready in less than 0.2s; exiting list (default).
```

Rune of Power was recommended at this time because Icy Veins is on cooldown for more than 12 seconds (the addon pretends CDs are on cooldown when you have them toggled off, which is true in your case) and Rune of Power is not up.

Were you thinking you shouldn't cast Rune of Power?

> Most likely 2 Ice Lance (To clear FoF stacks) then Flurry (using the Brain Freeze proc for 2 Winter Chill on Target) then 2 more Ice Lance

You have 1 stack of Fingers of Frost in the snapshot, with 10.24 seconds remaining.

```
player_buffs:
   359082 - *Sign of the Legion                      -   1 - 3600.00
   227723 - *Mana Divining Stone                     -   1 - 3600.00
     1459 - arcane_intellect                         -   1 - 3038.71
   278310 - chain_reaction                           -   3 - 2.36
   205473 - icicles                                  -   2 - 57.26
    44544 - fingers_of_frost                         -   1 - 10.24
   352865 - *Called Shot                             -   1 - 0.70
   190446 - brain_freeze                             -   1 - 12.26
```

The second recommendation in this snapshot is Ice Lance.  Multiple Ice Lance entries are tested.

The first is the 6th entry in the st (single target) action list.  Its criteria were not met:
` - this entry's criteria FAILS: remaining_winters_chill[0.00] & remaining_winters_chill[0.00] > buff.fingers_of_frost.react[1.00] & debuff.winters_chill.remains[0.00] > travel_time[0.32]`

`remaining_winters_chill` is basically your number of Winter's Chill stacks, accounting for any spells that are already in flight.

So this checked if you have more effective Winter's Chill stacks than FoF stacks and also checks if Winter's Chill would fall off before any Ice Lance hits.  You don't have any Winter's Chill stacks, so it failed as appropriate.

The second is the 11th entry in the st action list.  Its criteria were met:
` - this entry's criteria PASSES: buff.fingers_of_frost.react[1.00] | debuff.frozen.remains[0.00] > travel_time[0.32]`

This entry passes when you have any stacks of FoF (you have 1) or if the target is Frozen and will stay Frozen until your Ice Lance hits.  You have a stack of FoF so its correct to pass.

I do need to look at sim logic and see if the `frozen` debuff is treated as active while you have Fingers of Frost up.  That's something that could be missing here...but you'd get the same result in this snapshot regardless.

- [ ] TODO:  Check if Frozen is applied in sim when Fingers of Frost is up.

As far as I can see, there's no error with the recommendations at the time you made a snapshot.  If there are other specific scenarios that you're not clear on, you can take more snapshots and explain the issue with each.  For instance, in your ticket, you reported:

> Sometimes by purely following the ST rotation (cooldown & covenants activated) it sometimes let the procs end while it's still advising me to spam frostbolt, even with Fingers of Frost stacks or Brain Freeze (Free instant Flurry).

The snapshot you provided doesn't have CDs activated, doesn't have procs falling off (Chain Reaction will be refreshed by your Ice Lance).

> It will often wait for either 2 charges of FoF to advise to cast ice lance, or not at all.

I'd need to see more snapshots and scenarios where you think Ice Lance should be used but the addon isn't recommending it.  Snapshots have to be from that moment.  It would help tremendously if your snapshot(s) match the situation you've described (and I get that timing it can be challenging).

> Not sure if that's related but Hekili has been quite buggy ever since I did mage tower on different chars.

And just to loop back to this, what specifically is buggy?

**Comment by Hekili** [comment]
Also, you skipped the Raidbots sim report link -- that's needed to make comparisons.

> Raidbots Sim Report (Link)

**Comment by Amortalist** [comment]
Quite buggy as in locking me into spamming filler abilities, thing it has never ever done before in 3+ years for me I think. In this snapshot it made me flurry once, then consume one Winter Chill on the target with an ice lance, then immediately advised me to frostbolt instead of doing a second ice lance : https://pastebin.com/q4ApjTKr

Here is the raidbot sim : https://www.raidbots.com/simbot/report/hMsTiM7Qh5Kh5rSPtRWe7b

I'll try to provide more snapshots and screenshots. 

![image](https://user-images.githubusercontent.com/47482996/145654973-7bd2c891-909d-4368-9d6f-1afec49f3d53.png)

**Comment by Hekili** [comment]
> Quite buggy as in locking me into spamming filler abilities, thing it has never ever done before in 3+ years for me I think.

If you're leaving Rune of Frost sitting at the front of the queue, then keep in mind all the recommendations you are following are starting from second in queue. Which is odd. You can set it to be toggled off with CDs if you want it out of the way. 

> In this snapshot it made me flurry once, then consume one Winter Chill on the target with an ice lance, then immediately advised me to frostbolt instead of doing a second ice lance :

I'm not seeing that. I'm seeing a snapshot recommending  RoP, Ice Lance, Frostbolt. And I'm seeing one Winter's Chill stack in both your snapshot and screenshot.

**Comment by Amortalist** [comment]
The advices are going from right to left here. It seems to do the same with CD on and off

**Comment by Amortalist** [comment]
Wait ... could it be that somehow it has reset and the advices are going from left to right now ?

**Comment by Hekili** [comment]
The snapshot recommends RoP, Ice Lance, Frostbolt in that order.

**Comment by Amortalist** [comment]
Ok that is where it's weird, maybe updating it or mage tower had it reset but that might be why it's so weird. I've always had it recommending the most right to be the 1st ability to use

**Comment by Amortalist** [comment]
I'll try in a dungeon right now, changed the anchor, I'm ashamed lol

**Comment by Amortalist** [comment]
Ok got it working good, it seems like something happened that somehow reverted the anchors on my chars

**Comment by Amortalist** [comment]
Sorry for the extra work :)
