### ISSUE TITLE
Arcane Mage rotation a bit jumpy

### ISSUE THREAD

**Issue by Amortalist** [Hekili/hekili#1314]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Rotation is a bit missleading because it shows different spells are coming next that suddenly changes to the good ones when casting the previous ones. 

Example : In this snapshot it should show 2 Blast then Barrage (5x Blast and immediately a barrage during Radiant Spark), it shows that arcane missiles is coming but once you do the 2 blast it changes to the correct advice. 

### How to Reproduce

Playing Kyrian Arcane Mage normal raid spec cooldown activated (1-2-3-1-1-2-1 -- Mikanikos and usual conduits) with Arcane Infinity leggo on training dummy in Orgrimmar

### Snapshot (Link)

https://pastebin.com/SS7QkjE5

### Raidbots Sim Report (Link)

 https://www.raidbots.com/simbot/report/wYta8y3wqqjxq6LqdsZe3E

### Additional Information

Another example : https://pastebin.com/NgcJB1Aj

Here it says two blast then Missile & Barrage during burst (RS TOTM AP used), when it's normally 5 blast in a row. However once the first blast is used, the rotation switch to the correct one

### Contact Information

Nibana#6011

**Comment by Amortalist** [comment]
When I use the advised blasts, the rotation goes back to showing normal queued spells : https://pastebin.com/NuvQuHbq

**Comment by Amortalist** [comment]
Here is another one. 

Before : https://pastebin.com/jzcsxBJ3

Shows Blast > Barrage > Orb when it should show 5x Blast > 1x Barrage

After having snapshotted / casted the first Blast it's back to normal : https://pastebin.com/zTkMQU77

**Comment by Amortalist** [comment]
Mana Gem is not advised here but should be, it also never shown in 3+ minutes of rotation :  https://pastebin.com/UNunM6Qw

Not playing Enlightened, mana inferior to 80% and 3 gems in inventory.

**Comment by Amortalist** [comment]
Rotation broke at some point in a pull, AP is available and the rest of the burst should line up soon but Hekili tells me to use Fire Blast and Frost Bolt. Normally it should advise something like using Evocation to prepare the burst (or do orb > 3 blast > barrage if my mana was higher) and then do the normal burst rotation.

https://pastebin.com/d7HACCmg

![WoWScrnShot_121421_174808](https://user-images.githubusercontent.com/47482996/146042502-0bacb895-8a2a-4563-b259-da8c0f0af153.jpg)

**Comment by Hekili** [comment]
Evocation wasn't used because its criteria weren't met.

` - this entry's criteria FAILS: mana.pct[26.14] <= 30 & variable.outside_of_cooldowns[true] & ( talent.rune_of_power.enabled[true] & cooldown.rune_of_power.remains[22.18] < 10 )`

It doesn't want to Evocation until Rune of Power is almost ready.  Seems like the sim should probably check if Arcane Power is available since it'll provide RoP instead.

**Comment by Amortalist** [comment]
Yeah it makes sense. Even without evocation it should consider normal arcane spells rather than Fire Blast / Frost Bolt tho I think

**Comment by Hekili** [comment]
> Yeah it makes sense. Even without evocation it should consider normal arcane spells rather than Fire Blast / Frost Bolt tho I think

That's something to test in SimulationCraft, if you can write/edit priorities.  As written, the APL does use Fire Blast and Frostbolt filler in edge cases.

> Rotation broke at some point in a pull, AP is available and the rest of the burst should line up soon but Hekili tells me to use Fire Blast and Frost Bolt. Normally it should advise something like using Evocation to prepare the burst (or do orb > 3 blast > barrage if my mana was higher) and then do the normal burst rotation.

When reporting, it'd help me if you write in bullet points and not paragraphs, with just the specifics.  You're not obligated to do so, but we're already talking a lot so I figured I'd suggest it.

* ~~Rotation broke at some point~~ *(This means nothing and can be omitted; if you're reporting recommendations then I already know you're not seeing what you expect to see.)*
* I expected Evocation to be recommended.  (Or Orb > 3 Blasts > Barrage if I had more mana.)  *How much more mana?*
  * AP is available *(to provide RoP)* and the rest of the burst should line up.
* It's recommending Fire Blast and Frostbolt instead.

Good that you included a snapshot.  Comparing to a Raidbots sim again can help.  Looking at your earlier sim, Frostbolt and Fire Blast are rare but they do get cast occasionally in edge cases.  If you're starting fights with CDs not ready, it's possible you're more inclined to reach those edge cases where Fire Blast or Frostbolt are used for filler at lower mana.  

You might also resim with Bloodlust disabled since it doesn't look like you're hitting Time Warp when you do your testing.  It's purely a guess, but you might see your sim cast Frostbolt and Fire Blast more often without Bloodlust.

- [ ] TODO: Check impact on DPS sim if Evocation is cast if Arcane Power is coming off cooldown rather than waiting for RoP specifically.

**Comment by Amortalist** [comment]
I started fights with all CDs ready and available, did the normal opener. 

Did a dummy sim without bloodlust for 2 minutes while testing before : https://www.raidbots.com/simbot/report/meoGawT9DJ6aQJzgcpZRku

Here is another one for 5 mn : https://www.raidbots.com/simbot/report/4qbs16eAEWEDhmeFZ7vi6C

It shows damage from Fire Blast / Frostbolt but only one count of it (or none) in both fights.

- Fire Blast and Frostbolt are nowhere to be seen in any actual player rotations. I believe it only brings confusion to a rotation when they get advised by Hekili. In wowhead it's specificed : 

![image](https://user-images.githubusercontent.com/47482996/146052918-c4dbd6a1-fdef-44f1-a7b4-f983a3cb8aa1.png)

- After looking into it, it is not expected to use Evocation if the mana is sufficient for the entire burn phase because AP reduces the mana cost of your abilities. This is a misunderstanding on my side. >20% mana looks safe for an AP burn.

Corrected version : 

- I expected different filler spells used instead of Fire blast and Frostbolt for the next 8 seconds. Either Arcane Missiles with a clearcast proc or Arcane Blast. 

It might have happened because RS was 8 seconds off cooldown, when normally it lines up perfectly. Could be due to a bigger amount of clearcast procs (-0.5s on AP's CD every uses), but considering the fact TotM was also available, I believe it's due to RS not being used on cooldown : 

![image](https://user-images.githubusercontent.com/47482996/146058513-8c0fdb45-a7ee-475a-8454-b0046219eb9b.png)

**Comment by Amortalist** [comment]
Update : I tried not using rune on prepull and it's much better for this rotation. It might have been what messed up with the timers.

**Comment by Hekili** [comment]
You could probably look at the snapshots to see each entry that was considered and why the failed, if you're looking to investigate yourself.

In your last snapshot (https://pastebin.com/d7HACCmg):
1. You were almost done channeling Arcane Missiles.
2. You had 1 stack of Clearcasting.
3. You had 0 Arcane Charges.
4. You had 18 stacks of Arcane Harmony.

Technically, the recommendation was to clip that last Arcane Missiles tick with Fire Blast (for reasons, don't worry about it).  Assuming I prevent that, going forward, it seems like you'd expect Arcane Missiles (you have Clearcasting, you don't have Arcane Charges to dump).  So here are the entries for Arcane Missiles, and since you mentioned Arcane Blast, I'll include it as well.

<table>
<tr>
	<td>List
	<td>Entry
    <td>Spell
	<td>Reason
<tr>
	<td>harmony
	<td>2
    <td>Arcane Missiles
	<td>( variable.stack_harmony[true] | time[205.82] < 10 ) & buff.arcane_harmony.stack[18.00] < 16
<br /><br />You have more than 16 stacks of Harmony.
<tr>
	<td>harmony
	<td>3
    <td>Arcane Missiles
	<td>equipped.empyreal_ordnance[false] & time[205.82] < 30 & toggle.cooldowns[true] & cooldown.empyreal_ordnance.remains[0.00] > 168 & ! action.empyreal_ordnance.disabled[false]
<br /><br />You don't have Empyreal Ordnance.
<tr>
	<td>harmony
	<td>19
    <td>Arcane Blast
	<td>variable.just_used_spark[false] | ( debuff.radiant_spark_vulnerability.up[false] & debuff.radiant_spark_vulnerability.stack[0.00] < debuff.radiant_spark_vulnerability.max_stack[5.00] )
<br /><br />You didn't just use Radiant Spark / Radiant Spark Vulnerability isn't applied.
<tr>
	<td>harmony
	<td>22
    <td>Arcane Missiles
	<td>buff.clearcasting.react[1.00] & buff.arcane_power.up[false]
<br /><br />Arcane Power isn't up.
<tr>
	<td>harmony
	<td>24
    <td>Arcane Blast
	<td>buff.presence_of_mind.up[false] & ( buff.arcane_charge.stack[0.00] < buff.arcane_charge.max_stack[4.00] | ! ( buff.power_infusion.up[false] & buff.bloodlust.up[false] ) )
<br /><br />You don't have Presence of Mind up.
<tr>
	<td>harmony
	<td>26
    <td>Arcane Missiles
	<td>buff.arcane_harmony.stack[18.00] < 16
<br /><br />Arcane Harmony is already stacked up.
<tr>
	<td>harmony
	<td>29
    <td>Arcane Blast
	<td>buff.arcane_charge.stack[0.00] & buff.arcane_charge.stack[0.00] < buff.arcane_charge.max_stack[4.00]
<br /><br />Arcane Blast is not used here unless you already have a charge and are building them up (intentional).
<tr>
	<td>harmony
	<td>30
    <td>Arcane Missiles
	<td>! ( variable.time_until_ap[0.00] <= 10 & mana.pct[28.00] < 30 )
<br /><br />Only used when AP won't be ready in 10 seconds or mana is over 30%.
</table>

When all of those failed, it falls back on Frostbolt (since it used Fire Blast already, and Frostbolt is basically the spell of last result).

Stacking Arcane Charges via Arcane Blast here, at low mana (28%), seems like a problematic choice when you're looking at a burst phase soon.

That's all the time I have for today.
