### ISSUE TITLE
[BUG] Keybind display sometimes incomplete/"forgets" modifier

### ISSUE THREAD

**Issue by alxbelu** [Hekili/hekili#1319]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Sometimes, seemingly only after some time in combat/a number of spells cast, the keybind display will be incorrect, specifically missing out any modifier (e.g. shift, ctrl, etc).

For example, I have actions keybound to 1,2,3,4,E then five more actions bound to shift+[1|2|3|4|E].
When starting a rotation, keybinds will show up correctly, but after a while, occasionally, modifiers will be lost in the display (e.g. only showing a number/letter e.g. "2" or "E" instead of "S2" or "SE").

First example, right after having cast multiple spells (note that the keybind display differs from the action bar on the bottom):
![1](https://user-images.githubusercontent.com/4905468/146829265-91afd3cc-e150-415c-a0a7-11830215fa68.jpg)
After waiting a couple of seconds, note that the revised recommendation for next spell did manage to include the modifier:
![2](https://user-images.githubusercontent.com/4905468/146829367-c59a1acc-e679-43a5-a39b-b53637bacd89.jpg)
And, so far, the only fix I've found is to e.g. shape-shift:
![3fixed](https://user-images.githubusercontent.com/4905468/146829514-cc0bde8d-86f9-46f5-b4df-0b92a686d839.jpg)

I'm using Bartender4 (and a few other addons, but this seemed like the most relevant). All addons up to date.

### How to Reproduce

1. Have spells keybound with modifiers (at least shift or ctrl)
2. Display keybinding in Hekili
3. Cast a number (>10) of offensive spells
4. Be confused.

### Player Information (Link)

https://pastebin.com/brnhnLfV

### Error Messages (Link)

no bugs reported in bugsack

**Comment by Hekili** [comment]
Hmm.

What abilities/forms are you using before it happens?  After which spells?  Are you using any abilities that are perceived by the game as a shapeshift otherwise?  Does it happen inside of Ascendance only (or outside of Ascendance only)?

Are specific spells impacted consistently or is it all of your spells?  If it's one spell or a few spells in particular, I can supply a macro to check what keybind information that addon has stored for those abilities in particular.  Then you can use the macro to gather more information for testing purposes.

Keybind detection is really finicky, the usual answer is that you can manually set the keybind text in /hekili > Abilities.

If you can provide snapshots (not screenshots) of the addon's recommendations when this happens, I can investigate a bit more.

**Comment by alxbelu** [comment]
Alright, did some more testing (many training dummies died to bring us this information):
1. Cannot identify any particular previous spell.
2. Do not have Ascendance skill, so so far only outside.
3. Spells consistently affected: Icefury, Echoing Shock, Earthquake. NOT affected: Concentrated flame, Chain Lightning, Earth Shock, Flame Shock, Frost Shock, Lava Burst, Lightning Bolt
4. Snapshot of one instance where the issue occured: https://pastebin.com/TUkLDrE4

Happy to test out with macros if you think there might be potential for a fix, otherwise I guess I could also simply hardcode the keybinds as suggested.

(edit regarding point 3; this was based on shifting spells around and trying for "a while", obviously can't say any spells will never be affected...)

**Comment by Hekili** [comment]
I'm going to trust that you've hardcoded your bindings by now.  If this is persistently an issue, feel free to reopen and submit your Bartender keybindings.
