### ISSUE TITLE
Druid/Balance - Venthyr, CDs are not recommended at all.

### ISSUE THREAD

**Issue by marekCs** [Hekili/hekili#1322]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Unless I manually press Celestial Alignment myself, CDs are not recommended, I mean Venthyr covenant abilities, Celestial Alignment, trinkets, Berserking. It only works on Venthyr dummies, it's fine there. As soon as I start a fight elsewhere, nothing happens, just basic rotation. Toogles CDs are of course ON. If I manually press Celestial Alignment, the other CDs then run in sequence nicely and go on a nice burst.

### How to Reproduce

Go Balance druid as a Venthyr, fight in Maw or daily world quests.

### Snapshot (Link)

https://pastebin.com/7b7RKa83

### Additional Information

With Night Fae is everything ok

### Contact Information

Markô#2877

**Comment by Hekili** [comment]
Celestial Alignment's complete conditions:

```
variable.cd_condition_st[false] & ( buff.ca_inc.duration[20.00] >= 32 | ! covenant.venthyr[true] ) | 
buff.ravenous_frenzy.up[false] & buff.ravenous_frenzy.remains[0.00] < 9 + conduit.precise_alignment.time_value[0.00] + ( ! buff.bloodlust.up[false] & ! talent.starlord.enabled[false] )
```

This means CA is recommended when:
* `cd_condition_st` is `true` and either (1) Celestial Alignment's duration would be 32 or more (from a conduit) or (2) you're not Venthyr; **OR**
* Ravenous Frenzy is up, has fewer than 9 seconds (+ Precise Alignment's CA duration buff) + 1 second if Bloodlust is down and you don't have Starlord.

As written, this is never going to pass in your current gear -- you'd need Precise Alignment maxed out for the first condition to ever work as a Venthyr.

I'll check if this is something resolved in simc and I just need to update, or if there's more complexity to it.

Can you complete the Raidbots Sim Report link?  Sim your character as Venthyr, just like your setup from the snapshot, in a Patchwerk fight.  That'll help me find anything that's out of alignment.

**Comment by marekCs** [comment]
There is the sim from [raidbots](https://www.raidbots.com/simbot/report/wTzUs3HUjsBzDYBXG6u6ZF)

**Comment by Hekili** [comment]
Thanks.

Looking now, it looks like the sim uses Ravenous Frenzy before Celestial Alignment in a way the addon isn't matching.  I'll keep investigating.

**Comment by marekCs** [comment]
thanks a lot, believe me I am not the only Balance who solves this problem, so this will help many people :)

**Comment by Hekili** [comment]
So, the sim used Ravenous Frenzy before hitting Celestial Alignment, but the addon didn't recommend Ravenous Frenzy.

```
41.  ravenous_frenzy ( st - 13 )
The action (ravenous_frenzy) is usable at (2.42 + 0.00).
 - the action is ready before the current recommendation (at +0.00 vs. +10.00).
List ( st ) called from ( Balance:default:21 ) would PASS at 0.00.
NONE
 - this entry's criteria FAILS: buff.ca_inc.remains[0.00] > 15 | buff.ca_inc.duration[20.00] < 32 & variable.cd_condition_st[false]
```

Ravenous Frenzy doesn't get used by the addon, here, because it requires:
 * Celestial Alignment has 15 seconds remaining (i.e., you used it, but the sim is using RF first for you); **OR**
 * Celestial Alignment's total duration would be < 32 seconds and the `cd_condition_st` variable is `true`.

In your case, we need `cd_condition_st` to be true.  In your sim, it's occasionally true but in the addon it's not true in your case.  For reading snapshots, it helps to know that `!` means "not" and `|` means "or" and `&` means "and."  I've broken the snapshot conditions into pieces here, but I'll translate below.

```
! druid.no_cds[false] & variable.cd_condition[true] & (
    ( cooldown.empyreal_ordnance.remains[0.00] < 167 + ( 11 * runeforge.sinful_hysteria.enabled[false] ) & equipped.empyreal_ordnance[false] ) | 
    astral_power.current[62.00] >= 90 & (
        ! talent.fury_of_elune.enabled[true] | 
        buff.ca_inc.duration[20.00] > cooldown.fury_of_elune.remains[0.00] + 8
    ) & dot.sunfire.remains[1.62] > 8 & dot.moonfire.remains[4.31] > 9 & (
        dot.stellar_flare.remains[0.00] > 10 |
        ! talent.stellar_flare.enabled[false]
    ) & variable.thrill_seeker_wait[false] & ( 
        buff.kindred_empowerment_energize.up[false] |
        ! covenant.kyrian[false]
    ) & target.time_to_die[2.58] > buff.ca_inc.duration[20.00] * 0.7 |
    boss[false] & fight_remains[2.58] < buff.ca_inc.duration[20.00] |
    covenant.night_fae[false] |
    buff.bloodlust.up[false] & buff.bloodlust.remains[0.00] < buff.ca_inc.duration[20.00] + ( 9 * runeforge.primordial_arcanic_pulsar.equipped[false] )
) & ! buff.ca_inc.up[false] & (
    ! covenant.night_fae[false] |
    cooldown.convoke_the_spirits.up[true] |
    boss[false] & fight_remains[2.58] < cooldown.convoke_the_spirits.remains[0.00] + 6 |
    boss[false] & fight_remains[2.58] % 180 < buff.ca_inc.duration[20.00]
)
```

So, this is a lot.  I'll try to break it down, for you and for me:

<table>
<tr>
	<td colspan=2>#
	<td>Description
	<td>Pass
<tr>
	<td>1
	<td>
	<td>CDs are toggled on and <b>cd_condition</b> variable is <b>true</b>; <b>AND</b>
	<td>Yes
<tr>
	<td>
	<td colspan=3>Any of A, B, C, D, or E...
<tr>
	<td>
	<td>A
	<td>You have Empyreal Ordnance (nope) and it was recently used to sync up with CA; <b>OR</b>
	<td>No
<tr>
	<td>
	<td>B
	<td colspan=2><b>ALL of the following...</b>
<tr>
	<td>
	<td>
	<td>You have 90 AP (nope) and either didn't talent Fury of Elune (nope) or CA would last FoE's CD + 8 seconds (yep); <b>AND</b>
	<td>No
<tr>
	<td>
	<td>
	<td>Sunfire has 8+ seconds remaining (nope), Moonfire has 9+ seconds remaining (nope), and Stellar Flare has 10+ seconds remaining (nope) or you didn't talent for Stellar Flare (yep); <b>AND</b>
	<td>No
<tr>
	<td>
	<td>
	<td><b>thrill_seeker_wait</b> variable is <b>true</B> (nope) and either Kindred Empowerment is active (nope) or you're not Kyrian (yep); <b>AND</b>
	<td>No
<tr>
	<td>
	<td>
	<td>Your current target will live for 70% of a Celestial Alignment's duration (nope); <b>OR</b>
	<td>No
<tr>
	<td>
	<td>C
	<td>You're in a boss fight (nope) that will end within a Celestial Alignment's duration (yep); <b>OR</b>
    <td>No
<tr>
	<td>
	<td>D
	<td>You're Night Fae (nope); <b>OR</b>
	<td>No
<tr>
	<td>
	<td>E
	<td>Bloodlust is up (nope) and will expire during Celestial Alignment.
	<td>No
<tr>
	<td>2
	<td>
	<td>Celestial Alignment is down (yep); <b>AND</b>
	<td>Yes
<tr>
	<td>
	<td colspan=3>Any of W, X, Y, or Z...
<tr>
	<td>
	<td>W
	<td>You're not Night Fae (yep); <b>OR</b>
	<td>Yes
<tr>
	<td>
	<td>X
	<td>Convoke the Spirits is ready (yep, if you were Fae); <b>OR</b>
	<td>Yes
<tr>
	<td>
	<td>Y
	<td>You're in a boss fight (nope) and the fight will end within Convoke's CD + duration (n/a); <b>OR</b>
	<td>No
<tr>
	<td>
	<td>Z
	<td>You're in a boss fight (nope) and you'd need to use CA now to avoid wasting a cast of CA before the end of the fight (n/a).
	<td>No
</table>

So, for Ravenous Frenzy to get recommended here, we need 1 + any of A/B/C/D/E + 2 + any of W/X/Y/Z.  We have 1 and 2 and W and X.  That means I have to figure out which of A/B/C/D/E is successful in sim but not in the addon.

**A** requires a trinket you don't have, so we can ignore.

**B** would require:
 * 90+ AP (which is true in the sim) 
 * Sunfire and Moonfire to be refreshed (they're both low in your snapshot, but would've been cast 7-8 seconds ago in the sim)
 * `thrill_seeker_wait` is about timing Nadija's Euphoria proc, and you have only 11 stacks so this would take a long while
 * Your current target to live longer so using CA would hypothetically be worth it

If the conditions for B are routinely not met, that implies that the priority logic is spending down your AP when it could be used for CDs or that Sunfire/Moonfire aren't refreshed frequently enough to create a window for Ravenous + Celestial Alignment.

**C** requires you to be in a boss fight that is about to end so we're burning CDs.

**D** would work if you were Night Fae, but that's not what we're troubleshooting.

**E** would require Bloodlust to be up and for us to want to burn CDs before its over.

I can investigate this a bit further, and might resim your character a bit (i.e., without Bloodlust, with changes to thrill_seeker_wait) and see if that clarifies anything.  For **C**, requiring a boss fight is an addon change vs. SimulationCraft, because burning CDs at the end of every trash pack would not be great for M+.

- [x] Check sim without Bloodlust.
- [x] Check sim with Thrill Seeker bypassed.

Could you try to generate a new snapshot, but build AP up to 90+ and refresh Sunfire and Moonfire so they have quite a bit of time left?  If you do it vs. a target dummy, that may help as well since they'll live forever.

**Comment by Hekili** [comment]
Okay, so I realize your initial sim didn't have Bloodlust, so that was easy.

I do think I broke `thrill_seeker_wait` when I tried to put in "don't waste CDs" logic, but that change is 5 months old.  I'll remove it and we'll see if that makes a difference.  For future snapshots, we'll definitely want to confirm that you have 90 AP and that Moonfire and Sunfire are fresh as well.

**Comment by marekCs** [comment]
Fantastic! :-D Thank you so much. I can't wait to try the modified version

**Comment by Hekili** [comment]
This may be resolved in the latest release.
