### ISSUE TITLE
[REC] Tiger Palm never suggested for Brewmaster

### ISSUE THREAD

**Issue by CR82** [Hekili/hekili#1325]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For Brewmaster I expect Hekili to recommend Tiger Palm.

### How to Reproduce

1. Enter game as Brewmaster Monk
2. Fight

### Snapshot (Link)

https://pastebin.com/z3UNWbZc

**Comment by Hekili** [comment]
Sim yourself and provide the Raidbots link, please.

**Comment by CR82** [comment]
I don't understand why I should Sim myself. Is this (no Tiger Palm in rotation) working as intended?

**Comment by Hekili** [comment]
> I don't understand why I should Sim myself.

The ticket instructions explained why.

> The addon's recommendations are based on the SimulationCraft profiles generated for each specialization. It is very helpful, for testing purposes, to compare the addon's recommendations to your sim's actions. Raidbots is the fastest, easiest way to simulate your character.
> *    If the issue happens in single-target, link to your Patchwerk sim with 1 boss target.
> *    If the issue happens in sustained multi-target, link to your Patchwerk sim with the appropriate number of boss targets.
> *    If the issue happens in more chaotic scenarios, link to your Hectic Add Cleave sim with 1 boss target.
> *    You're welcome to link multiple sims using the Additional Information box, below.

I asked for it again for the same reasons.

> Is this (no Tiger Palm in rotation) working as intended?

There are two entries for Tiger Palm in the priority.  If you don't see Tiger Palm, it's because the conditions aren't met.

One entry is only used with RJW + Blackout Combo talented (so not for you).

The other entry is only used without Blackout Combo talented (so also wouldn't work for you).

Yes, it's pretty odd to have Blackout Combo and never end up using TP.  However, verifying whether the issue exists in the sim profile or not, and then using the sim to figure out what the usage *should* look like, is generally what would drive fixes or changes.

**Comment by CR82** [comment]
Works as intended.

**Comment by Hekili** [comment]
FWIW, I talked with emallson who is a BrM theorycrafter and not using Tiger Palm is *mostly* working as intended, but it does appear to be an oversight that the sim profile doesn't use it to maintain Eye of the Tiger if you have that talent.  So you may see changes to both the sim and the addon that involve using Tiger Palm under those circumstances.

Otherwise, Spinning Crane Kick just generally outperforms Tiger Palm unless you explicitly need to force your brew CDs to recover more quickly.
