### ISSUE TITLE
Warlock/Demo/Night Fae - GetTotemInfo not showing Vilefiend, Grimoire Felguard demons

### ISSUE THREAD

**Issue by marekCs** [Hekili/hekili#1327]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Addon doesn't want to recommend the "Summon Demonic Tyrant" spell and the resulting dps is about 1.8k less than it should be because Tyrant is the main damager.

### How to Reproduce

Enter game as Demo with Night Fae and without legendary.
Go single target dummy.

### Snapshot (Link)

https://pastebin.com/0gEq3Zn4

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/dPRRj3HMVkyPqQEKRnmPgX

### Contact Information

Markô#2877

**Comment by Hekili** [comment]
In that snapshot, you missed your window to extend basically all of your demons:

```
 - this entry's criteria FAILS: time[84.40] > variable.first_tyrant_time[12.00] & ( pet.dreadstalker.active[true] & pet.dreadstalker.remains[0.92] > action.summon_demonic_tyrant.execute_time[1.61] ) & ( ! talent.summon_vilefiend.enabled[true] | pet.vilefiend.active[false] ) & ( soul_shard[3.00] = 0 | ( pet.dreadstalker.active[true] & pet.dreadstalker.remains[0.92] < action.summon_demonic_tyrant.execute_time[1.61] + action.shadow_bolt.execute_time[1.61] ) | ( pet.vilefiend.active[false] & pet.vilefiend.remains[0.00] < action.summon_demonic_tyrant.execute_time[1.61] + action.shadow_bolt.execute_time[1.61] ) | ( buff.grimoire_felguard.up[false] & buff.grimoire_felguard.remains[0.00] < action.summon_demonic_tyrant.execute_time[1.61] + action.shadow_bolt.execute_time[1.61] ) )
 ```

1. Your Dreadstalkers will expire before you could finish casting Tyrant.
2. Your Vilefiend is not up.
3. Your Grimoire Felguard is not up.

Your next Vilefiend is available in 11.32 seconds and your next Dreadstalkers will be available in 9.86 seconds.  Tyrant will be recommended when you have demons up that are worth extending.  It looks like you probably pulled with your CDs out of sync, so the addon let you cast Vilefiend and keep going out of sync.  I can potentially put in logic to mitigate this, but for dummy testing purposes, you probably want to pull with your CDs ready to go anyway.

In your sim, you can see that it manages to cast Tyrant every 94ish seconds, *but* that's conveniently lined up with Vilefiend -- your sims CDs are always lined up at the start.

**Comment by marekCs** [comment]
Unfortunately, all my CDs were ready at the beginning of the pull. So should I manually fire some of my CDs at the beginning as prepull? Just learning Demo.

**Comment by Hekili** [comment]
No, if the goal is to make sure you use your Tyrant when it can extend your more powerful demons, desynchronizing CDs further will do the opposite of help.

Demonology, especially with your talents, is about syncing demons with Tyrant to get a super strong Tyrant by way of Demonic Consumption.

Your sim casts Dreadstalkers, Felguard, Vilefiend, and Tyrant at the following times.

<table>
<tr>
	<td>#
	<td>Time
	<td>Spell
	<td>Ends
<tr>
	<td>1
	<td>0:01.2
	<td>Grimoire Felguard (17s)
	<td>0:18.2
<tr>
	<td>2
	<td>0:02.4
	<td>Summon Vilefiend (15s)
	<td><b>0:17.4</b>
<tr>
	<td>3
	<td>0:07.2
	<td>Call Dreadstalkers (12s)
	<td>0:19.2
<tr>
	<td colspan=4>So, from the above, you can see that the window for Summon Demonic Tyrant to be *finished casting* closes at 0:17.4 -- if our Tyrant cast lands after that time, we missed the opportunity to extend Vilefiend and lost some of our buff for our Tyrant.
<tr>
	<td>4
	<td>0:10.8
	<td>Summon Demonic Tyrant (15s)
	<td>0:25.8
<tr>
	<td colspan=4>Based on the cast time for Tyrant, you can see the sim's initial cast would be done at about 0:12.4 seconds into the fight, so all of these demons got extended and we got a nice Demonic Consumption buff.  (It could've technically been better if we generated a few more imps, but we would've had 5 seconds to generate shards and then spend with Hand of Gul'dan...  We could've added 1-2 imps at most without missing the window where Vilefiend is still up.<br><br>I'll skip ahead a bit now.
<tr>
	<td>5
	<td>0:49.3
	<td>Summon Vilefiend
	<td>1:04.3
<tr>
	<td>6
	<td>0:52.5
	<td>Call Dreadstalkers
	<td>1:04.5
<tr>
	<td colspan=4>So, at this point, we used Vilefiend because we knew Tyrant wouldn't be available any time soon.  Even though there's a good overlap here (and Grimoire Felguard is a 2 minute CD, so won't line up here at all), we obviously can't cast Summon Demonic Tyrant until around 1:40 into the fight (90 seconds after we cast it).<br><br>I'll skip to our next demon window where Tyrant will be available.
<tr>
	<td>7
	<td>1:34.4
	<td>Call Dreadstalkers
	<td><b>1:46.4</b>
<tr>
	<td>8
	<td>1:36.8
	<td>Summon Vilefiend
	<td>1:51.8
<tr>
	<td>9
	<td>1:43.2
	<td>Summon Demonic Tyrant
	<td>1:58.2
<tr>
	<td colspan=4>Okay, so our next demon window, assuming similar proc rates to this particular sim, started at 1:34.4 and lasted until 1:46.4 -- the window opened with Call Dreadstalkers.  Vilefiend was summoned inside that window, and Summon Demonic Tyrant's cast finished at 1:44.8 (meaning it was finished with about 1.6 seconds left in the window where both Dreadstalkers and Vilefiend would be extended).
</table>

**Let's look at your snapshot.**

You have 2 Dreadstalkers who will be up for 2.22 seconds.  Your Vilefiend is down, your Grimoire Felguard is down.  You have 6 Wild Imps.

You're casting Shadow Bolt and that cast finishes in 1.3 seconds.  When that cast is finished, you'll have been in combat for 84.4 seconds, total.

Grimoire Felguard is off cooldown in ~36.5 seconds.
Summon Vilefiend is off cooldown in ~11.3 seconds.
Call Dreadstalkers is off cooldown in ~9.86 seconds.
Summon Demonic Tyrant is off cooldown *now*.

For Summon Demonic Tyrant to be off cooldown now (when you don't have any CDR effects), you would've never cast Summon Demonic Tyrant even in your opener.  If that's the case, the problem was 70+ seconds ago -- you missed your initial Tyrant window somehow.  To investigate that, we'll need another snapshot taken during your opener, after you've cast Call Dreadstalkers, Summon Vilefiend, and Grimoire Felguard -- when they are all still up.  I'd recommend getting a snapshot before 0:12 and after 0:12 (due to some nuances with how the priority is written).

If you don't have Tyrant recommended when all of those demons are active, it'd be suspicious and indicate a bug.

If you miss that initial Tyrant window due to lag/latency/mechanics/error, the next time the addon would've presented it would've been the period after numbers 5 and 6 in the table above, because you'd have Vilefiend and Dreadstalkers ready to be extended again.

The only other complicating factor that I can see is that the priority generally wants you to spend all your Soul Shards before Summon Demonic Tyrant (because you get 5 shards and because this also helps you maximize Imps).  However, it shouldn't really be a problem because the criteria for Tyrant will still have you summon if a major demon would otherwise fall off.

So, assuming you're starting from all CDs being available, to investigate further, I'll need:
- [x] Snapshot from 0:10 -- you should have Dreadstalkers, Felguard, and Vilefiend all up at this time.
- [x] Snapshot from 0:13 -- The above should still be true, and the addon should recommend Tyrant around now or no later than 0:15, because the window to extend your Vilefiend is closing.

If Tyrant isn't recommended in that initial window, then:
- [x] Snapshot from 0:55 - 1:00 :: Somewhere in this window, you should have Dreadstalkers and Vilefiend up and Summon Demonic Tyrant should've been recommended.

**Comment by marekCs** [comment]
Hello again, ok I did it:

10 sec: [https://pastebin.com/UTNz8v0h](https://pastebin.com/UTNz8v0h)
13 sec: [https://pastebin.com/28YrL2GC](https://pastebin.com/28YrL2GC)
44 sec: [https://pastebin.com/7neQ0uJg](https://pastebin.com/7neQ0uJg)
63 sec: [https://pastebin.com/T40cYvKx](https://pastebin.com/T40cYvKx)

I'm wondering if this (and similar reports from other users and other classes) is related to characters not being fully geared yet, not having full stats, not having max conduits, or not having a legendary. But it would be nice if the algorithm took these facts into account :)

**Comment by Hekili** [comment]
> I'm wondering if this (and similar reports from other users and other classes) is related to characters not being fully geared yet, not having full stats, not having max conduits, or not having a legendary.

No. 

For the first snapshot, the addon is not seeing that your Vilefiend is up for some reason. I'll investigate.

**Comment by marekCs** [comment]
Ok I will make wa for check the spell ID if weakauras can see that’s on CD or not. Let you know soon.

**Comment by Hekili** [comment]
What would be helpful is a screenshot of your UI when Vilefiend is up. If your UI shows totems, I should see Vilefiend there.

**Comment by marekCs** [comment]
Ok will do.

**Comment by marekCs** [comment]
I sent you a direct message on DC with photos.

**Comment by marekCs** [comment]
The code output of 
`/run for i = 1,5 do print( GetTotemInfo( i ) ) end`
was:
true nil 96455 12 1378282
false 0 0
false 0 0
false 0 0
false 0 0

**Comment by marekCs** [comment]
btw how do I know that the wow api system has registered that the viefiend is out, should I have the icon of Vilefiend somewhere under dummy icon? /edit I can see "Bile Spit" icon applied on dummy

**Comment by Hekili** [comment]
I mean, it's not something you're supposed to worry about -- but that macro is checking the API.  In normal UIs, they are shown the same as totems.

If you ran that macro with your Vilefiend active and your Grimoire Felguard (remember, I said use it after your big demons are out) then something is odd.  The first line there is your Dreadstalkers.  Neither your Grimoire Felguard nor your Vilefiend are listed.

**Comment by Hekili** [comment]
Sorry, just to be clear -- can you confirm that you ran that macro when your other demons were actually summoned?  I.e., Vilefiend is actually active (along with Grimoire Felguard, if talented) at the time you ran the macro.

**Comment by Hekili** [comment]
> 10 sec: pastebin.com/UTNz8v0h

This snapshot shows that you have 2 Dreadstalkers with 9.32 second remaining.  It shows no Vilefiend, no Grimoire Felguard, and no Wild Imps.

This doesn't make sense, given that your Grimoire Felguard is on cooldown for ~108.51 more seconds and your Vilefiend is on CD for ~36.32 more seconds.  That means both should be active.

This suggests that all the events that are managed to track these are simply not being detected.  Do you have BugSack and/or BugGrabber installed?  If so, are there any errors captured from the addon?  If not, install them and reload your UI and see what is caught.

If you turn off your other addons and just use Hekili, do you see a difference?

> 13 sec: pastebin.com/28YrL2GC
> 44 sec: pastebin.com/7neQ0uJg
> 63 sec: pastebin.com/T40cYvKx

None of these snapshots see your Vilefiend or Grimoire Felguard as being active.  Some show your Dreadstalkers as active.

**Comment by Hekili** [comment]
Hi, can you look at the previous two responses and answer any questions left unresolved?  Thanks!

**Comment by marekCs** [comment]
Yeah sorry I will make it again with your recommendation and let you know.

**Comment by marekCs** [comment]
Almost same result:
true nil 29120 12 1378282
false 0 0
false 0 0
false 0 0
false 0 0

The debug addons didn't show anything, or I don't know how to use them, I just installed them.

Anyway, I'll close the ticket because I decided not to play Demonology and I was the only one who had a problem with it. I don't have time for more tests. Thank you.

**Comment by Hekili** [comment]
> Almost same result:
> true nil 29120 12 1378282
> false 0 0
> false 0 0
> false 0 0
> false 0 0

This is again just showing you have Dreadstalkers out.  Can you confirm (again) that Vilefiend and Grimoire Felguard were active when you ran the macro?

> The debug addons didn't show anything, or I don't know how to use them, I just installed them.

If there were UI errors, the BugSack addon's icon would be red, and clicking on it would show any error messages.

> Anyway, I'll close the ticket because I decided not to play Demonology and I was the only one who had a problem with it. I don't have time for more tests. Thank you.

I'm going to have to find info about this at some point.  The other thing you didn't test, as far as I can tell, is to run the addon by itself (no other addons loaded) to see if that changed the result.  You're not obligated to continue testing, of course.

**Comment by marekCs** [comment]
> This is again just showing you have Dreadstalkers out. Can you confirm (again) that Vilefiend and Grimoire Felguard were active when you ran the macro?

Yes, I confirm. Both out.

I actually didn't even notice the icon, so I'm going to try again. I'll turn off the addons as well.

**Comment by Hekili** [comment]
Thanks for checking.  Are you using a different client language or anything?

> true nil 29120 12 1378282

That `nil` should be `"Dreadstalker"` -- it really makes me thing something outside the addon is overwriting `GetTotemInfo` in the global table.

![image](https://user-images.githubusercontent.com/9438134/148108511-a5708d4d-ab54-43a4-b639-362a3434173e.png)

**Comment by marekCs** [comment]
Well. Now I was thinking, it's a private server, couldn't it be that they have spells called differently, under a different spellID?

I did tests again with same result, no errors (just one Zygor guide).

**Comment by SpatenLa** [comment]
just burn him down.

**Comment by Hekili** [comment]
> Now I was thinking, it's a private server, couldn't it be that they have spells called differently, under a different spellID?

Private servers aren't the same as live servers, no, and I don't offer any support for private servers.  That really ought to have been pointed out from the start.
