### ISSUE TITLE
Issue with Masque addon

### ISSUE THREAD

**Issue by blecaplol** [Hekili/hekili#1344]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The skin will not stay and I delete both addons saved variables.

 I click enable twice on the addon on the minimap not a /reload and it got skinned but it is not persistent on /reload or entering the world, or loading into anotehr instance anything that invoke a loading screen.
 
 https://github.com/SFX-WoW/Masque/issues/157

### How to Reproduce

select the skin, for me Dream and then reload again. It went back to default now. 

### Snapshot (Link)

https://github.com/SFX-WoW/Masque/issues/157

**Comment by Hekili** [comment]
This is not the correct type of ticket.

You might try using an older Shadowlands version of Hekili and see if the issue persists with the old version.

If you find a version of Hekili where this works, you can tell me the version number and I can compare changes.

If you can't find a version of Hekili that plays well with Masque, it's probably a Masque issue.  (You could try the same thing; test with older versions of Masque.)

I'll look into this a bit, but you should resubmit this as a bug report, because this is not about the addon's recommendations.  Make sure to include the required information from that ticket.
