### ISSUE TITLE
[REC] Addon is recommending me to use Flame Shock on a target that already has it.

### ISSUE THREAD

**Issue by cfervir** [Hekili/hekili#1356]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The addon will sometimes recommend/flash the icon of Flame Shock for half a second or something like that when there are another buttons available to press (rare) or when they are "about to be available". One of those skills that are usually available are Sundering or Crash Lighting. I also noticed that it happens when Fire Nova is about to be ready, to give you an example of skills but I suppose it may happen with any.

In my case I can expect for the icon to appear and the addon to recommend it if there's nothing else to cast for a half a second, a second or something like that but if another skill is about to be ready and this happens I feel it may just confuse the player (it does to me as I might end clicking it by mistake and wasting a GCD).

### How to Reproduce

1.- Set spec to Enhancement.
2.- Get in front of a Dummy.
3.- Follow recommendations.
4.- Sometimes it will recommend what I stated before.

### Player Information (Link)

https://pastebin.com/dE2zPWSV

### Error Messages (Link)

No error!

### Additional Information

I took two snapshots, but I don't know if they actually worked because of time sensitivity (as it's really fast).

https://pastebin.com/1hahZJi0
https://pastebin.com/z6XVU8kC

I also took a video but I doubt I'll able to upload it here.

### Contact Information

BigBadLion#2348

**Comment by cfervir** [comment]
The video is here:

https://imgur.com/a/LKkootU

The recommendation happens when there are around 4 seconds left for the video to end Stormstrike is about to come out of CD (CL too).

**Comment by Hekili** [comment]
This is an issue with the addon's recommendations, so you should've filled out that template. Thanks for the snapshots. In both cases, the addon was recommending Lava Lash. You have to take the snapshots at the time you are seeing the Flame Shock and you think you shouldn't.

**Comment by cfervir** [comment]
Sorry about that, if needed perhaps we should close this and I should make another one? I just changed the title but I don't know if it might actually work.

Besides that I managed to get two Snapshots of FS, I'm not very sure about the first one but the 2nd one was more "close" to have another ability ready to cast.

https://pastebin.com/9gX6nhjJ
https://pastebin.com/8w8MJXQk

**Comment by Hekili** [comment]
> Sorry about that, if needed perhaps we should close this and I should make another one? I just changed the title but I don't know if it might actually work.

No need to do it.  You included the snapshots which is the most critical piece.  I appreciate it.

> [pastebin.com/9gX6nhjJ](https://pastebin.com/9gX6nhjJ)

So the above snapshot has 0.11 seconds left on the global cooldown.  The addon goes down the priority list and looks for when each ability will be ready and whether its conditions are met.

The first one it finds is Stormstrike (list = `single`, entry = `23`).  It would be ready in 1.61 seconds.  Its only requirement is that the `single` list would run (with one active enemy), so that requirement is met.  It holds that recommendation and looks to see what else is available sooner (i.e., anything on CD for more than 1.61 seconds is not considered).

The next option it finds is Flame Shock (`single`, `36`).  It is ready in 0.11 seconds.  It has the same criteria as Stormstrike (none, except that there's one active enemy), because this is low priority filler.  Since 0.11 is significantly later than 1.61, the addon decides to recommend Flame Shock vs. doing nothing for 1.61 seconds waiting for Stormstrike.

The Flame Shock entry was added intentionally.  It appears to be used around 3-4 times in a 5 minute fight in pure single-target.  The DPS increase is marginal, however.  Overall, it does reduce downtime or "waiting" time from above 1% to below 1%.

Sim:  https://www.raidbots.com/simbot/report/4EfDAZdDocPjX6GUxwBv2v

> [pastebin.com/8w8MJXQk](https://pastebin.com/8w8MJXQk)

This snapshot used the same Stormstrike entry first, with it ready in 2.47 seconds.  Then it found Lava Lash (`single`, `27) -- same conditions -- was ready in 0.47 seconds, so it planned to recommend Lava Lash unless something else was available sooner.  Finally, Flame Shock was ready immediately so it was chosen.

It's possible that additional sim tuning could be done, but 13 DPS basically statistical noise.  I may add an option that disables that filler Flame Shock as a matter of preference.

I tried more tests where the filler Flame Shock would only get recommended if both Stormstrike/Windstrike and Lava Lash would be on CD for at least 0.5 seconds.  Same basic result.

https://www.raidbots.com/simbot/report/j2SNFKjHnuyGPjKdyUqyX1

https://www.raidbots.com/simbot/report/5CeHQ4E7ezG1HXBYsZVT89

**Comment by cfervir** [comment]
I see,

I know the video is meaningless but if you see it in general the "time" Flame Shock will be available feels like less than a second and it being shown could make a confusion. May I add as well that I play with more "lag" than most ppl and that's perhaps why I see these things more "close" than what it may be?

Perhaps the option to disable Flame Shock as a filler could be a good plan? Just to avoid "confusions" specially because the numbers are just statistical noise as you said.

Also, is it OK as well for the addon to recommend Flame Shock before Primordial Wave at the very start? I don't know if I should add a snapshot for that considering it just happens at the very start of the fight.

**Comment by Hekili** [comment]
> I know the video is meaningless but if you see it in general the "time" Flame Shock will be available feels like less than a second and it being shown could make a confusion. May I add as well that I play with more "lag" than most ppl and that's perhaps why I see these things more "close" than what it may be?

In your video, it looks like Flame Shock and Stormstrike coming off CD would've been very close, and that Stormbringer may have procced at the last second to push Stormstrike ahead.  The addon can see if Stormbringer *has* procced, but it can't predict if Stormbringer *will* proc.

> Perhaps the option to disable Flame Shock as a filler could be a good plan? Just to avoid "confusions" specially because the numbers are just statistical noise as you said.

That's what I said.  "I may add an option that disables that filler Flame Shock as a matter of preference."

> Also, is it OK as well for the addon to recommend Flame Shock before Primordial Wave at the very start? I don't know if I should add a snapshot for that considering it just happens at the very start of the fight.

If you want to know why something was recommended at a specific time, a snapshot is how you can tell.

**Comment by cfervir** [comment]
In the video both things happened at the same second, or very close to it seems. An ability was about to be ready and then it procced. FS was just limited by the GCD as it was available before. I know Hekili can't predict a proc, because that's how things are but yeah.

The other option, well. I was just kinda repeating you. Sorry for that!

As for the other recommendation. Here´s a snapshot, I just placed my WF Totem and pretty much everything is available. Primordial Wave and Flame Shock have the same range too. It just feels weird (at least to me) to recommend FS and then PW.

https://pastebin.com/HjFdns87

**Comment by Hekili** [comment]
For the PWave question, it looks like it would be about a ~54 DPS increase to PWave (and then not need to Flame Shock).  That's not a lot, but it's greater than the margin of error.  I'll bring it up with the Enhancement simc crew, but that will likely get built in.

https://www.raidbots.com/simbot/report/hQ8wqg28JsMrKbovc7XBJK

For your video, it does look like Flame Shock and Stormstrike did come off cooldown very close together -- I don't see Stormbringer's .  If you'd snapshotted in that situation, it would tell us how close Stormstrike was to being off CD vs. Flame Shock.  For an entry lower in the priority to be recommended, the lower priority spell has to be ready at least 0.05 seconds sooner.

I can potentially expose options that would change that 0.05s value.  I'll think about it.

**Comment by cfervir** [comment]
I'll try to get another snapshot (like the one I got in the video) but to be honest I don't know if I'll get lucky enough to get it. After all, if you see it the icon of Flame Shock barely shows... but who knows!

Regardless, Flame Shock appears and I believe it'd be better if it didn't in a situation like that one as it may confuse the person (and click it when another option could be better).

Thanks by the way for your huge work, you and everyone else <3

**Comment by Hekili** [comment]
The good news from sim testing is that it doesn't matter in the larger context -- it washes out in aggregate that you cast Flame Shock when Stormstrike would've been ready in a tenth of a second.  It feels bad in that moment, but overall it doesn't matter.

> I'll try to get another snapshot (like the one I got in the video) but to be honest I don't know if I'll get lucky enough to get it. After all, if you see it the icon of Flame Shock barely shows... but who knows!

I mean, you have the answer for it.  Their CDs are very close.  It may happen to you more due to latency causing your casts to happen slightly behind the GCD.  As it stands, it's not a bug.  I'm going to close the ticket, but I'll let you know if I change some options to give more control over that window/delay.

Thanks!

**Comment by cfervir** [comment]
Thanks again! Let me know if anything happens <3
