### ISSUE TITLE
Getting spammed by Snapshots being created on Enhancement Shaman

### ISSUE THREAD

**Issue by Sratarak** [Hekili/hekili#1365]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Every time I even select a target or am in combat, Hekili is taking a screenshot and a snapshot for the interrupt order.

### How to Reproduce

Enter the game as an enhancement shaman
Select a target, watch the spam!
Turned Interrupt priority off, was being spammed for the AoE one.

I got up to 419 Interrupts and ~200 AoE Snapshots in about 5 minutes

https://pastebin.com/vwN53934

### Player Information (Link)

https://pastebin.com/QNz8HWXQ

### Error Messages (Link)

https://pastebin.com/vwN53934

**Comment by Hekili** [comment]
I don't know how you'd get multiple auto-snapshots in one episode of combat, but I put in a fix so that autosnapshots only happen if the Primary or AOE displays have an issue.

If you are still having this issue with 1.0.3c, I need you to check for actual error messages -- not snapshots.  You can check /hekili and see if there's a Warnings section and copy or screenshot if there are messages there.

If you do get an automatic snapshot, I need one from each display, because the AOE snapshots you posted don't have anything wrong.  So I'd want the Interrupts one (I assume) since that'd be the one that didn't display anything.

Thanks!

**Comment by Sratarak** [comment]
Sorry, I thought I'd posted one of the interrupts one's as well!

https://pastebin.com/RL1mFjyj

This is one of the interrupts one
![WoWScrnShot_022722_075043](https://user-images.githubusercontent.com/73387882/155874301-fa6d855d-d8eb-460f-a860-c80a0b18d568.jpg)
![WoWScrnShot_022722_073350](https://user-images.githubusercontent.com/73387882/155874307-3c8ae318-3ac9-4bc8-922d-51e8399fc5ca.jpg)
.
![WoWScrnShot_022722_073351](https://user-images.githubusercontent.com/73387882/155874322-89dcfc73-8c85-4bfb-93b1-c7566212b7f8.jpg)
![WoWScrnShot_022722_073352](https://user-images.githubusercontent.com/73387882/155874326-36e13098-23fb-4872-963b-09aab8905119.jpg)


First three screenshot taken, last screenshot taken.

**Comment by Raven7576** [comment]
I recently got a snapshot spam bug after updating to the latest version today. I was working on the group WQ in Revendreth (for the Calling) and the addon wouldnt quit making snapshots despite having a recommendation for me. The only thing I can offer to help for troublshooting is that I swapped from Necrolord to Venthyr on my DK to get some renown up. The Venthyr cove ability wasnt showing in the recommendations also while doing the quest.

![image](https://user-images.githubusercontent.com/42005883/155883066-dfabbf9d-15bf-47e6-a281-86d9415051ba.png)


https://pastebin.com/VZ0KkCKA

The below snapshot may be related OR just an issue I generated with my DK. The spam didnt occur with this message. Ill check back if I have a spam snapshot (they seem to be cleared for now because I did a reload)

**edit**:  moved to:  https://pastebin.com/62dCDm8P

**Comment by Raven7576** [comment]
Alright so it did it again: 

Primary: https://pastebin.com/0hPWQkQs
Cooldowns: https://pastebin.com/CMxghSLx
AOE (that only started generated when I opened up Hekili to grab the other two and stopped when Hekili was closed): https://pastebin.com/R4MT6tZ0)

Reverted back to 1.0.2 and have had no issue in the past hour.

**Comment by Hekili** [comment]
Please keep all snapshot info on Pastebin and link it. 

Do you have BugSack/BugGrabber? I need to know if there are error messages. If not in BugSack/BugGrabber directly, check if /hekili > Warnings exists and if so, if there are messages there.

**Comment by Razertongue** [comment]
Ive been getting 3 different bugs in BugGrabber/Sack. 2 reference Weakauras though so Im not sure if they are related. The other is this. Which isnt helpful at all too.

**Comment by Raven7576** [comment]
![image](https://user-images.githubusercontent.com/42005883/155885610-ece70547-b4ef-47b8-8360-502a0575f9e7.png)

I've linked you all the generated issues I could find, snapshot and my reporting screen. I dont see a "Warnings" button. Top right is  BugSack on TitanPanel and there are no bugs while this spam is occurring.  This is while running 1.0.3d, no errors come from 1.0.2 installed. Something implemented between these versions is messing up pretty quickly once in combat.

**Comment by Sratarak** [comment]
New release definitely appears to have fixed the issue for me.

**Comment by Raven7576** [comment]
> New release definitely appears to have fixed the issue for me.

Gonna turn off all addons except for Hekili and report back

**Comment by Raven7576** [comment]
https://pastebin.com/Syf0u8Us

Spam hasnt happened yet but it seems like its super sensitive to generating a snapshot as opposed to 1.0.2. 

![image](https://user-images.githubusercontent.com/42005883/155886254-ad01d853-c994-4906-8d39-51e6bef0fd49.png)

**Comment by Hekili** [comment]
> Spam hasnt happened yet but it seems like its super sensitive to generating a snapshot as opposed to 1.0.2.

The priority was updated, and Unholy's priority can be finicky.  That Primary display couldn't generate a recommendation.  Generating one snapshot because of it is the desired behavior.  What do you think it should've recommended?

It went Death Coil -> Festering Strike -> unsure.  Do you recall from that time?

**Comment by Raven7576** [comment]
> > Spam hasnt happened yet but it seems like its super sensitive to generating a snapshot as opposed to 1.0.2.
> 
> The priority was updated, and Unholy's priority can be finicky. That Primary display couldn't generate a recommendation. Generating one snapshot because of it is the desired behavior. What do you think it should've recommended?
> 
> It went Death Coil -> Festering Strike -> unsure. Do you recall from that time?

Personally, Im no DK all-star. I use Hekeli to allow me to do decent on classes I don't know well so I have no recommendation. I would personally just go back to using the previous priority for now as it seemed to work pretty well. 

Ill do some more testing and report back but I dont have the time to do it now. Would you like me to start a new ticket later?

**Comment by Hekili** [comment]
I have an adjusted priority for Unholy that may resolve this issue; it should affect the case where, with multiple enemies up that are close to death, the addon stops giving recommendations.

**Comment by Raven7576** [comment]
> I have an adjusted priority for Unholy that may resolve this issue; it should affect the case where, with multiple enemies up that are close to death, the addon stops giving recommendations.

Sounds great!

I think the last thing I have to ask, that is still on task to this original ticket... Does the snapshoting need to be a spam? It seems to keep going even after getting out of combat. Anyway you can limit snapshots to just be in combat?

**Comment by Hekili** [comment]
Yes, that's a bug that will be fixed along with the rest of the issue.

**Comment by Hekili** [comment]
Ok, this should be resolved for in https://github.com/Hekili/hekili/releases/v9.2.0-1.0.3e as soon as it's done being built.  If not, please reopen the ticket.
