### ISSUE TITLE
Arms warrior repeating error when boss is almost dead and and bladestorm is recommended. 

### ISSUE THREAD

**Issue by DanP1** [Hekili/hekili#1369]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

This happened with the last update too. The only way to get it to stop erroring is to /reload.  

### How to Reproduce

Arms warrior repeating error when boss is almost dead and and bladestorm is recommended. Cooldowns on. 

### Player Information (Link)

https://pastebin.com/MUZQT36v

### Error Messages (Link)

https://pastebin.com/jhv2pbkc

### Additional Information

I don't know if I pastebin ed properly.  So, I left a mess in the other sections. Sorry.

**Comment by Hekili** [comment]
Which version are you using when these errors occur?  Not "the latest" -- I have to know the version number so the lines match up.  Your Player Information shows 1.0.2 which isn't the latest (but that's probably because you reverted).  The error messages don't match up precisely with the current code, so I can't tell for sure.

Edit: I think I have the issue sorted and will test after dinner. If you can post the version you're talking about though, that's help. Thanks.

**Comment by DanP1** [comment]
Hi,
 I reinstalled with Hekili-v9.2.0-1.0.4.zip
<https://github.com/Hekili/hekili/releases/download/v9.2.0-1.0.4/Hekili-v9.2.0-1.0.4.zip>.
I tested it on a couple rares in Zereth Mortis. So far so good.
Thanks for the reply,
Dan
