### ISSUE TITLE
[REC] Warlock - Demonology Implosion not in the rotation since 1.0.8 update

### ISSUE THREAD

**Issue by Statticc** [Hekili/hekili#1406]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

With version 9.2.0 1.0.7 The Auto and AoE display modes would suggest implosion for Demonology in any aoe/cleave situation, in M+, open world, dummies etc, even at the end of an encounter to use the resource.

Since the 9.2.0 1.0.8 update, this no longer occurs. There is no Implosion recommendation/suggestion in Auto or AoE display modes

### How to Reproduce

DPS'ing in any cleave/aoe situation. There simply are no implosion recommendations in the display anymore since the update.

### Snapshot (Link)

https://pastebin.com/SE1xZgSw    ** Updated

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/vaY1rNA6VeSaPKpFTUX4VK

### Additional Information

Above sim is Add Cleave with 1 Boss, Sim shows implosion, however addon does not suggest this since the update.

The following sim is Hectic Add Cleave:
https://www.raidbots.com/simbot/report/9wJh8cVNv9GN3znedM4wVu

This one is Dungeon Slice (been playing demo in M+):
https://www.raidbots.com/simbot/report/spEK2LtvN341zcz8Y8W1Mf

Thanks.

**Comment by Hekili** [comment]
That's not a snapshot, per the instructions.  Get a snapshot when you think it should be recommending Implosion but isn't, please.  Thanks!

**Comment by Hekili** [comment]
![image](https://user-images.githubusercontent.com/9438134/157244254-d46c9e79-e607-4754-afc7-1517afcf0f0c.png)

**Comment by Hekili** [comment]
For reference, there are five entries for Implosion in the Demo Warlock priority; one higher up and four lower.  Here's the higher priority entry...

Default 14:  `boss & fight_remains < 2 * gcd`

You're in a boss fight and the boss will die in less than 2 GCDs.  This *was* recently changed to care about being in a boss fight, because you generally don't want to throw away imps that you'd otherwise feed your tyrants.

The other entries are...

Default 26:  `active_enemies > 1 + ( 1 * talent.sacrificed_souls.enabled ) & buff.wild_imps.stack >= 6 & buff.tyrant.down & variable.next_tyrant_cd > 5`

This means you have more than 1 target (more than 2 targets with Sacrificed Souls) and 6+ imps and your Tyrant isn't active and your next Tyrant's CD is more than 5 seconds.

Default 27:  `active_enemies > 2 & buff.wild_imps.stack >= 6 & buff.tyrant.down & variable.next_tyrant_cd > 5 & ! runeforge.implosive_potential.enabled & ( ! talent.from_the_shadows.enabled | debuff.from_the_shadows.up )`

This means you have more than 2 targets, 6+ imps, Tyrant isn't active and next tyrant is at least 5 seconds away, and you do not have Implosive Potential, and you either didn't take From the Shadows talent or From the Shadows is up on your target.

Default 28:  `active_enemies > 2 & buff.wild_imps.stack >= 6 & buff.implosive_potential.remains < 2 & runeforge.implosive_potential.enabled`

This means you have more than 2 targets, 6 or more imps, Implosive Potential expires in less than 2 seconds, and you are wearing the Implosive Potential legendary.

Default 29:  `buff.wild_imps.stack >= 12 & talent.soul_conduit.enabled & talent.from_the_shadows.enabled & runeforge.implosive_potential.enabled & buff.tyrant.down & variable.next_tyrant_cd > 5`

This means you have 12+ imps, Soul Conduit and From the Shadows talented, Implosive Potential legendary, your Tyrant is not active, and your next Tyrant cooldown is greater than 5 seconds.

**Comment by Hekili** [comment]
I'm closing this but you can reopen if/when you have add'l data/snapshots.

**Comment by Statticc** [comment]
Well, I couldn't give a snapshot when you requested as US went on maintenance.  

It's hard to get the exact time of the snapshot, I'm not a Demonology expert, hence using the addon, nor am I a coding expert. All I can tell you is this version is NOT recommending implosion on any m+/cleave fight, where as the 1.0.7 version was only hours earlier in keys.

**Comment by Statticc** [comment]
https://pastebin.com/SE1xZgSw

**Comment by Hekili** [comment]
Your imps weren't being detected in that snapshot. I'm assuming you did have imps at that time.

**Comment by Hekili** [comment]
Also, for reference, the instructions for submitting the snapshot were there when you submitted the original ticket.

> It's hard to get the exact time of the snapshot, I'm not a Demonology expert, hence using the addon, nor am I a coding expert. All I can tell you is this version is NOT recommending implosion on any m+/cleave fight, where as the 1.0.7 version was only hours earlier in keys.

You don't have to be an expert, you just have to push the button when you think it should've recommended Implosion but didn't. Then you upload that snapshot so I can review (which you now have done).

I'll continue to investigate. Thanks.

**Comment by Statticc** [comment]
Yes, I had 9 at the time

**Comment by Statticc** [comment]
oh, and yes, the not having the snapshot was my mistake, I assumed/copied the info I had in the original incorrect ticket.  Didn't read it was a different piece of info.  My comment was more in reference to not understanding the snapshot code, so not knowing if it's snapshotting the correct info

Thanks for your help and patience!

**Comment by Hekili** [comment]
This should be fixed in 1.0.8b.

**Comment by Statticc** [comment]
Legend, ty! I'll test it now

**Comment by Statticc** [comment]
Perfect!!! works great. Thanks so much!!
