### ISSUE TITLE
[Demonology] Playing DL SC is not recommending tyrant in opener

### ISSUE THREAD

**Issue by dubudevs** [Hekili/hekili#1419]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

During opener the addon recommends the opener correctly up until it wants to tyrant. I am not 100% sure whether this is an APL issue but I don't believe so.

I don't have any trinkets that would be recommended immediately before casting tyrant so I'm not sure exactly where it fails, but it does recommend ruby at an appropriate time, but it then doesn't recommend tyrant and instead continues the normal hog rotation, until it next summons dogs at which point it recommends tyrant correctly.

Example correct opener would be something along the lines of 
pre db>dogs>sb>sb>hog>sb>hog>tyrant
(you can get more imps with decent haste and no procs but without bl its only 1 extra so barely worth it)

Recommended opener is
pre db>dogs>sb>sb>hog>sb>hog>sb>sb>sb>hog>sb>sb>...>dogs>tyrant

Unsure exactly when a snapshot should be taken to show this issue. 

Note: I can't remember exactly whether it recommends db>dogs>sb>sb>hog>sb>hog or db>dogs>hog>sb>sb>sb>hog but it shouldnt be relevant.

### How to Reproduce

Do not talent vilefiend or grimoire: felguard and do your opener. 

### Snapshot (Link)

-

### Raidbots Sim Report (Link)

-

**Comment by Hekili** [comment]
Please add a snapshot -- multiple snapshots, if needed -- to capture what you are describing.

And link a sim for comparison.  Thanks!

**Comment by Hekili** [comment]
_Example Hekili Opener_

Pre-Pull:
![image](https://user-images.githubusercontent.com/9438134/157872043-b3d47a7e-021b-4261-bcb3-0ad57f3d7712.png)

While Casting Demonbolt:
![image](https://user-images.githubusercontent.com/9438134/157872129-d6a09bcc-275d-43d7-8e87-baffe3df8992.png)

Build:
![image](https://user-images.githubusercontent.com/9438134/157881385-b4268a4b-241e-48b5-a1a8-cab16cddb726.png)

  | Addon | SimC | Yours | SimC First Tyrant @ 22
-- | -- | -- | -- | --
Pre | Demonbolt | Demonbolt | Demonbolt | Demonbolt
1 | Soul Rot | Soul Rot | *Omitted* | Soul Rot
2 | Call Dreadstalkers | Call Dreadstalkers | Call Dreadstalkers | Call Dreadstalkers
3 | Hand of Guldan | Hand of Guldan | Shadow Bolt | Hand of Guldan
4 | Shadow Bolt | Shadow Bolt | Shadow Bolt | Shadow Bolt
5 | Shadow Bolt | Shadow Bolt | Hand of Guldan | Shadow Bolt
6 | Shadow Bolt | Shadow Bolt | Shadow Bolt | Shadow Bolt
7 | Hand of Guldan | Hand of Guldan | Hand of Guldan | Hand of Guldan
8 | Shadow Bolt | Shadow Bolt | Shadow Bolt | Shadow Bolt
9 | Hand of Guldan | Hand of Guldan | Shadow Bolt | Shadow Bolt
10 | Summon Demonic Tyrant | Summon Demonic Tyrant | Shadow Bolt | Shadow Bolt
11 |   |   | Hand of Guldan | Hand of Guldan
12 |   |   | Shadow Bolt | Demonbolt
13 |   |   | Shadow Bolt | Hand of Guldan
14 |   |   | ... | Shadow Bolt
15 |   |   | ... | Demonbolt
16 |   |   | ... | Demonbolt
17 |   |   | ... | Hand of Guldan
18 |   |   | ... | Shadow Bolt
19 |   |   | ... | Shadow Bolt
20 |   |   | ... | Shadow Bolt
21 |   |   | ... | Hand of Guldan
22 |   |   | … | Hand of Guldan
23 |   |   | Call Dreadstalkers | Call Dreadstalkers
24 |   |   | Summon Demonic Tyrant | Summon Demonic Tyrant

All of this is without Bloodlust, simply because in-game I didn't have a Bloodlust to use.

Adding a condition for this build such that the First Tyrant is at 22 seconds would get you what you've described.  However, that's a lot of casts/shard expenditure/CDR on Tyrant that is being thrown away by sitting on Tyrant for another 12 seconds, waiting for Call Dreadstalkers to come off CD.  That could be too high of an opportunity cost, or it could not.  If you ran without Demonic Consumption, you could potentially make other adjustments.

In my crappy gear, this brought sim DPS down by ~50 (7806 to 7753).

**Comment by dubudevs** [comment]
rewriting

**Comment by dubudevs** [comment]
Playing Niya also has some strange interactions too. Firstly, its suggesting sb>sb>tyrant when it is far in the future which is not optimal at all, but *may* be a result of the APL under certain conditions. https://puu.sh/IOdwf/b23f7f3a92.png https://pastebin.com/iuuY1zFL

But more importantly, it doesnt actually recommend tyrant for me when I get that far into the opener (opening with DB). https://puu.sh/IOdwJ/3500d8bb70.mp4

**Comment by Hekili** [comment]
Make sure to update to the latest version of the addon before submitting your rewritten information.  Thanks!

**Comment by dubudevs** [comment]
I should point out that this is still an issue playing all trinkets, albeit less consistent. I just haven't had a chance to sit at a dummy for 20 minutes to figure out when and when it doesn't happen.

**Comment by Hekili** [comment]
You can add to the ticket and reopen the ticket if/when you get information.

You can force a snapshot at any time you're seeing this issue; it doesn't have to be vs. a dummy.

**Comment by dubudevs** [comment]
Prepull https://pastebin.com/n7RBySEf 
Post pull https://puu.sh/IPZqw/f7896dea5d.txt
![image](https://user-images.githubusercontent.com/91028108/159273002-2983854a-3f2c-4eae-ae55-7be5862d6638.png)

512kb pastebin limit.

**Comment by Hekili** [comment]
So the first point where the Tyrant could've been recommended here was this:

` - this entry's criteria FAILS: time[10.35] > first_tyrant_time[10.01] & ( pet.dreadstalker.active[true] & pet.dreadstalker.remains[1.41] > action.summon_demonic_tyrant.execute_time[1.49] ) & ( ! talent.summon_vilefiend.enabled[false] | pet.vilefiend.active[false] ) & ( soul_shard[0.00] = 0 | ( pet.dreadstalker.active[true] & pet.dreadstalker.remains[1.41] < action.summon_demonic_tyrant.execute_time[1.49] + action.shadow_bolt.execute_time[1.49] ) | ( pet.vilefiend.active[false] & pet.vilefiend.remains[0.00] < action.summon_demonic_tyrant.execute_time[1.49] + action.shadow_bolt.execute_time[1.49] ) | ( buff.grimoire_felguard.up[false] & buff.grimoire_felguard.remains[0.00] < action.summon_demonic_tyrant.execute_time[1.49] + action.shadow_bolt.execute_time[1.49] ) )`

This is the first moment after `first_tyrant_time` that Summon Demonic Tyrant would be available, but your Dreadstalkers were falling off (1.49 seconds to cast Tyrant vs. 1.41 seconds left on Dreadstalkers).    At the next GCD, your Dreadstalkers have expired, so Tyrant is left to wait until your next set of Dreadstalkers.

This leads to the Shadow Bolt vs. Hand of Gul'dan feedback loop you see starting with entry number 8, which is based on this (HoG):
` - this entry's criteria PASSES: soul_shard[1.00] >= 1 & buff.wild_imps.stack[9.00] > 2 & variable.next_tyrant_cd[0.00] < gcd.max[1.11] & time[11.84] > first_tyrant_time[10.01] - gcd.max[1.11]`

This could also be adjusted to only fire when Dreadstalkers are up, since all Tyrant casts expect to have Dreadstalkers active.

In your prepull sim, the timing for the Tyrant landed at pretty close to the same time but your actual casting seems to have summoned Dreadstalkers before getting into combat (which is weird, based on the investigation we both did re: starting combat on-cast).

- [ ] Test: Update Hand of Gul'dan entry to only cast if Dreadstalkers are active so that Tyrant would actually be cast afterward.
- [ ] Test: Change `first_tyrant_time` for non-Demonic Consumption builds and/or when Bloodlust is not used in the opener.  Check if the opener Dreadstalkers cast would need to be delayed so it will last beyond the `first_tyrant_time`.

**Comment by dubudevs** [comment]
It's possible that it is getting confused by a demonic calling proc (demonbolt precast>instant cast dogs). This would make it look like combat was started by dogs because they are way faster than db, and they leave at the same time. 

Unsure whether this happens in sims too but I will look into it.

**Comment by dubudevs** [comment]
Yep, sim issue. https://www.raidbots.com/simbot/report/i9NLVdPjLEZvi5NvTA1Rda

Will suggest a fix shortly.

**Comment by dubudevs** [comment]
You actually have a better insight into the reasoning behind why things are or aren't used, so if you have a suggestiong for a fix that would be useful.

**Comment by dubudevs** [comment]
It is as simple as setting first tyrant time to 9 if you arent playing gfg or vf, that will be pushed to the simc apl shortly

**Comment by Hekili** [comment]
That would definitely cover the scenario in a truly fresh sim, but going pull-to-pull in M+ might suffer a bit.  But I can make that change for the addon plus some changes to support a not-fresh scenario.

**Comment by dubudevs** [comment]
The issue arises when you pull with dogs, which if anything is more likely in m+, especially considering that not playing VF GFG is the m+ build
