### ISSUE TITLE
Unholy DK - Death & Decay

### ISSUE THREAD

**Issue by ghost** [Hekili/hekili#142]
Death & Decay is suggested in the rotation even if it is stil on cooldown 5+ seconds. Single target seems to be working fine, But as soon as you start AOE'ing you notice a significant DPS loss because of that. This all started after v8.1.5-15, Therefore using that version again.

**Comment by Hekili** [comment]
Post the requested information with your ticket.

Also, assuming you're playing Unholy, check out /hekili > Unholy > Targeting > Recommend Target Swaps.  There's new logic to help spread your wounds before popping them in DnD.

**Comment by ghost** [comment]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

v8.1.5-18

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

None.

**Describe the Bug/Issue**
Death & Decay is suggested in the rotation even if it is stil on cooldown 5+ seconds. Single target seems to be working fine, But as soon as you start AOE'ing you notice a significant DPS loss because of that. This all started after v8.1.5-15, Therefore using that version again.

**To Reproduce**
Start AOE'ing using version v8.1.5-18

**Expected behavior**
Not suggesting D&D when its stil on a 5 second cooldown.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**
Character Data: https://pastebin.com/YCNcczLg

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**
AOE Snapshop: https://pastebin.com/uZ0pKZdt
Primary Snapshop: https://pastebin.com/VmrbvjYB

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
Did you look at the target swap setting I mentioned?

**Comment by ghost** [comment]
Yes i did, Same result. Also target swapping is not necessary as a dk as Virulent Plague spreads it self. Building Festering Wounds on multiple targets is a dps loss as well.

**Comment by Hekili** [comment]
...no, not really. I'll be making adjustments to the wound spreading (so that it doesn't impact folks who don't want target swap recommendations), but with Festermight, being able to pop wounds on more enemies means faster stacks during AOE burst.

**Comment by ghost** [comment]
Its not because "FOLKS" don't want target swap recommendations, Unholy DK's DO NOT target swap. And yet all of this has nothing to do with D&D being recommended when its still on a 5+ seconds cooldown. Everything was fine in version 15.

**Comment by Hekili** [comment]
Why did you capitalize "folks" and put it in quotes?  Seems kinda aggressive.

I'll promise you that I did an absurd amount of sim testing to identify the point at which it's more beneficial to spread wounds for AOE and pop them en masse during Death and Decay (so that you don't build Festermight stacks right as they are falling off).  It wasn't a capricious decision, and it does result in improved DPS in sustained multitarget.

Howver, as you are experiencing, it's pretty weird to wait on Death and Decay, even when it *is* optimal.  Which is why, as I mentioned, it will be made optional.  

What should you do in the meantime?

If you look at entries 13 and 14 in the **aoe** action list, this is where the relevant changes were made:

13 - Scourge Strike
`( cooldown.death_and_decay.remains > 9 | debuff.festering_wound.stack = 6 ) & ( ( debuff.festering_wound.up & cooldown.apocalypse.remains > 5 ) | debuff.festering_wound.stack > 4 ) & cooldown.army_of_the_dead.remains > 5`

14 - Clawing Shadows
`( cooldown.death_and_decay.remains > 9 | debuff.festering_wound.stack = 6 ) & ( ( debuff.festering_wound.up & cooldown.apocalypse.remains > 5 ) | debuff.festering_wound.stack > 4 ) & cooldown.army_of_the_dead.remains > 5`

What was added is the check that Death and Decay's CD is 9 seconds or more (or your target is capped on wounds) before using SS or CS.  This means that when your DND is under 9 seconds, you'll stop popping the wounds.  The recommendation to wait for DnD isn't that the addon wants you to DnD so badly, it's that it's currently holding SS/CS until you are in DnD to pop wounds for Festermight stacks in AOE.  Elsewhere, when **Recommend Target Swaps** is enabled, you're encouraged to Festering Strike a target that will live long enough to have its wound(s) popped during Death and Decay.

Again, this has been tested, it is a performance increase for sustained multitarget, and yes, I know you disagree and you're not experiencing it that way in your own play.

The good news is that you can always change the default priority or build your own priority if you disagree with what is included in the addon.  If you literally remove everything up to the first `&` from those entries, you'll keep popping the wounds instead of holding CS/SS for burst AOE when DnD is ready.

The result looks like:
`( ( debuff.festering_wound.up & cooldown.apocalypse.remains > 5 ) | debuff.festering_wound.stack > 4 ) & cooldown.army_of_the_dead.remains > 5`

That's all that you need to change.  And, like I've been trying to communicate, I'll be adjusting this behavior anyway so that:

- It's optional, via a checkbox.
- If checked, it will require that you actually have Festermight.
- If checked, it will also require that you have Recommend Target Swaps enabled for the spreading of wounds.
- If checked, it will stop saving your wounds if all of your valid enemies (enemies who will survive long enough to have wounds popped in AOE) already have wounds on them.

**Comment by Hekili** [comment]
19-alpha2 provides the option and restricts the scope a bit.
