### ISSUE TITLE
[REC] Shadow Priest - Devouring Plague

### ISSUE THREAD

**Issue by Thornic** [Hekili/hekili#1427]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

It happens that I have 100 insanity, but Devouring Plague is not showing up.

Text on the Devouring Plague ability:
`If this effect is reapplied, any remaining damage will be added to the new Devouring Plague`

With the 2-piece tier set you get the following:
`Casting Devouring Plague has a 40% change to grant Dark Thought.`

Dark Thought doesnt stack with a second Dark Thought.

So I expect that Devouring Plague shows up when I have 50 insanity, and not have a Dark Thought buff.

### How to Reproduce

Just a normal opener that the addon givers should give you the same result.

### Snapshot (Link)

https://pastebin.com/41hM9xkR

### Contact Information

Tornic#4809

**Comment by Hekili** [comment]
First recommendation was Void Bolt, because:

**void_bolt ( main - 11 )**
> insanity.current[100.00] <= 85 & talent.hungering_void.enabled[true] & talent.searing_nightmare.enabled[false] & spell_targets.mind_sear[1.00] <= 6 | ( ( talent.hungering_void.enabled[true] & ! talent.searing_nightmare.enabled[false] ) | spell_targets.mind_sear[1.00] = 1 )

The part that specifically passed was:
 `( ( talent.hungering_void.enabled[true] & ! talent.searing_nightmare.enabled[false] ) | spell_targets.mind_sear[1.00] = 1 )`
You have Hungering Void talented, and you don't have Searing Nightmare talented, so that would be sufficient.  It would also be used here simply based on only having 1 target.  This entry is higher in the priority list than Devouring Plague.


Second recommendation is Shadow Word: Death, because:

**shadow_word_death ( main - 9 )**
> pet.fiend.active[true] & runeforge.shadowflame_prism.equipped[true] & pet.fiend.remains[0.31] <= gcd.execute[0.91] & spell_targets.mind_sear[1.00] <= 7

Your Shadowfiend is active here, you have Shadowflame Prism, your Shadowfiend/Mindbender is expiring within a GCD, and you have fewer than 8 targets.  This entry is also higher priority than Devouring Plague.


Third recommendation is Devouring Plague, because:

**devouring_plague ( main - 13 )**
> ( refreshable[true] | insanity.current[100.00] > 75 | talent.void_torrent.enabled[false] & cooldown.void_torrent.remains[0.00] <= 3 * gcd.execute[0.91] ) & ( ! variable.pool_for_cds[false] | insanity.current[100.00] >= 85 ) & ( ! talent.searing_nightmare.enabled[false] | ( talent.searing_nightmare.enabled[false] & ! variable.searing_nightmare_cutoff[false] ) )

This passes because Devouring Plague is refreshable and Insanity is greater than 75 (only one of these was required), you're not pooling for CDs or Insanity is greater than 85 (100 is still more than 85), and you don't have Searing Nightmare talented.

Have you simmed yourself in single-target with your current gear/talents and looked to see if there are times that you overcap on Insanity?  This literally just had you Void Bolt, squeeze in a Shadow Word: Death to use your legendary, then spent Insanity.  Seems right.

**Comment by Hekili** [comment]
Example single-target sim using T28 Shadow profile:

https://www.raidbots.com/simbot/report/vKJct3CdQEDTYRHWRkVGf5/simc

![image](https://user-images.githubusercontent.com/9438134/158265649-e0365aba-fd22-4113-88f0-f799c9566ed8.png)

Gains | Type | Count | Total | Tot% | Avg | Overflow | Ovr%
-- | -- | -- | -- | -- | -- | -- | --
Insanity Gained from Auspicious Spirits | Insanity | 220.41 | 420.44 | 13.66% | 1.91 | 20.38 | 4.62%
Insanity Gained from Shadowfiend | Insanity | 188.50 | 855.64 | 27.80% | 4.54 | 86.84 | 9.21%
Mind Blast | Insanity | 80.34 | 736.52 | 23.93% | 9.17 | 34.78 | 4.51%
Mind Flay | Insanity | 142.13 | 510.85 | 16.60% | 3.59 | 0.82 | 0.16%
Shadow Word: Pain | Insanity | 10.93 | 43.73 | 1.42% | 4.00 | 0.00 | 0.00%
Vampiric Touch | Insanity | 8.27 | 41.33 | 1.34% | 5.00 | 0.00 | 0.00%
Void Bolt | Insanity | 43.70 | 469.48 | 15.25% | 10.74 | 54.91 | 10.47%

That's a fair amount of overcapping and waste.  Basically, depending on your haste / Bloodlust, that Shadow Word: Death at the end of your Shadowfiend's run can conflict with spending down Insanity.
