### ISSUE TITLE
Fury Warrior Merciless Bonegrinder no longer showing in priority

### ISSUE THREAD

**Issue by grayjared** [Hekili/hekili#1431]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Whirlwind no longer shows as a priority no matter how large of a group is within radius for Fury spec when Merciless Bonegrinder conduit is chosen. Have not tried in arms. I was unable to find how to add it into the priority again, it had worked pre-9.2 and was top priority after bladestorm in aoe situations.

build: v9.2.0-1.0.9a
level: 60 (60)
class: WARRIOR
spec: fury

talents: anger_management
    bladestorm
    cruelty
    double_time
    frenzy
    sudden_death
    warpaint

pvptalents: none

covenant: kyrian

conduits: condensed_anima_sphere = 11
   depths_of_insanity = 11
   inspiring_presence = 11
   merciless_bonegrinder = 11
   piercing_verdict = 11
   stalwart_guardian = 11

soulbinds: [forgelite_prime_mikanikos]
   brons_call_to_action = 1
   effusive_anima_accelerator = 1
   forgelite_filter = 1
   regenerating_materials = 1
   soulglow_spectrometer = 1
   soulsteel_clamps = 1

sets: inscrutable_quantum_device = 1

gear: azurevenom_choker = 1
    bloodoath_signet = 1
    breastplate_of_otherworldly_influence = 1
    cloak_of_enveloping_manifestations = 1
    fused_bone_greatbelt = 1
    guilewind_stone_talons = 1
    implacable_weatherproof_treads = 1
    inscrutable_quantum_device = 1
    legplates_of_the_slumbering_sentinel = 1
    phial_of_putrefaction = 1
    rimebinders_runeblade = 1
    shadowghast_ring = 1
    shadowsteel_helm = 1
    stoneflesh_spaulders = 1
    thunderous_echo_vambraces = 1

legendaries: signet_of_tormented_kings = 1

itemIDs: 171445, 178734, 178771, 178780, 178814, 178840, 178851, 178871, 178926, 179350, 180113, 180115, 185787, 185803, 189778

settings: aoe = 2
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    package = Fury
    petbased = false
    potion = potion_of_phantom_fire
    potionsReset = 20180919.1
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    check_ww_range = true
    heroic_charge = false

toggles: cooldowns = true
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true [overridden]
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    bladestorm         = 6   [01], 6   [06]
    bloodbath          = 4   [01]
    bloodthirst        = 4   [01]
    charge             = 0   [01]
    crushing_blow      = 2   [01]
    execute            = 1   [01]
    hamstring          = 9   [01]
    intimidating_shout = 1   [07], 1   [08]
    pummel             = =   [01]
    raging_blow        = 2   [01]
    rampage            = 3   [01]
    storm_bolt         = 8   [01]
    taunt              = S1  [06]
    victory_rush       = -   [01]
    whirlwind          = 5   [01]

### How to Reproduce

1. Play as fury warrior
2. select Bladestorm as a talent
3. select Merciless Bonegrinder as a Potency Conduit
4. bladestorm on a group of mobs, see that Merciless Bonegrinder is buffed after bladestorm has finished
5. Main Issue - hekili priorities doesn't show to spam Whirlwind after bladestorm, doesn't count merciless bonegrinder as a buff

### Snapshot (Link)

https://pastebin.com/443aFdHd

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/nzFSEA5RRReo6kifnbnK6m

### Additional Information

https://www.raidbots.com/simbot/report/5zZKN4MqWax9669zXk9eyF

Merciless Bonegrinder shows as a buff on raidbots, as well shows that whirlwind is a large part of the damage output when merciless bonegrinder and bladestorm are both selected.

here's a link comparing other abilities in aoe situations showing that merciless bonegrinder + bladestorm is the highest dps combination. https://www.raidbots.com/simbot/report/48hK7XZcw6Q27zxG1k6f5M

### Contact Information

Boomshakalaka#5142

**Comment by Hekili** [comment]
> 5. Main Issue - hekili priorities doesn't show to spam Whirlwind after bladestorm, doesn't count merciless bonegrinder as a buff
> Merciless Bonegrinder shows as a buff on raidbots, as well shows that whirlwind is a large part of the damage output when merciless bonegrinder and bladestorm are both selected.

The addon detected the buff in your snapshot.

> here's a link comparing other abilities in aoe situations showing that merciless bonegrinder + bladestorm is the highest dps combination. [raidbots.com/simbot/report/48hK7XZcw6Q27zxG1k6f5M](https://www.raidbots.com/simbot/report/48hK7XZcw6Q27zxG1k6f5M)

This sim doesn't show what you're saying it shows.

![image](https://user-images.githubusercontent.com/9438134/158654868-ea021500-6fd4-4f04-95e3-da1bb32c6bf7.png)

If you look at this part of the sim, after Bladestorm is used, other abilities are used in addition to Whirlwind -- the priority itself is still considered.

In your sim, the first Whirlwind is the equivalent of this entry:

```
21.  whirlwind ( default - 18 )
The action (whirlwind) is usable at (1.19 + 1.18).
 - the action is ready before the current recommendation (at +1.18 vs. +10.00).
 - this entry's criteria FAILS: level[60.00] > 36 & ( spell_targets.whirlwind[2.00] > 1 & ! buff.meat_cleaver.up[true] | raid_event.adds.in[3600.00] < gcd.execute[1.18] & ! buff.meat_cleaver.up[true] )
```

Your sim selected this entry, labeled `B` because Meat Cleaver was not active.  In the addon, you already have Meat Cleaver up.

The other entry that your sim (labeled as `L`) is:

```
actions.single_target+=/whirlwind,if=buff.merciless_bonegrinder.up&spell_targets.whirlwind>3
```

The addon didn't get to consider that entry, because a higher priority entry was already selected.  If it *had* been considered, it would not have been used because you only have 2 active enemies.  Your sim is based on 4 enemies.

The higher priority entry was:

```
61.  raging_blow ( single_target - 14 )
The action (raging_blow) is usable at (1.19 + 1.18).
 - the action is ready before the current recommendation (at +1.18 vs. +10.00).
List ( single_target ) called from ( Fury:default:35 ) would PASS at 1.18.
NONE
 - this entry's criteria PASSES: set_bonus.tier28_2pc[0.00] | charges[2.00] = 2 | ( buff.recklessness.up[false] & variable.execute_phase[false] & talent.massacre.enabled[false] )
```

This entry for Raging Blow is labeled `J` in your sim.  You can see the relative positioning of these entries here:

![image](https://user-images.githubusercontent.com/9438134/158657652-61f1a4b2-bacc-43c8-b950-f586d5411568.png)

The Whirlwind further down the list is not used when Raging Blow is available and its conditions are met.

![image](https://user-images.githubusercontent.com/9438134/158657567-7698c0eb-48c3-4453-a1e2-6daec4c81824.png)

Note the highlight on merciless_bonegrinder -- it is clearly active in the sim but Raging Blow is used.

Here is another sim of your character with 2 targets (to match your snapshot):

https://www.raidbots.com/simbot/report/r5LpzLVCSUWmhujxkfwwmm/simc

![image](https://user-images.githubusercontent.com/9438134/158658423-0cabca31-a617-499d-a190-ad5963df18d1.png)

You can see here that the behavior matches what the addon is recommending.  You're getting Whirlwind casts that proc Meat Cleaver, and then both charges are spent and then you Whirlwind again to reproc Meat Cleaver.

So, doing some additional testing, I ran another sim that modifies the default priority to be in line with what you're asking for -- and it *is* a DPS increase.

Changes:
* Moved Whirlwind with Merciless Bonegrinder above that entry for Raging Blow.
* Reduced the number of required targets for this entry from 4 to 2.

https://www.raidbots.com/simbot/report/4fdgGyCbpBV9jF4w8zJ93m

![image](https://user-images.githubusercontent.com/9438134/158659179-afb65975-9575-4140-83df-28b644bda537.png)

That means that this may be something that belongs in a SimulationCraft issue ticket, assuming that testing would show this is consistently better for other talent/gear/covenant combinations.

**Comment by Hekili** [comment]
I am running some comparison sims via Bloodmallet now to see if this should be changed for SimulationCraft.

**Comment by grayjared** [comment]
Thanks so much for looking into this for me. I really appreciate it.
________________________________

**Comment by Hekili** [comment]
I've fiddled with it a bit and it's just an optimization that becomes less and less valuable as you get better gear.  I'm not sure if it's genuinely worth pursuing without a lot more data.  Will continue to ponder.

**Comment by Hekili** [comment]
I'm not going to pursue this further because it's not proving beneficial consistently enough to build into the addon.

**Comment by grayjared** [comment]
Alright, thanks again. I’ll play around with it a bit more myself as well.
________________________________
