### ISSUE TITLE
[REC] MM Hunter Volley Trick Shots timing with Aimed Shot

### ISSUE THREAD

**Issue by Lipstopica** [Hekili/hekili#1435]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

On MM Hunter, doing an opener in AoE (without lust) and pretty sure during combat to it will follow the simcraft to Aimed Shot > Aimed Shot > Rapid Fire... but then Hekili will suggest to do an Aimed Shot isntead of the simc Multi-Shot. The buff Trick Shots runs out before the Aimed Shot even goes off, way before. Meaning it's not hitting multi targets.

I can only imagine this is because it's not working with the "buff.trick_shots.remains >= execute_time"

In the Snapshot I have linked, I took the snap at 0.1 seconds left of the rapid fire, still suggesting Aimed Shot, when Trick Shots has 0.7 left on its duration.

### How to Reproduce

Take Volley talent
Follow Hekili on multi target dummies without Lust
Follow until you done the following Aimed Shot > Aimed Shot > Rapid Fire
Watch the duration of Tricked Shots from Volley run out before you can even get an Aimed Shot off

### Snapshot (Link)

https://pastebin.com/HALWCewV

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/8LTZR7pwpQYkaWYX5ZUVUi

### Contact Information

Smudgie#2425

**Comment by Hekili** [comment]
There are multiple criteria for casting Aimed Shot in that scenario, not just Trick Shots.  However, there *is* a bug because the `focused_trickery_count` should be stuck at 0 while you don't have the tier set.

```
 - this entry's criteria PASSES: ( buff.trick_shots.remains[0.63] >= execute_time[1.26] | focused_trickery_count[30.00] > 0 ) & ( buff.precise_shots.down[false] | full_recharge_time[3.95] < cast_time[0.73] + gcd.execute[1.26] | buff.trueshot.up[true] | set_bonus.tier28_4pc[0.00] & runeforge.secrets_of_the_unblinking_vigil.enabled[false] )
```

\# | Criteria | Pass/Fail
--|--|--
A | buff.trick_shots.remains[0.63] >= execute_time[1.26] | Fail
B | focused_trickery_count[30.00] > 0 | **Pass**
C | buff.precise_shots.down[false] | Fail
D | full_recharge_time[3.95] < cast_time[0.73] + gcd.execute[1.26] | Fail
E | buff.trueshot.up[true] | **Pass**
F | set_bonus.tier28_4pc[0.00] & runeforge.secrets_of_the_unblinking_vigil.enabled[false] | Fail

Conditions are:  ( A or B ) and ( C or D or E or F ).  B and E are sufficient criteria for the recommendation.  But that would go away once I prevent you from getting credit for spending Focus for the 4pc bonus that you don't have.

**Comment by Lipstopica** [comment]
Oh so if I understood correctly. It currently thinks I have the 4pc bonus effect? So it thinks because I spend the rage, I should have the buff of trick shots? due to the two casts of aimed shot which is over 40 rage spent.

**Comment by Hekili** [comment]
No, it doesn't think you actually have the 4pc (`set_bonus.tier28_4pc[0.00]` means "you don't have the 4pc"), but the tracking mechanism that counts focus spent is still running anyway (`focused_trickery_count[30.00]`).  It's a simple fix.

**Comment by Lipstopica** [comment]
Can confirm, fixed in new update. Thank you.

**Comment by Hekili** [comment]
Will post in actual release in a little bit.
