### ISSUE TITLE
[REC] Ret using HP builders when capped during desync

### ISSUE THREAD

**Issue by cremor** [Hekili/hekili#1436]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

While fighting the first boss of the current raid, I had a situation where Hekili recommended using a Holy Power builder next (even waiting for it to come of cooldown) while I was already at 5 Holy Power.

I used the Seraphim and Final Reckoning talents in the fight and the problem happend during the adds phase. Seraphim was on cooldown, but the buff was not up any more. Final Reckoning was ready to use. It might have been a case where I just couldn't follow the recommendations to use Final Reckoning because there were no targets to fight in that moment.
But even if that happens, the addon should continue to make useful conditions and not waste Holy Power by using a builder while already at 5 Holy Power.

### How to Reproduce

1. Enter game as a Retribution Paladin.
2. Take the Seraphim and Final Reckoning talents (but not Execution Sentence).
3. Start a fight, use Seraphim when recommended.
4. Don't use Final Reckoning when recommended. Just do nothing until the Seraphim buff fades.
5. After the Seraphim buff fades, continue to follow the recommendations.
6. Notice that it recommends builders when already at 5 Holy Power.

### Snapshot (Link)

https://pastebin.com/d01CxZ57

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/bSX98vHvcv2ruiSC67Ji1z

### Additional Information

This time my issue is **not** about disabled or separately shown cooldowns :grin:

**Comment by Hekili** [comment]
The snapshot needs to come from the current version.  Thanks!

**Comment by cremor** [comment]
@Hekili I reproduced the problem with the current version on the target dummy and updated the issue with the new snapshot.

**Comment by Hekili** [comment]
Which finisher/cooldown should the addon have recommended, and why?

**Comment by Hekili** [comment]
I don't want to run a separate alpha release for this while I'm trying to wrap up another daily release, so I'm going to share the import string for a Ret priority that *might* address this.  It's a rush job so it might still be problematic, but should allow Divine Storm, and Templar's Verdict while Final Reckoning is off-cooldown but criteria isn't met to push the button.

[Priority](https://pastebin.com/40vncPjz)

To test it:
1. Open the link, copy the import string.
2. `/hek` > Priorities > Share Priorities > Import > Import String -- paste the string and press Accept.
3. Click Import Priority.
4. You may want to change the name to leave the default priority intact.
   - If so, just change it and press Enter.
5. Click Apply Changes.
6. Click Accept to create a new priority / overwrite the existing priority.
7. If you changed the priority name, go to the new Priority in the list and check Active *or* go to the Retribution spec options and select it from the list (both approaches accomplish the same thing).

This *doesn't* line up with my intended design philosophy that everything is proven via sims, because this is one of those situations where you are trying to recover from a scenario the sim wouldn't get into.  Let me know if this is closer to what you'd expect.

**Comment by Hekili** [comment]
I did my own testing and found issues, so I'm trying a new approach.

[Priority 2](https://pastebin.com/DpAk7j3M)

I think this one works (also, this is named `Retribution 2` by default -- make sure to activate it if you import it.)

**Comment by Hekili** [comment]
I'm going to go live with these adjustments and we'll see how it goes.

**Comment by cremor** [comment]
Looks good, thanks!

Just one thing I noticed:
I got the 2 set bonus in the meantime and the Seraphim proc from it is treated the same way as a "real" Seraphim buff. Meaning, when you are in a state where Seraphim and Final Reckoning are desynced, a 2 set bonus proc will cause Final Reckoning to be recommended, thus "extending" the desync.

I guess waiting for the "real" Seraphim buff would be better to sync it up with Final Reckoning again? But maybe it's not worth the effort to invest time in this?

**Comment by Hekili** [comment]
I'd hope it's something that the SimC maintainers have considered and factored into the priority. Maybe it doesn't matter. If you do some sim testing and find it makes a difference, please let me know.

**Comment by cremor** [comment]
Is this even something a sim could answer? A desync shouldn't happen in sims normally. You'd have to create a custom fight with downtime just at the right moment...

**Comment by Hekili** [comment]
It's easy to add a 5 second stun or a condition that would result in a desync.  But no, generally speaking, Seraphim is going to come off CD and get used before Final Reckoning under normal circumstances.
