### ISSUE TITLE
Havoc Demon Hunter - Hekili suggests casting Eye Beam at 50+ Fury (Blind Fury Talent skilled)

### ISSUE THREAD

**Issue by Geistergurke** [Hekili/hekili#144]
**Describe the Bug/Issue**
When playing a Havoc Demon Hunter with the Blind Fury Talent skilled, Hekili suggests casting Eye Beam regardless of how much fury you have.

**To Reproduce**
Skill into Blind Fury
Just fight something

**Expected behavior**
Normally you shouldn't cast it with more than 50 fury

**Character Data**
https://pastebin.com/1rZqk2BW

**Snapshot**
https://pastebin.com/ww40e6eU

**Screenshots**
https://i.gyazo.com/06706f12401f3b0449d53c0026b0d3af.png
(I have 120 fury and the next recommendation is Eye Beam)

https://i.gyazo.com/f05335f076694cc3f2576f78fcb65839.png
(The same goes for Immolation Aura. You shouldn't cast it at max fury)

**Comment by Hekili** [comment]
So, a few things to consider with the priority list:

1.  It generally assumes you are constantly actively doing everything you can.  Sometimes, sitting at Fury cap is because you were stopping to wait for something else to happen.

2.  Wasting Fury can be bad, certainly, but delaying Demonic can be worse (dependent on fight-time and add waves).

So, let's look at sims.  In these screenshots, "NoCapImmo" is a priority adjusted to avoid using Immolation Aura unless your Fury deficit is more than 20.  "EyeBeamSub50" only uses Eye Beam when Fury is under 50.  "BothChanges" is... well, both changes.

Patchwerk:  https://www.raidbots.com/simbot/report/9peXLHjLVxwdfnMBeDFhzJ
![image](https://user-images.githubusercontent.com/9438134/58031290-1d117800-7aee-11e9-9fe8-516cda656d80.png)
We can see that, on Patchwerk fights, holding Immolation Aura to avoid overcapping is a tiny loss, at best.  Delaying Eye Beam, on average, is a significant DPS loss.

Hectic Add-Cleave:  https://www.raidbots.com/simbot/report/seHykfWh78bh1QaMaWCaQu
![image](https://user-images.githubusercontent.com/9438134/58031367-43cfae80-7aee-11e9-8538-5d504605634a.png)
Same deal, except holding Immolation Aura becomes worse.

Dungeon Slice:  https://www.raidbots.com/simbot/report/f2LSENJLkgnpFBfp7MNBQ8
![image](https://user-images.githubusercontent.com/9438134/58031396-55b15180-7aee-11e9-85cd-950ac075553d.png)
Similar DPS impact as Patchwerk.

Here is a sample profile you can try adjusting to see if you get different outcomes:  https://pastebin.com/ZQ5yULLk -- you can paste that into an Advanced sim in Raidbots to do your own adjusting and testing.

Based on the sim output, it looks like a DPS loss to delay Immolation Aura and Eye Beam in order to try to save Fury.

**Comment by Geistergurke** [comment]
First of all thank you for the very quick response.
Looking at your sims it makes absolute sense to put Eye Beam and Immolation Aura at those higher priorities. I guess I got fooled by WoWAnalyzer who criticised my Eye Beam useage at high fury levels.

I just looked at the changelog there and they just added the "no eye beam above 50 fury-rule" a couple of weeks ago: https://i.gyazo.com/9f443e95e33cd5c6adb92823cd3673b6.png
I guess yajinni simmed something different?

**Comment by Hekili** [comment]
I'm guessing they have some reason for it -- it could be true at specific gearing levels, etc., but without data to demonstrate that it's beneficial, I can't really make a change.

My interpretation of that screenshot is that WoWAnalyzer wants to encourage you not to waste Fury, which is valid, but not always optimal as demonstrated above.  I think it's actually saying that wasting MORE THAN 50 Fury is bad (which will require another round of testing that I can't do this second).

**Comment by Rusah** [comment]
I agree with Hekili's interpretation - WoWAnalyzer is considering that a cast of eye beam when you are over 50 fury to be wasting potential fury. While this is true, its also a completely terrible rule to play around, and blind fury fury waste is _generally_ not a metric actually worth tracking. Simply executing your priority and hitting eye beam results in the most optimal play.
