### ISSUE TITLE
 [surv hunter] Another bug with a quick change of bombs with the mad bombardier talent

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#1441]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The bug that was earlier repeated again. Now the bombs are changing just as fast again, between two Raptor Strike Kill Command spells. I installed the alpha 2 version, everything works fine there, in the release version it repeats again.

### How to Reproduce

1. Get the mad bombardier buff
2. Throw a bomb

### Snapshot (Link)

https://pastebin.com/Pvpnife1

**Comment by Hekili** [comment]
If recommendations change quickly, you would need to provide information about what is shown before, what it changes to, what it ends up as.  A single snapshot can't show multiple sets of recommendations.

**Comment by Dragonfo** [comment]
Well, there, apart from Raptor Strike and Kill Command, it does not show anything. Often after Kill Command since we spam recommendations more often than Kill Command, this Kill Command is more often shown as priority 1 and then bomb and then Raptor Strike. Well, I'll try to capture this moment now. It is very difficult because there is a fraction of a second it flickers.

**Comment by Hekili** [comment]
So, let's pin down specifics.  You said:

> Now the bombs are changing just as fast again, between two Raptor Strike Kill Command spells. 

What do you mean, exactly?

Tell it in chronological order, without trying to persuade me of anything.  Just explain.
- I see X recommended, followed by Y.
- I press X.
- The recommendation changes to Z instead of Y, then quickly changes to Y.

Tell me what you see.

**Comment by Dragonfo** [comment]
https://pastebin.com/G5pszh6u 
https://pastebin.com/9KLKnYJ8

I took 2 pictures here. Each time different ability is recommended once can be kill command or raptor strike

**Comment by Hekili** [comment]
You're not providing the information I need from you to help.  Please answer what I'm asking you.  I need the actual context.  

> Each time different ability is recommended once can be kill command or raptor strike

What does this mean in relation to the title of this ticket?

**Comment by Dragonfo** [comment]
Is this some kind of joke? I've provided you with 2 snapshots. I can't how can I capture this moment in a split second? there is a 1 second shift that changes as fast as the blink of an eye. Can you catch it? me not. You fixed this earlier, but didn’t add it to the release, you have an alpha 2 version that fixes this but not the release one. It turns out that you did not add the fix that you previously did. I kind of do not understand your request to provide what happens in a split second. I can show the video clip again and you will see how quickly it happens. If you catch this moment then cool I can't.

**Comment by Hekili** [comment]
> Is this some kind of joke?

No, I asked:  Tell it in chronological order, without trying to persuade me of anything. Just explain.

> I've provided you with 2 snapshots. I can't how can I capture this moment in a split second? there is a 1 second shift that changes as fast as the blink of an eye. Can you catch it? me not.

So explain, as I asked.  What do you see?  What does it change to?  What does it change to after that?

> You fixed this earlier, but didn’t add it to the release, you have an alpha 2 version that fixes this but not the release one. It turns out that you did not add the fix that you previously did.

All the code that was in the alpha is in the release, so I need you to provide the explanation you asked for.  It wouldn't really make sense for me to just unfix something that I already deliberately fixed, so it's more reasonable to expect that there's another factor.

> I kind of do not understand your request to provide what happens in a split second. I can show the video clip again and you will see how quickly it happens. If you catch this moment then cool I can't.

I have not asked you to provide the snapshot of the split second.  I said that you would `need to provide information about what is shown before, what it changes to, what it ends up as.`  I've asked that same question multiple different ways while you provide other information instead.  I've asked you to explain how to reproduce the issue, and what you see at each stage.  

A new video would also be fine.  If you can't or won't, just confirm that.

**Comment by Hekili** [comment]
I've made updates that may address this in 1.0.12.

**Comment by Dragonfo** [comment]
https://imgur.com/a/8DRauOw
I recorded a video, again I was not able to take a snapshot of the problem as you ask. Just physically, in the video you will see exactly why. If you tell me exactly where I should click on the snapshot and make it write, I will do it. I updated if that addon but the problem is not solved.

**Comment by Hekili** [comment]
> If you tell me exactly where I should click on the snapshot and make it write, I will do it.

I think something is being lost in translation, because I explained that I need you to explain/describe what you see vs. what you're expecting -- but that a video would be fine, so the video does help.  Can you confirm that the video was recorded on the current release?  Based on what you said, I don't know if you downloaded the update before/after recording that bit.

In your video, I see the bomb icon changing before recommendations are updated.  It is misleading you a bit.  That isn't the addon switching to recommend a different bomb.  That's the addon updating the existing recommendation's icon a split second before new recommendations are generated.  Again, it's misleading, and I might be able to address it, but the alternative would be that the existing bomb's icon would remain there until the new recommendations are generated.

Does that sound better or worse?

**Comment by Dragonfo** [comment]
https://imgur.com/a/mtb6Rjp
I have attached a screenshot with the addon version. I was making a video on it now. Regarding the new idea that was proposed, I think this, in turn, can worsen the current situation. I guess I'd better get used to this quick change of bombs. I just understand that when we throw a bomb, the mad bombardier buff is still hanging on us, after when the bomb hits the target, the buff is used after 1 sec, and gives us a free bomb, at this moment the addon recommendation shows me that during the collision I had there are 0 of them because I only had 1 bomb in stock, and the mad bombardier buff gives me a free bomb, but in a different color, and the addon rearranges its recommendations based on the next bomb. I just think it's not how not to fix it. Because no matter how hard we try to remove this micro moment in the recommendations, the addon needs to understand that we will have the next bomb. And as practice shows, random bombs do not always go in order. Thank you for trying again to fix the problem, but for now I suggest leaving it as it is. It just reminds me of the recommendation mechanic on MM hunter. There are the same situations when we cast an arrow, the addon still recommends this arrow, after when the arrow was fired, the addon recommends another arrow. With bombs, the situation is approximately the same. It just takes some getting used to, I guess.

**Comment by Hekili** [comment]
> [imgur.com/a/8DRauOw](https://imgur.com/a/8DRauOw)

You could've just said, "yes, the recording is from 1.0.12."  But this works.

> I guess I'd better get used to this quick change of bombs.

The icon swap might be addressed in the 1.0.13-alpha1.

> I just understand that when we throw a bomb, the mad bombardier buff is still hanging on us, after when the bomb hits the target, the buff is used after 1 sec, and gives us a free bomb, at this moment the addon recommendation shows me that during the collision I had there are 0 of them because I only had 1 bomb in stock, and the mad bombardier buff gives me a free bomb, but in a different color, and the addon rearranges its recommendations based on the next bomb. 

This explanation helps a lot.  I had understood that Mad Bombardier is removed when the bomb impacts the target, but had not modeled that the charge gain happens then as well.  I can have the addon anticipate the additional charge based on this feedback.  Thank you.

I just want to add that the addon cannot predict unpredictable mechanics.  So it's still entirely possible that the addon's recommendations will change after using a specific bomb, because the addon can now answer "which bomb is available?" accurately instead of just saying "it's not the last one you threw."

> It just reminds me of the recommendation mechanic on MM hunter. There are the same situations when we cast an arrow, the addon still recommends this arrow, after when the arrow was fired, the addon recommends another arrow. With bombs, the situation is approximately the same. It just takes some getting used to, I guess.

If this is happening, it hasn't been reported to me.  You're welcome to report those with all the relevant information.  It likely means that, like Wildfire Bomb, there are mechanics that are not modeled properly in the addon to differentiate what happens when you use the ability vs. what happens when the ability hits the target.  That could be resolved fairly easily.

I'm going to make make Mad Bombardier generate a bomb charge when the bomb explodes on the target, then post 1.0.13-alpha2.  I think it should be an improvement.

**Comment by Dragonfo** [comment]
https://imgur.com/a/rrtfwIl
I recorded a video of what happened with your modifications. As for me, it's good, better than it was, of course, when it just switched quickly. Thanks for the great idea and your work. P.S. I apologize in advance if I was rude at the beginning)

**Comment by Hekili** [comment]
Thanks for the follow-up video.  And there's no need to apologize, I could've been more polite as well.  Your feedback has been really helpful.

I will say that I really don't *like* that there's a moment where the icon updates before new recommendations occur -- since that *seems* like a recommendation change and might lead people to react incorrectly.

It's a hard problem to solve, because the addon wants to make recommendations as quickly as possible, but the information isn't always available immediately upon using an ability.

I've considered stuff like:
- If you just cast the spell that was recommended, shift the existing recommendations forward 1 slot until new recommendations are generated.  But that requires generating an additional recommendation to fill in the last recommendation, so more CPU is used for minimal benefit.
- Force recommendations to re-update even faster immediately following a cast, so this may occur but it will happen for a smaller fraction of a second.
- Prevent the icon auto-update from occurring for a short time after a cast -- the original icon would show until it changes, but this is also weird.

I'll keep thinking about it.
