### ISSUE TITLE
[BUG] Demonology Warlock rotation wrong 9.2

### ISSUE THREAD

**Issue by ghost** [Hekili/hekili#1442]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

there is problem with Demo Lock rotacion , problem is addon skip 2 spells from rotacion and insted of me doing 10k dps i do only 5k dps. did olso try to sim my self to see how much i need to do and i schoud do 10k dps .Name of two spells are [Summon Demonic Tyrant][Grimoire: Felguard]. did also try to import my profile from sim program to addon rotacion but still same problem. did also try to install 2 addon [BugSack] [BugGrabber] but it look there is no problem. This is my sim and here there is also how i schoud do my rotacion but in game addon do says differently. https://www.raidbots.com/simb  please help me thanks

### How to Reproduce

Demonology Warlock

### Player Information (Link)

https://pastebin.com/pe4gy4kD

### Error Messages (Link)

https://pastebin.com/pe4gy4kD

### Contact Information

dotfree92tommy#2555

**Comment by Hekili** [comment]
1. You have Cooldowns turned off.  See /hekili > Toggles.  You'll want to get used to toggling them on/off so the addon recommends them only when you want them to show up.
2. If you submit another ticket in the future, please select the right ticket type (this was about recommendations), and then make a more serious attempt to fill out the questions that are asked.

**Comment by Hekili** [comment]
Also, I realize my response was harsh, so I apologize for that.  There is a Getting Started article in the wiki here that explains a bit about toggles, etc., which can help you get started.

The reason for those toggles is that there are times where you'd want the addon not to recommend those big cooldowns and toggling them off/on is how you control that.  I don't leave them on by default because I want people to familiarize them with the toggles in the first place.

But, again, sorry for my initial response.  I was trying to rush to answer things between meetings and I shouldn't have been rude.  Take care!
