### ISSUE TITLE
Marksman Hunter 4 piece with unblinking vigil priority

### ISSUE THREAD

**Issue by NokuraWoW** [Hekili/hekili#1454]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

While having 4p + vigil equipped, the priority shifts drastically as you will have a significantly larger amount of aimed shots through procs as well as you can ignore precise shots unless you are about to go into trueshot or you are at 5/40 on the 4p tracker or below. 

### How to Reproduce

Be marksman hunter
equip 4 piece
equip unblinking vigil
happens everytime

### Snapshot (Link)

https://pastebin.com/6LW1F39p

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/cxbozKy51tJaUq6KmQAz5w

### Contact Information

Nokura#1874 discord

**Comment by Hekili** [comment]
> While having 4p + vigil equipped, the priority shifts drastically as you will have a significantly larger amount of aimed shots through procs as well as you can ignore precise shots unless you are about to go into trueshot or you are at 5/40 on the 4p tracker or below.

Hey, I'll need you to be a lot more specific with the report.  What makes you think this isn't already factored into the priority?  What recommendation are you seeing that you think you shouldn't?  What recommendation are you not seeing that you think you should?

> happens everytime

What happens everytime?  Your snapshot shows:

1. Pre-pull Aimed Shot.

2. Volley: `buff.resonating_arrow.up[false] | ! covenant.kyrian[false] & ( buff.precise_shots.down[false] | ! talent.chimaera_shot.enabled[false] | active_enemies[1.00] < 2 ) & ( ! talent.double_tap.enabled[true] | ! set_bonus.tier28_2pc[1.00] | set_bonus.tier28_4pc[1.00] | buff.double_tap.up[false] )`

The above recommendation happens because you're not Kyrian, you didn't take Chimaera Shot (also it's single-target), and you have Tier 28 4pc.

3. Rapid Fire: `( cooldown.resonating_arrow.remains[0.00] > 10 | ! covenant.kyrian[false] | ! talent.double_tap.enabled[true] | soulbind.effusive_anima_accelerator.enabled[false] ) & focus.current[72.54] + cast_regen[10.00] < focus.max[100.00] & ( buff.double_tap.down[true] & buff.eagletalons_true_focus.down[true] | talent.streamline.enabled[true] )`

This recommendation was made because you're not Kyrian and you're not about to overcap Focus and Double Tap isn't active and Eagletalon's True Focus isn't active (also because you talented Streamline).

What about it is wrong?  The priority is aware of your 4pc as well as the current `focused_trickery_count` as you go.  Your sim would open differently, but only because Double Tap and Wild Spirits were on cooldown when you took the snapshot.

**Comment by NokuraWoW** [comment]
its recommending that i keep aimed shot capped, which is the #1 priority as MM not to do. its much more important to use aimed shot than it is to cap focus. i was having 2 aimed shot charges and it was telling me to rapid fire

**Comment by Hekili** [comment]
There's no recommendation that translates to "keep Aimed Shot capped."  Take a snapshot when you think Aimed Shot should be recommended, but isn't recommended, and we can look at that.
