### ISSUE TITLE
[REC] Feral opener, Convoke before Rip?

### ISSUE THREAD

**Issue by Fringetastic** [Hekili/hekili#1460]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

With the latest update to feral priority, during the opener when I use my berserk+tiger's fury macro, the recommended action changes from recommending [Tiger's Fury -> (4 CP) Rip] to recommending [Convoke -> (5 CP) Rip] -- without a rip currently active and while having nearly full energy. This is different than the recommendations from last week and a little surprising because I thought it was a good idea to get rip going with Tiger's Fury up prior to convoking (and having FBite extend the rip). 

I tried it with Frenzyband equipped and without and got the same behavior each time.

My actions, the buttons/abilities activated, are displayed just to the left of the dps meter.

Here's a short video of it. I mouseover the paused recommendation around 13 seconds.
https://www.youtube.com/watch?v=iUrSTsCFomo

### How to Reproduce

1. Be on a (my) feral druid. 
2. Target something with a lot of health, so it will not die quickly.
3. Enter stealth.
4. Attack target with: rake, thrash, brutal thrash (got 4 CPs)
5. Activate Berserk and Tiger's Fury (macro)
6. Now Convoke is recommended instead of Rip.

### Snapshot (Link)

https://pastebin.com/dDEqHQbk

### Additional Information

@Frngtstc on twitter. Thanks for talking with me about this there!

### Contact Information

Fringe#6272 or twitter @Frngtstc

**Comment by Hekili** [comment]
The reason Convoke was recommended here was because you were in Berserk.

```
 - this entry's criteria PASSES: ( dot.rip.remains[0.00] > 4 & combo_points.current[4.00] < 5 & ( dot.rake.ticking[true] | spell_targets.thrash_cat[1.00] > 1 ) & energy.deficit[0.00] >= 20 & cooldown.bs_inc.remains[180.00] > 10 ) | boss[true] & fight_remains[384.00] < 5 | ( buff.bs_inc.up[true] & buff.bs_inc.remains[15.37] > 12 )
        Action chosen:  convoke_the_spirits at 0.00!
```

If I had to guess, your Tiger's Fury button is macro'd to also cast Berserk.

**Comment by Fringetastic** [comment]
I finally got time to look into this further, thank you for this. Yes, I have TF macroed together with Berserk. I did mention it but maybe it wasn't clear.

I don't understand why simc would have ferals convoke before rip is up but okay. It still feels wrong to me so I dug around to learn how to change the behavior. I ended up changing the convoke action under cooldowns in the action list. I added a condition to the last clause with the idea being if rip isn't up but I'm already at 4 or 5 CPs and have energy, don't convoke yet:

 ( buff.bs_inc.up & buff.bs_inc.remains > 12 & (dot.rip.remains > 0 | combo_points < 4 | energy.deficit > 40 ) )

I learned a lot today. Like finding where to make a change if I want to only rip with 5 combo points and such. I appreciate the help!

**Comment by Hekili** [comment]
> I don't understand why simc would have ferals convoke before rip is up but okay.

It's not that it explicitly wants to; it's that your TF/Berserk macro puts you in a situation that the sim wouldn't put itself in.  The sim would not have used Berserk before Rip is up:

`actions.cooldown+=/berserk,if=dot.rip.ticking&(cooldown.convoke_the_spirits.up|cooldown.convoke_the_spirits.remains>32|fight_remains<20)`

But you're using Berserk early, and skipping past that point.

If I adjust the sim profile to use Berserk if TF is up, you end up with the same outcome -- Convoke before Rip:

![image](https://user-images.githubusercontent.com/9438134/161452254-24e0bb4c-5834-462c-9d10-63afabb603d5.png)

So what if I adjust _that_ profile, so that TF and Berserk are used together but Convoke won't be used until Rip is up?

![image](https://user-images.githubusercontent.com/9438134/161452290-e1922b04-246f-4d58-be61-74cd6fb3bca4.png)

That seems like what you're wanting to see.  Now lets look how all 3 compare:

![image](https://user-images.githubusercontent.com/9438134/161452305-ac99b706-faa2-4783-8b37-e8122bec2b25.png)

https://www.raidbots.com/simbot/report/toWdfzcKSd5Byeh2uSAdzx

#### T28 Druid Feral
Default profile, which would not use Berserk until after Rip in the opener.

#### TFBerserk
Modified profile, uses Berserk when TF is up to mimic your macro's behavior.

#### NoVokeWithoutRip
Same as TFBerserk, but also will not use Convoke until Rip is applied.

The outcome is that your macro, as-is, is a 2.2% loss vs. the default profile -- the macro is a bad idea.  If the priority were written to compensate for your macro, that 2.2% loss can be mitigated 50%, losing only 1.1% DPS instead.  Still not a great plan.

It's better to just keep TF and Berserk on separate buttons.

**Comment by Fringetastic** [comment]
Thanks again. I can see how I've gotten to this point. 

I removed Berserk as a possible recommendation because there are times/phases/events that I want to hold it and I didn't like trying to figure out what actions to take while ignoring the recommendation. I have an alert for when it is available so I don't forget to use it.

That, along with the feral guide on wowhead recommending berserk+TF at 3 CP (https://www.wowhead.com/feral-druid-rotation-guide#openers-for-feral-druids with brutal slash and bloodtalons), made me think it was okay to use my berserk macro (which includes casting TF) when the addon recommended TF in the opener.

I'll have to re-think how I have things setup.
