### ISSUE TITLE
No More Purifying Brew or Expel Harm?

### ISSUE THREAD

**Issue by SirWillae** [Hekili/hekili#147]
**To Reproduce**
- Be in Brewmaster spec
- Engage in a fight
- Notice Purifying Brew and Expel Harm are no longer in the rotation

**Expected behavior**
I expect to see Purifying Brew and Expel Harm in the rotation.  They definitely USED to show up.  Not sure when they stopped showing up.  I don't think I messed up any of my settings but... I can't be 100% sure.

Here's a link to the issue reporting information: https://pastebin.com/UGvbh8NL

I'm happy to provide screenshots, but it's kind of hard to get a screenshot of something NOT in the rotation.  :-P

Thanks,
Korra

**Comment by Hekili** [comment]
2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.

**Comment by Hekili** [comment]
Snapshots are useful even when what you want to see is *not* recommended.

Also, take a look at your toggles re: Defensives.

**Comment by SirWillae** [comment]
Defensives are definitely enabled.  I see Ironskin Brew in the rotation, just not Purifying Brew or Expel Harm.  It's not just that I don't see them at the correct times - I NEVER see them any more.  It's like they're disabled (so checking on the defensives toggle was the first thing I did).

So I went to a training dummy and followed Hekili's recommendations exactly.  It wrecked me pretty good.  I took this snapshot right before I ran away (because I was about to die).  My health was at ~30% and my stagger was well over 50%.  Would have been a great time for a Purifying Brew.

https://pastebin.com/Um2WdevV

**Comment by Hekili** [comment]
Purifying Brew's stagger threshold is pretty high -- I'll add in a way to quickly adjust that.  For reference:

```
[ 18]  Checking purifying_brew (Brewmaster - default - 15 )...
purifying_brew is known and enabled.
The action (purifying_brew) is usable at (0.00 + 0.00).
 - the action is ready before the current recommendation (at +0.00 vs. +4.87).
 - this entry's criteria FAILS: stagger.pct[7.00] > ( 25 * ( 1 + group[false] ) ) & buff.ironskin_brew.up[true] & ( 2 - charges_fractional[3.76] ) * recharge[8.96] < buff.ironskin_brew.remains[5.86]
```

The addon is looking for your Stagger ticks to be hitting for 25% of your *current* health before recommending Purifying Brew (50% when you are in a group).  Check out the setting in /hekili > Brewmaster after updating to 8.1.5-20-alpha2.

```
[ 20]  Checking expel_harm (Brewmaster - default - 17 )...
expel_harm is known and enabled.
The action (expel_harm) is usable at (0.00 + 0.00).
 - the action is ready before the current recommendation (at +0.00 vs. +4.87).
 - this entry's criteria FAILS: health.pct[29.56] < 5 * health_sphere.count[[string "return health_sphere.count"]:1: attempt to index global 'health_sphere' (a number value)] | ( healing_sphere.count[2.00] >= 3 & health.pct[29.56] < 50 )
```

Expel Harm isn't being recommended here because `health_sphere.count` isn't a supported expression.  It should be `healing_sphere.count`.  I'll clean up the APL to account for that as well.  This is fixed in 8.1.5-20.alpha2.

**Comment by SirWillae** [comment]
Based on your explanation, I was FINALLY able to get Hekili to suggest a Purifying Brew - I saw it flash once, right before the training dummies killed me.

Unfortunately, I'm not very knowledgeable about Brewmaster (I'm a Windwalker who moonlights as a tank).  As such, I can't really offer any insight as to what heuristics to use for recommending Purifying Brew.  But it seems like it definitely needs to happen more often.  I'm getting WRECKED in M+.  Heck, even those training dummies were able to kill me!  :-P

**Comment by Hekili** [comment]
Training dummies will kill you over time.  I think you probably over-estimate Purifying Brew -- as recently as Uldir, there was almost no significant difference in purifying vs. not purifying.  Brewmaster with Ironskin Brew up basically just needs a healer to keep on healing and should otherwise be pretty tough.

Just keep in mind, the lower you put the Purifying Brew slider, the more frequently you'll use it, but you'll still be reserving your shared brew charges to keep ISB up 100% of the time since that's actually critical.

As a tank, other proactive stuff is up to you.  It's better to Fortifying Brew *before* getting hit by a big chunk of damage than to use it *after* (to buy time for your healers).
