### ISSUE TITLE
 [MM Hunter] Problem with Secrets of the Unblinking Vigil.

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#1471]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

There is an issue with Aimed Shot when taking the legendary power Secrets of the Unblinking Vigil. When using Aimed Shot while casting, Rapid Fire is recommended, and after casting Aimed Shot, Rapid Fire disappears and Aimed Shot is recommended again. If we wait 1-2s between casting Aimed Shot. Because we have procs from Secrets of the Unblinking Vigil at this moment. Then I saw that this could happen again and when Rapid Fire is on CD Arcane Shot will also be recommended in the rotation as long as we use Aimed Shot. The crux of the problem lies in Secrets of the Unblinking Vigil with Aimed Shot procs. This is about the same problem as Surv hunter and Mad bombardier had.

### How to Reproduce

1. MM Hunter with t4 set.
2. use Secrets of the Unblinking Vigil on the character
3. Press Aimed Shot.
4. At the end of casting Aimed Shot, wait 1 second for the rotation to change back to Aimed Shot.

### Snapshot (Link)

https://pastebin.com/245ZDBmE

### Additional Information

Fitting another snapshot that Arcane Shot recommended to me when Rapid Fire was on cd. https://pastebin.com/MYC5SPWh

**Comment by Hekili** [comment]
You can't predict that the legendary is going to proc when Trick Shots is gained; it would be incorrect for the addon to tell you that you'll be able to press Aimed Shot.

> If we wait 1-2s between casting Aimed Shot. Because we have procs from Secrets of the Unblinking Vigil at this moment

You can't predict it, and if you're waiting 1-2 seconds, you're probably making a poor choice because waiting is worth 0 DPS.

> The crux of the problem lies in Secrets of the Unblinking Vigil with Aimed Shot procs. This is about the same problem as Surv hunter and Mad bombardier had.

It's not the same thing; when Mad Bombardier is up and your bomb explodes, you reliably get a charge of Wildfire Bomb back.  When Trick Shots procs from tier or otherwise, you have a 50% chance at a charge of Aimed Shot.  It's not safe/sane for the addon to assume you'll get that charge in advance.  The addon will react if you do get the proc, but will not anticipate it.
