### ISSUE TITLE
[REC] Fury Warrior Recommending triple whirlwind

### ISSUE THREAD

**Issue by CDelongchamp** [Hekili/hekili#1477]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

During DPS sometimes I will encounter a situation where I am recommended to whirlwind three times in a row. Sometimes I get the recommendation after casting whirlwind twice, sometimes I get all three suggestions to be whirlwind. This doesn't make much sense since Bloodthirst is a higher priority ability, and it's cooldown is 3 x GCD, as such, you shouldn't be recommended to cast whirlwind three times, instead it should be 

BT -> whirlwind -> whirlwind -> BT, 

but never

BT -> whirlwind -> whirlwind -> whirlwind

It also happens whenever it's been two GCDs since I cast a BT, for example, I get the recommendation 

BT -> Raging Blow -> Raging Blow -> whirlwind 

instead of 

BT -> RB -> RB -> BT

Recommendation is whirlwind at 0.00 + 0.02.
Recommendation #1 is whirlwind at 0.02s (0.02s).

Recommendation is whirlwind at 0.03 + 1.16.
Recommendation #2 is whirlwind at 1.16s (1.19s).

Recommendation is whirlwind at 1.19 + 1.16.
Recommendation #3 is whirlwind at 1.16s (2.35s).

The Raidbots simulation, even when run for 10 minutes does not ever show whirlwind being cast three times in a row, nor does it cast a whirlwind while a bloodthirst is off Cooldown.

Thanks a bunch for all the hard work!

### How to Reproduce

1. Play Fury warrior
2. Choose as such to make whirlwinds come up more. (Ex: Frothing Berserker instead of Cruelty.)
3. DPS target dummy. During a drought where there are no Rampages, Raging Blows or Bloodthirsts to be cast it will recommend Whirlwind. A portion of the time it will show it three times.

### Snapshot (Link)

https://pastebin.com/V5BMbE9B

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/8cnmMKA6hVdJZYVPmkvC4z

### Contact Information

Funty#2174

**Comment by Shamuray82** [comment]
Merciless bonegrinder conduit may cause that if it hapeens after bladestorm or you may not have enogh rage so it tells u to use free ww

**Comment by CDelongchamp** [comment]
> Merciless bonegrinder conduit may cause that if it hapeens after bladestorm or you may not have enogh rage so it tells u to use free ww

In this setup Merciless Bonegrinder isn't equipped, and both bloodthirst and whirlwind are rage builders, as such are cooldown based. So I don't think that's the culprit.

**Comment by Shamuray82** [comment]
then i dont know what to tell you, works fine for me every time. You sure u havent modified the default rotation to change some variables?

**Comment by CDelongchamp** [comment]
> then i dont know what to tell you, works fine for me every time. You sure u havent modified the default rotation to change some variables?

I haven't knowingly changed any variables that would affect this, but the issue is more than just whirlwind three times, rather it's suggesting abilities that mathematically shouldn't be priority.

**Comment by Hekili** [comment]
The simple reason for 3 Whirlwinds there is that despite being "3 GCDs" for Bloodthirst is that that your GCD is as  the timing is as follows:

<table>
<tr>
	<td>Time
	<td>Action
    <td>Notes
<tr>
	<td>0.00
	<td>Still on GCD
    <td>GCD has 0.02 seconds remaining.
<tr>
	<td>0.02
	<td>Whirlwind
    <td>Bloodthirst had 2.47 seconds left on its cooldown (ready at +2.49 from the time recommendations were generated).
<tr>
	<td>0.02 - 1.19
	<td>GCD
    <td>
<tr>
	<td>1.19
	<td>Whirlwind
    <td>Bloodthirst is still not ready until 2.49.
<tr>
	<td>1.19 - 2.37
	<td>GCD
    <td>
<tr>
	<td>2.37
	<td>Whirlwind
    <td>Bloodthirst is still not ready until 2.49 (0.12s).
</table>

Could your haste have changed (increased) since casting Bloodthirst?  Do you have anything that procs temporary haste?

Do you normally have about 29% haste?  That's what it would take for your GCD to be around 1.16 seconds, which is what the addon is expecting.  If not, how much haste do you actually have?

If your GCD is about 1.16 seconds, we'd expect Bloodthirst's cooldown to be 3.48 seconds.  When recommendations were generated, you had 0.02 seconds left on your first post-BT GCD.  If your haste were unchanged, we'd expect that to mean 1.14 seconds have passed and Bloodthirst would have 2.34 seconds remaining on its cooldown.  But you have 2.49 seconds left on its cooldown.

This would normally be due to a change in haste -- you gained haste after Bloodthirst was put on CD, so now you can fit multiple GCDs into the BT window.

If that's not the case, it's at least the starting point to investigate.

**Comment by Hekili** [comment]
@CDelongchamp -- there is an existing feature that may help resolve this; I'd appreciate it if you would test it.

Go to /hekili > Abilities > Bloodthirst, and set the "Clash" to something around 0.2.  That should address it in your snapshot (since the CD difference was 0.12 seconds).  I'm going to close the ticket since there is a solution, but let me know if this doesn't meet your needs for some reason.
