### ISSUE TITLE
Fury Warrior - stuck on Furious Slash

### ISSUE THREAD

**Issue by Snichy** [Hekili/hekili#148]
With the Fury warrior rotation, it often gets "stuck" on Furious Slash - not just for 3 GCDs which is recommended but indefinitely, sometimes selecting another ability "unsticks" it but sometimes it just gets stuck on FS being the next ability then randomly stops after a dozen or so hits.

build: v8.1.5-18
level: 120
class: WARRIOR
spec: fury

talents: bladestorm
    bounding_stride
    carnage
    double_time
    furious_slash
    siegebreaker
    war_machine

**Comment by Hekili** [comment]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check the bits about snapshots and bug reports below; I'll need that information to explore this further.


**To Reproduce**
Steps to reproduce the behavior:
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**WHEN SUBMITTING AN ISSUE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**
