### ISSUE TITLE
[REC] Ranged character doesn't match expected AOE/target numbers

### ISSUE THREAD

**Issue by UFTimmy** [Hekili/hekili#1490]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I am sure that I have something configured incorrectly or something, but this is the first time playing a ranged character. As a melee character Hekili was always great at recommending AOE/Single Target, but I can't seem to make Hekili see the correct number of targets I'm engaged in. I've tried many various combinations of pet nameplate detection, previously damaged, previously dotted, and it doesn't seem to detect that I am in combat with multiple things.

Is this just a target dummy limitation? Have I configured the addon incorrectly?

### How to Reproduce

I have tried both the dual display and the reactive dual display, and I'm fighting a set of three target dummies in the Night Fae area. Hekili doesn't seem to think that I am in combat with multiple enemies.

### Snapshot (Link)

https://pastebin.com/Tpu1UZwU

### Additional Information

Is there an easy way to see how many targets Hekili thinks I'm engaged with?

**Comment by Hekili** [comment]
> Is this just a target dummy limitation?

Yes.  Dummies repeatedly "die" which can purge them from the target count.

> Have I configured the addon incorrectly?

Yes, probably.  Pet-based detection counts targets near your pet, which isn't particularly useful for Destruction, since your pet is also at ranged.  Nameplate-based detection isn't helpful either, because you can have nameplates on screen that are far away from one another that you're not *really* interested in hitting.  The tooltips for those options try to explain the drawbacks.

You'd likely want to just focus on damage-based target detection, and when you hit (normal) things, they'll count.  Feel free to reopen if you have issues with the regular settings vs. other targets.

**Comment by UFTimmy** [comment]
Hello,

Thanks for the fast reply. I am using felhunter on the target dummies, so it is in melee range of all of them. Additionally I am both dotting them all up with immolate, and casting rain of fire. So all three target dummies are:

1. Within melee range of my pet
2. Receiving dot damage from Immolate
3. Receiving periodic damage from rain of fire.

But, you are of course correct. Detection works just fine on normal mobs, but not on target dummies.

Thanks again!

**Comment by Hekili** [comment]
I'll look at keeping dummies from lying about dying and impacting target detection, but no promises.  Glad things are working under normal circumstances.
