### ISSUE TITLE
[BUG] Unable to make recommendation for Primary #2; triggering auto-snapshot..

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#1492]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

While playing on Frost DK, I get a notification like this in the screenshot. Shows this message very often. Rotation does not break from an error. But the addon shows me this notification with an interval of 1-3 minutes during the battle
![1](https://user-images.githubusercontent.com/63850853/165996560-0cb39e97-aea3-4372-9c86-a39e57b4ff29.jpg)
.

### How to Reproduce

1. Start a fight with a dummy
2. Include in the Show Separately setting.
3. And just strictly follow the rotation.

### Player Information (Link)

https://pastebin.com/7GDZHykr

### Error Messages (Link)

There are no errors in the addon.

**Comment by Hekili** [comment]
Closing; you are able to disable auto-snapshotting in your addon settings (/hekili > Snapshots).  

When auto-snapshotting is enabled, it will create them if a recommendation slot could not be filled.  This is usually related to a nuance of a particular action list.  If you have new, recent, snapshots for the current addon you can submit a ticket for it (since this has aged a bit).
