### ISSUE TITLE
[REC] Frost DK Unable to make recommendation for Primary #7

### ISSUE THREAD

**Issue by Noodleboy0** [Hekili/hekili#1502]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Addon seems to fail to suggest an ability on Primary #7 on both Frost and Unholy (though the issue in Unholy seem to trigger far less often). It doesn't overly make the add-on unusable but happens enough to warrant an issue report. 

### How to Reproduce

Basic Frost and Unholy rotation on single target and 2 target cleave.

### Snapshot (Link)

https://pastebin.com/3U8HytVb

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/jp5sToNWU8EqjWf1YjsSoQ

### Contact Information

Spaghetti#3936

**Comment by Hekili** [comment]
There's really no point in having 7+ recommendations, especially on a spec that has any procs whatsoever -- the entropy and RNG will make any recommendations that far out invalid.  The option to show that many recommendations is mainly for testing and philosophical purposes.

You're otherwise able to spend down runes and RP to the point where you really have nothing to do in the period of the time that the addon concerns itself with giving recommendations for.
