### ISSUE TITLE
Addon not working on my warlock but works on my rouge

### ISSUE THREAD

**Issue by xiiblitz** [Hekili/hekili#153]
build: v8.2.0-01
level: 120 (120)
class: WARLOCK
spec: destruction

talents: burning_rush
    cataclysm
    dark_soul_instability
    demonic_circle
    flashover
    grimoire_of_supremacy
    reverse_entropy

azerite: azerite_empowered=3
    chaos_shards=1
    chaotic_inferno=3
    crashing_chaos=1
    gutripper=1
    impassive_visage=1
    lifeblood=1
    overwhelming_power=2
    treacherous_covenant=1
    vampiric_speed=1

essences: [the_crucible_of_flame]=1, none

sets/legendaries/artifacts: none

gear:     balefire_branch=1
    band_of_multisided_strikes=1
    bloodhunters_drape=1
    crown_of_the_seducer=1
    divine_fury_raiment=1
    heart_of_azeroth=1
    honorbound_artificers_amice=1
    honorbound_artificers_sandals=1
    loapledged_rod=1
    plaguebringers_armwraps=1
    plaguebringers_gloves=1
    renowned_guild_tabard=1
    shadra_silk_sash=1
    shirakess_pants=1
    tailored_members_shirt=1
    thornwoven_band=1
    vessel_of_skittering_shadows=1
    wand_of_zealous_purification=1

itemIDs: 157908, 158075, 158321, 159610, 159630, 162459, 162548, 163285, 165466, 165471, 165565, 165818, 165834, 166672, 170107, 170529, 69210, 89192

build: v8.2.0-01
level: 120 (120)
class: ROGUE
spec: outlaw

talents: acrobatic_strikes
    alacrity
    cheat_death
    dancing_steel
    prey_on_the_weak
    quick_draw
    vigor

azerite: ace_up_your_sleeve=2
    azerite_empowered=3
    deadshot=2
    elemental_whirl=1
    gutripper=1
    keep_your_wits_about_you=2
    longstrider=1
    overwhelming_power=1
    resounding_protection=1
    vampiric_speed=1

essences: none*, none

sets/legendaries/artifacts: none

gear:     azerokks_resonating_heart=1
    blight_toadskin_leggings=1
    deathsnap_jerkin=1
    deathstalkers_shoulderguards=1
    footbomb_championship_ring=1
    galecallers_boon=1
    gonk_outrunner_belt=1
    heart_of_azeroth=1
    honorbound_outriders_bracers=1
    honorbound_outriders_gloves=1
    igneous_winterskorn_loop=1
    irontide_captains_hat=1
    kraggs_rigging_scalers=1
    renowned_guild_tabard=1
    soulrending_claw=1
    tailored_officers_shirt=1
    voiddrenched_cape=1
    zemlan_slicer=1

itemIDs: 155862, 155888, 157916, 157942, 158075, 158132, 159289, 159345, 159462, 159612, 159614, 160269, 163309, 163437, 165477, 165680, 69210, 89194

**Comment by Hekili** [comment]
I'll take a look after you complete the whole ticket.  Thanks!

**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by xiiblitz** [comment]
what other information do you require??

i linked from the issue reporting tab from my warlock and rouge

**Comment by Hekili** [comment]
Screenshots
If applicable, add screenshots to help explain your problem.

WHEN SUBMITTING AN ISSUE:

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot. This is not a screenshot. A snapshot can be generated by binding the Pause feature on the Toggles tab. When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab. Copy and paste this to pastebin.com and provide the link here.

PUT SNAPSHOT LINK HERE:

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located. You can paste the error information here or use pastebin.com for that as well.

PUT ERROR MESSAGE(S) HERE:

**Comment by Hekili** [comment]
(Also, upgrade to v8.2.0-02 and recheck, please.  The first note in the template is to make sure you're using the latest.  Thanks.)

**Comment by xiiblitz** [comment]
![image](https://user-images.githubusercontent.com/52292516/60285265-7480e000-9905-11e9-8a61-103e24c1b902.png)

![image](https://user-images.githubusercontent.com/52292516/60285319-9a0de980-9905-11e9-94c7-61b7e3949827.png)


the twitch app only shows me v8.2.0-0.1

**Comment by xiiblitz** [comment]
![image](https://user-images.githubusercontent.com/52292516/60288043-43a3a980-990b-11e9-9e22-95909dcabe95.png)


can you provide a link to the latest update because i can't seem to find it

**Comment by Hekili** [comment]
Thanks.  I'll take a look.  I'm fixing an issue that will get 8.2.0-02 posted, but I'll see if I can find an issue on my Warlock myself.

**Comment by Hekili** [comment]
8.2.0-02 should be on Twitch now.

**Comment by Hekili** [comment]
If your Warlock still doesn't work, please type /hekili and look at the Destruction tab.  Make sure Enabled is checked and a Priority is selected.

![image](https://user-images.githubusercontent.com/9438134/60290548-fc0b2680-98e6-11e9-95fe-53152de5a270.png)

Also, try pressing ALT-SHIFT-P to pause the addon and see what happens.  Then check /hekili > Snapshots and see if you can open a snapshot re: addon decision-making.

**Comment by xiiblitz** [comment]
![image](https://user-images.githubusercontent.com/52292516/60290836-87011680-9911-11e9-95d8-579052537d3d.png)
![image](https://user-images.githubusercontent.com/52292516/60290873-997b5000-9911-11e9-8a28-a00a970f368e.png)

still doesn't seem to be working after update

**Comment by xiiblitz** [comment]
it's working now didn't realise the position had reset thank you for your help
