### ISSUE TITLE
[REC] Affliction recommends cancelling decibolt buffed DS when you get a tier proc

### ISSUE THREAD

**Issue by dubudevs** [Hekili/hekili#1536]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Playing MW lego a large amount of your damage comes from decibolt buffed drain souls, which should NOT be cancelled when you get a tier proc, unlike the rest of the time when you are fishing for tier procs with DS and want to spend them as soon as possible.

I am checking now with aff APL writers for the specific cases when you DO want to cancel DS with tier procs, eg is it a gain to extend MW if it will fall off in the middle of the DS. I highly doubt it is, because the decibolt buff is far larger than the MW buff.

### How to Reproduce

Play NL aff with MW lego, cast decibolt, cast DS, get tier proc and observe recs.

### Snapshot (Link)

I am channeling DS with decibuff and this is the rec the moment I noticed it, with a while left on the DS cast.
https://pastebin.com/9uwy9Xp2

### Contact Information

dubu#2080

**Comment by Hekili** [comment]
This was a little hard to read.

The issue here is a functional difference between SimC and the addon.  The addon has no way to know *why* you cast a particular Drain Soul -- you could've cast because it was the addon's recommendation or your cat might've walked across the keyboard.  The addon has to consider all "interrupt_if" conditions and if any of them pass, the channel is considered interruptible.

The solution for addon purposes is to ensure all of the "interrupt_if" conditions for Drain Soul will fail when you don't want Drain Soul to break.  If you want to write out in more detail, explicitly clarifying when canceling would be correct vs. when it would not be, I'll explore it further.  But, uhh, help me out with full words and bulletpoints.

**Comment by Hekili** [comment]
Test fix is here:  https://github.com/Hekili/hekili/releases/download/v9.2.5-1.0.3-alpha1/Hekili-v9.2.5-1.0.3-alpha1.zip

**Comment by Hekili** [comment]
This is live; feel free to reopen the ticket if you're seeing issues.
