### ISSUE TITLE
Reverse Harm Logic

### ISSUE THREAD

**Issue by behub-au** [Hekili/hekili#159]
Please describe your idea or feature and when it would be useful.
With the recent change to Reverse Harm logic where it will suggest using it on a group member,  is it possible to have a toggle for a different set of conditions?

Just a simple check for focus friendly below 92% or yourself.  Just is a easier game play option than having to find the party member below 92% in the frames, hover over (or click) them and use Reverse Harm. The Focus / yourself setup just allows you to put a member on focus (a tank in raid for example) and if it pops up with like a 'F' (or the current cycle target display) then you know to use it on focus or yourself.

Personally I would not want the party option. I don't know if there is a toggle for that yet. New version up on curse is throwing errors. Making a post about that now.

**Comment by Hekili** [comment]
It's worth exploring; I can potentially offer a spec option to select from a list of potential targeting options.

Let's look at the most useful options:

1.  Check yourself (generally alright, but may not be the most-effective, because 8% of a tank's health is potentially more damage).
2.  Check your focus (leaves you to manage who is checked, but potentially sets you up to misuse -- maybe you're in a raid with 2 tanks, your Reverse Harm would be delayed when your tank is not taking damage).
3.  Check the tank's (or tanks') health.  Would need to indicate who they are.
4.  Check the target's target (who will be a tank under ideal circumstances).
5.  Check anybody in your group/raid.

Okay, now we need to think about how to indicate who to hit:

1.  If it's yourself, show nothing.  Just assume you'd heal yourself?
2.  If it's someone else, show... What?
- The cycle-target indicator?
- Their name?
- An indicator on their raid frame?
- Something else?

So what would be the options that people would need for this to be effective, and how do we show that in an effective way?

**Comment by behub-au** [comment]
I’ll have a proper read of this when I’m home, but is there or can you add a focus condition ? Instead of target health I can check a focus target and if they are friendly. I can just adjust the rotation for my personal needs outside of the default solutions.

**Comment by behub-au** [comment]
I think a spec option as a drop down would be great. I'd pick a focus or target of target option for myself. I would always opt out to have to react to using it on a party member. At least then it would be my responsibility on reacting correctly. 

I agree with the concerns of point 2.

Target of Target would feel easy to manage personally. It's easy to have a modifier on an ability where it goes to @focus / @targettarget.

I suppose for indicators it would require defining new ones and would they be able to be used elsewhere and not just for monk. Would they add complexity to a new user, or even current ones who aren't expecting it.

For me simple indicators like a 'F' for Focus or 'TT' for Target of Target appearing on the button would be enough. I could manually manage that with conditions that check focus / targettarget by using a caption too.

**Comment by AlviSVPP** [comment]
I'm with behub-torch on this one, an option to display "TT" or "F" or "Self", say above the priority icon, would be ideal for me. 
If we go with just checking ourselves and the target's target (which would ideally be the tank indeed), maybe just the target swap icon is sufficient.

**Comment by AlviSVPP** [comment]
An important thing that's missing from the Reverse Harm logic at this point is taking into account the health deficit on the possible targets (say, ourselves and the targettarget). 
RH heals the target for 8% of its missing health and converts that heal into damage, so the gain would be way larger when it goes onto a tank than ourselves. 

Right now the addon's logic goes "if we're missing 8% health, suggest RH on ourselves, then check the other targets/group/focus" when it should compare the health deficit of the targettarget (or any other target for those who'd like that) as well, and then suggest the better target.

**Comment by GoldObama** [comment]
Another thing to note is that In a pve situation, you should be casting reverse harm just about every 10 seconds, regardless of if you or the targettarget is missing 8% health, at least according to the windwalker discord. I've tested the current RH logic a little and as far as I can tell this isn't the way its currently working.

**Comment by Hekili** [comment]
-05 release will scan the raid for the largest health deficit in your party/raid and put their name on the icon.

I may also add a toggle that will light up the raidframe of the optimal RH target.  I'd like your feedback on this!

**Comment by AlviSVPP** [comment]
At this point I believe it's mostly a question of usability in a real raid condition at any given point. And to be honest, I'm not willing to go to the extent of looking at the raid's unitframes and throwing a heal on someone who may even be out or range/LOS when I only have a split second of decition time for that. 

The macros recommended by Babs on the Peak discord are simple: 
- yourself
- targettarget (which hopefully is the tank + is in range)

Going for more than that will probably be detrimental to gameplay (at least for me). 

So I'd appreciate some kind of toggle to enable the "larger scans" beyond just myself & targettarget/focus. 
But for those that are willing to go beyond that, glowing up the unitframe sure is handy.

**Comment by Hekili** [comment]
I may allow for a simpler setup, but you still run the risk of doing 0 damage with Reverse Harm a fair portion of the time (especially in non-raid settings) if you aren't looking for a target.

As a Feral Druid, I'm pretty used to looking to dump a Regrowth where it's useful and not just on myself.

Babs has a new post with a recommended WeakAura that lights up raid frames just as I'd described, too.  But I'll keep tinkering.

**Comment by AlviSVPP** [comment]
Yeah at some point Babs had a macro that also had a @mouseover part just for that, but since then he got back to the simpler macros (seen in WW-discussion). 
On the topic of options, a slider to define the threshold of missing life% would be awesome as well, since a static 8% is too harsh a condition to wait for.

**Comment by Hekili** [comment]
I am not sure a slider is useful, tbh.  It only takes a very small % of damage for RH to be better than Tiger Palm.  I have RH requiring a 2% health deficit when soloing, for instance.

**Comment by AlviSVPP** [comment]
Oh true, I didn't notice that specifically when I checked. Yeah that should be good enough.

That leaves us with the issue of the rangecheck; not only for the heal range (10y from me), but also for the damage part (5y from the target healed), which mostly leads to why it's going to be bothersome to take all those factors into consideration instead of going for the "safer" choices like tank/ourselves
