### ISSUE TITLE
[BUG] Shadow Spec Rotation Helper Displays While In Holy Spec

### ISSUE THREAD

**Issue by jmtenet211** [Hekili/hekili#1618]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

As the title states, the Shadow Spec Helper is displaying when in a non-DPS spec. This is quite odd. I have taken screenshots to show the behavior.

### How to Reproduce

1. Load game.
2. Select priest.
3. Switch to shadow spec (Hekili displays properly)
4. Switch to holy spec (Hekili continues to display).
5. Look all over the web for reasons why this might be happening.
6. Reach out to community and post ticket.

### Player Information (Link)

https://pastebin.com/ACnAjddG

### Error Messages (Link)

https://pastebin.com/ACnAjddG

### Additional Information

Nothing to add. There is NO error being pushed to BugSack. I can say that I am in Shadow Spec...queueing for random dungeons while questing....and when the spec is switched automatically by the game when entering the dungeon as a healer, the issue tends to show.

### Contact Information

DocSkillz#5401

**Comment by jmtenet211** [comment]
![Hekili - Shadow Spec](https://user-images.githubusercontent.com/113951822/191142124-0cccf4ca-3c62-4599-8510-5c09fdea6050.jpg)
![Hekili - Holy Spec](https://user-images.githubusercontent.com/113951822/191142132-01bb7851-42ac-4660-b617-b01d354f3e9a.jpg)

**Comment by Kerberos9** [comment]
I can confirm this happens when you queue as a different role and get changed automatically. The addon probably doesn't change the spec until it sees the "spec change" event manually, and thus doesn't change when joining a dungeon. Not specific to spriest, I had this happen on my monk.

**Comment by Hekili** [comment]
That's one scenario that can trigger it, it seems.  I'll be posting a tentative fix for that scenario, which will recheck your specialization before continuing to generate recommendations.  One part of this issue was that if it takes 2+ frames to generate recommendations, and your specialization changed between frames, when the recommendations thread resumed it would already have passed that checking.

It's very likely for scenarios where you've swapped from a DPS spec to an unsupported healer spec, the addon auto-generated default options for the unsupported specialization.  That would mean you could have a spec invisibly enabled that has no actual module for the addon.  I'm working on sanity-checking that right now.

Thanks for these reports.

**Comment by Kerberos9** [comment]
Just in case I'll add that it happens to me as Windwalker into Brewmaster monk, which both have supported rotations.

Thanks for the support!

**Comment by Hekili** [comment]
Yup, that case should be covered by the solution that I'm testing.

* When a specialization change is detected normally, the event handler will kill the recommendations thread and force it to restart on the next frame.
* Before resuming the recommendations thread, the addon will check to see that your current specialization matches the specialization you were in when the thread started.  If they don't match, the addon kill the thread and force the event handler for specialization changes to fire before allowing a new recommendations thread to start.

What I am testing now is whether there is any odd behavior that results from killing the thread.  Right now, the UI elements of a display are locked while recommendations are being generated for that display (to avoid updating with incomplete recommendations, like having only your first icon appear until recommendation 2 and 3 are calculated).  If a display is locked when the thread is killed, it will remain locked until the next set of recommendations is generated for that display.

It *should be* fine and generally not noticeable since this is happening during spec changes and dungeon teleports, but I want to be sure that there isn't a scenario where a display remains locked indefinitely.  In fact, now that I think about it, I can probably purge recommendations if you swap to a spec that doesn't have a module (healers) and let the display update itself so it doesn't stick with old recommendations for your previous spec.

I haven't actually seen it stick since making these changes, but I'm still testing.

**Comment by dubudevs** [comment]
The same happens when you get changed from a supported spec to another, eg WW to BM monk. To trigger BM recommendations you need to reload.

**Comment by jmtenet211** [comment]
Yeah,

A quick /rl resolves the issue. At least in a "workaround" mode. Not really
a big deal...its probably difficult to code for/account for auto-switching
of specs using the dungeon/raid finder.

**Comment by Hekili** [comment]
I have a tentative fix that I haven't shared yet.  Sorry for the wait, but (1) it's not really critical and (2) I'm pulled in at least 3 different directions right now for WoW while working 60+ hours.  I'm literally just out of hours in the day.

**Comment by jmtenet211** [comment]
No worries.

 

JMT

**Comment by Hekili** [comment]
This should be resolved.
