### ISSUE TITLE
 Arms warrior Rotation and overlap with sunder armor , and buffs ( battle shout , command shout )

### ISSUE THREAD

**Issue by Lillefot92** [Hekili/hekili#1659]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Rotation dont recommend mortal strike at all
Aoe seems wrong aswell, dont really recommend Cleave that much as it should 
Addons wants the to use sunder armor even if there is Expose armor or even Shattering throw on target already.
Addons wants to use Battle shout even when i have BoM ( improved) on me so i cant overtake it with mine, same goes with commanding shout.

### How to Reproduce

Enter as Arms warrior
look into rotation , singel and aoe 
overlap with sunder armor , expose and shattering throw
overlap with Battle shout and command shout
addont dont recommend slam or mortal strike with juggernaut talent

### Snapshot (Link)

https://pastebin.com/JxAjxrQM

### Contact Information

LILLEFOT92

**Comment by Hekili** [comment]
Ok, so filling out the ticket properly is critical.  You've listed a bunch of things, so let's go through them, starting with this:

> [pastebin.com/JxAjxrQM](https://pastebin.com/JxAjxrQM)

That's not a snapshot.  Here are the instructions for snapshotting, which were part of the original ticket template.

> Snapshot (Link)
> 
> Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.
> 
> * Log into your WoW character.
> * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
> * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
>   * You can change these keybindings in /hekili > Toggles if needed.
> * Type /hekili and press Enter.
> * Open the Snapshots section on the left side.
> * Select the display which is showing the recommendation (usually Primary).
> * Select the snapshot number (usually 1, if you took only 1 snapshot).
> * Copy all of the text in the lower box.
> * Paste the text to Pastebin (https://pastebin.com/).
> * Provide the Pastebin link here.
> 
> This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.
> If you do not provide this information, I cannot triage your problem.

I just want to stress, again, that a snapshot taken when you're actually seeing the issue you're concerned with, is critical.  Otherwise, it's like you're providing a colonoscopy and asking me to diagnose your toothache.  We're not looking in the right place to solve the problem.

Now, on to your specific issues:
> Rotation dont recommend mortal strike at all
> addont dont recommend slam or mortal strike with juggernaut talent

Provide a snapshot when Mortal Strike could've and should've been recommended, but wasn't.  That means, for example, that you'd have enough resources to Mortal Strike in the first place.

> Aoe seems wrong aswell, dont really recommend Cleave that much as it should

Provide a snapshot when you thought the addon should've recommended Cleave but didn't.  Again, make sure you have resources to Cleave.  If you have a reference/resource that you're basing your issue with not cleaving enough on, feel free to add a link to that as well.

> Addons wants the to use sunder armor even if there is Expose armor or even Shattering throw on target already.

This is a good call-out; the main issue is that I haven't finished implementing Rogues so viewing Expose Armor and Sunder Armor as the same debuff is not yet implemented.  IIRC, Shattering Throw stacks with Sunder Armor, though.

> Addons wants to use Battle shout even when i have BoM ( improved) on me so i cant overtake it with mine, same goes with commanding shout.

This is another good call-out, for similar reasons.  Overlapping/competing raid buffs are not really accounted for yet, but it's on my to-do list.

**Comment by Lillefot92** [comment]
https://pastebin.com/TeSwkp2T
here i see a "opening" for mortal strike to come in ,i belive you should use mortal strike when no procs are avaiable (Overpower and execute) , im not an expert on the rotation but thats when it feels like its the best timing for it to be used.
i noticed also that Bloodfury ( Orc racial ) is never recommend , i have it enabled in the addon but still no show.

For the Aoe , the addon for some reason wants me to use Thunderclap on CD when there are 2 or more targets , maybe this is correct but im not sure, feels strange that thunderclap is recommended and not Cleave.
https://pastebin.com/uFPTFxW0

also good call out on Shattering throw stacking with sunders.. thats my bad i didnt notice that

overall i hope this helps a little bit, as i said i might be wrong about the mortal strike rotation , but perhaps worth looking into in the future =)

thx for a great addon

**Comment by Hekili** [comment]
Sorry for the struggle with snapshots; these are not complete.  There's more text in the box that you didn't capture, unfortunately.  When you put the mouse in the box, press CTRL+A (to select all) and then CTRL+C (to copy).  That'll give you thousands of lines of text that explains why you're seeing what you're seeing, even though you can't see it all in-game.

**Comment by Lillefot92** [comment]
https://pastebin.com/hn79rZK0
https://pastebin.com/fuLt943G

this is both for singel and aoe i hope. :)

**Comment by Hekili** [comment]
> For the Aoe , the addon for some reason wants me to use Thunderclap on CD when there are 2 or more targets , maybe this is correct but im not sure, feels strange that thunderclap is recommended and not Cleave.

Read the linked guide re: the priority.

I'm making some priority updates that will go out today.
