### ISSUE TITLE
Feral Druid priority questions (Shred, Convoke)

### ISSUE THREAD

**Issue by somedhclass** [Hekili/hekili#1672]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

i was having problems with swap recommended on single target i swap to min 2 targets so it would force shred .... my next problem is it wont recommend a covenant with out incarnation ... even with the cd reduction there was 1 min 30 second left on incarnation and still no convoke recommend 

### How to Reproduce

https://pastebin.com/GViNittg

### Snapshot (Link)

https://pastebin.com/6twt1jYx 

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/fdpEaJW11suMMkcRWk8HAB

**Comment by Hekili** [comment]
> i was having problems with swap recommended on single target i swap to min 2 targets so it would force shred 

If you do weird things, you get weird results.  My best guess from what you're saying is that you are trying to force Shred vs. Swipe in single-target, which is not optimal in terms of converting Energy into damage.

> my next problem is it wont recommend a covenant with out incarnation ... even with the cd reduction there was 1 min 30 second left on incarnation and still no convoke recommend

Which snapshot is meant to reflect this situation?  In your first one, Convoke the Spirits is on cooldown for another 48 seconds.  In your second snapshot, you're in the middle of casting Convoke the Spirits.

You will need to provide a snapshot of the scenario you described -- Incarnation (or Berserk) on CD for a longer span of time than Convoke's cooldown, Convoke off cooldown, and Convoke not being recommended.  It's generally preferable to get past your opener before taking these kinds of snapshots so that your initial bleed setup is already completed as well, otherwise those abilities will fill up the queue before we get to look at Convoke.

**Comment by somedhclass** [comment]
https://pastebin.com/hAyha3wX

**Comment by Hekili** [comment]
No, that snapshot is not in combat. I'm going to decline this ticket and we'll just see how things go in Dragonflight.
