### ISSUE TITLE
Protection Paladin: Consecration

### ISSUE THREAD

**Issue by yuisyui** [Hekili/hekili#173]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
Just to be ready in advance, please actually fill out the form above.  Thanks.

**Comment by yuisyui** [comment]
Sometime after logging and doing some combat the protection paladin rotation will show to use consecration on cooldown, single target or multi, no error message occurs and happens inside or outside consecration.
Hekili works perfectly and i am unable to find a cause, reloading does fix it till it happens again however reseting the profile does not fix it, it has to be a ui reload -- sorry if its on my end.

talents are 1212312

EDIT: was able to find the cause, using a portal or zoning causes the issue wether consecration is up or not.

**Comment by Hekili** [comment]
Fill out the template so I have all the information I may need to diagnose and test.  Thanks.

**Comment by yuisyui** [comment]
**Describe the Bug/Issue**
Shows the use of consecration when its already active and your inside, will always tell you use to consecration on cooldown, reset profile does not fix, reload ui does.

**To Reproduce**
Go through a portal e.g Sithilus/Nazjatar.

**Expected behavior**
Tell user to use consecration when it is not active, when its active but you are not already inside or when all other abilities are on cooldown.

https://pastebin.com/kFMHU4Rh talents/gear
https://pastebin.com/dJbFudZV snapshot the reuse of consecration is the 4th ability shown if that helps
https://pastebin.com/wLbk7PNC snapshot but incombat with target dummy paused at same time best i could

**Comment by Hekili** [comment]
WHEN SUBMITTING AN ISSUE:

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

PUT ISSUE REPORT LINK HERE:

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
PUT SNAPSHOT LINK HERE:

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

PUT ERROR MESSAGE(S) HERE:

**Comment by Hekili** [comment]
The most critical part that is still missing is a snapshot when you are seeing this occur.  (See the instructions re: Snapshot, this is not a screenshot.)

**Comment by yuisyui** [comment]
added the snapshots to my other post.

**Comment by Hekili** [comment]
I think the part that is misleading is that the precombat entry for Consecration doesn't have any conditions and is still considered usable even if you're standing in Consecration.

The recommendations given otherwise make sense.  As far as I can tell, your consecration would be ready in the case where it shows up as the fourth recommendation.

That is where the significant change is to be found in the priority.  I will pull the precombat Consecrate since it is distracting.

**Comment by yuisyui** [comment]
The combat snapshot showing consecration to used as the 4th is incorrect according to the addon itself, when i took that combat snapshot all other abilties had charges and were ready to be used and the priority shows that consecration should be only be used when 1. it is not active, 2. it is active but not currently at your position and 3. when all other abilities, bar cooldowns and mitigation are on cooldown sorry for bad messages english is not my primary langauge, thanks again.

**Comment by Hekili** [comment]
So let's look at snapshots.  The first one:

1. SotR, mitigation 1, immediately (0.00s):
`! talent.seraphim.enabled[false] & action.shield_of_the_righteous.charges[3.00] > 2 & ! ( buff.aegis_of_light.up[false] & buff.ardent_defender.up[false] & buff.guardian_of_ancient_kings.up[false] & buff.divine_shield.up[false] & buff.potion.up[false] )`

2. Judgment, default 9, immediately (0.00s):
`( cooldown.judgment.remains[0.00] < gcd.execute[1.23] & cooldown.judgment.charges_fractional[2.00] > 1 & cooldown_react[true] ) | ! talent.crusaders_judgment.enabled[true]`

3. Judgment, default 9, in 1.23s (1.23s):
`( cooldown.judgment.remains[0.00] < gcd.execute[1.23] & cooldown.judgment.charges_fractional[1.25] > 1 & cooldown_react[true] ) | ! talent.crusaders_judgment.enabled[true]`

4. Consecration, default 8, in 1.23s (2.47s):
`! consecration.up[false]`

So, in this case, the double Judgment is more questionable (looks like I may need to improve the "cooldown_react" expression so that it is only true for a short time after an ability comes off cooldown, but that's not the issue we're looking at here).

The recommendation for Consecration is in 2.47s from the current time, and I see nothing that indicates that isn't reasonable.


Now, the second snapshot:

1.  SotR, mitigation 1, immediately (0.00s):
`! talent.seraphim.enabled[false] & action.shield_of_the_righteous.charges[3.00] > 2 & ! ( buff.aegis_of_light.up[false] & buff.ardent_defender.up[false] & buff.guardian_of_ancient_kings.up[false] & buff.divine_shield.up[false] & buff.potion.up[false] )`

2. Judgment, default 9, immediately (0.00s):
`( cooldown.judgment.remains[0.00] < gcd.execute[1.22] & cooldown.judgment.charges_fractional[2.00] > 1 & cooldown_react[true] ) | ! talent.crusaders_judgment.enabled[true]`

**Note, to reach default #9 at this point, default #8 has to have been overlooked.  In this case, Consecration was ready in 1.08 seconds, so Judgment was chosen because it was ready sooner.**

3. Consecration, default 8, in 1.22s (1.22s):
`! consecration.up[false]`

4. Judgment, default 9, in 1.22s (2.44s):
`( cooldown.judgment.remains[0.00] < gcd.execute[1.22] & cooldown.judgment.charges_fractional[1.50] > 1 & cooldown_react[true] ) | ! talent.crusaders_judgment.enabled[true]`


Both of these look valid.  Since the criterion we're concerned with here is `! consecration.up` which means "I am not standing in Consecration at that time", let's check that it works.

Here's a snapshot of my own Paladin:  https://pastebin.com/8SMr7Y33
`! consecration.up[true]`

So the addon is properly detecting whether I'm standing in Consecration.  If I walk out of Consecration, the addon quickly accounts for it and recommends Consecration again.

Everything appears to be working as intended on this end, consistent with the priority (which has been edited to remove Consecration as a pre-combat recommendation).

If I stand still and cast Consecration, I can watch Consecration move back into the queue as the duration of Consecration ticks away.  If I use Consecration and take a portal, the Consecration buff goes away and Consecration is recommended again as soon as it comes off CD.

**Comment by yuisyui** [comment]
Yes it works all fine till you use a portal or zone into dungeon / be summoned to raid, then hekili simply thinks that your never in consecration it was never a issue with the rotation only when the bug occurs, but i can just remember to reload every loading screen, thanks for all the hard work you put into this addon and thanks for all the replys!
