### ISSUE TITLE
Arms Missing, Fury Broken, Ret minor broken

### ISSUE THREAD

**Issue by Dov1an** [Hekili/hekili#1754]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Arms isn't displaying at all on zandalari warrior
Fury is only showing Whirlwind

Belf Ret Pally is using all attacks except templar's verdict, if not intentional. 

### How to Reproduce

1. enter game as prot warrior
2. switch to arms
3. switch to fury

1. enter game as ret pally
2. verdict never comes up

### Player Information (Link)

https://worldofwarcraft.com/en-us/character/us/stormrage/korbaraj

### Error Messages (Link)

n/a

### Additional Information

https://worldofwarcraft.com/en-us/character/us/stormrage/mylenthil

**Comment by xathian** [comment]
Doesn't really matter much, Hekili is basically worthless for Warriors right now anyway. The dev didn't pull down functional prepatch APLs from the Warrior Discord (I don't blame him, they're hard as hell to find), he just imported Simc's defaults which are not updated at all and are just copypasted from Shadowlands.

This leaves Fury not ever casting Avatar, Slam (Annihilator), Thunderous Roar, Shockwave, Spear of Bastion or Odyn's Fury regardless if you have the talents. It also doesn't account for the Raging Blow priority change due to Slaughtering Strikes talent, nor WW priority change with Storm of Swords. 

Arms is even worse off, its priorities have shifted quite a lot with several spec choices on the new trees and again these are ignored entirely because it's a copypasted Shadowlands APL.

Right now I'm trying to take the latest Warrior APL from Raidbots (Which was given to the raidbots dev by the Warrior Discord without it being made public) and put that into Hekili to get it properly working. Problem is the Raidbots APL isn't public in its raw Simc input form. You can only get it by running a sim on your character then clicking the "Full HTML Report" button and scroll all the way down to the APL section of that page. But that section isn't formatted the same as the raw input so I have to copy it over and reformat it into a Simc input so Hekili can read it and it's 4:30am so I'm done for tonight lol

Edit: Ok got it working for Fury. If you want to use it open hekili, expand Priorities on the left side, select Fury and go to the Profiles tab. Delete the block of text in there and replace it with this, then press Accept and then Import

```
actions.precombat+=/recklessness,if=!runeforge.signet_of_tormented_kings.equipped
actions.precombat+=/fleshcraft
actions=pummel
actions+=/auto_attack
actions+=/charge,if=time<=0.5|movement.distance>5
actions+=/heroic_leap,if=(raid_event.movement.distance>25&raid_event.movement.in>45)
actions+=/potion
actions+=/pummel,if=target.debuff.casting.react
actions+=/ravager,if=cooldown.avatar.remains<3
actions+=/use_item,name=gavel_of_the_first_arbiter
actions+=/blood_fury
actions+=/berserking,if=buff.recklessness.up
actions+=/lights_judgment,if=buff.recklessness.down&debuff.siegebreaker.down
actions+=/fireblood
actions+=/ancestral_call
actions+=/bag_of_tricks,if=buff.recklessness.down&debuff.siegebreaker.down&buff.enrage.up
actions+=/avatar,if=talent.titans_torment&buff.enrage.up&(buff.elysian_might.up|!covenant.kyrian)
actions+=/avatar,if=!talent.titans_torment&(buff.recklessness.up|target.time_to_die<20)
actions+=/recklessness,if=talent.annihilator&cooldown.avatar.remains<1|cooldown.avatar.remains>40|!talent.avatar|target.time_to_die<20
actions+=/recklessness,if=!talent.annihilator
actions+=/spear_of_bastion,if=buff.enrage.up&(buff.recklessness.up|buff.avatar.up|target.time_to_die<20)
actions+=/whirlwind,if=spell_targets.whirlwind>1&!buff.meat_cleaver.up|raid_event.adds.in<2&!buff.meat_cleaver.up
actions+=/call_action_list,name=single_target
actions.single_target=rampage,if=buff.recklessness.up|buff.enrage.remains<gcd|(rage>110&talent.overwhelming_rage)|(rage>80&!talent.overwhelming_rage)|buff.frenzy.remains<1.5
actions.single_target+=/execute
actions.single_target+=/condemn
actions.single_target+=/bloodthirst,if=buff.enrage.down|(talent.annihilator&!buff.recklessness.up)
actions.single_target+=/thunderous_roar,if=buff.enrage.up&(spell_targets.whirlwind>1|raid_event.adds.in>15)
actions.single_target+=/odyns_fury,if=buff.enrage.up&(spell_targets.whirlwind>1|raid_event.adds.in>15)
actions.single_target+=/onslaught,if=!talent.annihilator&buff.enrage.up|talent.tenderiz
actions.single_target+=/raging_blow,if=charges>1
actions.single_target+=/crushing_blow,if=charges>1
actions.single_target+=/bloodbath,if=buff.enrage.down|talent.annihilator
actions.single_target+=/bloodthirst,if=talent.annihilator
actions.single_target+=/rampage
actions.single_target+=/slam,if=talent.annihilator
actions.single_target+=/bloodthirst,if=!talent.annihilator
actions.single_target+=/bloodbath
actions.single_target+=/raging_blow
actions.single_target+=/crushing_blow
actions.single_target+=/whirlwind
actions.single_target+=/wrecking_throw
```

That will give you the most up to date Fury APL right now. Caveat is it only has an APL for single target, as is the case with all Raidbots APLs at the moment.

**Comment by Hekili** [comment]
> Doesn't really matter much, Hekili is basically worthless for Warriors right now anyway. The dev didn't pull down functional prepatch APLs from the Warrior Discord (I don't blame him, they're hard as hell to find), he just imported Simc's defaults which are not updated at all and are just copypasted from Shadowlands.

Yeah, it'd be great if SimulationCraft priorities for Dragonflight were found in the dragonflight branch of SimulationCraft.

In the future, @xathian, when there are out-of-date priorities, you can just put in a ticket with the updated APL and its source and I'll check it out.  Thanks for posting this here.

@Dov1an:  Please don't put 3 separate issues in one incomplete bug report.  If you're not seeing recommendations for Arms, put in a Recommendations ticket for Arms with the required information.  I'm loading the Fury priority that xathian provided now.  Retribution Paladin is also fixed based on another ticket.  There will be a new release available in a few minutes.
