### ISSUE TITLE
Further Customizing When Abilities are Suggested

### ISSUE THREAD

**Issue by ghost** [Hekili/hekili#177]
An example would be being able to disable certain abilities from being recommended based on your targets buffs/debuffs. I feel as this may be the most universally helpful way to expand upon the system.

For instance, if you knew an ability made something immune to magic damage, you could manually go to each of your magic abilities and set them not to recommend when the target is under those effects.

This function is sort of implemented already with the ability to disable overall based on amount of targets and so forth, but allowing further customization regarding this would be a huge improvement and a great feature overall.

**Comment by Hekili** [comment]
To some extent, this could be supported going forward.  The problem is, it ends up requiring keeping a database of effects that are stuns, full immunes, partial immunes, etc.  As that list gets longer, checking whether a target is immune/CC'd/etc. becomes more expensive in terms of CPU time, which means you end up reducing your FPS looking for marginal, edge-case stuff.

You can already use most of the expressions from a SimulationCraft query, but a few things aren't really populated.  For instance, `raid_events.adds.in>10` is how you'd check to see if the next wave of adds, if any, will arrive in more than 10 seconds.  The addon doesn't predict fight mechanics, so it will lie and always say that adds will show up in an hour.  However, when you do have additional enemies up, the addon will show you the count (`active_enemies`) and the `raid_event.adds.up` expression will be `true` since that's not predictive, that's current information.

The second paragraph is a bit of a tangent.  For things like this, I'd say I need details of a specific aura that you'd want to detect, a use-case for it, and an example of your use-case.

The use-case part is really complicated, because you'd need to develop a sim that shows your priority is more effective in those particular conditions vs. just using the same priority and exercising your judgment about a fight mechanic.

**Comment by ghost** [comment]
One situation I can think of right off the top of my head would be the [Repeat Performance](https://www.wowhead.com/spell=304409/repeat-performance) skill in the [Queen's Court](https://www.wowhead.com/guides/queens-court-azsharas-eternal-palace-raid-strategy-guide) fight.

It's technically a debuff on your character instead of on your target, but I think it will fit for the example.

The rotation addon doesn't take into effect the silence you receive when using the same skill twice in a row during this phase of the fight. Presumably, most classes would do better by not repeating the same skill even if normally it would be a less optimal choice, due to the two second silence you receive if you do.

I definitely understand the resources argument to this suggestion as well. Is there any situation where the information could be manually input by the player on a case by case basis, allowing the extra customization without bogging down the addon for everyone who uses it?

**Comment by Hekili** [comment]
You can already customize your priority, but different buffs/debuffs are added on a case-by-case basis.

The addon is already aware of Repeat Performance.  But the priorities don't account for it beyond waiting for it to fall off.

**Comment by Hekili** [comment]
Note:  I just double-checked Repeat Performance vs. what appears in WarcraftLogs and found the spell ID was off by 1.  So that'll be corrected and the ability delay will be functional at that time.

**Comment by Hekili** [comment]
I'm going to close this ticket, but feel free to report back if the Repeat Performance solution doesn't feel good.
