### ISSUE TITLE
How to create a rotation for ADK in PVP?

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#182]
Good day.  I apologize in advance.  But help please.  I want to play PVP with your addon, I am completely satisfied with your rotation in the addon.  But I have no knowledge, experience, how to add Necrotic Strike, for the place of Scourge Strike.  And also add a simple condition for Death Strike, in the form:
 1. What if the HP character has reached 75% of the mark and lower, then he suggests Death Strike; if above 75%, then we beat Death Coil.
 2. And if Dark Succor is triggered, then we apply the condition as with Sudden Doom to the free Death Coil.
These are the banal conditions I want to add to your rotation add-on, but I do not know where, what and how, to change it.  And correctly change without violating the rotation.  I really hope that you can help, as you have already done so much for us.  Thanks for your work.

P.S.  I really apologize for my EN.  I am fluent in RU language, but not EN.  If you can write to RU and you will understand me later, I can describe the request more correctly.

**Comment by Hekili** [comment]
I'll assume you're able to locate /hekili > Priorities, make a copy, and edit the copy with basic stuff (like adding an entry or modifying an entry in one of the lists).  When you've made edits to the copy of the Unholy profile, you can check "Active" or select it via /hekili > Specializations > Unholy > Priority.

1.  Add an entry for Death Strike, criteria: `health.percent <= 75`.  Add an entry for Death Coil, criteria: `health.percent > 75`.

2.  Add an entry for Death Strike, criteria: `buff.dark_succor.up`.

As far as prioritizing it, that part is going to be up to you to figure out.  For Death Strike stuff, I'd probably look at including it in the `mitigation` list somewhere or otherwise in the `default` list.  Death Coil probably belongs in the default priority.

PvP is a very different beast and sim tools generally don't know what to expect vs. a player.

**Comment by geraint425** [comment]
Thanks for your reply. I try to add these conditions to the rotation. By the way, I was just trying to change the terms of Scourge Strike to Necrotic Strike. And it turned out that in the rotation it was not displayed properly, there was simply no icon. I suspect I did something wrong. As for the rotation in PVP, what you described, I realized that you wanted to say that there are no clear conditions what to do, etc. But let's say there are such guides as on Wowhead and icy-veins where the base rotation is described, by the way, it’s enough for the eyes. The man was able to implement the rotation of PVP with the help of the addon GSE: Gnome Sequencer Enhanced: Advanced Macros. Where the rotation is simply repeated sequentially. You currently have a rotation for the ADC. It is enough to simply change Scourge Strike to Necrotic Strike and add the conditions that you described about the Death Strike. And here it is the basic rotation for PVP. And already subtle moments in terms of mills, protection, etc. This is what we do with pens without addon.
I will certainly try to rotate, not sure what will happen, but still for the tip where to dig thanks from you.

**Comment by Hekili** [comment]
Troubleshooting that ability would need all the information for a regular ticket, including snapshots.  But my best guess is that you're using the current release, and Necrotic Strike has had some adjustments in my latest alpha releases.

And yes, you can write a priority based on guides (and I have).  But you have to consider the implications and that sometimes guides have vague conditions or conflicting requirements that are hard to explain to a computer.  But you are certainly welcome to give it a shot.

**Comment by geraint425** [comment]
Well, I now use the macro that does the basic rotation.
/cast [combat] Unholy Frenzy
/cast [combat] Dark transformation
/cast [@player] Death and Decay
/castsequence  reset=combat  Festering Strike, Festering Strike, Necrotic Strike, Necrotic Strike, Necrotic Strike, Festering Strike, Necrotic Strike, Necrotic Strike, Outbreak
/cast Soul Reaper
/cast [combat] Death Strike
Such a rotation is used in one macro in PVP.
I understand it is enough for me to simply create a new rotation sheet, sign it PVP and add a sequence like this and it will work? If so, that's great. If not, then you can at least one example of how it should be. So based on your example, I was able to continue to rotate based on the guides with Wowhead and Icy

**Comment by Hekili** [comment]
No, what that macro reflects is a sequence of actions.  It doesn't really convey how to prioritize abilities aside from doing them in that order.  You'd need to explore why you Fester 2x before Necrotic Striking 3x and so forth, and include those conditions in your priority.

**Comment by geraint425** [comment]
So I can not figure out why. I just consistently made a macro and that's it. Without any condition. And just repeat it in a circle. I tried to do a pvp rotation with Wowhead, but it didn't work out. I do not have enough skill yet to do it correctly as you do. I just added:

Add an entry for Death Strike, criteria: health.percent <= 75. Add an entry for Death Coil, criteria: health.percent> 75.

Add an entry for Death Strike, criteria: buff.dark_succor.up.

These two conditions, in PSU, they work fine. on ADK. But with the pvp rotation, I could not cope). By this, I will continue to use just this macro. Maybe there is a person who has already made a rotation for himself and he will share it under PVP
Thanks again for the help.

**Comment by Deaddraw** [comment]
Helle Hekili,

thanks for your great addon! Im using it with DK in shadowlands. I just wanted to know, if its possible to put Death Strike in my Rotation as DPS DK in the defensive section, if the conditions <75% AND Dark Succor up are met.

The Problem is: If i do it the way you wrote above, it just doesnt work. So here what i did, i wrote the following in the conditions window right under the enable Action with Death Strike. Both doesn't work.

https://imgur.com/a/i25lqIZ

if i do not write criteria, atleast there is no error, but hekili doesnt recognize the buff correctly and its remaining false whole time
https://imgur.com/BpoBCL8

Is it possible to get it work?

Thanks for your replay!

**Comment by Hekili** [comment]
Yes, `criteria:` doesn't go in the box.

If you don't actually have Dark Succor up, it will not show.  If you have Dark Succor up and it still says `false`, show me the spell ID of your Dark Succor buff.

And don't use a really old, closed ticket for this.  :)
