### ISSUE TITLE
Feral Druid only recommending Primal Wrath in both Aoe and single target

### ISSUE THREAD

**Issue by Memorialized** [Hekili/hekili#1892]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

I'm doing some open world leveling and my feral druid seems to only be recommending primal wrath as a finisher. Even while rip is up on the target, it won't recommend ferocious bite or any other finisher. 

My profile is default and no settings have been changed.

### How to Reproduce

1. Enter a single target scenario with a feral druid
2. Build combo points and wait for addon to recommend a finisher
3. Only finisher recommended is Primal Wrath

### Talent Loadout

BcGAGX1kx6Mci9Zl2t+S+sRoPCAAAAAAIkU0gkkEJFNARyBSCAAAAAAaCACAISSSwCiIBAAAAAAAIB

### Snapshot

https://pastebin.com/4Yrcst52

**Comment by Hekili** [comment]
Yes; that's correct.  That's the talent build you selected.  With Tear Open Wounds and Rip and Tear, using Primal Wrath to consume some of your Rip and refresh/extend it is intentional.  There may be further tuning for that later (i.e., determining that you could get a Ferocious Bite off and then PW again before Rip falls off), but this is a correct interpretation of the priority.
