### ISSUE TITLE
How we choose the talnet to fit Hekili?

### ISSUE THREAD

**Issue by daxigua249121589** [Hekili/hekili#1898]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

Because the talnet has been renew, how we choose the talnet which fit the Simulation and hekili?

**Comment by vond82** [comment]
As long as you use the latest version of Hekili and one of the supported specs it just works. Do /hekili in game to see what specs are currently supported. If your spec isnt on that list, just remain patient until its added. :) The prepatch changed a lot of things so its a lot of work for Hekili to implement each spec

**Comment by Hekili** [comment]
You don't pick your talent build around the addon.  The addon priorities are written to work with any talents.  Because it is prepatch and early in Dragonflight, some may require further updates.  You don't need to import anything, and you certainly should not pick your class/specialization/talents around the addon.
