### ISSUE TITLE
Protection Warrior never recommends Revenge

### ISSUE THREAD

**Issue by jmusick** [Hekili/hekili#1987]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Hekili will never recommend Revenge as Prot Warrior.

### How to Reproduce

Play Prot Warrior with Hekili

### Talent Loadout

BkEAR5QSZgdnGefDo4ho9ZGXKLgAAAAASSSkkQSLpkgWBRgQRiElkEgAAtQSCIQIAAAAAAAABAAlGA

### Snapshot

https://pastebin.com/xy6XwJJf

**Comment by Wyste** [comment]
Check to see if you have the 'Only Revenge when Free' option checked within the spec options. See screenshot below for finding it.

![image](https://user-images.githubusercontent.com/5103286/202739423-017170ec-8099-4a66-9046-2a0f21c6a689.png)

**Comment by Hekili** [comment]
Yeah, they do have `free_revenge` enabled per the `settings` section of the snapshot.  That setting exists to help ensure you keep some Rage reserved for your mitigation abilities, but it's not intuitive.  @Wyste, we may want to think about revising that option to use a Rage reserve threshold instead of being simply on or off.

The snapshot also shows a warning for the Outburst buff being referenced without being defined.  I'm taking a look at that now.

**Comment by jmusick** [comment]
I overlooked that setting for Revenge. Sorry

**Comment by Wyste** [comment]
Thanks jmusick. I agree with Hekili though, there's three approaches I feel here for long-term design intent.

1 - Remove the option entirely. DF's prot changes have made TClap substantially better and slowed the spec down. Having Shield Slam + TClap filler is more frequent and helps break up any Revenge spam seen. This really depends on simc APL's being optimal though.

2 - Change the option to only use revenge while maintaining enough rage to use a defensive (Ignore Pain or Shield Block).

3 - Default the option to 'off' by default, to prevent users feeling the spec is broken out of the box.

**Comment by Tzuyume** [comment]
Sorry to butt in on another conversation but is it possible to do something similiar for Execute as it uses up all rage for execute and you get no rage for defensives if you follow hekili. Like an option to turn it off or maybe like wyste say add execute as a condition when you have too much rage and is able to execute.

**Comment by Wyste** [comment]
Good point, it does feel unintuitive to have Execute spam and be rage starved at the end of a fight, especially if it were a raid boss kind of fight, I can see how that would be problematic.  This could maybe be solved with just a BOSS or TTD conditional in the APL though.

Lets wait a bit to see what Hekili's thoughts on the whole matter are, and if he has any different direction he feels would better.

**Comment by Hekili** [comment]
For tanks, design intent is generally to keep you able to maintain rotational defenses / active mitigation since otherwise you die.  That's why `free_revenge` has been a default; it prevented you from depleting your rage when you need it.

A `reserve_rage` slider that impacts Execute and Revenge, such that they are only recommended if free or if using the ability won't spend below the reserve threshold, seems like the most straightforward option.

Any choice here is going to result in more questions, though.

**Comment by Hekili** [comment]
This is changed to a slider in 1.6.2; it will work to reserve enough Rage to Ignore Pain or Shield Block by default.
