### ISSUE TITLE
Question/Inquiry: Action recommendations for Bar 2 aren't showing binding

### ISSUE THREAD

**Issue by karpana** [Hekili/hekili#1995]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

Not a feature request, but a question/inquiry.

I use Bar1 and Bar2 for all my combat actions bars/buttons.
Bar1 has keybindings for `1` thru `=` keys on my keyboard.
Bar2 has keybindings for `F1` thru `F12` keys on my keyboard.
All Keybindings were set (many years ago now) using Blizzard's Keybinding Interface.

Action recommendations for Bar1 are properly showing the keybinding in Hekili 
Action recommendations for Bar2 aren't showing the applicable keybindings

What setting(s) do I have to change to resolve this?

**Comment by karpana** [comment]
This might be related to #1982 
As I also use Bartender.

I'll review this other item and advise.

**Comment by Hekili** [comment]
I'll need more information to know what's going on.

Since this doesn't seem recommendations related, I'd need the information from /hekili > Issue Reporting at the very least.  I just posted an update in the past half hour or so; are you having this with the latest version (v10.0.2-1.5)?

If so, did it just start with the latest version?  Or has this been an issue for a while?

**Comment by karpana** [comment]
I'm closing in favor of #1982, as I also using Bartender and just noticed/realized I have bar2 keybound with bartender (and not the stock UI)

Thank you for the quick response/reply.
