### ISSUE TITLE
Add an indication when to activate spells for Fire Breath Eternity Surge abilities

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#2002]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

You have an indication already in the form of an indication at which stage to press. But I would like to see an icon that would be responsible for when it is better to click. An example of the Eternity Surge ability, it is recommended to use it at the 1st stage for the purpose, but in AOE it is recommended to use it at the 2nd second. So when I click on Eternity Surge, the addon drew a cross on top of the icon if it's not worth pressing the ability now, and as soon as Eternity Surge reached stage 2, the addon showed green what needs to be activated now. This would simplify the tracking of abilities, so as not to accidentally click earlier than the specified time, when there is still no necessary charge on the ability. Thank you in advance if it will be possible to do this with these two abilities

**Comment by Hekili** [comment]
I'm confused.  The addon already presents information about when to trigger an empowered spell.  Did you change options to something that is more confusing?

![EmpowerProcess](https://user-images.githubusercontent.com/9438134/202914067-96048877-933d-4460-8d86-b5aacb4e5d62.gif)

Here, you can see that I've set up the addon to recommend empowering to 3 -- the roman numeral at the bottom indicates the empowerment level.  I started the spell, and you can see a timer spiral begin that counts down to empowerment level 3.  When I reach empowerment level 3, the button lights up showing it is charged to the recommended level.

1. The roman numeral is controlled via /hekili > Displays > Primary (or whichever) > Empowerment.
2. The timer spiral is based on having Delays > Extend Spiral configured to show the timing.
3. The illumination upon reaching the appropriate empowerment level is built-in and not configurable.

I do not plan to put an "X" on top of the icon saying to hold it now, because that is misleading in another way.  The addon recommends what to push and when; it doesn't say when not to do things.

**Comment by Dragonfo** [comment]
I'm sorry, I have a Suf addon and it shows it a little differently. I just didn't notice it. Thanks for the informative picture. I'm sorry for the stupid question.

**Comment by Hekili** [comment]
No, thanks for asking.  Is SUF changing the way it appears in my addon?  Or it just looks different in SUF itself?  Thanks!
