### ISSUE TITLE
Windwalker gets stuck

### ISSUE THREAD

**Issue by chiraino** [Hekili/hekili#2006]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Sometimes Windwalker craps out and waits a long time despite energy/chi available

### How to Reproduce

Just going through the single target list.

### Talent Loadout

B0QAdeydY63Y4XKaboK13uRRQAAAAAAAAQSkkElISEAAAAgIRgAkkQaokkQSikDkkkEAAAA

### Snapshot

https://pastebin.com/EckGcEYK

**Comment by Hekili** [comment]
This looks as though it's working as intended, given you've disabled Expel Harm and Flying Serpent Kick.

<details>
<summary>Blackout Kick was excluded because it would break Hit Combo.</summary>

66.  blackout_kick ( st_cleave - 19 )
The action (blackout_kick) is unusable at (0.00 + 0.00) because would break hit_combo.
</details>

<details>
<summary>Crackling Jade Lightning was ruled out.</summary>

 - this entry's criteria FAILS: buff.the_emperors_capacitor.stack[0.00] > 19 & energy.time_to_max[2.98] > execute_time[1.00] - 1 & cooldown.rising_sun_kick.remains[2.19] > execute_time[1.00] | buff.the_emperors_capacitor.stack[0.00] > 14 & ( cooldown.serenity.remains[0.00] < 5 & talent.serenity.enabled[false] | cooldown.weapons_of_order.remains[120.00] < 5 & action.weapons_of_order.known[false] | fight_remains[68.74] < 5 )
</details>

<details>
<summary>Tiger's Palm was ruled out three times since it would overcap resources.</summary>

fallthru 2:
 - this entry's criteria FAILS: combo_strike[true] & buff.bonedust_brew.up[false] & chi.max[6.00] - chi.current[6.00] >= ( 2 + buff.power_strikes.up[false] )

fallthru 6:
 - this entry's criteria FAILS: combo_strike[true] & chi.max[6.00] - chi.current[6.00] >= ( 2 + buff.power_strikes.up[false] ) & buff.storm_earth_and_fire.down[false]

fallthru 8:
 - this entry's criteria FAILS: combo_strike[true] & chi.max[6.00] - chi.current[6.00] >= ( 2 + buff.power_strikes.up[false] )
</details>

<details>
<summary>Spinning Crane Kick could've been recommended if you had Chi Energy.</summary>

 - this entry's criteria FAILS: combo_strike[true] & buff.chi_energy.stack[0.00] > 30 - 5 * active_enemies[1.00] & buff.storm_earth_and_fire.down[false] & ( cooldown.rising_sun_kick.remains[2.19] > 2 & cooldown.fists_of_fury.remains[4.05] > 2 | cooldown.rising_sun_kick.remains[2.19] < 3 & cooldown.fists_of_fury.remains[4.05] > 3 & chi.current[6.00] > 3 | cooldown.rising_sun_kick.remains[2.19] > 3 & cooldown.fists_of_fury.remains[4.05] < 3 & chi.current[6.00] > 4 | chi.max[6.00] - chi.current[6.00] <= 1 & energy.time_to_max[2.98] < 2 ) | buff.chi_energy.stack[0.00] > 10 & fight_remains[68.74] < 7
</details>

<details>
<summary>Flying Serpent Kick is disabled.</summary>

77.  flying_serpent_kick ( fallthru - 10 ) - ability disabled ( preference )
</details>

That leaves the Rising Sun Kick entry that was ready in 2.19 seconds.
