### ISSUE TITLE
cooldowns

### ISSUE THREAD

**Issue by mspykerez** [Hekili/hekili#202]
Add an option to only show cooldowns on boss encounters.
Also I notice that the addon for my shaman isn't recommending the use of Earth Elemental in any circumstances, I wonder why.

**Comment by Hekili** [comment]
Just toggle cooldowns on/off before/during/after boss encounters.

Earth Elemental isn't recommended because the criteria for it are literally "just use it on CD if it's not going to overwrite a real DPS elemental."  It is far better to save it for utility.

But you can add it into your own custom priority if you desire.
