### ISSUE TITLE
Pyre usage (sims vs. guide)

### ISSUE THREAD

**Issue by Pulseonline** [Hekili/hekili#2023]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Consistently Pyre is not being recommended when it needs to be.  On both 3 and 4+ target counts.  I think its only basically recommending Pyre at 20 stacks of Charged Blast and this is not correct.  Which means its recommending way to much Azure Strike.  

At 3 targets it should be Pyre at 10 Stacks of Charged Blast and Above.  At 4 targets it should be recommending Pyre as soon as we have the essence for it.  

### How to Reproduce

Enter game as Devastation Evoker
Find 3 targets
Do rotation.

### Talent Loadout

BsbBnWR3R1Z1HmbUKIpvm3XXhDIAAAAAAgWIJikQgEJlkkAASSIJxBQSSChkkA

### Snapshot

https://pastebin.com/3Frh0K5F

### Contact Information

Pulse#0223

**Comment by Hekili** [comment]
Please provide a sim of your character in similar circumstances as your ticket.

**Comment by Pulseonline** [comment]
> Please provide a sim of your character in similar circumstances as your ticket.

I dont' know how to do that

**Comment by mightymist3ry** [comment]
This is the same issue i have discussed before in 3 target disengrate will be recommended when it should indeed be pyre if Volatility talent is selected, the incenerate talent allows pyre 15% chance to blow up 3 more times. and in my testing is gotten more damage, i also feel essence burst is still recommending improperly with the instant cast. https://github.com/Hekili/hekili/issues/1988 Theres quite afew snapshots here showing all that and a user (Ble43) showing a screenshow from wowhead showing how essence burst should be used with pyre etc. Ths would make evoker peform much better with hekili.
![202828569-07346370-8262-484e-9f78-4b6651a46b4b (1)](https://user-images.githubusercontent.com/46112381/203905282-da38152f-0811-4bca-bd4d-6caf5aca5ce4.png)


> Please provide a sim of your character in similar circumstances as your ticket.

**Comment by Bsirk** [comment]
You only fire on 3 or more with Pyre if you have Volatility chosen. Otherwise, you wait until you have at least 10 stacks of CB.

**Comment by mightymist3ry** [comment]
> You only fire on 3 or more with Pyre if you have Volatility chosen. Otherwise, you wait until you have at least 10 stacks of CB.

Youa re right its Volatility..lol, but yeah in 3 target hekili alwasys recommends desigentrage over pyre so i just press pyre insted. Theres suppsoed to be some way to change the proority but idk how to.

**Comment by Bsirk** [comment]
You might want to check if you have at least 10 stacks of CB. If you don't then Disintegrate is the correct answer. If you do and it still is recommending Disintegrate, then I suggest getting a snapshot when you think it should be and add it to this ticket.

**Comment by Bsirk** [comment]
I suggest getting a snapshot and adding it to the ticket when it should be casting Pyre. That way Hekili can figure out the issue.

**Comment by mightymist3ry** [comment]
> You might want to check if you have at least 10 stacks of CB. If you don't then Disintegrate is the correct answer. If you do and it still is recommending Disintegrate, then I suggest getting a snapshot when you think it should be and add it to this ticket.

like i said before in the previous post https://github.com/Hekili/hekili/issues/1988 theres plenty of them there cause i was confused aswell there was even a scenario in one of my snapshots there where i was hitting more than 4 targets 5-6 i believe and essence burst was upa nd it was telling me to use 4 more azure strikes  and by then the mobs would have died in the scanario i was in

**Comment by Pulseonline** [comment]
> > You might want to check if you have at least 10 stacks of CB. If you don't then Disintegrate is the correct answer. If you do and it still is recommending Disintegrate, then I suggest getting a snapshot when you think it should be and add it to this ticket.
> 
> like i said before in the previous post #1988 theres plenty of them there cause i was confused aswell there was even a scenario in one of my snapshots there where i was hitting more than 4 targets 5-6 i believe and essence burst was upa nd it was telling me to use 4 more azure strikes and by then the mobs would have died in the scanario i was in

This ^^^  This is my issue, its not that its recommending disintegrate, im fine with that.  But its recommending More azure strikes over using pyre on like 4+ targets where the charged blast stacks dont matter.  You use pyre on CD in AOE at 4+ targets with Volatility.

**Comment by Dragonfo** [comment]
Now in AOE it is working well only these two scenarios according to my sim. 
2x Target - https://www.raidbots.com/simbot/report/t8zazateZX7exSebUFVdLE
3x Target - https://www.raidbots.com/simbot/report/sUUSxXyH8baQN9v79fRKVY
These two conditions for goals 2 and 3 work as they should. But what is expected when the goals become 4, then there is an error in logic. Here's A Snapshot. https://pastebin.com/JjU772Ub Here it is clearly shown that the addon really strives to gain a lot of stacks before Pyre. But if you look into the simulation itself 
4x Target - https://www.raidbots.com/simbot/report/gRMnWpLZfZmYqSGkoBXR7S
Then there is really no error, because according to the simulation, the addon does sometimes make 20 stacks, for Pyre. Even when there are 5 Goals, we still don't use Pyre anymore as we should. The simulation again tries to get 20 stacks, for a more powerful charge.
5x Target - https://www.raidbots.com/simbot/report/25WZnsvg3Cj8AHKDJCiSSi
It seems to me that it still makes sense to do the guide above from Wowhead, for AOE, because we can get [Essence Burst](https://www.wowhead.com/spell=359618/essence-burst) with a 15% chance due to [Azure Essence Burst](https://www.wowhead.com/spell=375721/azure-essence-burst) talent and with a 20% chance we can not spend Essence Burst due to [Hoarded Power](https://www.wowhead.com/spell=375796/hoarded-power) talent. The game in aoe is very similar to Surv Hunter via Mad Bombardier. We strive to use Azure Strike to get Essence Burst so that we can use Pyre many times in the future.

**Comment by Hekili** [comment]
I would recommend suggesting your changes for SimulationCraft -- you can make edits and contribute there.  If/when the Devastation priority is updated there, I will make similar edits here.

**Comment by Hekili** [comment]
I'll be posting some priority changes which will use Pyre more often with version 1.8.10.  Additional priority changes will take place after SimulationCraft does its own updates.
