### ISSUE TITLE
Unholy DK recommending Apocalypse w/o 4 wounds

### ISSUE THREAD

**Issue by Cheetah714** [Hekili/hekili#2031]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

for my unholy dk the rotation suggest Apocalypse although i dont have 4 stacks of Festering Wound on the target also the opener is not right based on icy veins guide but the addon recommend using Dark Transformation as opener 
![image](https://user-images.githubusercontent.com/117462129/203868787-3d6faf69-b3f5-4d4c-a2dc-7228603b1706.png)

### How to Reproduce

1. enter the game as unholy dk
2. follow the rotation untill you hit the Apocalypse window
3. addon recommend using apocalypos while theres 1 or 2 wound on the target

### Talent Loadout

BwPAdLUHklrTr3hBIcYWdbnCGDAkgkwBiIRQiEhAJJRCAAAAAAAAAAEBkkGAApIlDEJJJSSA

### Snapshot

https://pastebin.com/S1zWCuyw

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/xvC3Jf9xgCdAHDHaxjtNQp

**Comment by Hekili** [comment]
The addon is based off SimulationCraft tested priorities, not the Icy-Veins guides specifically.

I am investigating the Festering Wounds issue.  That is an issue of translating simc into the game.

**Comment by Hekili** [comment]
It looks like your sim actually behaved the same; there's no condition for Apocalypse that requires Festering Wound at 4+, though clearly it should.

Your customized sim for Streets makes it hard to assess with so many confounding variables.  Because of that, your sim wouldn't use Dark Transformation until 40 seconds into the dungeon.

I've made some changes since it seems the SimC priority isn't accounting for some nuances; they are in v10.0.2-1.8.4 which will be available soon.

**Comment by Veinsbane** [comment]
I am having this problem as well on the new content since Dragonflight 10.0.5 mainly in Mythic+ @Hekili
