### ISSUE TITLE
Spellflash no circle

### ISSUE THREAD

**Issue by Jingle627** [Hekili/hekili#2041]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

I can't get spellflash texture to change to anything but star (default). I want to change to one of the circles. I change it in the settings and reload and it doesn't change. I have it on one character (Gingle-Anvilmar). I switched to Gingle's profile on this toon (Villanel) and it changed everything  except the circle. When I change the texture to anything on this toon (Villanel-Anvilmar), it doesn't change on this toon, but it does change on Gingle. I haven't been able to change the texture on any other toon except Gingle.
I can change the color, but not the texture.

### How to Reproduce

edit: don't need to paste the same content three times

### Player Information (Link)

```Text
build: v10.0.2-1.8.5
level: 22 (22)
class: DEMONHUNTER
spec: havoc

talents: blazing_path
    critical_chaos = 2/2
    eye_beam = 1/1
    felblade = 1/1
    first_blood = 1/1
    imprison = 1/1
    improved_chaos_strike = 1/1
    improved_disrupt = 1/1
    insatiable_hunger = 1/1
    pursuit = 1/1
    unrestrained_fury = 2/2
    vengeful_retreat = 1/1

pvptalents: none

covenant: none

conduits: none

soulbinds: []

sets: none

gear: eternal_horizon_choker = 1
    illidari_bracers = 1
    illidari_ring = 1
    inherited_cape_of_the_black_baron = 1
    lekos_leash = 1
    mardum_lord_signet = 1
    power_handlers_gloves = 1
    preened_tribal_war_feathers = 1
    preened_wildfeather_leggings = 1
    stained_shadowcraft_spaulders = 1
    stained_shadowcraft_tunic = 1
    surestep_boots = 1
    swift_hand_of_justice = 1
    venerable_dalrends_sacred_charge = 1
    vigorous_belt = 1

legendaries: none

itemIDs: 112452, 112459, 122249, 122255, 122261, 122351, 122358, 122361, 122383, 122664, 128946, 128958, 133314, 25717, 51964

settings: aoe = 2
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 10
    nameplateRange = 7
    nameplates = true
    noFeignedCooldown = false
    package = Havoc
    petbased = false
    potion = phantom_fire
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    demon_blades_acknowledged = false
    recommend_movement = true
    unbound_movement = false

toggles: cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    demons_bite     = 0   [02]
    fel_rush        = R   [06]
    felblade        = 9   [02]
    immolation_aura = -   [02]
    metamorphosis   = =   [02]
    throw_glaive    = 7   [02]

warnings: none
```

### Error Messages (Link)

edit: don't need to paste the same content three times

### Additional Information

idk

**Comment by Hekili** [comment]
Are you sure that you're reloading after changing the texture?

![image](https://user-images.githubusercontent.com/9438134/205186466-afe234a6-5ee1-4a6f-b8ec-03d5666537df.png)

![image](https://user-images.githubusercontent.com/9438134/205186055-ee930990-8277-4b8b-abba-6935b41eee76.png)

![image](https://user-images.githubusercontent.com/9438134/205186069-c0ba1144-f6b0-4c35-8292-939d8597c205.png)

![image](https://user-images.githubusercontent.com/9438134/205186250-d282727a-bbad-43a2-8b49-1acf0c31f656.png)

`/reload`

![image](https://user-images.githubusercontent.com/9438134/205186214-67346d21-8ae9-4ec9-8918-27e8010b85e4.png)

![image](https://user-images.githubusercontent.com/9438134/205186278-ae8e155b-299b-473a-800c-64f3688f2e1e.png)

`/reload`

![image](https://user-images.githubusercontent.com/9438134/205186352-f8534243-c4b7-4aff-b13f-bc16bd4742ab.png)

I'm not able to replicate the issue that you describe.  Changing the flash texture requires a `/reload` before it will change due to how SpellFlash sets up its flashes.
