### ISSUE TITLE
UH DK Priority Changes

### ISSUE THREAD

**Issue by UltiDeeps** [Hekili/hekili#2051]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

There are several minor issues with the current UH DK APL.

Current Issues Recognized:
Algethar Puzzle Box not recommended in opener: https://pastebin.com/Qz0ukX3u

Apoc being shown in spell order after Dark Transformation but then disappears from recommendations after Dark Transformation is cast, leaving Apocalypse free to use: https://pastebin.com/h51ryNCK

ST rotation miscellaneous issues(RP and rune capped but addon still recommending Festering Strike, no Scourge Strikes recommended while talented into Plaguebringer): https://pastebin.com/CwK2fDA7

Able to replicate the DC spending issue again with a different talent setup except this time it just spams Scourge Strike:
Talents: BwPAdLUHklrTr3hBIcYWdbnCGDACkkQiIRCSSEikkIRAAAAAAAAAAQSSIkkGAApIlDEJJJSyBA
Snapshot: https://pastebin.com/LAxcK834

As DT and Apoc are coming off CD, I forcibly hit Apoc after DT during this go at the dummy only Festering Strike and DC being Recommended: https://pastebin.com/EX6UDefy

### How to Reproduce

Enter game as Unholy Dk.
Load with recommended raid talents: BwPAdLUHklrTr3hBIcYWdbnCGDAkISSSgEESSEiIJSkAAAAAAAAAAKJJhIAAgEpIlEJJJSC
Find target dummy to hit.
Follow rotation.

### Talent Loadout

BwPAdLUHklrTr3hBIcYWdbnCGDAkISSSgEESSEiIJSkAAAAAAAAAAKJJhIAAgEpIlEJJJSC

### Snapshot

Several Pastebins posted in description

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/mg23iLY6D6J1EHWdFRW8do

### Additional Information

Opener as Suggested by Class Discord: 

![image](https://user-images.githubusercontent.com/95395399/204723416-e6d51add-005a-4194-a292-10e8912aa9d4.png)

Rotation as Suggested by Wowhead:

![image](https://user-images.githubusercontent.com/95395399/204723564-26cac31c-2ae5-4b84-b796-3f65be950c58.png)

### Contact Information

Ulti#3784

**Comment by Hekili** [comment]
Laundry list tickets are generally problematic because eventually we're tracking 5 different things, many of which will be addressed by routine priority updates when sims are updated.

That being said...

> Algethar Puzzle Box not recommended in opener: [pastebin.com/Qz0ukX3u](https://pastebin.com/Qz0ukX3u)

New trinkets aren't implemented yet.

> Apoc being shown in spell order after Dark Transformation but then disappears from recommendations after Dark Transformation is cast, leaving Apocalypse free to use: [pastebin.com/h51ryNCK](https://pastebin.com/h51ryNCK)

This is an easy fix, will be addressed in next release.

> ST rotation miscellaneous issues(RP and rune capped but addon still recommending Festering Strike, no Scourge Strikes recommended while talented into Plaguebringer): [pastebin.com/CwK2fDA7](https://pastebin.com/CwK2fDA7)

You don't seem to be RP capped here:

```
    There are 1 queued events to review.
    Resources: runes[ 6.00 / 6.00 ], runic_power[ 15.00 / 100.00 ]
```

> Able to replicate the DC spending issue again with a different talent setup except this time it just spams Scourge Strike:
> Talents: BwPAdLUHklrTr3hBIcYWdbnCGDACkkQiIRCSSEikkIRAAAAAAAAAAQSSIkkGAApIlDEJJJSyBA
> Snapshot: [pastebin.com/LAxcK834](https://pastebin.com/LAxcK834)

Unholy has a `pop_wounds` variable that defines when it wants to actually pop wounds.

```
( cooldown.apocalypse.remains > variable.apoc_timing[8.00] | ! talent.apocalypse.enabled[true] ) & ( variable.festermight_tracker[true] | debuff.festering_wound.stack[3.00] >= 1 & ! talent.apocalypse.enabled[true] | debuff.festering_wound.stack[3.00] >= 1 & cooldown.unholy_assault.remains[47.33] < 20 & talent.unholy_assault.enabled[true] & variable.st_planning[0.00] | debuff.festering_wound.stack[3.00] > 4 | fight_remains[20.45] < debuff.festering_wound.stack[3.00] * gcd.max[1.09] )
```

There may be an issue that Apocalypse's cooldown isn't shown here (I can see that is was on CD for 6.8 seconds in another entry, though).  Is Apocalypse on CD for more than 8 seconds (or Apocalypse not talented)?  Nope.

8 seconds seems like a lot of time to save wounds for Apocalypse, though.  I anticipate that will change with time (accounting for targets dying, or time to replace the wounds you spend).

> Opener as Suggested by Class Discord:
> Rotation as Suggested by Wowhead:

Are there specific differences (aside from the pieces I mentioned I will fix) that you're concerned with?  The addon will follow sim behavior.

**Comment by UltiDeeps** [comment]
Gotcha, that’s my bad I opened multiple tickets previously for issues and
thought that was the less enjoyed alternative.

I made these last night before bed so when I get home I will do my best to
replicate them again when I return.

Since it seems most of these are just routine fixes over time I’m gonna
trust the process and trust your judgement. You’ve not let me down before
not going to doubt you now.

Appreciate the time key response brotha.

**Comment by Hekili** [comment]
For the record, it was helpful that you snapshotted these.  Apocalypse vanishing from recommendations is a bug that I've solved and will post the fix for.

Opener stuff is usually a "don't bother" for tickets because that's all sim work.  If the addon and the sim are giving different results, that comparison matters.  Guides often over-emphasize openers to begin with.

The Death Coil and wound popping stuff seems to align with the intent of the theorycrafters, until/unless something else changes.
