### ISSUE TITLE
Feral Not Prioritizing Finishers at 5 Combo Points

### ISSUE THREAD

**Issue by Grayfox2325** [Hekili/hekili#2065]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Feral is using combo point generating abilities while at max combo points. Have seen it use rake, thrash, brutal slash, shred while at 5 combo points. Snapshot is just one instance of this. 

### How to Reproduce

Issue is not consistent, not too sure what the condition for it to occur are. Most noticeable after using Feral Frenzy when in an aoe situation.

### Talent Loadout

BcGAYhlYdy9RJ6ROrphOEi69vCAAAAAAIkUSTikkEJl0OAKJRikAAAAAAgiAIJAIikQCJ0SolkAAAAAAASA

### Snapshot

https://pastebin.com/Eyb1vTRU

**Comment by Grayfox2325** [comment]
Better snapshot - https://pastebin.com/rQAsSyxv

**Comment by Hekili** [comment]
In your better snapshot, you're getting Rake recommended in order to set up Bloodtalons.  This happens occasionally in simulation, as well.

<html><body>


<html><body>


Time | List | # | Name | Target | Resources | Buffs
-- | -- | -- | -- | -- | -- | --
1:11.765 | finisher | c | rip | Fluffy_Pillow | 25.0/100: 25% energy 10000.0/10000: 100% mana 5.0/5: 100% combo_points | predatory_swiftness, tigers_fury, worthy_mastery_rating
1:13.279 | default | A | feral_frenzy | Fluffy_Pillow | 25.2/100: 25% energy 10000.0/10000: 100% mana 0.0/5: 0% combo_points | predatory_swiftness, tigers_fury, worthy_mastery_rating
1:14.282 | Waiting |   |   | 0.948 sec | 13.6/100: 14% energy 10000.0/10000: 100% mana 5.0/5: 100% combo_points | predatory_swiftness, tigers_fury, worthy_mastery_rating
1:15.995 | bloodtalons | L | rake | Fluffy_Pillow | 36.6/100: 37% energy 10000.0/10000: 100% mana 5.0/5: 100% combo_points | predator


</body>
</html>

In this case, Rip spent Combo Points and Feral Frenzy refilled them.  Then Rake was used to reproc Bloodtalons.  I'm assuming that the sim didn't proc Bloodtalons before the Rip just because the window for getting enough BT triggers wouldn't have allowed it to happen, but after Feral Frenzy, it could do so.

I went ahead and did a comparison sim using my level 60 Feral, where I put Bloodtalons lower in priority than Finishers at 5 CP.  It looks like a worthwhile adjustment -- on average it doesn't change much, but potential higher top-end damage and the low-end damage also shifts upward a little bit.

![image](https://user-images.githubusercontent.com/9438134/205376459-08891f0c-d4db-49ed-920a-f364947dd503.png)

I'll put this change in place in the next release.
