### ISSUE TITLE
Not pooling for Ferocious Bite condition or option

### ISSUE THREAD

**Issue by Kittiez** [Hekili/hekili#208]
So obviously majority of the time, I'd love to pool 50 energy so it showing as delay usage until i got that is absolutely awesome and great. But a few times i need to fb urgently (etc opener but without Berserk) and with how it currently forced to pool to 50 energy even if rip will fall off, it just happens to actual fall off because i might have brainafk'ed that one or 2 tries. Normally i just ignore it because obv normally you have Berserk. But lately i've been progressing a bit in a way that requires me to save my cd and so i often run into the problem that i pool 50 energy for FB an rip falls off somewhere during that.

**Comment by Hekili** [comment]
Add'l context:  In SimC, the flag `max_energy=1` tells the sim to wait until 50 energy.  At the moment, this addon just always waits until 50 energy, since it hadn't presented an issue until recently.  I've noticed this as well since we are now potentially casting an Essence ability and channeling Cyclotronic Blast during our opener -- getting Rip extended can be a real challenge.

Respecting a `max_energy` flag would require a system of ability-specific options that can be imported *and* are supported through the /hekili > Priorities UI.  Not a huge challenge, but non-trivial.

**Comment by Hekili** [comment]
Testing a change in 8.3 that will avoid worrying about pooling if you have a Rip falling off and the Sabertooth selected.
