### ISSUE TITLE
Ret Seraphim is never recommended when cooldowns are disabled

### ISSUE THREAD

**Issue by cremor** [Hekili/hekili#2116]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Even though Seraphim itself doesn't use the cooldown toggle, it is never recommended when the cooldown toggle is disabled and the talent Final Reckoning is used.

### How to Reproduce

1. Play as Ret Paladin with Seraphim and Final Reckoning talents.
2. Disable cooldowns in Hekili.
3. Verify that Seraphim is not configured to use the cooldowns toggle.
4. Build to 5 Holy Power.
5. Notice that Seraphim is not recommended.
6. Enable cooldowns in Hekil.
7. Build to 5 HP again.
8. Notice that Seraphim is now recommended.

### Talent Loadout

BYEAwtJ2KpR8WbGzhz/jy2AP8AAAAAAgIAiokWSiEQSSapkkElAAAAAAAIEJJplEkAtkkEloEA

### Snapshot

https://pastebin.com/1SP7tmRf

### Additional Information

Similar to #1394

**Comment by Hekili** [comment]
Thanks; I was anticipating a ticket along these lines.  I'll put a test fix in the next beta build.

**Comment by Lunshea** [comment]
Do you also experience Templar's Verdict being suggested a lot in AoE scenarios when Hekili is set to auto? This never was a problem for me in SL.

**Comment by cremor** [comment]
Should this be in v10.0.2-2.0.4? Because I'm still not seeing it.
https://pastebin.com/uJ5Pp5c8

**Comment by VincentCassiau** [comment]
My analysis: I think it is because the Final Reckoning spell is in the cooldown group, which leads to simulating its maximum cooldown constantly. The problem is that in the simulation, a phase called **es_fr_pooling** is supposed to cast seraphim but to enter this phase, the remaining cooldown of Final Reckoning is supposed to be less than 9 seconds.

`actions+=/call_action_list,name=es_fr_pooling,if=(!raid_event.adds.exists|raid_event.adds.up|raid_event.adds.in<9|raid_event.adds.in>30)&(talent.execution_sentence&cooldown.execution_sentence.remains<9&spell_targets.divine_storm<5|talent.final_reckoning&cooldown.final_reckoning.remains<9)&target.time_to_die>8
`

Possible solutions in my opinion are:

- Modifying the APL file directly, but I doubt that is advised (to confirm).
- Removing the Final Reckoning spell from the cooldown group via the addon options.
- Using the Cooldown: Show Separately: Use Actual Cooldowns option. This can, however, interfere with some recommendations depending on the talents that are chosen.

**Comment by cremor** [comment]
I think it should be possible to fix this in the same way as #1394 was fixed. The APL also contained those "es_fr" parts back then.
