### ISSUE TITLE
[Retail] DH Havoc Essence Break is never suggested

### ISSUE THREAD

**Issue by james-yin** [Hekili/hekili#2119]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

DH Havoc Essence Break is never suggested

### How to Reproduce

1. Enter game as DH Havoc spec
2. hit training dummy
3. Essence Break as the base Havoc spell is never suggested

### Talent Loadout

BEkACnvaHJn8GSPD6tpaeczPThkkkkIlg0SSEJCJBAAAAAAQLJBRKkElgkkWSgEIB

### Snapshot

Havoc; Primary - Immolation Aura(0.00), Throw Glaive(1.41), Felblade(2.83)

**Comment by rubix87** [comment]
Having the same issue.

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Hekili** [comment]
It is likely that you have Recommend Movement disabled, which isn't extremely compatible with taking Tactical Retreat and Momentum in your build.  The priority is written to check for Tactical Retreat before using Essence Break.  I'll adjust the priority but keep in mind, if you take talents that rely on movement but leave movement disabled, the addon isn't going to give suggestions for proccing those effects.

**Comment by james-yin** [comment]
This works now with the latest release. Thanks.

**Comment by pdrayton** [comment]
This issue is back in the latest release. It might be "intentional" based on the APL but it also removes the ability to have Hekili work in a "don't recommend movement" mode which is unfortunate.

Hekili used to offer a "don't recommend movement" option for players who didn't want movement in the suggestion list. This was useful because even in the Momentum-based builds, at times movement might be undesirable but one still wants Hekili recommendations. 

The 10.0.5 - 1.0.18 build removed the "don't recommend movement" option and the recommended solution is to disable Fel Rush and Vengeful Retreat abilities if you don't want them recommended. The problem is that the APL has some baked-in rules that make it so if you disable FR & VR when using the most common Momentum builds, then you will NEVER see Essence Break suggested. 

The issue is this part of the APL - if one takes Momentum and Tactical Retreat, it will never recommend Essence Break until after doing either a FR or a VR. Doing VR into EB is good practice but not the only valid use and effectively it is hiding EB from the suggestions.

`actions+=/essence_break,if=(active_enemies>desired_targets|raid_event.adds.in>40)&!variable.waiting_for_momentum&fury>40&(cooldown.eye_beam.remains>8|buff.metamorphosis.up)&(!talent.tactical_retreat|buff.tactical_retreat.up)`

I was able to work around this by modifying the APL, but would it be possible to get the "Don't recommend movement" feature back as an option? Alternatively, some build-in variable to force essence break usage if available (which is how I solved this on my side - basically added a new **force_essence_break** variable that I could toggle in the APL, the amended this APL line to 

`( active_enemies > desired_targets | raid_event.adds.in > 40 ) & ( variable.force_essence_break |  ( !variable.waiting_for_momentum ) ) & fury > 40 & ( cooldown.eye_beam.remains > 8 | buff.metamorphosis.up ) & ( variable.force_essence_break | ( ! talent.tactical_retreat.enabled | buff.tactical_retreat.up ) )`

**Comment by Hekili** [comment]
This is a lot of effort to go to in order to break the priority.  I'm not sure why using a custom priority (as you have) isn't sufficient.  I don't know that I want the addon to be explicitly guiding people to play suboptimally.  If you're not going to use VR/FR to buff your Essence Break, why take the talents?

**Comment by pdrayton** [comment]
Fair enough. I totally understand if you don't feel this is generally useful. Thanks for the response.

wrt your question, my scenario is that I 100% do use VR/FR to buff my EB, but I prefer to have Hekili "not recommend movement" so it is providing the next 2-3 recommended damage abilities and handle the movement entirely on my own. When VR/FR is recommended, Hekili recommendations get hung up on the VR/FR recommendation and stop showing the other DPS abilities until I am able to use the VR/FR. 

The custom priority works for me, I just prefer to not customize Hekili too much since I can then easily update.

**Comment by james-yin** [comment]
There are situations where VR/FR is not practical or just deadly and causing wipes to the raid. I had though the old "not recommend movement" option was great. Or the addon can just ignore and drop off the VR/FR when it's not triggered in a few seconds. But I do understand how it's difficult to work around something that's "baked" in for the whole pipeline.
