### ISSUE TITLE
Display Shift modifier on show keybindings.

### ISSUE THREAD

**Issue by lightsourced** [Hekili/hekili#2134]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

Hello, currently with Keybinds enabled, it will show a C9 for Ctrl+9, however, it does not do this for Shift keybind modifier. It will display my Shift+1 action as just 1, so it gets confusing sometimes when trying to press the correct keybind. It would be nice if it displayed as S1 so I know to press shift along with 1. Thanks!

**Comment by SanjoSolutions** [comment]
I had the same issue when switching from Bartender4 to the default action bars. It turned out that when I turned Bartender4 back on that some abilities were also in the "Bonus Action Bar" (that seems to be the bar that replaced the first action bar during dragon riding). To fix the issue, I have done the following:

With Bartender4 turned on: **remove all abilities from the "Bonus Action Bar"**. Which bar the "Bonus Action Bar" is, can be found out by disabling the lock in the Bartender4 settings (`/bartender` and then unticking the "Lock" checkbox on the top left). Then the names of the bars show on the bars.

After that the shift modifier seem to correctly display in the Hekili bar. That the ability showed without the shift modifier seems to be because for the ability a second key binding was set. This can be seen with `/dump Hekili.KeybindInfo`.

So displaying the shift modifier seems to work fine in the latest version of Hekili.

**Comment by lightsourced** [comment]
I’m currently using Dominos and it doesn’t have that bar labeled as such (it’s just Bar 2) and it isn’t the one that switches during dragon riding. 

The odd thing is that Bar 3 that has all my ctrl keybinds works fine. 

 Unfortunately, I’m unable to fix this issue with your solution. :(

**Comment by SanjoSolutions** [comment]
@lightsourced 

With `/dump Hekili.KeybindInfo` you can check if one of the abilities which show the keybinding without shift, has an additional keybinding to the key without shift. If that's the case then the solution from my previous post might work, if you install Bartender4 temporarily to fix it.

**Comment by Hekili** [comment]
Yeah, this is not a feature request, this is really a bug report.

You can provide the information from your Issue Reporting tab, which would include keybindings-as-detected, or you can simply manually set the key binds via /hekili > Abilities > *select the ability* > Override Keybind Text.
