### ISSUE TITLE
BM not recommending Blood Fury

### ISSUE THREAD

**Issue by JimA1966** [Hekili/hekili#2135]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

log into BM, run through rotation, blood fury not recommended even if cooldown checked or not and un cliqued in toggles

### How to Reproduce

1. enter game as BM
2. either check cooldowns or unclique in toggles
3. blood fury not recommended

### Talent Loadout

B0PAIlFMjeNhnEouGfV8Ij2uS5ACaJAABAAAAAAAAAAgGRKSolEJSi4A5AoJEhkQSSEakEB

### Snapshot

https://pastebin.com/xQBz9W0E

### Contact Information

Asgar#6151

**Comment by Hekili** [comment]
These recommendations appear to correctly match the priority, but I'm considering whether this should have an edit:

```
19.  blood_fury ( cds - 13 )
The action (blood_fury) is usable at (0.00 + 0.00).
 - the action is ready before the current recommendation (at +0.00 vs. +10.00).
List ( cds ) called from ( Beast Mastery:default:3 ) would PASS at 0.00.
NONE
 - this entry's criteria FAILS: buff.call_of_the_wild.up[false] | ! talent.call_of_the_wild.enabled[false] & ( buff.bestial_wrath.up[true] & ( buff.bloodlust.up[false] | target.health.pct[98.73] < 20 ) ) | boss[false] & fight_remains[476.48] < 16
````

Here, Bestial Wrath is up, but Bloodlust is down and your target's health is not below 20%, so those conditions aren't met.  You're not in a boss fight, but if you were, the addon would recommend Blood Fury if the fight looks like it will end in 16 seconds.

I'll likely make it so that, in addition to Bloodlust or being in execute range, the addon can recommend Blood Fury if it will still be usable again in the same fight.

A sim of your character on Raidbots in a longer (8 minutes?) Patchwerk (1 target) fight might be helpful to triage investigate this further.

**Comment by JimA1966** [comment]
I will put a sim in the pastebin but even though it should recommend it as opener? Correct?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by JimA1966** [comment]
https://pastebin.com/E2P2r2a9
