### ISSUE TITLE
[Warlock] Demonology call_dreadstalkers delayed too much

### ISSUE THREAD

**Issue by xinni** [Hekili/hekili#2136]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

The call_dreadstalkers was delayed too much. According to the snapshot, it tries to align the call_dreadstalkers with the tyrant. However, I tested that we can cast call_dreadstalkers at this point, and it will be ready again when the tyrant cooldown. Otherwise, the DPS is much lower than the simulation.

I think maybe the `summon_demonic_tyrant.remains_expected` calculation didn't take Demonic Calling into consideration? Not sure about this, didn't test without this talent.

### How to Reproduce

Talent with Demonic Calling, and follow the default rotation.

### Talent Loadout

BoQAbtPS25JQs0VfQSDmhm+p3gESSkIBSTLCS7AJJkSAAAAAQLCSAikIJJJl0SSCCAAAAAAA

### Snapshot

https://pastebin.com/gitR4k3F

**Comment by Kintoun** [comment]
Offering some more data, `summon_demonic_tyrant.remains_expected` is a key piece of Warlock APL and seems to always resolve to 90s in Hekili no matter what when talent.grand_warlocks_design is taken. 90s is the base CD of the ability. Something seems bugged here.

The reason remains_expected is important is because Demo Warlocks take talent.grand_warlocks_design which reduces the CD of summon_demonic_tyrant for each shard spent. Generally speaking the 90s CD becomes 55-65s CD instead.

**Comment by Hekili** [comment]
> Offering some more data, summon_demonic_tyrant.remains_expected is a key piece of Warlock APL and seems to always resolve to 90s in Hekili no matter what when talent.grand_warlocks_design is taken. 

Snapshot:
> `cooldown.summon_demonic_tyrant.remains_expected[30.46]`

When your Cooldowns toggle is turned off, Cooldown abilities are treated as though they're on their max cooldown.  This prevents priorities written to ramp up in preparation for a cooldown from getting stuck ramping endlessly when you're opted not to press the button.

In your snapshot, Cooldowns are toggled on, so the snapshot doesn't reflect what you described.  `remains_expected` is automatically calculated based on how quickly your cooldown has recovered vs. its normal fixed cooldown.

Example:  SDT is 90 second CD.  You use it, then 30 seconds pass.  Without CDR, you'd have 60 seconds left.  But your actual remaining time is 45 seconds (your cooldown has recovered 45 seconds in 30 seconds).  It looks at the actual remaining time -- 45 seconds -- and calculates that the remaining 45 seconds will get used up in 30 seconds.

If there's some other issue with Call Dreadstalkers being delayed, you'll want to take a snapshot when Call Dreadstalkers is not on cooldown, you think it should be recommended, but it is not being recommended.

```
13.  call_dreadstalkers ( default - 5 )
The action (call_dreadstalkers) is usable at (0.00 + 0.00).
 - the action is ready before the current recommendation (at +0.00 vs. +10.00).
tyrant_prep_start Result = 12.
 - this entry's criteria FAILS: cooldown.summon_demonic_tyrant.remains_expected[30.46] > action_cooldown[20.00] + variable.tyrant_prep_start[12.00]
 ```
 
It looks like this is already addressed in the updated priority since your post:
`actions+=/call_dreadstalkers,if=cooldown.summon_demonic_tyrant.remains_expected>cooldown`
