### ISSUE TITLE
Addon showing wrong keybind

### ISSUE THREAD

**Issue by xAatras** [Hekili/hekili#215]
Good evening.
Firstly, excuse my english, I'm not native speaker.
I'm playing Feral druid and the addon is not showing the right keybind, that I use for the spell. For example my Regrowth is binded on Shift-1 and addon shows me to press 3. You can take a closer look at it on included screenshot. This is just a little problem, but it makes you from time to time stop and think what to press now.
This problem aside, the addon is working perfectly.
Thank you for the work and answer.
![Feral-druid-hekili](https://user-images.githubusercontent.com/54371576/63453959-1aeeea80-c44a-11e9-9f15-0d9daac5ebda.png)

**Comment by Hekili** [comment]
This is a "bug" sorta, but not something that is going to be fixed any time soon.

Because of the way action slots (buttons) are recycled, the addon assumes that you have your bars set up similar to the default layout (i.e., which bars are visible based on your form and stealth status).

If you don't want to rearrange your action bars and buttons to try to match those defaults, you can specify the keybind for any action manually in the addon's options.

/hekili > Abilities > Regrowth; fill in the keybinding text with what you want to see.

Also, your PS vanished, but I just wanted to add, the default ("Automatic") behavior is for the addon's Primary display to adjust recommendations based on # of targets.

**Comment by xAatras** [comment]
I did not expect this fast response. Thank you so much, everything now works.
Keep up the amazing work!
