### ISSUE TITLE
Incorrectly displayed after pressing Fire Breath charge

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#2155]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

In aoe, when calculating targets, it showed 2-3 Fire Breath charges. When clicking on Fire Breath, it showed me that 1 charge should be pressed.

### How to Reproduce

1.Mark 3-4 goals
2.Click on Fire Breath

### Talent Loadout

BsbBnWR3R1Z1HmbUKIpvm3XXhDAAAAAAAaapISiERSiEJtkkUISLESIJSQSiEikkA

### Snapshot

https://pastebin.com/G1mWd0tp

**Comment by Hekili** [comment]
This almost entirely doesn't matter, but I'm making an adjustment just in case.  The issue is the addon cannot know why you started empowering the spell, so it has to be able to fallback and cast Fire Breath if that's what you're empowering no matter what.  Anyway, I'm making a priority adjustment that should mostly alleviate this.
