### ISSUE TITLE
Shadow dance not being suggested when it should

### ISSUE THREAD

**Issue by Neekodesu** [Hekili/hekili#2167]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Shadow dance is being suggested 4 times in a 40 min mythic+ having 1 min cd on the skill... 

### How to Reproduce

Play a mythic+ for 15-20 min and see 0 suggestions of Shadow Dance. It will only show in single target but 0 times in AOE.

### Talent Loadout

BQQAOB/7AZ//CwQOf4fPMswHVDAAgERSAkkEJSSCkEJRikkkkECAAAAAAQSSimDUSCIBBAAAA

### Snapshot

https://pastebin.com/tdpJJa1Y

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/iu33hUuVXry8jfbqu9DrAU

### Contact Information

Neko#7422

**Comment by Neekodesu** [comment]
Im also posting a Snapshot when it actually suggests it (randomly after using hook and not being close to any target) [I also don't know if that snapshot is the first one or the second one but i would say is this second one)
https://pastebin.com/5vHyQ0VB

**Comment by Neekodesu** [comment]
I have to mention that the only way to make it suggest is being in Single target, otherwise it will never show in AOE.
So basically the bug is Shadow dance not showing when AOE

**Comment by Neekodesu** [comment]
in theory: You use shadow dance when you have no opportunity or audacity procs and vanish is on cooldown.
But I just can't find hekili to suggest it on AOE it just suggests on ST

**Comment by Hekili** [comment]
The snapshot that is needed would be taken when you think that, at that moment, Shadow Dance should've been recommended, but was not recommended.  Which snapshot would that be?  Do you need to provide a new one?

**Comment by Hekili** [comment]
Upon review, you have Cooldowns set to show separately, and Shadow Dance is on your Cooldowns toggle.  You would need to provide a snapshot of your Cooldowns display rather than your Primary display if we are to investigate this.

**Comment by Neekodesu** [comment]
Aight sorry for the late response, I just went into dummys and got a snapshot. Hope you can explain this:
Primary: https://pastebin.com/UXfRJehS
Cooldowns: https://pastebin.com/gNNH0bNe

**Comment by Hekili** [comment]
Pasting the response from Discord here:

So, there are two entries for Shadow Dance under consideration, `stealth_cds - 7` and `8`.

```
29.  shadow_dance ( stealth_cds - 7 )
The action (shadow_dance) is usable at (0.00 + 0.00).
 - the action is ready before the current recommendation (at +0.00 vs. +10.00).
List ( cds ) called from ( Outlaw:default:11 ) would PASS at 0.00.
List ( stealth_cds ) called from ( Outlaw:cds:4 ) would PASS at 0.00.
! stealthed.all[false] | talent.count_the_odds.enabled[false] & ! variable.stealthed_cto[false]
shadow_dance_condition #1 [Outlaw:stealth_cds:6]; conditions = PASS: NONE
 - value = nil.
shadow_dance_condition Result = false.
 - this entry's criteria FAILS: ! talent.keep_it_rolling.enabled[false] & variable.shadow_dance_condition[false] & buff.slice_and_dice.up[true] & ( variable.finish_condition[false] | talent.hidden_opportunity.enabled[true] ) & ( ! talent.hidden_opportunity.enabled[true] | ! cooldown.vanish.ready[true] )
```

The first one doesn't fire because `shadow_dance_condition` is false.  *That* condition is:
`talent.shadow_dance.enabled[true] & debuff.between_the_eyes.up[true] & ( ! talent.ghostly_strike.enabled[false] | debuff.ghostly_strike.up[false] ) & ( ! talent.dreadblades.enabled[false] | ! cooldown.dreadblades.ready[true] ) & ( ! talent.hidden_opportunity.enabled[true] | ! buff.audacity.up[false] & ( talent.fan_the_hammer.rank[2.00] < 2 | ! buff.opportunity.up[true] ) )`

The part of that condition that fails is `( ! talent.hidden_opportunity.enabled[true] | ! buff.audacity.up[false] & ( talent.fan_the_hammer.rank[2.00] < 2 | ! buff.opportunity.up[true] ) )`

The first part (before the `|`) is false because you have Hidden Opportunity.
The second part fails because you have 2 ranks of Fan the Hammer and Opportunity is up.  If you had one rank of FtH or Opportunity weren't up, it would've been selected.

The second one:

```
30.  shadow_dance ( stealth_cds - 8 )
The action (shadow_dance) is usable at (0.00 + 0.00).
 - the action is ready before the current recommendation (at +0.00 vs. +10.00).
List ( cds ) called from ( Outlaw:default:11 ) would PASS at 0.00.
List ( stealth_cds ) called from ( Outlaw:cds:4 ) would PASS at 0.00.
! stealthed.all[false] | talent.count_the_odds.enabled[false] & ! variable.stealthed_cto[false]
 - this entry's criteria FAILS: talent.keep_it_rolling.enabled[false] & variable.shadow_dance_condition[false] & ( cooldown.keep_it_rolling.remains[0.00] <= 30 | cooldown.keep_it_rolling.remains[0.00] > 120 & ( variable.finish_condition[false] | talent.hidden_opportunity.enabled[true] ) )
```

This fails because you don't have Keep it Rolling talented and `shadow_dance_condition` is false.

So the question is whether shadow_dance_condition works properly in sims or if there's a priority change needed with your build.
I'm rerunning your sim as 5 target Patchwerk because DungeonSlice is too chaotic to be useful.
Your sim uses Shadow Dance 4.24x in a 4-6 minute fight with 5 targets.
It looks like Vanish not being used could be a factor as well (you have Solo Vanish disabled).

![image](https://user-images.githubusercontent.com/9438134/209599293-0e133dcb-a013-4780-99e4-4e6edf009ecb.png)

![image](https://user-images.githubusercontent.com/9438134/209599305-4b448e6d-a7e2-4cc1-8010-a830c8324903.png)
