### ISSUE TITLE
Crusader strike recommended ignoring holy power

### ISSUE THREAD

**Issue by rikdol** [Hekili/hekili#2170]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

While at 5 holy power, Crusader strike is prioritzed instead of spenders. This doesn't happen immediately and can take some time before it's reproduced. Once it has happened, it seems to happen more frequently. /reload usually clears it, but can return afterwards.

### How to Reproduce

1. Enter game as retribution paladin
2. Enter combat 
3. build up holy power until 5 points.
2. see recommendations

### Talent Loadout

BYEAwtJ2KpR8WbGzhz/jy2AP8AAAAAAIiEAiWKJJkEkcgokSSSUCAAAAAAg0EJJpIBJJl0kERBB

### Snapshot

https://pastebin.com/GVvFerJH

### Additional Information

Happens occasionally, not on every encounter .

### Contact Information

Rik#9999

**Comment by Hekili** [comment]
Provide a Raidbots sim of your character for comparison, please.

**Comment by Ikutabikdu** [comment]
I am having this same issue or something similar. it seems that it is not pulling the finishers all the time? many times it will show cursader strike at 5 holy power. 

https://www.raidbots.com/simbot/report/h3K2axYmeybyi4M7HieKuN
here is my raidbots sim

https://www.raidbots.com/simbot/report/h3K2axYmeybyi4M7HieKuN/simc
and the html report

**Comment by rikdol** [comment]
https://www.raidbots.com/simbot/report/2aYSjdCid4xuC8A6aGGq4D

using this profile today: https://pastebin.com/KGw9SB80

**Comment by cremor** [comment]
I also saw this yesterday with the current version of Hekili. Sadly I didn't take a snapshot.

Maybe the problem has to do with CDs desyncing? Because for me it happend during the Broodkeeper Diurna bossfight where I was on add duty and sometimes used CDs when they were not being recommended.

> https://pastebin.com/GVvFerJH

If I read this snapshot correctly the problem is:

- Seraphim buff was active.
- Templars Verdict was not recommended because Final Reckoning was ready.
- Final Reckoning was not recommended because Avenging Wrath was ready.
- Avenging Wrath was not recommended because Seraphim was ready.
- Seraphim was not recommended because Avenging Wrath was ready.

If this is correct, it should be reproduceable by casting Seraphim before all other CDs.

**Comment by Hekili** [comment]
I definitely need a current snapshot.  Yes, it's a CD desync issue.

**Comment by cremor** [comment]
I tried a few things at the target dummy but couldn't reproduce it. It's not as easy as I thought it would be. The situation that I explained in my last comment can only happen if Seraphim procs (otherwise it won't be ready while the buff is active). But even when Seraphim procs at the target dummy I always get a correct recommendation to use Avenging Wrath/Crusade.

**Comment by cremor** [comment]
Just got it in a boss fight with the current version of Hekili.
Snapshot: https://pastebin.com/PdLaEL7K
Talents: `BYEAwtJ2KpR8WbGzhz/jy2AP8AAAAAAACgIKplkIBkkkWKJJRJAAAAAAACRSSaJBJINJJJloEA`

**Comment by Hekili** [comment]
This should be addressed (at least partially) in the latest release.
