### ISSUE TITLE
MM Hunter 2-set affecting Lock and Load

### ISSUE THREAD

**Issue by F074** [Hekili/hekili#2210]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

This is more of a bug on the side of Blizzard, but I was hoping it could be fixed on the Hekili side at least for the time being.

Marksmen hunter's new 2 set gives you a buff called "find the mark" and it makes your aimed shot glow on your action bars. It also glows now for hekili. This makes it very confusing to know whether or not you have a "lock and load" proc for instant cast aimed shot and it affects whether or not I can be mobile in a fight. This new proc glow effect is useless to track and I'm not sure why it's glowing aimed shot in the first place. Is it possible to stop the glow effect on hekili if I just have "find the mark" and not "lock and load"?

**Comment by RussellAnas** [comment]
Hey another MM main here. I actually like the glow. It reminds me that my next Aimed Shot will cause the target to bleed due to 2-piece set.

I do agree the glow in hekili is for both Lock and Load and for Find the Mark. The way I differentiate is that the Blizz UI shows an additional sign on top of the character when Lock and Load has procced. So if that isn't there, only hekili Aimed Shot is glowing, then it's Find the Mark. If both are present, then it's Lock and Load.

**Comment by Hekili** [comment]
The glow in the addon for these procs comes directly from the default UI's glow.  If the default UI glows, the addon will glow as well.
