### ISSUE TITLE
Demonology Warlock:  Implosion not used before imps expire in lead up to Summon Demonic Tyrant

### ISSUE THREAD

**Issue by SaschaDaSilva** [Hekili/hekili#2228]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Due to a heavily flawed APL on SIMC, Hekili just lets IMPs run out whenever Tyrant is about to be up. As a demonology this is a fatal error, you should always implode on 2+ targets before they run out. And NOT implode after summoning tyrant cause u wanna stack them

The fix is quite easy, i looked into the APL and its flawed on SIMC.

1. Change APL to Implode on 2 Targets or higher with imp gang boss talented (5k dps gain) 
( actions+=/implosion,if=active_enemies>1&buff.wild_imps.stack>=6 ) change this to >1 instead of >2 )

2. Remove implosion from recommendation while tyrant is up, imps should ALWAYS only be imploded when about to run out (which they dont when tyrant is up) to not waste GCDs. So only IMPLODE <3s before tyrant runs out

3. Preperation time for Tyrant should not affect implosion recommendation (it does stop recommending implosion around 15s before tyrant is off cd wasting an entire implosion.. Should force implosion around 8s before tyrant is off cd, to get the implosion dps and start stacking for next tyrant

### How to Reproduce

1. Use everything on CD so you have no cooldowns left
2. Follow rotation on Hekili.
3. Around the 1m mark it starts happening before 2. or 3 tyrant

The SIMC API seems do be flawed here, it tries to save the imps for next tyrant cast but losses all of them in the meantime.
-> https://www.raidbots.com/simbot/report/5XFyi3cSHjK3sj8LCKrEro  1 Minute to 1:15

I think the -- variable.tyrant_prep_start -- is too high. Preperation should not go above 9 secs bc of imps lasting 10

Here you can clearly see on the left (seconds of imps left) half my imps are about to run out, yet i get 3 recommendations (3 globals) that do not include implosion, on 5+ Targets

![imps](https://user-images.githubusercontent.com/68031789/210231285-70466d96-b52e-431f-b817-2e14dd5ab981.jpg)

### Talent Loadout

BoQAbtPS25JQs0VfQSDmhm+p3gcASSkIBSTjg0SSSkSAAAAAQLCSIhIJSSyBi0SicACAAAAAAA

### Snapshot

https://pastebin.com/i8JF68gy

### Contact Information

Sascha#6220

**Comment by Hekili** [comment]
I am very sorry to hear that you died due to this fatal issue.  (More seriously, your ticket does not need a dramatic name like a YouTube video.)

The addon is following the SimulationCraft priority, which does not appear inclined to burn imps with Implosion in the several seconds leading up to Summon Demonic Tyrant.  There may be room to optimize for this, but I'm fairly certain if you simmed yourself in a similar multi-target scenario, you would not see Implosion used when there is about ~7 seconds to Summon Demonic Tyrant, even if the majority of your imps are not going to survive until your Summon Demonic Tyrant cast.

**Comment by SaschaDaSilva** [comment]
Yes, they are not used cause the APL is flawed.
I fixed it myself and its a DPS increase with ->

4-5k dps increase on 2 Targets due to 2+ change not 3+ and not imploding while tyrant
4k dps again with this change to the implosion timing (not imploding every 6imps, but implosion on last/secondlass imp cast

actions+=/implosion,if=last_cast_imps>0&buff.tyrant.down&active_enemies>2+(1*talent.sacrificed_souls.enabled)

**Comment by Hekili** [comment]
> Yes, they are not used cause the APL is flawed.

You can contribute your edits to SimulationCraft and/or make comparison sims to show the value of your changes.  You have to prove your work to solicit edits that might have unanticipated impacts to the priority.

There is very likely some extensive simming needed to balance how many high-energy imps you might be willing to burn in order to get the benefit of Implosion on your low-energy imps.  That balance probably also shifts if you take Reign of Tyranny, but nobody really takes Reign of Tyranny as far as I can see.

Are you able to do some sim comparisons to show your changes are more performant in multi-target scenarios?

**Comment by SaschaDaSilva** [comment]
2 Target, default APL : https://www.raidbots.com/simbot/report/oKqy3UfGi1GsFjJpkgbyFw
2 Target, custom APL : https://www.raidbots.com/simbot/report/8x5pLriRDMakcnWQf7iVU2

7,000 DPS gain with custom apl

5 Target, default APL :  https://www.raidbots.com/simbot/report/vFMsRQgDktvBzPdPbQr3Gw
5 Target, custom APL : https://www.raidbots.com/simbot/report/ju7B57d2NDJTuQB31Diwab

3,000 DPS gain with custom apl

1 Target, default APL : https://www.raidbots.com/simbot/report/52BAxJxSU42HmYtXyNuvBQ
1 Target, custom APL : https://www.raidbots.com/simbot/report/qe7JNo6ncDkAEiMgEHtY8x

1.000 DPS gain with custom apl

All these sims are with the go to AOE builds, patchwerk 5 min

**Comment by eivl** [comment]
Im here looking for the same, and I was not aware until now that it uses SimC as a base. How can I add this to my version of the addon to test it out without relying on waiting for a potential SimC update?

**Comment by Hekili** [comment]
This has been incorporated into the addon.  Thanks!

**Comment by cprn1337** [comment]
This update recommends implosion on a single target, afaik implode should only be used with 2+ targets.

**Comment by Hekili** [comment]
In single-target with Imp Gang Boss, this does result in more DPS according to sims.  Let me know if you see otherwise.
