### ISSUE TITLE
The problem with the Maelstrom Weapon overcap and the frequent recommendation of Lava Lash

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#2229]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

I noticed one strange thing in the aoe addon recommendation script. He's been holding the Maelstrom Weapon stacks for too long. It shouldn't be like this. Because we're going into an overcap. He can ignore the chain lightning and just the lightning and continue to spam Lava lash. Because of this, I lose damage because the addon does not offer me to use lightning or chain, but simply spams Lava lash further, and only with a trifle can make a recommendation for 5 seconds that I use stacks. I checked in simcraft on rotation everything is fine there are no overcaps, rotation can hold stacks, but literally for 1-2 abilities, which is not critical.

### How to Reproduce

Start the fight with 5 targets, and continue to rotate as in the screenshot until 0:06:613 and at the next segment 0:07:368 the chain lightning will be skipped and Lava Lash will be offered, which goes to 0:08:122.
![image](https://user-images.githubusercontent.com/63850853/210231250-1296b4f4-98ba-45af-a46d-6a6557bb69dd.png)

### Talent Loadout

BcQAfcj78nJtvjmejSqe5Zhm9IRSaRCiIhIJJUSkAAAAAAAAAAAAAQJCRIJCRBSJJJFAlEJBA

### Snapshot

https://pastebin.com/exn68QuL

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/b4dSRpZPwdaAaxzpP7xEaM

**Comment by Hekili** [comment]
> Start the fight with 5 targets, and continue to rotate as in the screenshot until 0:06:613 and at the next segment 0:07:368 the chain lightning will be skipped and Lava Lash will be offered, which goes to 0:08:122.

The snapshot you provided didn't *skip* any usage of Chain Lightning.  It didn't reach the entry for Chain Lightning because the other entries are higher in priority and reached first.  This also occurs in your sim:

<html><body>


Time | List | # | Name | Target | Resources | Buffs
-- | -- | -- | -- | -- | -- | --
4:03.914 | default | E | feral_spirit | Fluffy_Pillow | 50000.0/50000: 100% mana | flurry(3), splintered_elements(5), ashen_catalyst(5),  crash_lightning, hot_hand, stormbringer, maelstrom_weapon(9),  elemental_chaos_frost
4:04.830 | aoe | N | lava_lash | enemy2 | 50000.0/50000: 100% mana | flurry(2), splintered_elements(5), feral_spirit,  icy_edge, molten_weapon, ashen_catalyst(8), crash_lightning, hot_hand,  stormbringer, **maelstrom_weapon(10)**, elemental_chaos_frost
4:05.745 | aoe | N | lava_lash | enemy3 | 50000.0/50000: 100% mana | flurry, splintered_elements(5), feral_spirit, icy_edge,  molten_weapon, ashen_catalyst(5), crash_lightning, hot_hand,  stormbringer, **maelstrom_weapon(10)**, elemental_chaos_frost
4:06.662 | aoe | O | chain_lightning | Fluffy_Pillow | 50000.0/50000: 100% mana | flurry, feral_spirit, icy_edge, molten_weapon,  ashen_catalyst(5), crash_lightning, hot_hand, stormbringer,  maelstrom_weapon(10), elemental_chaos_frost


</body>
</html>
