### ISSUE TITLE
i want my cooldowns to reccomend shadow dance off cooldown like adrenaline rush

### ISSUE THREAD

**Issue by Askew666** [Hekili/hekili#2259]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

i expect the addon to recommend shadow dance off cool down on the cooldowns section of hekili li0ke it does with adrenaline rush but it never recommends shadow dance ever

### How to Reproduce

1. enter the game as an outlaw rogue
2. open hekili and check cooldown and show separately on the toggle tab
3. have shadow dance selected as a talent
4. it doesnt ever recommend shadow dance

### Talent Loadout

BQQAOB/7AZ//CwQOf4fPMswHVDAAgERSAkkEJSSCkEJRikkkkECAAAAAAQSSimUSCIBAAAA

### Snapshot

https://pastebin.com/wcYhWKwu

**Comment by vond82** [comment]
Shadow dance isnt used on cooldown for outlaw and as long as you have somewhat decent luck with rng it can be a long time before it should be used

**Comment by n00del** [comment]
I also got some strange issues, that hekili was not recommending blade flurry in aoe situations like in the versions before.
Maybe its just an issue registering my talents. 
Is there any way to force this again or check this ingame?

**Comment by Hekili** [comment]
@n00del You can submit your own ticket for your issue, but I guarantee the addon detected your talents.  If you haven't imported or written a custom priority, I'll troubleshoot when you provide the snapshot in your own ticket.

@Askew666 Shadow Dance wasn't recommended here because it isn't intended to be used as soon as it's up for Outlaw.  You could take a look at the [FAQ](https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions) and add it to your priority without conditions, but I don't think you'll find it optimal.

Shadow Dance's conditions in the priority are a bit complicated because there's a variable for it (`shadow_dance_condition`) which checks multiple talents and also required Between the Eyes to be up on your target.  It'd be easy to do a target swap and no longer have that condition met.

`shadow_dance_condition`: `talent.shadow_dance.enabled[true] & debuff.between_the_eyes.up[false] & ( ! talent.ghostly_strike.enabled[false] | debuff.ghostly_strike.up[false] ) & ( ! talent.dreadblades.enabled[false] | ! cooldown.dreadblades.ready[true] ) & ( ! talent.hidden_opportunity.enabled[true] | ! buff.audacity.up[false] & ( talent.fan_the_hammer.rank[2.00] < 2 | ! buff.opportunity.up[false] ) )`

Condition for use (w/o Keep it Rolling):  `! talent.keep_it_rolling.enabled[false] & variable.shadow_dance_condition[false] & buff.slice_and_dice.up[false] & ( variable.finish_condition[0.00] | talent.hidden_opportunity.enabled[true] ) & ( ! talent.hidden_opportunity.enabled[true] | ! cooldown.vanish.ready[true] )`

I'm going to keep the addon's recommendations consistent with the sim priority at this time, so I won't be making changes directly here.

**Comment by krij03** [comment]
Im new to the game so forgive me if im wrong. Shadow Dance applies all combat benefits that Stealth does, right? So with Nightstalker (+8% damage) and Take 'em by Surprise (10% haste) not using it on cooldown seems like a dps loss. Can the 1 time those conditions are met make up for all the damage thats lost by not using it?

Is there a way to check what forcing the sim to use it would do to the dps and compare?

**Comment by chevyn11** [comment]
@krij03 the rogue discord has channels for theorycrafting these sort of things, its likely already been found to be optimal the way it is but you are welcome to go in and present your ideas, perhaps someone will show you how to edit the sims to test it. 
If its found to be better, then the official simc apl will be updated and hekili will follow soon after.

**Comment by vond82** [comment]
Its also worth noting that Nightstalker does not give +8% dmg as its been bugged since DF release. Even when it does start working its a dps loss to use on CD for outlaw though as per rogue theorycrafters
