### ISSUE TITLE
Enhancement shaman do not recommend chain lightning with multi-targets

### ISSUE THREAD

**Issue by ZeenL** [Hekili/hekili#2268]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

With the multi-target, it will choose to recommend elemental blast instead of chain lightning.

### How to Reproduce

when the maelstorm weapon got 10 stacks in aoe environment and there is no primordial wave buff, the next common recommendation might be chain lightning.

### Talent Loadout

BcQAAAAAAAAAAAAAAAAAAAAAAIRSKRCIJhIJJUSkAAAAAAAAAAAAAQJJkES0CRBIJJFAlEJBA

### Snapshot

https://pastebin.com/xjUF3Jfb

### Contact Information

Arthur#5956

**Comment by Hekili** [comment]
You did not supply a complete snapshot.

**Comment by ZeenL** [comment]
https://pastebin.com/wNFs1TPF
sorry,  my mistake

**Comment by Hekili** [comment]
The recommendation is consistent with the priority; if Elemental Blast weren't available, Chain Lightning would've been the next ability to test and recommend.

`Elemental Blast`:  `( ! talent.elemental_spirits.enabled[false] | ( talent.elemental_spirits.enabled[false] & ( charges[2.00] = max_charges[2.00] | buff.feral_spirit.up[true] ) ) ) & buff.maelstrom_weapon.stack[10.00] = 10 & ( ! talent.crashing_storms.enabled[false] | active_enemies[5.00] <= 3 )`

Essentially, Elemental Blast was used here because Elemental Spirits was not talented, Maelstrom Weapon was capped, and Crashing Storms is not talented.

You could try re-ordering the AOE action list in SimulationCraft and simming in multi-target scenarios.  If it results in higher DPS, report it to SimulationCraft and I'll follow their lead here.
