### ISSUE TITLE
Blood DK not recommending Whetstone or Lichborne

### ISSUE THREAD

**Issue by IdiotSavante** [Hekili/hekili#2276]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

I haven't seen either of these 2 spells enter in to my rotation regardless of what options I select.

### How to Reproduce

1. Enter the game as Blood DK
2. Have the trinket equipped
3. Spec into Lichborne
4. 

### Talent Loadout

BoPAdLUHklrTr3hBIcYWdbnCGDCJhgkkkISERiIhgDkkEJAAAAAAJSSOQQSTISAAARSSSCAAAA

### Snapshot

https://pastebin.com/PZ37qHeV

**Comment by xNeptune** [comment]
I went ahead and looked into the Action priority list for your specialization and turns out lichborne is never checked so it'll never be suggested.
As for the trinkets, the current APL has some conflicting conditions that prevent it from suggesting a buff trinket if both are off cooldown and one doesn't have a use action.

If you're comfortable enough to go into hekili's profile and look at the simc profile import section, you can scroll to the bottom of the code that's there and you should find a couple lines that look nearly identical to what's below. Select the lines that match and replace them with what I have written below. At that point you'd just "import" again and it'll commit those changes to the priority helper. 

actions.trinkets+=/use_item,slot=trinket1,if=variable.trinket_1_buffs&(buff.dancing_rune_weapon.up|!talent.dancing_rune_weapon|cooldown.dancing_rune_weapon.remains>20)
actions.trinkets+=/use_item,slot=trinket2,if=variable.trinket_2_buffs&(buff.dancing_rune_weapon.up|!talent.dancing_rune_weapon|cooldown.dancing_rune_weapon.remains>20)

**Comment by IdiotSavante** [comment]
Thank you so much! I applied this fix and Whetstone is being recommended now! Does this also make Lichborne work, or is there something separate I need to do?

**Comment by Hekili** [comment]
Lichborne will not be added to the base priority; it's more of a utility ability that you should use at your discretion.
