### ISSUE TITLE
Frost Shock when Icefury buff is on not being recommended soon enough

### ISSUE THREAD

**Issue by mspykerez** [Hekili/hekili#230]
Hi,
When playing elemental shaman with Icefury talent selected I notice the following:

Hekili is not suggesting the use of Frost Shock enough times before Icefury buff expires! Meaning that when I press Icefury i got a 15s window to use 4xFrost Shock for an addition 200% damage and generate 8 maelstrom, the thing is the addon is not suggestion the use of frost shock enough times before humanly possible to press before the buff of Icefury expires (I notice it suggests the use of Frost Shock when Icefury buff on a random fashion and I never ever get to press 4x Frost Shock because there is no time to do if I follow the addon suggestions). Isn't always beneficial to use Frost Shock when we have Icefury buff on?

**Comment by Hekili** [comment]
You would need to test priority changes in SimulationCraft for something like this.

**Comment by mspykerez** [comment]
One thing is for sure, every guide I read out there says its imperial to use all your Frost Shock charges before the buff of Icefury expires, so something in SimulationCraft is wrong or is it something that has to do with the addon and how it approaches stuff.

**Comment by Hekili** [comment]
It's a matter of timing GCDs before the Icefury buff falls off. I can make an option to expand the window for using the buffs but you still haven't shown any adjustments to sims to confirm an improvement in DPS.

**Comment by Hekili** [comment]
Okay, so after some additional research, the key things impacting these Frost Shock recommendations are:

1.  The SimulationCraft profile uses a lot of `cooldown_react` conditionals for Lava Burst.  In the sim, this means that these entries for Lava Burst can be used immediately when the LvB cooldown naturally expires or 0.5 seconds (default reaction time) after the LvB cooldown is reset by a Lava Surge proc.  The addon doesn't emulate those reaction times because, well, you are a human with your own actual reaction time.

2.  The oh-god-don't-waste-Icefury entry for Frost Shock is very far down the action list -- it's the 28th entry in the single-target list.  And it only budgets an extra 10% of the global cooldown per stack of Icefury remaining.

![image](https://user-images.githubusercontent.com/9438134/71826749-ade09800-306c-11ea-8dbc-d4223992966f.png)

The easiest workaround for the moment is to move that Frost Shock entry up the priority a fair bit.  It looks DPS neutral at worst, and sometimes beneficial, to just move it higher and higher in the APL.  Clicking the up arrow at the screen above until it's second in the single_target priority list seems to sim best out of all the positions I tried.

Examples:
> https://www.raidbots.com/simbot/report/ojixV6J36MY8gThQpn43Kk
> https://www.raidbots.com/simbot/report/g6akym1PLEaLitQUuCtXcG
> https://www.raidbots.com/simbot/report/6TF6TDruj1QpgBJfLv4TNp
> https://www.raidbots.com/simbot/report/eSB9jiCFPq8prTJrvbQUmy

I'll toy with it a bit further and see what I might need to do differently so that `cooldown_react` entries are more consistent with SimulationCraft.  Tracking proc-based CD resets is a fair bit more complicated than it might seem.

**Comment by mspykerez** [comment]
Thx for helping out!
