### ISSUE TITLE
SimC profile not updated?

### ISSUE THREAD

**Issue by Neekodesu** [Hekili/hekili#2303]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

I'm having doubts or issues regarding to the SimC default profile of Outlaw Rogue. Someone told me that you can actually import your sims to make Hekili suggest you better, somehow didn't look like it has nothing to do with raidbots, more like "SimC".
I downloaded SimC.exe and imported some SimC profile based on my current character. That SimC profile had nothing to do with the supposed profile by default in Hekili, tons of things were different so I was wondering if this is on purpose or not.
I'll share pastebins of the supposed SimC profile of SimC.exe and the one that Hekili has on default,  since im not exactly sure if this changes are made on purpose for Hekili:
Updated one: https://pastebin.com/LRAWjmQz
Hekili default SimC profile: https://pastebin.com/95NXyeAg

This research i made is kinda based on a YouTube video I found about setting up Hekili to enhace your rotation: https://www.youtube.com/watch?v=h-OTQRnZ9a8 and looks like makes it more accurate based on your character. Would like to confirm if this is true

### How to Reproduce

Kinda a doubt/question not a bug

### Talent Loadout

BQQAOB/7AZ//CwQOf4fPMswHVDAAgERSAkkEJSSCkEJRikkkkECAAAAAAQSSimDUSCIBBAAAA

### Snapshot

Sorry I guess no snapshot is needed for this

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/idoPE8kv6rK8EYiiNptAUz

### Additional Information

By just watching raidbots quick sim in pre-pull i can see that the opener suggestion is totally different from what hekili is suggesting, as i can see Ambush > Adrenaline > Whetstone > Ambush > Between the eyes.

### Contact Information

Neko#7422

**Comment by Hekili** [comment]
The snapshot is required.

**Comment by Neekodesu** [comment]
Here is the snapshot i guess
https://pastebin.com/zXLRsuqS

**Comment by Neekodesu** [comment]
Also, this is what WoWAnalyzer says when I follow Hekili... https://www.wowanalyzer.com/report/BJ4F87m31MVDYxXg/4-Heroic+Dathea,+Ascended+-+Kill+(3:44)/Nekoo/standard/overview

**Comment by xNeptune** [comment]
I went ahead and looked at all the information you provided regarding the differences in profiles and suggestions etc. and to start I'd like to mention that raidbots is obviously a controlled environment with predetermined timings and outcomes so certain actions are taken out of the profile when converted into Hekili's lists. 
As far as the profiles go that you provided, both of them are nearly identical, apart from the precombat recommendations that get removed. I say nearly identical because the only things that change between the two are the orders in which some of the lists are checked. The snapshot you provided for hekili's actions match the raidbot pre-pull as well. Hekili suggested you Stealth>Roll the Dice>Ambush & had another recommendation been given it would've been Adrenaline Rush as your snapshot procc'd the recommendation but couldn't show it due to not having combo points. Raidbots uses SimulationCraft's profiles, Hekili uses SimulationCraft's Profiles (with slight alterations due to obvious differences of a controlled encounter simulation)

**Comment by chevyn11** [comment]
to add to this:
1. an actual fight log is worthless to hekili because you have to make your own decisions in the middle of a fight and cant guarantee that you are perfectly following hekili.
2. wowanalyzer is not up to date or maintained often enough to keep up with current sim recommendations.

**Comment by Neekodesu** [comment]
But I downloaded SimC 1002.01 and imported from Blizz character, and the SimC profile is way different from the Hekili one. Which one should I be using?

**Comment by Neekodesu** [comment]
So there is no way to optimice the SimC Profile in Hekili based on my Char/talents/stats/gear? The default one is already the best for my current char?

**Comment by chevyn11** [comment]
yeah default simc (which hekili already uses) is best, it already takes into account your talents. 
Simc also doesnt evolve the APL based on your stats/gear it still uses the one APL for everything, changes to it have to be made by the developer.

**Comment by Neekodesu** [comment]
Aight that was a clear answer, thank you so much for resolving my doubts <3 I was confussed about the youtube video telling me doing that was the best way to setup Hekili (importing the SimC profile)

**Comment by chevyn11** [comment]
no worries! and yeah I've seen that video before and I think its just false information. 
Unfortunately plenty others have seen it too and best case scenario is it works the same as default, but at worst it can actually break your profile because sometimes hekili modifies the apl a little bit to better translate into the addon.

**Comment by Hekili** [comment]
Thanks for working through it, @chevyn11.  You don't need to import anything, and priority lists don't (generally) customize to your character in any meaningful way.  I account for those changes with the defaults.
