### ISSUE TITLE
Arcane Mage Rotation messes up with lust on pull.

### ISSUE THREAD

**Issue by MeowthMeows** [Hekili/hekili#2320]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Arcane Mage opener messes up when lust off start. It is basically recommending nether tempest , rop , arcane blast x4 , Radiant spark then it does not show Arcane Surge into mana gem then barrage + totm when lust is active on pull.

### How to Reproduce

Be arcane spec mirror image, evo, arcane orb and then double lust. Priority is incorrect after that.

### Snapshot (Link)

https://pastebin.com/ZUTedi5x

**Comment by Hekili** [comment]
Your snapshot doesn't align with the timing you describe.  You don't have Time Warp (or any Bloodlust) up.

**Comment by MeowthMeows** [comment]
https://pastebin.com/mpAfPbTq

should be updated with lust active now.

**Comment by Hekili** [comment]
At the time you took your snapshot, what did you expect it to recommend instead?  Do you have Touch of the Magi macro'd somewhere?

Can you provide a Raidbots sim link for comparison?

**Comment by MeowthMeows** [comment]
![image](https://user-images.githubusercontent.com/120591954/214709711-82061a2a-35b1-49c8-911e-f57c5fd4177c.png)
is from the arcane discord it self. 

https://www.raidbots.com/simbot/report/bzZyA8PKQy6rERfnhwV8Eq

is an example of sim of how it should perform roughly. 
The main problem from what i see is that it does not recommend arcane surge at all during lust opener

**Comment by Hekili** [comment]
> At the time you took your snapshot, what did you expect it to recommend instead?

> Do you have Touch of the Magi macro'd somewhere?

**Comment by MeowthMeows** [comment]
I do have it macro’d. it is on my e button and it’s cast sequence with barrage so I just have to hit e twice to cast barrage then magi. I took snap after I had ran out of mana to show it didn’t recommend arcane surge at all within that time frame.

**Comment by Hekili** [comment]
Casting ToTM is like flipping a switch to go into the Touch of the Magi priority.  If you are casting TotM before Arcane Surge, you're effectively blocking the priority from working as written.

![image](https://user-images.githubusercontent.com/9438134/214735643-2dfe9f3f-e545-40c4-b0bc-dc29d0e2f84f.png)

Are you pressing TotM because it was recommended, or are you using it early and causing the addon to jump out of the precursor phase before the touch phase?

**Comment by MeowthMeows** [comment]
I am using it because the addon recommended me to.

**Comment by Hekili** [comment]
Great, can you snapshot when TotM is being recommended despite Arcane Surge not having been used yet?  Thanks!

**Comment by MeowthMeows** [comment]
Skips arcane surge completely and recommends barrage then magi

**Comment by MeowthMeows** [comment]
Sure let me log on

**Comment by MeowthMeows** [comment]
https://pastebin.com/2RsUw9R9

hopefully i did it right. waiting 10 mins for lust stinks.

**Comment by Hekili** [comment]
Okay, this one is subtle.  I have a potential fix that I'll leave for you to test.  The biggest issue is that when Bloodlust is up, Nether Tempest is cast earlier in the priority (`spark_phase - 1`).  There is a second cast of Nether Tempest (`spark_phase - 8`) before Arcane Surge, which Arcane Surge relies upon in its conditions: `( ! talent.nether_tempest.enabled & prev_gcd.4.radiant_spark ) | prev_gcd.1.nether_tempest`).  This means that Arcane Surge is cast when Radiant Spark was used 4 GCDs ago if Nether Tempest isn't talented, otherwise it is used immediately following Nether Tempest.

So the problem is that SimulationCraft controls these entries using the `line_cd` feature.  `spark_phase - 1` can only fire every 15 seconds and the same goes for `spark_phase - 8` -- they have *independent* 15 second cooldowns.  However, the addon *cannot* know why you pushed Nether Tempest; it doesn't know that your first cast was `spark_phase - 1` because maybe you just pushed it by mistake.  So `line_cd` in the addon actually treats all Nether Tempest entries as through they're on the same 15 second cooldown.

I've removed the 15s `line_cd` from `spark_phase - 8` and adjusted its logic.  I'll post a release in a bit that includes these changes.

**Comment by Hekili** [comment]
Please let me know if you've observed a difference since the update.  Thanks!

**Comment by MeowthMeows** [comment]
It still has not fixed. It recommends the same as before. I have noticed though during the lust window if i just pause and wait 2-3 seconds while lust is active it will recommend arcane surge, but that requires to pause for 2-3 seconds which isn't ideal.

**Comment by Hekili** [comment]
Let's see a snapshot with the latest release then.

**Comment by MeowthMeows** [comment]
same as last time? snapshot when it recommend barrage + totm?

**Comment by Hekili** [comment]
Based on this:

> I have noticed though during the lust window if i just pause and wait 2-3 seconds while lust is active it will recommend arcane surge, but that requires to pause for 2-3 seconds which isn't ideal.

I'd say a snapshot when it should be recommending Surge but isn't, and then a snapshot after waiting 2-3 seconds and Surge *is* recommended.

**Comment by MeowthMeows** [comment]
weird. It's starting to recommend it correctly when it wasn't when i had tried up when i last updated.

https://pastebin.com/Sxsp3sE9 <--- Either way here is a snapshot where addon dissappears and comes back.

waiting till lust is up again to see if i can replicate arcane surge not being recommended again.

**Comment by Hekili** [comment]
> here is a snapshot where addon dissappears and comes back.

I don't know what this means.
