### ISSUE TITLE
Vengeance recommendations omitting some rotational abilities

### ISSUE THREAD

**Issue by Havaianas1** [Hekili/hekili#2340]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Im having a problem with DH Vengence with this last update. It wont recommend some core abilities anymore (sometimes it shows on the queue, but not on primary), some of the abilities it isnt recommending are Soul Carver, Fiery Brand, Fel Devastation, The Hunt, Immolation Aura, Elysian Decree. It basically just rotating between Fracture, Soul Cleave, Sigil of Flame and Throw Glaives.

### How to Reproduce

1. Enter as Vengeance DH
2. Any endgame talent build (best with some of the core abilities like Soul Carver, Elysian Decree and The Hunt). Here is the one I'm using (BUkACnvaHJn8GSPD6tpaeczPTBAgIIJBJRDJJARDkEtQikkkkElkgkkEpEEAAAAA)
3. Start rotation on any target dummy (single target or cleave)
4. Core abilities described should never pop up (Soul Carver, Fiery Brand, Fel Devastation, The Hunt, Immolation Aura, Elysian Decree)
5. Sometime some of the core abilities appear on the 2nd or 3rd queue position, but never becomes recommended on main one.

### Snapshot (Link)

https://pastebin.com/3V2yxx6C

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/tTkvzHHEBVH7wqkFgQ7hQv

### Contact Information

Havaianas#8955

**Comment by IanLukeFinley** [comment]
I am having exactly the same issue.  Commenting here to follow the thread.

**Comment by SnoweyBallz** [comment]
Having the same issue.

Snapshot (Link):
https://pastebin.com/LXCXD5Tc

Raidbots Sim:
https://www.raidbots.com/simbot/report/crPqvm8zPGYjgB3cYGb1zW

**Comment by Hekili** [comment]
I have a release coming out this evening that may address it.

**Comment by Hekili** [comment]
Let me know if you're still experiencing issues since 1.0.4 was posted.  Thanks!

**Comment by PopsGG** [comment]
I am still having the same issue with build: v10.0.5-1.0.4. Exactly as described in the OP. @Hekili 
Not sure if its related but I got the 2 set bonus this week.

**Comment by Hekili** [comment]
Thanks, an updated snapshot would be helpful.

**Comment by PopsGG** [comment]
> Thanks, an updated snapshot would be helpful.

https://pastebin.com/RMPCvVKP
Here is a new pastebin snapshot. You can see Fiery Brand is next in line, however it will not be recommended, it will likely be Fracture or Soul Cleave instead.

**Comment by Hekili** [comment]
Thanks.  I have another testfix coming out in 1.0.4a-beta1, which should be available soon.  Please test again.  If you're still having issues, please paste your talent string again as well as a new snapshot.  I appreciate your help.

**Comment by PopsGG** [comment]
@Hekili Same issue with 1.0.4a-beta1
Snapshot: https://pastebin.com/R65eBXv1
Talents: BUkACnvaHJn8GSPD6tpaeczPTBAgIIJREARCQSJBJR7ARiEJhEtkUSSSSoEJBAAAAA

**Comment by Hekili** [comment]
According to your snapshot, The Hunt is on cooldown for 90 seconds -- as though you *just* used it.  That also happens if the ability is disabled.  Did you disable The Hunt?

**Comment by Hekili** [comment]
Alternately, did you put The Hunt on a different toggle?  The addon shows The Hunt's cooldown as 90s everywhere it checks in your snapshot, which is when an ability is forbidden from being used (whether disabled or toggled off).

**Comment by PopsGG** [comment]
Yes The Hunt is on a different toggle, I do not want it recommended.

**Comment by Hekili** [comment]
So what ability did you think should've been recommended, but wasn't, at the time of your most recent snapshot?  The Vengeance priority is built around phases for your capstone talents like The Hunt.  Eliminating it from recommendations will definitely break the priority.

**Comment by PopsGG** [comment]
I am not sure of the terminology but in the UI I see the next 3 recommendations in order. 
IE: Fracture(1.17), Fiery Brand(2.47), Immolation Aura(3.78)

I expect Fiery Brand to move from #2 to #1 after I cast Facture. Instead all 3 abilities are replaced and Fiery Brand never becomes #1. As OP stated, I never see some core abilies make it to the #1 slot. Like Soul Carver, Fiery Brand, Fel Devastation and others.

**Comment by Hekili** [comment]
Are there other abilities you've disabled or moved to a different toggle?

**Comment by PopsGG** [comment]
No, The Hunt and Infernal Strike are the only abilities I have disabled or put on a toggle from default.

**Comment by IanLukeFinley** [comment]
Thank you for your prompt and dedicated work on this.  The problem continues for me, although The Hunt now does display.  In the screenshot here, you'll see that while both Fel Devastation and Soul Carver are up, neither is recommended (they are in fact never recommended).  

Let me know if there's other information I can provide, and thank you again for your support on this project.

Talents:  BUkACnvaHJn8GSPD6tpaeczPTBAQJClkEAFRSCQ0AJRLkIJJJJRLJIJJhSkEAAAAA
Screenshot: ![WoWScrnShot_012823_204235](https://user-images.githubusercontent.com/107075390/215299965-80a84546-a38c-4a7c-8e77-98df6aaf051c.jpg)

**Comment by Hekili** [comment]
@IanLukeFinley Could you get a snapshot when you think those abilities should be recommended but aren't? I'm assuming cooldown abilities are toggled on.

**Comment by ryanjoliveira** [comment]
Figured I'd submit my own snapshot as I see the exact same thing.

https://pastebin.com/0zr7AYk9

AoE snapshot; why i think it is incorrect:  Throw glaive is recommended while Immo Aura is off cooldown, Fel Dev is off cooldown, and I have enough fury to cast Fel Dev also.

Would also like to suggest that it could be talent related.  My M+ build seemed to be giving me fine recommendations.  My raid build was not.  I kept moving talents around changing my raid built toward my M+ build and eventually taking out the 2 points in "Fiery Demise" and putting them in "Feed the Demon" and suddenly Fel Dev, Fiery brand, Immo aura, etc are all being recommended properly again (as far as I can tell, at least).

If I had to guess, since those are all fire abilities, and Fiery Demise buffs fire damage, it seems like something is improperly waiting for fiery brand/fiery demise to be applied before it casts these other big fire abilities?  But even if I force cast Fiery brand (outside of recommendation), it seems hard to get it to recommend these abilities, so I don't know.

**Comment by Hekili** [comment]
Yes, having Fiery Demise talented impacts a branch in the priority list.  The branch is checked when the addon goes to generate recommendations, but isn't setting properly for you (and apparently others).  I'm still investigating.  If you want to paste your talent string along with your snapshot(s), that'll help me compare apples to apples.  Thanks!

**Comment by ryanjoliveira** [comment]
This would be the talent build that goes along with my earlier snapshot:

BUkACnvaHJn8GSPD6tpaeczPTBAQJQJJRkEQkAkUSgEtEJSkEOQSJJIJJRKBBAAAAA

**Comment by towicode** [comment]
@Hekili Another (related? the same?) bug seems to be with the phasing.

In this snapshot (im posting it below) Fiery Demise should be casting, but for some reason the variable fails. Even though both
`Soul Carver` and `Fel Devestation` are off cooldown.
```        35.  run_action_list:fiery_demise_window ( default - 23 )
        Criteria for fiery_demise_window FAIL at +0.00 - variable.fiery_demise_in_progress[false]
```

I see later in the snapshot that the variable gets set to true, but is this too late? I'm not sure what `runHandler` and `resetPrecast` entail. But I think that's likely the issue.

```
    Completed default action list [ Vengeance - default ].
    Recommendation is soul_cleave at 0.00 + 0.00.
    Recommendation #1 is soul_cleave at 0.00s (0.00s).
    [ Vengeance ] Phase 'fiery_demise_in_progress' set to 'true' (runHandler) - virtual.
    [ Vengeance ] Phased variable 'sub_apl_in_progress' set to 'true' (runHandler) - virtual.
```

Snapshot: https://pastebin.com/Hi4NW9pU
Desired Action: Cast Fiery Brand


Also in discord I linked a video of a weird bug that could possibly be related to this. When you hover over the window and the text for the variable you get different results.
https://discord.com/channels/307520968895627264/307520968895627264/1069698840548093982

**Comment by Hekili** [comment]
Yes, needing to have phases and phased variables that have memory from one iteration to the next is really finicky and new to the addon.  I just posted 1.0.4b which seems to function, though I made some alterations to the fiery_demise_in_progress logic so that the window doesn't close prematurely and cause Fiery Brand and Soul Carver to keep drifting forward in time instead of getting recommended.  Let me know if it seems to resolve our issues.  If it doesn't, new snapshots are needed again.

**Comment by towicode** [comment]
@Hekili you can likely mark this closed, at least on my end. Abilities are now being shown in the primary spot.

**Comment by IanLukeFinley** [comment]
Ditto here, the most recent update suggested all my abilities as I would expect them; my rotation feels complete again.  Thank you again for your hard work on this!

**Comment by ryanjoliveira** [comment]
I think the good news is it is in way better shape now.  I don't think any abilities are being completely omitted.  

However I still worry that good opportunities to cast fel dev are being missed.

Here is another snapshot.

https://pastebin.com/dQqP6nEC

I made a point of capturing a screenshot at the same time as the snapshot:

https://imgur.com/a/nRxakPf


Talents: BUkACnvaHJn8GSPD6tpaeczPTBAQJQJJRkEQkAkUSgEtEJSkEOQSJJIJJRKBBAAAAA

My thought process: Fiery Brand has spread to all 5 of my targets.  The shortest duration brand left is 5 seconds, so I am quickly going to lose my window of getting a sick fel devastation off against 5 branded targets.  But its recommending me to throw glaive in AoE, and no fel dev in sight for the next couple predicted moves either.  I'm fury capped so I dont see why it wouldnt at least be telling me to Soul Cleave or something.

My basic issue with this new version, even though it is HUGELY improved is there were Fiery brands that went out and then ended without a recommendation of Fel Dev.  Maybe its an APL issue and not a Hekili issue, but I just thought it was worth mentioning before this gets closed too fast.  I'm happy to open a different issue ticket rather than piggybacking off this one though.  It just seems like too many stars are being waited to align to cast Fel Dev or something.

https://www.raidbots.com/simbot/report/x7grKL2K6Qhnadr9jKaWhX

Granted, even in this sim, it seems to only cast fel dev twice in 5 minutes? Thats odd and maybe the APL is shot as well.  In that case I could take this up somewhere else.  

But if I could ask for anything, could we maybe get a toggle for "prioritize fel dev even outside of fiery demise ramps"?  I do feel like maybe the current APL (and not just hekili) waits too much for certain stars to align and this would be a quick fix for me, even if not totally optimal.

**Comment by Hekili** [comment]
@ryanjoliveira Yeah, that's really an APL issue that should be tested in SimulationCraft.  You're right that 2-3 casts of FD in 5 minutes is a problem.  Maybe @towicode wants to take a look at your Raidbots report.

**Comment by Hekili** [comment]
Closing this ticket for the original issue.  I'll continue to watch for Vengeance APL updates that increase the use of Fel Devastation with Fiery Demise.
