### ISSUE TITLE
Outlaw Rogue 10.0.5 RTB boardside buff should always keep after pistol nerf due to combo point nerf

### ISSUE THREAD

**Issue by steveozz** [Hekili/hekili#2342]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

RTB boardside buff should always keep after pistol nerf due to combo point nerf, but it will let me roll the bone to roll off boardside buff away when it is single buff, after 10.0.5 it should be keeped.  Also sometime combo points will overcap. 

### How to Reproduce

Keep boardside RTB buff
[ Slice and Dice](https://www.wowhead.com/spell=315496/slice-and-dice) if at max, or -1 from maximum combo points with [ Broadside](https://www.wowhead.com/spell=193356/broadside) or [ Opportunity](https://www.wowhead.com/spell=195627/opportunity) active, if missing or has has 12 or less seconds remaining.
[ Between the Eyes](https://www.wowhead.com/spell=315341/between-the-eyes) on cooldown if at max, or -1 from maximum combo points with [ Broadside](https://www.wowhead.com/spell=193356/broadside) or [ Opportunity](https://www.wowhead.com/spell=195627/opportunity) active.
[ Dispatch](https://www.wowhead.com/spell=2098/dispatch) if at max, or -1 from maximum combo points with [ Broadside]

### Snapshot (Link)

https://pastebin.com/tmWqLcVe

### Additional Information

when i have boardside rtb buff it will let me roll away the buff.

**Comment by Hekili** [comment]
When sims are updated, the addon will be updated.

**Comment by Hekili** [comment]
The sim profile is still explicitly written to reroll with Hidden Opportunity if (a) you will *not* lose Skull and Crossbones _and_ (b) you'll lose fewer than 2 buffs (not counting Grand Melee) -- part (b) changes to 3 buffs if Loaded Dice is up.  The comment in the sim profile states:  `With Hidden Opportunity, prioritize rerolling for Skull and Crossbones over everything else`

In your snapshot, you have Broadside and Grand Melee up and both will be rolled away.  You're talented for Hidden Opportunity.  You don't have Loaded Dice up, and you'll lose one buff -- Broadside -- since we don't count Grand Melee.  Therefore, the reroll logic is met.

`! rtb_buffs_will_lose_buff.skull_and_crossbones[false] & ( rtb_buffs_will_lose[2.00] - rtb_buffs_will_lose_buff.grand_melee[true] ) < 2 + buff.loaded_dice.up[false]`

This matches the pin in the Outlaw channel in Ravenholdt, as well:
![image](https://user-images.githubusercontent.com/9438134/215640238-fb2d706f-9a42-4b3b-a801-50a194743957.png)
