### ISSUE TITLE
Not the correct priority of Lava lash and Flame shock

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#2348]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The essence of the problem is simple. During AOE, when we started the fight, we start using Flame shock and after Lava lash, so that we can impose Flame shock on nearby targets. But if we have a goal that stands a little further from the main goals, and when we approach it, the addon first recommends pressing Lava lash and then Flame shock. In this case, the addon violates the main rule that if the target does not have Flame shock, then we use it. Or the second condition, if there is already Flame shock on nearby targets, then we use Lava lash through the main target with Flame shock to spread to nearby targets. The addon should not advise using Lava lash without Flame shock first. There should always be a check on the target whether there is a Flame shock or not. And then use the rotation further

### How to Reproduce

1. Start the battle in waldraken with dummies 5 goals
2. Start using your rotation.
3. And at the moment of using rotation in the middle of the battle, take a walk up to another nearby target and click on it. Rotation using Lava lash will be offered

### Snapshot (Link)

https://pastebin.com/WCHBs0ca

**Comment by Hekili** [comment]
No, this matches the current priority.

**Comment by Dragonfo** [comment]
No, it doesn't work fine. What makes you think that ? The addon cannot recommend using Lava lash without Flame shock. Moreover, it was clearly visible there that the addon showed even on Lava lash to switch to another target where there is Flame shock. It's your addon's problem that it doesn't track Flame shock on the target. Moreover, in AOE, using Lava lash for a purpose is a loss of dps + not spreading Flame shock for other purposes. I'm even ready to attach a screenshot that the addon recommends Lava lash with an arrow to switch targets.

**Comment by Hekili** [comment]
> No, it doesn't work fine. What makes you think that?  The addon cannot recommend using Lava lash without Flame shock. 

I said it matches the current priority.  Which it does.  In your snapshot, there's one target detected based on nameplates within 8 yards.  The `single` action list is invoked.  The second entry in the `single` list is to use Lava Lash if (a) Hot Hand is up, (b) Ashen Catalyst is at 8 stacks, or (c) AC is at 5+ stacks with Maelstrom of Elements up and 6 or fewer stacks of Maelstrom Weapon.  In your case, (b) is true.

` - this entry's criteria PASSES: buff.hot_hand.up[false] | buff.ashen_catalyst.stack[8.00] = 8 | ( buff.ashen_catalyst.stack[8.00] >= 5 & buff.maelstrom_of_elements.up[false] & buff.maelstrom_weapon.stack[6.00] <= 6 )`

Why would you let Lava Lash sit off cooldown for another GCD vs. consuming your AC stacks?  Especially when you do not have other targets detected.  The priority is clearly written to avoid opportunity cost of wasted Ashen Catalyst stacks / CDR.

In a multi-target situation, using Lava Lash to consume Ashen Catalyst is lower in priority for the reasons you described, but the addon isn't aware of any other targets within 8 yards.  You could consider expanding your target detection range if there were more targets nearby just outside of 8 yards that you'd want to count.  There are trade-offs and limitations with regard to target detection.  For example, if there were more targets just outside of detection range, you had Flame Shock on your target, and you hit Lava Lash, are you confident that the Flame Shock spread would've reached them?  Maybe, but maybe not.

> Moreover, in AOE, using Lava lash for a purpose is a loss of dps + not spreading Flame shock for other purposes. I'm even ready to attach a screenshot that the addon recommends Lava lash with an arrow to switch targets.

You weren't in an AOE situation as far at the addon could see based on your targeting settings.  As far as being ready to attach a screenshot, I genuinely don't know why you wouldn't have included a screenshot before if you felt it would help explain your point.

As far as the target swap indicator goes, for Lava Lash, it appears under the following circumstances:
1. You talented Lashing Flames and you already have Lashing Flames on your current target, indicating to swap to a target without Lashing Flames.
2. You have Flame Shock on another target, but not on your current target, indicating to swap to a target with Flame Shock for its spread effect.

The second option here can feel misleading, as your ticket seems to suggest, because as far as the addon is concerned, you do have Flame Shocks applied to other targets but only your current target meets your target detection requirements.  I'm going to revise the second option to only show if there are multiple targets detected to avoid causing that sort of confusion.

Regardless, you're at a point where you disagree with how the priority works, so I'd really encourage you to start proving your work with SimulationCraft if you'd like to see changes to the sim priority or the addon's version of it.  Or you can just write your own customized priority that does what you want regardless of whether I agree with  your proposals.

Finally, I'd appreciate if you'd keep in mind that I'm just a random person on the internet who makes a tool that you seem to want to use.  Ultimately, the work I prioritize on the addon is my decision to make.  If you disagree with my decisions, don't like the addon, or have any other strong feelings about it, you're under no obligation to use the addon.  I will continue to prioritize or close tickets as I see fit.
