### ISSUE TITLE
Havoc/Immolate Recommend Target Swaps Issue (destruction warlock)

### ISSUE THREAD

**Issue by SansDIO** [Hekili/hekili#2365]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

On my destruction lock, I talented into Cataclysm to avoid manually applying immolate on multiple targets. When off CD, Hekili will still recommend I manually apply Immolate to each target. If I try to avoid this by disabling the "Recommend Target Swaps" feature, then Hekili no longer recommends Havoc (it only does so with the feature enabled). 

### How to Reproduce

1. Enter game as Destruction Warlock
2. Disable "Recommend Target Swaps"
3. See recommendations (Havoc will not be recommended)
4. Enable "Recommend Target Swaps"
5. See recommendations (Havoc will now be included)

### Snapshot (Link)

https://pastebin.com/RvQ4ArNs

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/mU3zg15vbDKafRTBq3n77U

**Comment by Hekili** [comment]
Not using Immolate just because you've talented for Cataclysm is going to be less than optimal.  Looking at your sim:

\# | count | action,conditions
-- | -- | --
J | 8.70 | cataclysm
K | 43.02 | immolate,cycle_targets=1,if=dot.immolate.remains<5&(!talent.cataclysm.enabled\|cooldown.cataclysm.remains>dot.immolate.remains)&(!talent.raging_demonfire\|cooldown.channel_demonfire.remains>remains)&active_dot.immolate<=6
Q | 0.75 | immolate,if=dot.immolate.refreshable

You have ~9 casts of Cataclysm and ~44 Immolates.  Foregoing all those Immolates is almost certainly a DPS loss.

The options that you have are:
1. Create a custom priority; this is complicated and is not actively supported.  See: https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions
2. Disable Immolate in /hekili > Abilities.  If you do so, you'll need to manually enable it when Cataclysm isn't talented.  Kinda awkward.
3. Limit the number of targets for Immolate.  In /hekili > Abilities, set Maximum Targets to 1 (or 2, however many you want to cast).
