### ISSUE TITLE
[REC] Unholy DK high outbreak priority 

### ISSUE THREAD

**Issue by Vanadin1** [Hekili/hekili#2366]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Unholy Death Knight primary rotation Outbreak spam. Same bug as 2 weeks ago. 

It's telling me to use outbreak even though the mob already has plagues on it. It continues to tell me to press outbreak even though I just pressed it, over and over again.

https://www.youtube.com/watch?v=xD33hHTbo8U

### How to Reproduce

Play unholy DK. > Use Hekili > ??? > Profit! 

BwPAdLUHklrTr3hBIcYWdbnCGDAIkkwBSJSASSESkkkkEAAAAAAAAAAkkECJpBAQKS5ARSSikcA

### Snapshot (Link)

https://pastebin.com/Y8sttByd

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/5UJUBsdGh5KP8xsXmFfpLb

### Additional Information

And just because I know someone might ask if this is because of elvui or another addon. Here's the same issue with literally only hekili on. It's painful to play like this lol  https://www.youtube.com/watch?v=lneoevUy-o8

### Contact Information

Vanadin#0001

**Comment by Hekili** [comment]
You have forced AOE mode but only have one target; the addon is following your instructions to act as though there are more enemies than there are.  Since you have fewer Virulent Plagues up than targets, it's recommending Outbreak on the imaginary second target that it is pretending exists.

I'm going to change how `cycle_enemies` works internally to not use feigned targets based on AOE mode, since it pushes you to do something that you cannot do (dot a target that doesn't exist).
