### ISSUE TITLE
Subtlety Rogue - issue with target detection w/o nameplates shown

### ISSUE THREAD

**Issue by eriksen080499** [Hekili/hekili#2367]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Alright, so this is my first post here, so i am sorry if i am lacking info, or it is not done right.

I just switched to subtlety to try and learn the spec, and wanted to use Hekili to start with.

However, when i am attacking dummies, it's the same spells being recommended over and over again - When display mode is set to auto its recommending: Gloom Blade and Eviscerate, along with Symbols of death, over and over again.
It also tried to recommend shadow dance, even though i dont have that talented.. no other spells are being recommended. (After this, i went into settings and disabled it could recommend shadow dance.)
FYI: i am attacking the 5 dummies next to each other.

When set to AOE its recommending: Shuriken storm, then Eviscerate, Shuriken Storm, Shuriken Storm, Eviscerate, and the occasional rupture, nothing else. No black powder, secret technique or anything else.

Cold Blood has never been recommended at any point, and i do have that talented.

Character Data:
https://pastebin.com/crPgZbe4

### How to Reproduce

1. Enter the game as rogue, and set spec to subtlety.
2. attack dummies
3. Notice the recommendations being made.

### Snapshot (Link)

https://pastebin.com/scSh5q8M

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/7KZn9qMuoHZzrzh4UBtVXc

### Contact Information

Erikzen#5541

**Comment by vond82** [comment]
Shadow Dance is baseline for subtlety. Getting the talent just gives you 2 charges.

Sub is a bursty  spec that relies heavily on dance/cb/sectech so outside of the dance windows you wont really see anything else recommended than gloom/evisc/rupture, and since you disabled that it makes sense. 

As for the aoe rotation, it sounds like funnel mode is enabled in the settings?

**Comment by eriksen080499** [comment]
Ah i see, thanks for the information!
Where do i check funnel mode settings?

**Comment by eriksen080499** [comment]
And do you know if there's a reason cold blood is never recommended?

**Comment by vond82** [comment]
/hekili > subtlety there are some settings you can look at

**Comment by eriksen080499** [comment]
Funnel is not enabled.

It's a bit strange, since for a second it shows a bunch of different abilities recommended, but then it goes back to gloomblade and eviscerate constantly.
Hmm.

I'll do some testing.

**Comment by eriksen080499** [comment]
It's a little hard to describe, but like while im fighting its suggesting a BUNCH of abilites, and before i even get to press them, it goes back to gloom blade and eviscerate, then i start pressing that, and then for a splitsecond it suggest a bunch of abilities again, but before i even get to press any of them, it goes back to gloom blade again... is there some way of slowing it down, it often suggest shuriken storm, but before i get to press it, it just goes back to gloom blade... maybe something about it not detecting more than 1 dummy?

**Comment by vond82** [comment]
It could be an issue that comes from you disabling shadow dance, as many recommendations will check if shadow dance before firing

**Comment by eriksen080499** [comment]
My last comment came after re-enabling shadow dance

**Comment by eriksen080499** [comment]
I think its weird it keeps recommending gloomblade, gloomblade, then eviscerate, over and over, in AoE, even when display mode is set to AoE, and not recommending black powder even once?

**Comment by Hekili** [comment]
You did not provide a complete snapshot (press CTRL+A before CTRL+C to get all lines of information).  That will also provide more details about your addon settings.  If the addon provides AOE recommendations and then swaps back to single-target, it seems likely you've adjusted targeting settings to be based on damage and your off-targets are expiring.  If you use nameplate-based target detection as melee, you're all set.

But you'll have to provide the data that lets me look at your actual situation.

> I think its weird it keeps recommending gloomblade, gloomblade, then eviscerate, over and over, in AoE, even when display mode is set to AoE, and not recommending black powder even once?

Take a snapshot when it's happening.

**Comment by iNupidstoob** [comment]
I have the same issue. I am basically doing my shuriken/blackpowder aoe combo and then it wants to switch to gloomblade; https://pastebin.com/raw/n5vB6iAf

Let me know in case I took the snapshot at the wrong time.

Edit: Queued recommendations seem to change once we press shadow dance.

**Comment by Hekili** [comment]
In your case, it ruled out Shuriken Storm because Premeditation was up (because you went into stealth).

```
shuriken_storm ( stealthed - 13 )
List ( stealthed ) called from ( Subtlety:default:9 ) would PASS at 0.00.
 - stealthed.all[true]
This entry's criteria FAILS: spell_targets.any[5.00] >= 3 + buff.the_rotten.up[false] & ( ! buff.premeditation.up[true] | spell_targets.any[5.00] >= 7 )
```

Then it selected Shadowstrike by default.

```
shadowstrike ( stealthed - 15 )
List ( stealthed ) called from ( Subtlety:default:9 ) would PASS at 0.00.
 - stealthed.all[true]
This entry has no criteria to test.
```

After Shadowstrike, Gloomblade was selected based on the following criteria:
`buff.danse_macabre.stack[2.00] < 5 & ( combo_points.deficit[2.00] = 2 | combo_points.deficit[2.00] = 3 ) & ( buff.premeditation.up[false] | effective_combo_points[5.00] < 7 ) & ( spell_targets.shuriken_storm[5.00] <= 8 | talent.lingering_shadow.enabled[true] )`

Can you provide a sim of your character for comparison purposes, @iNupidstoob?  Ideally, Patchwerk with 5 boss targets.  I can't use @eriksen080499's character because he doesn't have Black Powder talented.

**Comment by Hekili** [comment]
edit:  Shadow Dance and Vanish weren't applying Premeditation in their forecasting, resulting in surprise changes to the priority when using them.  I'll be correcting that in the next release.

**Comment by Hekili** [comment]
@eriksen080499 You've confused me with your character information vs. sim.  Your sim doesn't have Cold Blood or Black Powder, so the addon is not going to recommend those abilities.  Do you have a snapshot that shows the issue you described?

**Comment by iNupidstoob** [comment]
Thanks for the quick follow-up Hekili! 👍 I think most issues are gone besides one.

Gloomblade sometimes still randomly disappears as a suggestion. 

Example: 
It is suggesting Shuriken Storm > Gloomblade. After casting Shuriken Storm the gloomblade recommendation disappears.

The before recommendation:
https://pastebin.com/raw/s6pnXs3U

After casting Shuriken Storm:
https://pastebin.com/raw/cSTgAAsu

Let me know if this isn't useful.

**Comment by vond82** [comment]
In the 2nd snapshot you're at 7 combopoints after the SS, that's why gloomblade isn't recommended anymore

**Comment by eriksen080499** [comment]
Hi, sorry for the late reply, i have not been home until now.

So i have a new snapshot here:
https://pastebin.com/tNvPEVvQ

I'm wondering, when im attacking 5 dummies, why it keeps recommending gloomblade, and then eviscerate, and not Shuriken Storm / Black Powder?

and regarding my character sim, that is my bad for not checking if raidbots had updated my character, it had not.
I have created a new sim, my exporting straight from game, where my talents are now correctly shown:
https://www.raidbots.com/simbot/report/7uJFbUbeaJGay31VLKp1ta

Let me know if i can do anything else to assist with getting to the bottom of this.

**Comment by eriksen080499** [comment]
Just a side info, when following the rotation i get from Hekili, im doing overall 43k dps on 10m dmg on 5 dummies.
When all i do is spam SS and then black powder constantly, im doing 95k overall on 10m dps. So it might not register the 5 targets correctly. Thats my thoughts ^^

**Comment by Hekili** [comment]
@iNupidstoob 

> After casting Shuriken Storm the gloomblade recommendation disappears.

As @vond82 noted, you generated more combo points than the addon could forecast for you, so there's no longer a Gloomblade cast to weave in.

@eriksen080499 

> [pastebin.com/tNvPEVvQ](https://pastebin.com/tNvPEVvQ)

Do you have enemy nameplates actually enabled?  Can you post a screenshot of you at the cleave dummies in a situation more or less identical to the snapshot you provided?

Your snapshot shows only one target:

```
targets:
    nameplate2   -  0 - Creature-0-1463-2444-26813-198594-00016260B3 - 185.00 - 10 - Cleave Training Dummy 
```

The only way I could replicate that was if I went into WoW's options, Gameplay > Interface > Nameplates and *un*checked Always Show Nameplates.  At that point, I could stand at the cleave target dummies and only my current target's nameplate would be detected.

If you're wanting the addon to rely on nameplates for target detection, you'll want to have nameplates showing.  Alternatively, you can rely on detecting damaged enemies in /hekili > Subtlety > Targeting > Detect Damaged Enemies and disable Use Nameplate Detection, but then additional enemies won't be detected until you do something proactive to engage them (i.e., hit Shuriken Storm).  Alternately, you can uncheck On Screen Enemies Only since they're not "on screen" if they don't have a nameplate.

**Comment by vond82** [comment]
Looking at that snapshot, you only have one target so that would explain why it's suggesting ST rotation. How it's only catching 1 of the 5 cleave dummies as a target I don't know though but Hekili can probably fill you in if this doesn't steer you in the right direction 

Edit: Oops he replied before me! :)

**Comment by eriksen080499** [comment]
I see! manually forcing nameplates seem to have helped.
I dont prefer nameplates to always show though.

These are my hekili settings for subtlety:
https://imgur.com/a/OOGKCmc

I have set it to detect damaged enemies, but i guess that doesnt work?
Or should i disable nameplate detection beforehand?

**Comment by Hekili** [comment]
As noted above, you can uncheck Use Nameplate Detection if you don't want to use nameplates, or you can uncheck On Screen Enemies Only so that your damaged targets aren't filtered out due to not having a nameplate.

**Comment by eriksen080499** [comment]
Ah, i see. I was thinking if both was enabled, that it would detect both. Both nameplates and and damaged enemies. Did not think that it would remove that target if a nameplate was not found, even while damaging enemies.

**Comment by Hekili** [comment]
> Ah, i see. I was thinking if both was enabled, that it would detect both. Both nameplates and and damaged enemies. Did not think that it would remove that target if a nameplate was not found, even while damaging enemies.

You can uncheck On Screen Enemies Only so that your damaged targets aren't filtered out due to not having a nameplate.

**Comment by eriksen080499** [comment]
Thanks for the final reply.
It worked good, until i logged on just now, without me having changed anything, it suddently keeps recommending rupture when i have full combo points, even when its recognizing 5 targets..
https://pastebin.com/jJGc2Eya - snapshot.

And i see that it is showing Shuriken Storm, and then black powder, however when i use shuriken storm, and get full combo points, it changes the black powder, to rupture all over.. 
Is there a simple explanation for that?

**Comment by Hekili** [comment]
The simple explanation is that it's what the priority is written to recommend under those circumstances.  

![image](https://user-images.githubusercontent.com/9438134/217625772-cfa36a09-3402-4d29-8ecc-9329280fc21a.png)

Here's an example from your earlier sim.  You can see it getting some Ruptures applied in multi-target.  There might be a strong case for modifying the sim priority to use Black Powder more often, but you'd have to modify your sim profile and do testing to demonstrate that, or wait for the Rogue theorycrafters to sort that out themselves.

![image](https://user-images.githubusercontent.com/9438134/217626204-a44313b9-6d75-4790-ba2f-3f5b2371dc4d.png)

Based on the above, it looks pretty deliberate to apply Ruptures to targets who are going to live long enough.

**Comment by eriksen080499** [comment]
I see. i barely do 50k dps on 5 targets, with just SS and rupture however, and i dont get why thats different from a few days ago, when it recommended SS and black powder constantly? but i'll just learn to play the spec instead of using hekili for sub rogue i guess ;p on my sham and warr, it works fine, so i'll stick to just using it there ^^
Thanks again

**Comment by vond82** [comment]
Rupturing every target that will live 12s or longer is a dps gain up til 25 targets for sub, just position yourself so that you actually hit 2 targets per application so you dont have to cast it 5 times - and don't cast rupture inside Shadow Dance. Outside of dance sub is a maintenance spec where what you're doing is maintaining SnD and Rupture
