### ISSUE TITLE
Incarnation: Chosen of Elune does not show in rotation

### ISSUE THREAD

**Issue by EmmsDK** [Hekili/hekili#2377]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

As Balance druid, Incarnation: Chosen of Elune does not show in my rotation after one of the latest updates. I have checked through the addon to make sure that it is not disabled anywhere in settings, but I have it enabled. 

### How to Reproduce

1. Enter the game as balance druid
2. Pick Incarnation Chosen of Elune talent
3. Remove incarnation of elune in toggles under balance in the addon
4. Test the rotation on test dummies

### Snapshot (Link)

https://pastebin.com/WPqDQviF

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/iuk7GB36fRoWLmutX6uvb3

**Comment by Hekili** [comment]
Hey, I'm sorry the intro experience for the addon isn't great.  I recommend checking out [Getting Started](https://github.com/Hekili/hekili/wiki/Getting-Started) since there's information there not kept in-game.

In this case, the Incarnation ability is consisted a "Cooldown" and is assigned to the Cooldowns toggle, which is off by default.  You can control this toggle by pressing `ALT-SHIFT-R` (by default).  This helps you to tell the addon you do or do not want Incarnation (and other cooldowns) to be recommended at different times.

You can adjust the cooldown and other settings in /hekili.  The specific section you'll want to look at is /hekili > Toggles.  There are some other features in there worth checking out, including toggles for Interrupts.  You can customize toggles and add/remove abilities to/from them, but it gets fairly complicated fast.  Feel free to reach out on Discord if you have questions.

**Comment by insomniaq123** [comment]
ignore me im dumb xD
