### ISSUE TITLE
Enhancement Shaman Primordial Wave Recommendation Issue

### ISSUE THREAD

**Issue by Keepoo** [Hekili/hekili#2386]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When using Primordial Wave and the buff has less than 3 seconds and 8+ maelstrom is up hekili is failing to make lightning bolt recommendation in AOE before the Primordial Wave buff runs out which results in a major dps loss.

### How to Reproduce

1. Enter game as Enhancement Shaman
2. Take Splintered Elements, Primordial Wave
3. Go to Target Dummy any other instance that will replicate aoe Rotation
4. Use Prim Wave into Chain Lightning or any other spender twice with sufficient Maelstrom for instances where you want Prim Wave on Cooldown but dont want to instantly spend the Lightning Bolts in favor of more Splintered Elements Haste Buff this can be helpful. With sufficient Haste you can weave in two Maelstrom spenders e.g Chain Lightning, Elemental Blast or anything else and then build up enough Maelstrom to Lighnting Bolt with Primordial Wave buff active. However Hekili will fail to make a lightning Bolt recommendation and Prim Wave Buff will run out unused.

I am unsure if the Snapshot i provided will provide the the exact moment where hekili is failing to recommend lightning bolt before Prim Wave runs out. however its almost impossible to make a good Snapshot due to the incredibly high haste and very narrow Window that the snapshot has to be made in (<1 sec). The snapshot i took is about 0.5 to 1 sec later after it failed to make the recommendation and Prim Wave buff has already run out. However it isnt making the recommendation at all after the first 2 spenders were cast.

### Snapshot (Link)

https://pastebin.com/iihQ18dx

### Contact Information

Trancendence#8723 (discord)

**Comment by Hekili** [comment]
I think here is where you're going awry, based on the sim priority:

> With sufficient Haste you can weave in two Maelstrom spenders e.g Chain Lightning, Elemental Blast or anything else and then build up enough Maelstrom to Lighnting Bolt with Primordial Wave buff active. However Hekili will fail to make a lightning Bolt recommendation and Prim Wave Buff will run out unused.

With Overflowing Maelstrom talented, the priority is written to use Lightning Bolt at 10 stacks of Maelstrom Weapon.  If you've spent on EB or CL and haven't regenerated 10 stacks of MSW, its conditions are not going to pass:

>28.  lightning_bolt ( aoe - 2 )
>The action (lightning_bolt) is usable at (0.00 + 0.00) with cost of 500 mana (have 50000).
>- the action is ready before the current recommendation (at +0.00 vs. +10.00).
>List ( aoe ) called from ( Enhancement:default:18 ) would PASS at 0.00.
>   active_enemies[5.00] > 1
>- this entry's criteria FAILS: ( active_dot.flame_shock[5.00] >= active_enemies[5.00] | active_dot.flame_shock[5.00] > 5 ) & buff.primordial_wave.up[true] & `buff.maelstrom_weapon.stack[8.00] >= ( 5 + 5 * talent.overflowing_maelstrom.enabled[true] )` & ( ! buff.splintered_elements.up[false] | fight_remains[322.14] <= 12 | raid_event.adds.remains[322.14] <= gcd.max[1.17] )

You have 8 stacks of Maelstrom Weapon, not 10.  I'd expect that it's probably better to just go ahead and LB instead of letting PW fall off, but that's not the sim behavior.  Of course, the sim wouldn't get in this situation because it would've used Lightning Bolt much earlier.

> for instances where you want Prim Wave on Cooldown but dont want to instantly spend the Lightning Bolts in favor of more Splintered Elements Haste Buff this can be helpful

Can you say this a different way?  How are you getting more Splintered Elements haste out of *not* casting Lightning Bolt?  Do you mean that you're holding it for an add spawn or something?

**Comment by Keepoo** [comment]
Hi, thanks for the fast reply. 

> You have 8 stacks of Maelstrom Weapon, not 10. I'd expect that it's probably better to just go ahead and LB instead of letting PW fall off, but that's not the sim behavior. Of course, the sim wouldn't get in this situation because it would've used Lightning Bolt much earlier. 
for instances where you want Prim Wave on Cooldown but dont want to instantly spend the Lightning Bolts in favor of more Splintered Elements Haste Buff this can be helpful
Can you say this a different way? How are you getting more Splintered Elements haste out of not casting Lightning Bolt? Do you mean that you're holding it for an add spawn or something.


Yes that is correct. Im talking about scenarios where im knowingly going against Hekilis/Sim Priority list based on context. Lets say you are fighting Kurog Mythic. You know that an add is about to spawn but it wont spawn directly on pull. Now you want to save your buffed up lighnting bolt for when the add spawns so you can get the extra haste buff from Splintered Elements, but you also don't want to delay any Prim Wave casts to get in on CD. The best Line of play here is to Spirit Wolf-> prim wave into Ele Blast into some fillers to generate Maelstrom TWICE until you gained enough maelstrom and Prim Wave is barely running out and the add has spawned. What the Priority List/hekili is failing at is recommending Lightning Bolt before Prim Wave has run out( not sure how this statement holds up in ST) even if you are not 10 stacks because obviously its better casting it with any number of Maelstrom stacks but still buffed then not all. In theory you can even get up to 10 stacks again if you are lucky, but that is not my point. What it should do is save the last possible GCD for a LB with Prim Wave buff active independent of how many maelstrom stacks you have.

**Comment by Hekili** [comment]
Right, okay.  I'll probably make an edit that will consume Primordial Wave in that last GCD (or 1.5 GCDs, since you generally need some amount of padding).  Keep in mind, this isn't presently sim tested because the sim is written to not put itself in that position.

**Comment by Keepoo** [comment]
Much appreciated. Doing gods work with this addon!

**Comment by Dragonfo** [comment]
![image](https://user-images.githubusercontent.com/63850853/218138976-4ac1b5e0-4608-475d-b77e-0381f64778e5.png)
I would like to introduce a couple of nuances. What the person above asks for looks like this: rotation on Kurog Mythyc. To tighten the use of Light bolt to get the maximum increase in DPS because 2 goals will be better than 1 goal. But let's look at it from the other side. There are no more bosses like kurog in the raid. And if you add such a delay for the primordial wave , how will it affect other bosses ? and I am very interested in Mythyc + where the scenario does not go according to the Simc plan at all and if there are conditions for postponing the use of Light bolt to get % speed, it will look like a loss of dps. Plus, again, I will add to this everything that is bos in the Sennarth raid, where we want to get a buff% of the speed from the primordial wave faster. Again, I will also emphasize the factor that Kurog that this delay can be done manually by yourself simply using 3 additional ions in rotation, which perfectly help me manually shift the time of application of the primordial wave through light bolt. I just have concerns that this delay may harm us on other bosses and especially M+

**Comment by Hekili** [comment]
> I just have concerns that this delay may harm us on other bosses and especially M+

There's no delay being added.  There's a safety net that will recommend Lightning Bolt as PWave is falling off if you chose not to use it earlier.

> I will also emphasize the factor that Kurog that this delay can be done manually by yourself simply using 3 additional ions in rotation

Or you can use the existing toggles to tell the addon you're intentionally holding those abilities so it doesn't recommend them, then toggle them back on afterward.

**Comment by Hekili** [comment]
This has since been released.
