### ISSUE TITLE
LUA error w/ BugGrabber report

### ISSUE THREAD

**Issue by Aintru** [Hekili/hekili#240]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**To Reproduce**
No idea. I used Blade Dance on my DH on a archer at Tower Point while in Korrak's Revenge (AV) event.

**Expected behavior**
I expected it to not throw an error I guess.

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/StcREaVf

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

https://pastebin.com/AXTsSFy3

**Comment by Aintru** [comment]
https://pastebin.com/F184AZG7

Also just received this one while reporting the previous one.

**Comment by Aintru** [comment]
Possibly related, but not Hekili specific and just occured as well within a short timespan of the other 2: 
https://pastebin.com/CsUjBBG1

**Comment by Hekili** [comment]
The first occurred because the event for changing your specialization fired.  I'll see if this is happening on changing subzones and prevent that from happening.

The second looks like you were exiting the config UI, probably in combat.  Script ran too long means this addon or multiple addons spent too much time calculating inside of a single frame.  I used to prevent people from configuring during combat in order to prevent it (some configuration changes involve recompiling all the scripts, which can be slow depending on CPU).

The third isn't useful at all.  I'll look into the first part.
