### ISSUE TITLE
[REC] Havoc Fel Rush/Immolation Aura "Buffer" Period

### ISSUE THREAD

**Issue by ifailbignoob** [Hekili/hekili#2429]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For Havoc DH(Especially now with low haste), there may be times where the add-on will recommend a damage button when momentum would fall off during the GCD. It'd be nice to add a "buffer" period similar to other classes, where it'd recommend a momentum activation anywhere between 0.1-2 seconds(or something similar) to account for GCD's if momentum is about to fall off and the next recommended cast is a throw glaive/deathsweep

It also seems to not want to recommend immolation aura on cooldown if burning hatred is talented, is this due to overcapping fury(Or maybe due to Unbound Chaos)? Perhaps we could have a toggle for this too as any builds with ragefire will just want to use immolation aura on cooldown to activate it, rather than saving it for UBC/Fury Gen.

Other small nitpicky recommendations could be saving "The Hunt" until you have an "initiative" buff if VR is almost off CD, ensure soulrend is on a target as a priority if talented unless in ESSB(I think this already is the case to an extent, but it won't recommend applying soul rend before the VR/ESSB or in opener to apply Soulrend/Burning wound before the window). I think it also saves ESSB sometimes regardless of whether you have initiative(I.E you VR'd but didn't ESSB back and casted something else instead like Eye Beam or Boon), I think it should still recommend ESSB instead of saving it for the next CD window

### How to Reproduce

1. Enter game as Havoc Demon Hunter 
2. Talent into Burning Hatred, Ragefire and Momentum Talents: BEkACnvaHJn8GSPD6tpaeczPThkkkkIlg0SSEJSrFBAAAAAAgkEEpQSUCSSaJBSgEA
3. The add-on will recommend the next ability until the momentum buff has completely dissapeared(i.e a death sweep or throw glaive) even if the GCD will force the ability to not be momentum buffed 

### Snapshot (Link)

https://pastebin.com/qfDaFbaW

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/2hHRFbnRXTLYNuDQYs1QJ9

### Additional Information

I really appreciate the recent changes to proc Inner Demon :) 

### Contact Information

Aarondh#7513 Discord

**Comment by Hekili** [comment]
There's a lot here, so I'm going to carve it up a bit.

> For Havoc DH(Especially now with low haste), there may be times where the add-on will recommend a damage button when momentum would fall off during the GCD.

Can you be more precise?  Which abilities?  Provide a snapshot when that is occurring.  If you want to sim test for this, you're probably looking to modify the `waiting_for_momentum` variable from `talent.momentum&!buff.momentum.up` to `talent.momentum&buff.momentum.remains<gcd.max`.  That essentially means you'll treat Momentum as no longer active and/or due for a refresh when there's less than a GCD left on it.

- [ ] Snapshot when a damage button is recommended but Momentum will fall off in GCD
- [ ] Provide Raidbots sim showing that it is more performant to ignore last GCD of Momentum than current priority

> It also seems to not want to recommend immolation aura on cooldown if burning hatred is talented, is this due to overcapping fury(Or maybe due to Unbound Chaos)?

Have you reviewed the priority list?  The only conditions for Immolation Aura are that a higher priority ability isn't ready and:
```
!buff.immolation_aura.up&(!talent.ragefire|active_enemies>desired_targets|raid_event.adds.in>15)
```
This means it won't recommend Immolation Aura until Immolation Aura is down.  The other checks pretty much wash out in terms of always passing:  `active_enemies>desired_targets` basically means "there are multiple targets" and `raid_event.adds.in>15` means "there is a single-target" as far as the addon is concerned).

If you can provide a snapshot where you think Immolation Aura should be recommended but isn't, we can review that.

- [ ] Snapshot when Immolation Aura is off CD and should be recommended but isn't

> Perhaps we could have a toggle for this too as any builds with ragefire will just want to use immolation aura on cooldown to activate it, rather than saving it for UBC/Fury Gen.

In theory, the sim is written to do the exact opposite with regard to Ragefire, though, again, those conditions basically wash out.  Have you tried modifying the sim to show a different result?  You could remove the `!buff.immolation_aura.up&` part of its conditions that we looked at above.

- [ ] Provide Raidbots sim showing better to use Immolation Aura even if Immolation Aura is already active with Ragefire talented

> Other small nitpicky recommendations could be saving "The Hunt" until you have an "initiative" buff if VR is almost off CD, ensure soulrend is on a target as a priority if talented unless in ESSB(I think this already is the case to an extent, but it won't recommend applying soul rend before the VR/ESSB or in opener to apply Soulrend/Burning wound before the window).

Have you modified the sim priority to test for these changes?  I'd be really surprised if the DH theorycrafters didn't test these when building the priority list in the first place.  There are a lot of things that sounds great but have a higher opportunity cost than yo might expect.  Saving a big cooldown becomes costly if it means you lose a use of that cooldown over the course of a fight.  Even a couple of GCDs can tank the overall average DPS in surprising ways.

- [ ] Provide Raidbots sim showing saving The Hunt until Initiative is active (when talented) is more performant than current priority

> I think it also saves ESSB sometimes regardless of whether you have initiative(I.E you VR'd but didn't ESSB back and casted something else instead like Eye Beam or Boon), I think it should still recommend ESSB instead of saving it for the next CD window

What makes you think this?  Essence Break's only conditions are that nothing higher priority is ready, and:
```
(active_enemies>desired_targets|raid_event.adds.in>40)&!variable.waiting_for_momentum&fury>40&(cooldown.eye_beam.remains>8|buff.metamorphosis.up)&(!talent.tactical_retreat|buff.tactical_retreat.up)
```
Which means all of the following conditions are met:
* You're not waiting for Momentum (meaning that if you've talented for Momentum, Momentum is active)
* You have 41+ Fury
* Eye Beam is on cooldown for more than 8 seconds **OR** Metamorphosis is active
* You did not talent for Tactical Retreat **OR** Tactical Retreat is up

I think you could test your theory by modifying that last portion:  `(!talent.tactical_retreat|buff.tactical_retreat.up|cooldown.vengeful_retreat.remains>5)`
You can change the 5 to however long you do find it acceptable to wait for Vengeful Retreat before using Essence Break.  As written, you have the 10 seconds from Tactical Retreat to use it, otherwise it waits the remaining 10 seconds on the VR cooldown (and for you to actually use VR) before it is recommended again.

- [ ] Provide Raidbots sim showing that allowing Essence Break to occur when you've missed a Tactical Retreat window is more performant than current priority

For most of your concerns, you'd need to provide snapshots that show the specific issue that you're describing; one snapshot doesn't cover all these scenarios.  For your suggestions, some kind of data (sims, usually) is needed to show there is value in making the changes you suggest.

**Comment by ifailbignoob** [comment]
Thanks for the super detailed reply, It's 5am and I'm just heading to bed so I'll start on checking these situations and get back to you a bit later, just to confirm I should be snapshotting after the end of rotation(just after it's recommended the cast and before I press it?) 

I'll see if I can get these simmed, for the first point it's mainly Eye Beam/Death Sweep, I'll have to check it when I'm online later instead of being feelcrafty, but since it doesn't snapshot we'd want momentum lasting the whole cast to ensure final hit is buffed.

The pre-application of soulrend is usually just what is written out in most of the playstyle/rotation guides, but on sims I believe it just manually swaps targets to auto attack and apply burning wounds to 3 targets while the fight is ongoing during that window(which would require watching a swing timer and tab targetting while doing your rotation as normal, or just throwing 1 glaive previously which I believe is recommended in the soulrend/ragefire build on AoE Guides)

I think I have a feeling the 41+ Fury condition might be what's causing me to feel like it's not recommending the ESSB when in fact I should just be generating to make sure I have enough during the window, this is probably my bad! 
My personal experience from this was on Mythic Broodkeeper, where I'll forcefully VR to break shroud(or VR to boon into an add pack for an initiative buffed boon) and ESSB will never get recommended throughout the window.

The Hunt optimisation is mentioned by some of the theorycrafters, I'll see if I can add a condition to the cast for sims and compare, just to confirm the current iteration is that it's just cast on cooldown unless I currently have the momentum buff? I'll review the priority list when I wake up too :)

**Comment by Hekili** [comment]
> I should be snapshotting after the end of rotation(just after it's recommended the cast and before I press it?)

Yeah, you should snapshot the recommendation you disagree with before you follow the recommendation.

> The Hunt optimisation is mentioned by some of the theorycrafters, I'll see if I can add a condition to the cast for sims and compare, just to confirm the current iteration is that it's just cast on cooldown unless I currently have the momentum buff? I'll review the priority list when I wake up too :)

If you can sim and show that it's equal or better, it's good to propose the change to SimulationCraft since folks tend to prefer that sims and guides are aligned.  The addon would then ingest the changes downstream of simc.

That said, if the change is at least equal for most/all builds and players might want to opt in/out of it, that's when I will consider adding a specialization option to choose between default behavior and the proposed behavior.

**Comment by Hekili** [comment]
(Also, I'm sick right now and have bad brain fog, so keeping each change carefully labeled and distinct will help keep me from getting confused.)
