### ISSUE TITLE
[FEATURE] Sub Rogue: Toggle to disable Shuriken Tornado on ST

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#2447]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

It's a DPS gain to use shuriken tornado on ST as the addon correctly suggests, however it can be useful to save it for add phases or packs in m+.  

Would like to request a toggle that would effectively disable shuriken storm until x number of targets are present (either 2+ or a slider).

**Comment by Hekili** [comment]
This would overlap too much with the /hekili > Abiliities > Shuriken Tornado > Minimum Targets feature.

If anything, it's probably better to handle this sort of thing by putting Shuriken Tornado on a toggle, or using a custom priority to require multiple targets.

I'll think about it a bit, though.  People have been asking for more elaborate options recently, but the issue is that runs the risk of creating unintuitive problems (i.e., interdependent ability conditions in the APL).

**Comment by fzarr** [comment]
Whoops, I didn't know about the abilities options having that functionality, amazing!. That will do what I want, thanks!
