### ISSUE TITLE
[FEATURE] Feral to Bear Stance as a Defensive

### ISSUE THREAD

**Issue by GigaToons** [Hekili/hekili#2462]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Feral Druid to show Bear Form as a defensive based on incoming damage.

I am curious to know if it's possible to show bear form as a defensive when incoming damage is greater than X% (i.e 30%) - then show cat form after the damage. Ideally it may even switch stance to bear and include things like iron fur, or Frenzied Regeneration if talented. Or switch to bear form and begin a bear stance sequence if targeted by a boss - like becoming a tank when the tank dies.

This would be useful to increase survival as a feral druid in different scenarios.

**Comment by Hekili** [comment]
The addon does not predict future damage.  For example, `incoming_damage_5s` reports how much damage you have taken in the past 5 seconds.  The addon would be recommending that you swap to Bear Form because you just received damage, or your health was low.

You could use a custom priority for this, for the time being.  If you want to swap to Bear Form if you're in a boss fight and something is targeting you, you could try `boss & aggro` as conditions.  If you wanted to factor in health or incoming damage, you could use something like:

* Health is under 60%:  
`boss & aggro & health.pct < 60`
* Have taken 25% of your maximum health in damage:  
`boss & aggro & incoming_damage_5s > 0.25 * health.max`
* Both of the above:  
`boss & aggro & health.pct < 60 & incoming_damage_5s > 0.25 * health.max`

See the FAQ for making the addon recommend abilities:  https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions

You'll want to note that the default Feral priority will recommend switching back to Cat Form (see default 3 and default 5).  To recommend bear abilities while in Bear Form, you'd *probably* want to add another action list for bear and then put a Call Action List entry for bear when `buff.bear_form.up` somewhere before Cat Form would otherwise be recommended.  You'd put your Bear Form abilities in that list, and also probably include something in that list to swap back to Cat Form (i.e., if not a boss fight, if no aggro, if health is full, etc.).

Those are things you can try, but are outside the scope of the addon in terms of what I would build in as a default.
