### ISSUE TITLE
cant move UI

### ISSUE THREAD

**Issue by Kelthahzzarr** [Hekili/hekili#247]
Hey, new to this addon, but I cannot move the ui for this addon, nor do i want to move my already established ui on specific characters just to use this addon, please help

**Comment by wow1989** [comment]
interface > addons > hekili > open hekili options panel > drag windows where you want them

**Comment by Kelthahzzarr** [comment]
cant even do that, the window opens up right on top of the ui, and i cant move the window away

**Comment by Hekili** [comment]
Type /hekili to open the addon options.  Drag the options window to the side.  Click and drag the displays.

Or go to /hekili > displays > (whichever you want to move) and set the position by X and Y.

**Comment by Mageical** [comment]
I also can't move the Hekili menu at all which is very frustrating.  Hekili is a fantastic addon, but without being able to move the menu to one side so that I can actually SEE the aoe/single displays that I want to resize etc its very frustrating.  I can move any other addon menu to the side... dominos, wa, grid2, mythic dungeon tools etc etc ... the only one I can't move (click drag does not worked the menu is totally fixed in place bang in middle of screen which is totally inconvenient as it covers the hekili items you are trying to adjust so you can't see them to know if in right place/big enough etc.  Please please fix this for what is an otherwise amazing addon.  Thanks

**Comment by Hekili** [comment]
Click the title and drag. If anything is preventing it from moving, it's another addon.

**Comment by Mordbreygon** [comment]
The options menu opens over the addon and the typing command doesn't bring anything up

**Comment by Hekili** [comment]
> Click the title and drag. If anything is preventing it from moving, it's another addon.

Or use `/hekili unlock` and `/hekili lock`.
