### ISSUE TITLE
Primary Display showing 3 when slider is at 4.

### ISSUE THREAD

**Issue by UltiDeeps** [Hekili/hekili#2473]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Unholy DK when targeting a boss only shows 3 icons when the slider is set to 4.

### How to Reproduce

1. Enter Game as Unholy DK.
2. Target Animated Duelist Raider's Training Dummy
3. Set slider to 4 and confirm only 3 show.

P.S. AoE Display showing the appropriate amount.

### Snapshot (Link)

https://pastebin.com/VKEiZXjH

Second snapshot is following first 3 icons and Primary Display dissapearing entirely while only suggesting Death and Decay in single icon for AoE: https://pastebin.com/Persn5n2

### Additional Information

I am aware that the current APL is set for 10.07 as mentioned in the Changelog of the specialization priority and unsure how much of an impact that has on the addon pre patch drop.

**Comment by Hekili** [comment]
Yeah, that happens when a recommendation can't be generated for that slot.  In the `garg_setup` list, it's pretty restrictive about using a wound builder, wound spender, or Death and Decay.  Death and Decay would've been recommended in the 4th slot, but you have it disabled for single-targets.

```
29.  any_dnd ( garg_setup - 9 ) - ability disabled ( active_enemies[1] is less than ability's minimum targets [2] )

30.  festering_strike ( garg_setup - 10 )
The action (festering_strike) is usable at (2.34 + 1.16) with cost of 2 runes (have 2).
 - the action is ready before the current recommendation (at +1.16 vs. +10.00).
List ( garg_setup ) called from ( Unholy:default:18 ) would PASS at 1.16.
variable.garg_setup[0.00] = 0
 - this entry's criteria FAILS: debuff.festering_wound.stack[2.00] = 0
```

The Festering Strike entry only wants to Festering Strike when there are no Wounds.

```
31.  death_coil ( garg_setup - 11 )
The action (death_coil) is usable at (2.34 + 1.16) with cost of 30 runic_power (have 40).
 - the action is ready before the current recommendation (at +1.16 vs. +10.00).
List ( garg_setup ) called from ( Unholy:default:18 ) would PASS at 1.16.
variable.garg_setup[0.00] = 0
 - this entry's criteria FAILS: rune.current[2.00] <= 1
```

The Death Coil entry only wants to be used when you have no Runes.

Is it possible you upgraded to the 10.0.7 alpha and then downgraded to 10.0.5?  I'm looking at the Apocalypse entry in the `garg_setup` list:
| | Conditions
|-|-
| Yours | debuff.festering_wound.stack >= 4 & ( buff.commander_of_the_dead.up & pet.gargoyle.remains < 21 \| ! talent.commander_of_the_dead.enabled )
| 10.0.7 | debuff.festering_wound.stack >= 4 & ( buff.commander_of_the_dead.up & pet.gargoyle.remains < 21 \| ! talent.commander_of_the_dead )
| 10.0.5 | debuff.festering_wound.stack > 3 & ( buff.**commander_of_the_dead_window** /.up \| cooldown.dark_transformation.remains > 20 | ! talent.commander_of_the_dead )

If so, you'll need to reset the priority to revert to the older priority using the little circle-arrow on /hekili > Priorities > Unholy before testing further.
