### ISSUE TITLE
FireMage When checking Scorch instead of Fireball/Pyroblast in moving, Pyroblast is not recommended when Hot Streak! Buff is on. Unless the current target HP is below 30%

### ISSUE THREAD

**Issue by Livvvvvvven** [Hekili/hekili#2477]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

FireMage When checking Scorch instead of Fireball/Pyroblast in moving, Pyroblast is not recommended when Hot Streak! Buff is on.

### Additional Information

nothing.

**Comment by Hekili** [comment]
Since this is an issue regarding the recommendations made by the addon, you'll need to submit the right kind of ticket with the required information.

[Recommendations Ticket](https://github.com/Hekili/hekili/issues/new?assignees=Hekili&labels=recommendation%2Ctriage&template=Recommendation-Report.yml&title=%5BREC%5D+REPLACE+THIS+TEXT+WITH+YOUR+CLASS%2FSPEC+AND+BRIEF+ISSUE+DETAILS)
