### ISSUE TITLE
Ret Paladin - Actions displaying as available for use when they're still on cooldown

### ISSUE THREAD

**Issue by smcgettrick** [Hekili/hekili#2490]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I've noticed since 10.0.7 that I'm getting recommended actions that are not off cooldown yet.  In the past I feel like if an action was queued up to be used but not off cooldown there would be a visual indicator of such, but in this case the add-on is telling me to use an action that is unavailable.  This seems to primarily happen with: BoJ, Judgement, and Final Verdict.

### How to Reproduce

1. Spec Ret
2. Fight mobs

### Player Information (Link)

https://pastebin.com/03aqqVQQ

### Error Messages (Link)

No Error Messages

**Comment by smcgettrick** [comment]
Gonna close this out because of course as soon as I report it, it seems to have stopped happening.  Will re-open if if starts up again.

**Comment by Hekili** [comment]
If you experience it again, please submit the correct type of ticket (Recommendations) with all the information required there.  It explains how to get a Snapshot (not a screenshot), place on Pastebin, and link in the ticket.  Thanks!

**Comment by smcgettrick** [comment]
This is occurring again and just to confirm, you want this to be opened as a recommendation and not a bug, because it seems like a bug.

**Comment by Hekili** [comment]
Yes, I did need the information I asked for, but someone else has supplied it elsewhere.

If you look at the ticket descriptions, an In-Game Error ticket is for times when the addon doesn't load or you have error messages.  In your case, the addon loads and doesn't have error messages per your original ticket.

A Priority/Recommendation Issue ticket is for times where the addon appears fully functional, but its recommendations don't match your expectations.  You're expecting to see Rebuke recommended (quite reasonably) but it's not.  So that's the correct ticket.
