### ISSUE TITLE
[REC] Ret Paladin Crusading Strikes issues

### ISSUE THREAD

**Issue by Bingo176** [Hekili/hekili#2499]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When using the Crusading Strikes talent the priority seems to only show Wake of Ashes and Divine Toll for a split second. I'm guessing it has to do with the auto attack giving resources. 

### How to Reproduce

Enter game as Ret Paladin.
Go to target dummies.
Go through opener with wings and final reckoning.
Wake of Ashes and Divine toll will then only appear for a brief period then show the next priority. 

### Snapshot (Link)

https://pastebin.com/w68TU8w6

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/9cTBULKjruQmvBaVT5LJCH

**Comment by Bingo176** [comment]
I forgot to add that this will happen with Blade of Justice also. Should be shown in the snap shot but if not https://pastebin.com/zhngw3fR

**Comment by Hekili** [comment]
Ok, so I looked at both of these.  I may need you to clarify your concern(s) because it's not totally clear.

### Snapshot 1
Templar's Verdict(0.00) - https://pastebin.com/w68TU8w6

For your first snapshot, Templar's Verdict is recommended.  Your concern is that Wake of Ashes and Divine Toll could've/should've been recommended but ticked away?  Is that accurate?

If so, it makes sense that TV is recommended in your snapshot because you've maxed out on Holy Power.  If there was only a very narrow window where you weren't maxed on HoPo, it would also make sense that the recommendation appeared until your HoPo-generating Crusading Strikes swing ticked you up to 5 HoPo.

### Snapshot 2
Wake of Ashes(0.00) - https://pastebin.com/zhngw3fR

Your second snapshot recommends Wake of Ashes.  Are you saying that the recommendation changed from Blade of Justice to Wake of Ashes?  What does "this will happen" mean in the context of "I forgot to add that this will happen with Blade of Justice also"?

Did you grab the wrong snapshot?  I'm noticing that you posted the AOE snapshot for this one, but the Primary snapshot for the other.  (It's generally better to use Auto mode and post snapshots from Primary unless you're specifically highlighting an issue with AOE recommendations.)

If Wake of Ashes is available and you have 2 or fewer HoPo, it's going to be recommended over Blade of Justice.

### Fix 1

I did some investigating and found that in multi-target scenarios, every enemy hit by Crusading Strikes was counting as a swing which impacted the swing counter in terms of forecasting the next HoPo-generating swing.  That'll be fixed in the next build.

### More Research

Don't get too hung up on all this, I just wanted to keep track of my investigating here.  I looked at your sim to see what a typical fresh-start looks like:

![image](https://user-images.githubusercontent.com/9438134/228028083-a33cd5d7-f904-4529-868b-d7c07ba57394.png)

Your snapshots don't have Bloodlust active, so I re-ran your sim with Bloodlust disabled and got this instead:

<details>
<summary>Judgment > BoJ > BoJ > AW > Potion > Trinket > HoW > FR > DS > Wake > DS > J > DS > Divine Toll > DS</summary>

Time | List | # | Name | Target | Resources | Buffs
-- | -- | -- | -- | -- | -- | --
0:00.000 | generators | Q | judgment | Fluffy_Pillow | 0.0/5: 0% holy_power | shield_of_vengeance
0:01.200 | generators | R | blade_of_justice | Fluffy_Pillow | 2.0/5: 40% holy_power | shield_of_vengeance, divine_arbiter, prepared_time(5)
0:02.342 | generators | R | blade_of_justice | Fluffy_Pillow | 3.0/5: 60% holy_power | shield_of_vengeance, divine_arbiter(2), prepared_time(5)
0:03.481 | cooldowns | I | avenging_wrath | Fluffy_Pillow | 4.0/5: 80% holy_power | shield_of_vengeance, divine_arbiter(2), blessing_of_dawn, prepared_time(5)
0:03.481 | cooldowns | F | potion | Fluffy_Pillow | 4.0/5: 80% holy_power | shield_of_vengeance, divine_arbiter(2), avenging_wrath, blessing_of_dawn, prepared_time(5)
0:03.481 | cooldowns | G | use_item_blazebinders_hoof | Fluffy_Pillow | 4.0/5: 80% holy_power | shield_of_vengeance, divine_arbiter(2), avenging_wrath, blessing_of_dawn, prepared_time(5), elemental_potion_of_ultimate_power
0:03.481 | generators | V | hammer_of_wrath | Fluffy_Pillow | 4.0/5: 80% holy_power | shield_of_vengeance, divine_arbiter(2), avenging_wrath,  blessing_of_dawn, prepared_time(5), bound_by_fire_and_blaze,  elemental_potion_of_ultimate_power
0:04.620 | cooldowns | J | final_reckoning | Fluffy_Pillow | 5.0/5: 100% holy_power | shield_of_vengeance, divine_arbiter(4), avenging_wrath,  blessing_of_dawn, prepared_time(5), bound_by_fire_and_blaze(2),  elemental_potion_of_ultimate_power
0:05.760 | finishers | K | divine_storm | Fluffy_Pillow | 5.0/5: 100% holy_power | shield_of_vengeance, divine_arbiter(4), avenging_wrath,  blessing_of_dawn, prepared_time(5), bound_by_fire_and_blaze(2),  elemental_potion_of_ultimate_power
0:06.900 | generators | N | wake_of_ashes | Fluffy_Pillow | 2.0/5: 40% holy_power | shield_of_vengeance, divine_arbiter(5), avenging_wrath,  blessing_of_dusk, prepared_time(5), bound_by_fire_and_blaze(2),  elemental_potion_of_ultimate_power
0:08.041 | finishers | K | divine_storm | Fluffy_Pillow | 5.0/5: 100% holy_power | shield_of_vengeance, divine_arbiter(5), avenging_wrath,  blessing_of_dawn, blessing_of_dusk, prepared_time(5),  bound_by_fire_and_blaze(4), elemental_potion_of_ultimate_power
0:09.183 | generators | Q | judgment | Fluffy_Pillow | 3.0/5: 60% holy_power | shield_of_vengeance, divine_arbiter(6), avenging_wrath,  blessing_of_dusk, prepared_time(5), bound_by_fire_and_blaze(4),  elemental_potion_of_ultimate_power
0:10.324 | finishers | K | divine_storm | Fluffy_Pillow | 5.0/5: 100% holy_power | shield_of_vengeance, divine_arbiter(7), avenging_wrath,  blessing_of_dusk, bound_by_fire_and_blaze(4),  elemental_potion_of_ultimate_power
0:11.524 | generators | O | divine_toll | Fluffy_Pillow | 2.0/5: 40% holy_power | shield_of_vengeance, divine_arbiter(8), avenging_wrath,  blessing_of_dusk, bound_by_fire_and_blaze(4),  elemental_potion_of_ultimate_power
0:12.724 | finishers | K | divine_storm | Fluffy_Pillow | 5.0/5: 100% holy_power | shield_of_vengeance, divine_arbiter(13),  avenging_wrath, blessing_of_dawn(2), blessing_of_dusk, divine_resonance,  bound_by_fire_and_blaze(4), elemental_potion_of_ultimate_power

</details>

It's hard to pin down where the sim is generating your Holy Power via Crusading Strikes.

1. [0.0] You have 0 Holy Power; use Judgment; gain 2.
2. [1.2] You have 2; use Blade of Justice; gain 1.
3. [2.3] You have 3; use Blade of Justice; gain 1.
4. [3.5] You have 4; use Avenging Wrath; no change.
5. [3.5] You have 4; use Potion; no change.
6. [3.5] You have 4; use Trinket; no change.
7. [3.5] You have 4; use Hammer of Wrath; gain 1.
8. [4.6] You have 5; use Final Reckoning; no change.
9. [5.8] You have 5; use Divine Storm; lose 3.
10. [6.9] You have 2; use Wake of Ashes; gain 3.
11. [8.0] You have 5; use Divine Storm; lose 3.
12. [9.2] **You have 3** (expected to have 2).

It looks like your first Holy Power generating swing must be lost in overflow.  The first spot where you demonstrably have more Holy Power than expected is at 9.183 seconds into the fight, where you have 3 HoPo after using Divine Storm.  You could've generated HoPo between 3.5 seconds and 5.8 seconds, between when you just pushed HoW to generate your 5th HoPo and when you cast Divine Storm to spend down.

I think there's probably a sim error here, because you should get your first Crusading Strikes swing immediately upon casting Judgment -- even before Judgment fully executes.

```
14:30:46> [Your] Judgment energized [You] 2 (Holy Power).  
14:30:46> [You] cast Judgment [Humility's Obedience].  
14:30:46> [Your] Blessing of Dawn applied [You].  
14:30:46> [Your] Let Go of the Past applied [You].  
14:30:46> [Your] Crusading Strikes energized [You] 1 (Holy Power).  
14:30:46> [Your] Crusading Strikes hit [Humility's Obedience] 435 Physical.  
...
14:30:46> [Your] Crusader's Reprieve healed [You] 0 Holy. (1,136 Overhealed)  
14:30:46> [Your] Judgment hit [Humility's Obedience] 5,779 Holy. (Critical)  
14:30:46> [Your] Judgment afflicted [Humility's Obedience].  
...
14:30:46> [Your] Judgment hit [Humility's Obedience] 1,445 Holy.  
...
```

In the above, my first swing is the second Crusader Strikes swing so it generated Holy Power.  In the sim, I'd expected an immediate non-productive swing.  Your first productive swing should be a single hasted-swing from the start of combat, not ~4.6 seconds into the fight, unless there's something I'm missing.  (Is there time spent running to the target before the first melee occurs?)

It looks like the sim has Crusading Strikes landing every 2.3 seconds, so it looks like the first swing is being queued at 0 instead of landing on initial attack.

![image](https://user-images.githubusercontent.com/9438134/228035262-67efe9fa-8f77-4b3c-9610-c4e04f8b6e61.png)

As it stands, in the addon, your first swing would be at 0.00 (if you're in melee range), then your first HoPo-generating swing would be at 2.3, which would explain the second BoJ cast changing to Avenging Wrath -- you'd have 4 Holy Power (Judgment: 2, Blade of Justice: 1, Crusading Strikes: 1).

**Comment by Bingo176** [comment]
Reset to defaults and using automatic for this snapshot. https://pastebin.com/FPB5b07x

I'm guessing the issue is mostly the aoe swings being counted towards the predicted HP gain. I will test when you post.

My concern was that Wake of Ashes and Divine Toll will be recommended but only for a fraction of a second every time they show up. I'm guessing its the HP prediction issue?

**Comment by Hekili** [comment]
> I'm guessing the issue is mostly the aoe swings being counted towards the predicted HP gain. I will test when you post.

It didn't count the extra targets in terms of gaining extra Holy Power, mind you.  It just meant that knowing whether the next swing would generate HoPo or not is off.  But yeah, that'll be fixed.

> My concern was that Wake of Ashes and Divine Toll will be recommended but only for a fraction of a second every time they show up. I'm guessing its the HP prediction issue?

You'd want to snapshot them being recommended; if you have 2 HoPo and a swing in 0.1s to grant you a third HoPo, either you have to beat the swing or the recommendation will change when you gain the third HoPo.  If there's something else to factor in, the snapshot would tell us.

It does look like the sim risks delaying Wake and Divine Toll, likely because of the HoPo checks.

![image](https://user-images.githubusercontent.com/9438134/228049396-2b82dad8-ef2b-44c7-aca5-6c7d5fa688fb.png)

It's possible the priority needs some work to spend down HoPo at 4 with Crusading Strikes to avoid overcapping or having spenders significantly delayed because you jumped back up to 3 HoPo.  That requires some testing, though.

**Comment by Hekili** [comment]
I did some investigation yesterday and have a few sims:

## [5 Target Patchwerk](https://www.raidbots.com/simbot/report/98WAo2WBZyQSXExQGQ6Ekk)
![image](https://user-images.githubusercontent.com/9438134/228292607-2e60b4c5-c626-4ce3-be4a-22f029d2b339.png)

### Original (Resources):
![image](https://user-images.githubusercontent.com/9438134/228294835-8e121b06-33af-4f83-b765-d6099242b391.png)

### Modified (Resources):
![image](https://user-images.githubusercontent.com/9438134/228295001-f199ddec-79e1-4a1f-b569-7662bdb33a7e.png)

## [Patchwerk](https://www.raidbots.com/simbot/report/1TuXUmrPK9t4RD6JKpZP56)
![image](https://user-images.githubusercontent.com/9438134/228293096-e489a02c-80e5-42aa-85db-7ab893a83407.png)

### Original (Resources):
![image](https://user-images.githubusercontent.com/9438134/228293633-81ee1b63-5adf-483f-b34c-a875efaeaf10.png)

### Modified (Resources):
![image](https://user-images.githubusercontent.com/9438134/228293907-223ea609-870e-49cd-9d08-a808593e9d7e.png)

## Summary

These changes mostly center on enabling Finishers at 3 or 4 HoPo if Crusading Strikes is taken and/or using Judgment at a lower HoPo threshold depending on Boundless Judgment as well.  With my changes, there's less wasted HoPo from Crusading Strikes.  Most of Judgment's loss is probably from Divine Toll / Divine Resonance since those count as Judgment casts on each target.

Overall, it looks DPS neutral for single-target and less than an 0.5% improvement in DPS for 5-target sustained.  However, it *probably* also reduces your risk of seeing Divine Toll or Wake of Ashes bumped based on a resource-generating Crusading Strikes swing landing just after a HoPo spender is used.

These tests only apply to your character build and gear; I didn't test for other talents or look for other potential impacts (Of Dusk and Dawn, etc.).

**Comment by Bingo176** [comment]
Functionally testing this yesterday it felt good in a couple dungeons. The flicker of WoA and DT basically went away. Not a huge fan of the play style but wanted to test it out.  Willing to test anything if any changes are applied. Appreciate your explanations and hard work.
