### ISSUE TITLE
[REC] Ret Paladin Wake of Ashes

### ISSUE THREAD

**Issue by Bingo176** [Hekili/hekili#2500]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Wake of Ashes will always default to first in priority. The sim will use WoA about 5-6 seconds into the fight after using Final Reckoning. 

### How to Reproduce

Enter game as Ret Paladin.
Go to target dummies.
With 0 Holy Power the priority will default to Wake of Ashes.

### Snapshot (Link)

https://pastebin.com/WabrULBE

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/9cTBULKjruQmvBaVT5LJCH

**Comment by Hekili** [comment]
The sim doesn't have Cooldowns split off to a different display.  When you have Cooldowns shown separately, the addon has to make adjustments in the Primary display since it has to assume you won't be using the abilities that are considered Cooldowns.

**Comment by Bingo176** [comment]
This the pastebin from the other ticket with defaults on everything. It should show the functionality I was describing. I have it set to a different display because of above reason.  https://pastebin.com/FPB5b07x . If this does not work can submit one after work.

**Comment by Hekili** [comment]
No, the snapshot you're showing there is recommending Divine Storm, so it doesn't tell us anything about Wake of Ashes for this ticket.

The short answer is that if Cooldowns are shown in a separate display, those abilities are treated as on-cooldown in the Primary/AOE displays.  Wake of Ashes has a condition related to Cooldown usage, so it can be recommended despite Avenging Wrath not having been used yet.  I'll explain further, but it's just a consequence of that choice.  The addon has a workaround option that I don't typically recommend (check `Cooldowns: Show Separately - Use Actual Cooldowns` in Retribution > Toggles), but might give you recommendations closer to what you expect.  I'll elaborate below.

If you show Cooldowns in a separate display (Toggles > Cooldowns > Show Separately), those abilities are disqualified from showing in the Primary display.  When they're disqualified, they're treated as being on cooldown so that non-Cooldown abilities that depend on their use can still be recommended.

Since Avenging Wrath is a Cooldown and goes to that display, and Wake of Ashes is not a Cooldown and stays in the Primary display, Wake of Ashes can be recommended in the Primary display if its Conditions are met.  In other words, if you split abilities in your "opener" between two displays, there's no way the addon can present you with those abilities in the same order they'd appear in your sim in a single display.  

You *could* bypass that feigned cooldown if you go to `/hekili` > `Retribution` > `Toggles` and check `Cooldown: Show Separately - Use Actual Cooldowns`, but there's a reason that is not a default option.  It can break the recommendations in a different way, if the priority is written to pool resources for one of your major cooldowns (and therefore refuses to use a spender until you *do* use Avenging Wrath or whatever other Cooldown it considers), then you might find yourself having HoPo generators recommended endlessly without ever using a HoPo spender, until/unless you pop those cooldowns for real.  That may or may not be the case with the current priority; it's just a potential impact of using that feature.

In other words, showing Cooldowns in a separate window means "show me recommendations assuming I won't use my major Cooldowns" as far as the Primary/AOE displays are concerned.  Without the feigned cooldown for those disqualified actions, many/most priorities would have you endlessly preparing to pop your Cooldowns in really unproductive ways.  (An older example would be an Elemental Shaman endlessly reapplying Flame Shock because they don't want to refresh it during Ascendance, but never actually popping Ascendance.)

Here's the entry that was considered for Wake of Ashes from your snapshot here:

> 28.  wake_of_ashes ( generators - 2 )
> \- this entry's criteria PASSES: holy_power.current[1.00] <= 2 & ( **cooldown.avenging_wrath.remains[120.00] | cooldown.crusade.remains[120.00]** ) & ( ! talent.execution_sentence.enabled[false] | cooldown.execution_sentence.remains[0.00] > 4 | target.time_to_die[300.00] < 8 ) & ( ! raid_event.adds.exists[false] | raid_event.adds['in'][3600.00] > 20 | raid_event.adds.up[false] )

You have 2 or fewer Holy Power, the display treats AW as being on cooldown because of your display/toggle preference, you don't have Execution Sentence talented, and none of the `raid_event`-related conditionals matter, so Wake of Ashes can be recommended.  It's actually the first HoPo generator in the action list (`generators - 1` calls the `finishers` list), so it's the top priority generator under the given circumstances.

If CDs were not shown separately (or if you force the addon to use their real cooldowns anyway), then this entry for Wake of Ashes would not be recommended until after you've used Avenging Wrath.  If that ends up delaying your use of Wake of Ashes by a total of 30 seconds in any given encounter, you've lost a cast of Wake of Ashes and almost certainly cost yourself damage.

**Comment by Bingo176** [comment]
That all makes sense. Appreciate the breakdown :)

**Comment by Hekili** [comment]
Thanks for reading.  It was a lot of words.  :)
