### ISSUE TITLE
[REC] Havoc and Movement-Related Talents

### ISSUE THREAD

**Issue by JRDK92** [Hekili/hekili#2525]
### Before You Begin

- [x] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Started using this addon recently, and had to tweak it by disabling several abilities that should not be used in dungeons/group content: Vengeful retreat and fel rush should not be used during group content as they will likely result in you accidentally pulling extra stuff, and they're mostly used for PvP. I have not seen a single DH who uses movement abilities as part of their normal DPS rotation. 

Also, a bug I noticed is with "Glaive Toss". There's a specific build for Havoc DH relying heavily on Glaive Throw. The addon prioritizes filler abilities over glaive toss with lots of enemies around you, which is not correct. Glaive Toss should be priority (at least once, if you have 2 of them up...) if you have more than 3 enemies, in my experience

Notice how in my paste, glaive toss is never included anywhere in the recommendation, but fel rush is.... that is just weird. 

### How to Reproduce

1. Enter game as Havoc DH. 

### Snapshot (Link)

https://pastebin.com/pnT0xpaJ

**Comment by Hekili** [comment]
> Started using this addon recently, and had to tweak it by disabling several abilities that should not be used in dungeons/group content: Vengeful retreat and fel rush should not be used during group content as they will likely result in you accidentally pulling extra stuff, and they're mostly used for PvP.

This is extremely incorrect.  If you're taking talents like Momentum and not using Fel Rush / Vengeful Retreat in group content, you're throwing away talent points and DPS.  They can be the right button to push, but you're responsible for positioning yourself to use them safely.  I mean, ultimately you're always responsible for opting to follow the guidance or not, and there are tons of times to deviate for fight choreography and circumstances, but yeah.  When it's recommended those abilities, it's fully intentional.

![image](https://user-images.githubusercontent.com/9438134/230906684-f295edc9-c4b3-4f93-b26d-888d6a422495.png)

On Mythic Eranog, 94% of players talent for Momentum.  That whole column at the bottom right relies on using Fel Rush and Vengeful Retreat to have any DPS value whatsoever.

That said, in the /hekili > Havoc section, a great deal of this is already spelled out along with some options associated with those abilities.  I personally am not a fan of the forced movement for DPS, either, but the solution to that is to take talents that don't require movement (and eat the DPS loss).

> Also, a bug I noticed is with "Glaive Toss". There's a specific build for Havoc DH relying heavily on Glaive Throw. The addon prioritizes filler abilities over glaive toss with lots of enemies around you, which is not correct. Glaive Toss should be priority (at least once, if you have 2 of them up...) if you have more than 3 enemies, in my experience

The priority (for the addon and in sims) uses Throw Glaive under 3 sets of conditions:

- Below Blade Dance but above Annihilation:  `talent.soulrend&(active_enemies>desired_targets|raid_event.adds.in>full_recharge_time+9)&spell_targets>=(2-talent.furious_throws)&!debuff.essence_break.up`

This is used with Soulrend talented and multiple targets while Essence Break isn't applied to your target.

- Below Annihilation but above Immolation Aura: `actions+=/throw_glaive,if=talent.serrated_glaive&cooldown.eye_beam.remains<4&!debuff.serrated_glaive.up&!debuff.essence_break.up`

This is used with Serrated Glaive talented and Eye Beam coming off cooldown and Serrated Glaive not already applied and Essence Break not applied.

- Filler (absolutely nothing else to push): `(talent.demon_blades|buff.out_of_range.up)&!debuff.essence_break.up`

Either Demon Blades is talented (so Fury gen is unpredictable) or you're out of range, and Essence Break isn't active on your target.

> https://pastebin.com/pnT0xpaJ

This link doesn't contain any snapshots, it just contains the first summary line.  When copying, you have to press CTRL+A to select all the text.  The Pastebin will have hundreds if not thousands of lines of information about how the addon made its decision.

What was the part about Defensive abilities?

**Comment by JRDK92** [comment]
Wow... Just learned that I do not fully understand Havoc, and that there's a talent point that buffs you if you use movement abilities. This is user error on my part. Thanks for the incredible explanation. 

I didn't take Momentum, but figured out that I can actually go into 'Abilities', select both Fel Rush and Vengeful Retreat and disable them entirely. This solves my issue, as I'm mostly just playing casual content (dungeons, timewalking) and not doing any competitive content (M+, raids)

Thanks again!!
