### ISSUE TITLE
WOTLK - SpellFlashCore library not available for Wrath Classic

### ISSUE THREAD

**Issue by peepeebumbum** [Hekili/hekili#2528]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When navigating to the spellflash tab, it says "These settings are unavailable because the SpellFlash addon / library is not installed or is disabled. I also tried installing the old SpellFlash addon (https://www.curseforge.com/wow/addons/spellflash) and it still won't load.
![Capture](https://user-images.githubusercontent.com/130389229/230946922-23784cc7-2caa-4b07-83a9-128fd2c18d3e.PNG)

### How to Reproduce

1. Launch WOTLK with the latest wotlk hekili version
2. Click on a display and navigate to the spellflash tab
3. The setting is unavailable

### Player Information (Link)

https://pastebin.com/h80sf08w

### Error Messages (Link)

https://pastebin.com/h80sf08w

### Contact Information

KEA#8538

**Comment by Hekili** [comment]
SpellFlash is a separate addon that's packaged up and included here.  I'm not the developer for it.  It explicitly disables itself in versions below 10.0 (because it uses modern API that doesn't match Wrath).  I bypassed that restriction by going into Hekili/Libs/SpellFlashCore/SpellFlashCore.lua and changing the 100000 on line 1 to 30000.  At that point, it will load but it will also have errors associated with trying to register events that don't exist in Wrath (i.e., PLAYER_SPECIALIZATION_CHANGED).  It may sort of work regardless or it might not, but I don't have plans to work on SpellFlashCore myself.

**Comment by Hekili** [comment]
I recommended changes to SpellFlashCore here:  https://github.com/Tga123/SpellFlashCore/pull/3

**Comment by Hekili** [comment]
Doesn't look like my pull request to SpellFlashCore is going to be accepted.  I will not be able to impact this request.

**Comment by Blueing** [comment]
I think your pull request got accepted yesterday, I downloaded the new version but Hekili still says SpellFlashCore isnt installed/enabled :(
