### ISSUE TITLE
Balance Druid moving modifier

### ISSUE THREAD

**Issue by kots33** [Hekili/hekili#2531]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

As a Balance Druid I am trying to change the modifier from Wrath and Starfire so that the addon does not suggest them when the character is in movement. But I can't seem to enter the command. could you tell me, how should the command be done manually, so that the addon does not suggest these two spells when my character is moving? Thanks.

### How to Reproduce

i don't know how to fill up this section

### Snapshot (Link)

https://tinypic.host/i/okmj1x

**Comment by Hekili** [comment]
First, keep in mind, this approach goes against the addon's intended to design.  My intent is to show you what would be the best button to push, and it's better to calm your movement whenever possible so that you can get your hardcasts in when appropriate.

That said, sometimes you have to move and you don't want to stop moving.  Balance has a few instant casts you can fill with while moving, so if you really want them to be recommended, you can make a copy of the Balance priority (because I'll overwrite your changes otherwise), then any of the following approaches:

1. Take the existing conditions for any hardcast spells in the priority and wrap them with: `! moving & ( `*original conditions here*` )`
The challenge for this is that Balance has a fairly long priority, so this is a lot of edits.
2. For any of the hardcast spells in the priority, go to the bottom and click "Show Modifiers."  Set "Check Movement" and then set "Movement" to  "Stationary."
3. Add new entries for your instants to near the top of the priority, with appropriate conditions.  So you might add these entries to the `default` action list before any Call Action List or Run Action List entries split off.  This requires you to set up conditions (likely including `moving`) that will enable casting repeatedly (so the priority never goes any further while moving), but also such that you have instant spenders factored in.  It's complicated.
