### ISSUE TITLE
Ret Paladin: Templar Strikes/Slash priority too high?

### ISSUE THREAD

**Issue by b19h75** [Hekili/hekili#2538]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [ ] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

With the latest version of Hekili, Templar Strikes/Templar Slash (TS) is being recommended even when at 5 Holy Power. At times it will do nothing BUT recommend TS until Holy Power has been spent. I did not observe this behavior prior to the most recent version.

### How to Reproduce

1. Select Templar Strikes talent.
2. Build to 5 Holy Power.
3. Observe recommendation of Templar Strikes above spenders even when at 5 Holy Power.
![WoWScrnShot_041223_074201](https://user-images.githubusercontent.com/130879709/232262336-c978c01c-0e0c-4e21-b848-6e8219c446f7.jpg)

### Snapshot (Link)

https://pastebin.com/gYA38Gem

**Comment by Hekili** [comment]
Your priority doesn't look like mine.  Did you import or change something?  It looks like you've removed or disabled the entry for the Cooldowns list, which will impact other recommendations.

**Comment by Hekili** [comment]
I'm going to go ahead and close this ticket since it doesn't meet the requirements for triage here.

If I had to guess, you toggled off cooldowns but saw that Execution Sentence was still recommended.  If that's what you were trying to solve for with your edits, you should probably just disable the abilities that you don't want to have recommended via /hekili > Abilities instead of editing the priority.  When Execution Sentence is disabled, it is treated like it is fully on cooldown so that other recommendations that relate to Execution Sentence can still fire.

You could also use /hekili > Abilities and set Require Cooldown to Cooldowns for Execution Sentence and potentially get a similar result.

Your regular Holy Power spenders include conditions that either you didn't take Execution Sentence or that Execution Sentence is on cooldown for more than 2 GCDs so that you don't spend down Holy Power right before you need it for cooldown alignment.
