### ISSUE TITLE
[BUG] Brewmaster Monk displays not showing.  Windwalker/Mistweaver show okay.  

### ISSUE THREAD

**Issue by StarfuryZeta** [Hekili/hekili#2613]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Displays not showing when spec'd into Brewmaster Monk.   Windwalker and Mistweaver will show displays when spec changed.  

### How to Reproduce

Created and levelled a Kul Tiran brewmaster monk (started level 10).  After levelling to 18, noticed that the Rotation displays will not display.   Change specialization to windwalker, rotation display will show.  change to Mistweaver, display shows.  Change back to brewmaster, display disappears.  

### Player Information (Link)

https://pastebin.com/KGWSTca0

### Error Messages (Link)

https://pastebin.com/xnEugEAL

### Contact Information

StarfuryZeta#4744

**Comment by Hekili** [comment]
The error messages you provided aren't related to the addon.

You can attempt to take a snapshot (`ALT-SHIFT-P` to pause, by default); copy and paste the info from /hekili > Snapshots and provide a Pastebin link here.

If there's any information in /hekili > Warnings, you can supply that as well.

As noted when you first start combat, the addon is not really written for low-level characters because you are missing so many abilities and it's possible that the spell IDs will also change as you level.  If you provide the above information, I'll take a quick look.

**Comment by StarfuryZeta** [comment]
Thank you for the response.   There are no warnings in /hekili and the only bugsack error was the gathermate error.   

Here are two snapshots.   The first is prior to any combat, the second during combat.  

[https://pastebin.com/nHwVf01k](https://pastebin.com/nHwVf01k)

[https://pastebin.com/WMCEBxyM](https://pastebin.com/WMCEBxyM)

If this spec is just too low level, I understand.

**Comment by Hekili** [comment]
Thanks; the snapshot does help.  I omitted the fallback action list when you don't have any of the talents required otherwise.  I'll add it now.

**Comment by Hekili** [comment]
This will be resolved in https://github.com/Hekili/hekili/releases/v10.1.0-1.0.1c.
