### ISSUE TITLE
[BUG] Runaway CPU/Memory Usage in Raid

### ISSUE THREAD

**Issue by Raven7576** [Hekili/hekili#2618]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Basically, using Spell Flash and a single bar with 4 spots, I get a increase in CPU usage according TitanPanels built in performance scans, and the addon "AddOns CPU Usage".

This was collected while ideal, number would increase each second. 
![image](https://github.com/Hekili/hekili/assets/42005883/c2749a70-e674-48fb-8081-4b13442f4dc8)

This was collected while doing the 2nd Boss in LFR.
![image](https://github.com/Hekili/hekili/assets/42005883/2242823b-c31b-47a1-b39e-773e1519b288)

Here is a picture of the elements I use from the addons. 
![image](https://github.com/Hekili/hekili/assets/42005883/1399f3f2-f3d5-4bb5-b0df-f7ba36e67219)

Honestly dont know how else to describe this, im trying to bust having super low FPS in a raid setting. 

I have a i7-12700K and a 3070TI for reference and only get about 40FPS during raid.

### How to Reproduce

1. Download addon
2. Play Warlock?
3. Use DPS and Cool Downs bars with Spell Flash Circles
4. Monitor CPU usage with addon

### Player Information (Link)

https://pastebin.com/beRKAhMk

### Error Messages (Link)

none

### Contact Information

Razør#0394

**Comment by Hekili** [comment]
Yes, all of those numbers are going to increase over time.

If the performance impact is too high, do not use the addon.

**Comment by Raven7576** [comment]
Feel like I bothered you with this one and Im sorry. Just really fustrated with getting 40 FPS in raid on a decent rig. Your addon was the first red harring I followed. Still dont know the issue but 5 FPS gained from disabling wont fix much. 

You make an outstanding product, i just dont know much about addon impact and all that jazz.

**Comment by Hekili** [comment]
I shouldn't have responded in such a cranky fashion to a ticket; I apologize.

I am always working to improve the addon's optimization.  There is some (seemingly hidden) CPU usage that I can't otherwise account for right now, but I'm working to figure it out.  In environments where your FPS is already reduced, the addon's CPU time seems to increase, even when paused.

Unfortunately, Blizzard took away one of the tools I would use to track which functions are using more CPU, so testing is impacted.

The best things you can do to make the addon use less CPU is:
- Use only the Primary display, if possible (i.e., don't have Cooldowns/Interrupts/Defensives "Shown Separately")
- Reduce the number of recommendation icons.  Each one costs a little more CPU
- In your spec's Performance options, you can try throttling how much CPU the addon is allowed to use.  The first checkbox is for reducing how frequently it updates recommendations.  The second is for determining how much time per frame the addon can spend calculating recommendations.  

I've noticed that on some CPUs, turning *up* the amount of time the addon can spend will make it so recommendations are fully calculated in a single frame and use less CPU associated with doing work over multiple frames.

I will probably set up a pinned ticket re: performance concerns.  Memory usage literally doesn't matter, though.  The Lua system will collect and destroy lingering, unused tables when it feels it is necessary.  Manually cleaning/reusing the tables myself instead costs CPU.  But I'll keep chipping away at the CPU usage.

Take care!
