### ISSUE TITLE
[REC] Sub rogue opener recommending Shadow Blades instead of channelling on-use trinket after initial shadow strike

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#2625]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

In the opener rotation, simc recommends to channel manic grieftorch after the initial shadowstrike hit, then shadow blades. Addon suggests using shadow blades first, then grieftorch. Simc makes more sense as otherwise you are losing shadowblades uptime as grieftorch is channelling. 

Snapshot seems to imply that stealth will still be up after the initial shadowstrike but this isnt the case as subterfuge is not talented.

### How to Reproduce

Enter game as sub rogue with manic grieftorch equipped and enter stealth. Rotation will show as described above.

### Snapshot (Link)

https://pastebin.com/WgV31mmM

**Comment by Hekili** [comment]
I'll need you to add a sim for comparison.

**Comment by fzarr** [comment]
Example sim here: https://www.raidbots.com/simbot/report/v1VkvMcBio5to2NyBgXRcy

**Comment by Hekili** [comment]
I did some investigating and there has been a difference in addon vs. sim behavior with regard to off-GCD abilities.  In the sim, they will sync to the GCD unless `use_off_gcd` is flagged.  In the addon, they do not sync to the GCD by default.  I'm turning this back on, which should cause the trinket to be recommended before Shadow Blades.

**Comment by fzarr** [comment]
If this fix is already present in v10.1.0-1.0.1g, then it hasn't fixed the issue. Still seeing grieftorch being recommended after shadowblades.

**Comment by Hekili** [comment]
Add an updated snapshot.

**Comment by fzarr** [comment]
Pre-pull: https://pastebin.com/3xPkVpyG
When grieftorch should be recommended (after initial shadowstrike): https://pastebin.com/Thm8yP55

**Comment by Hekili** [comment]
Thanks.  I've had to add some additional nuance to how off-GCDs get handled (the addon was intentionally short-circuiting when it found the highest priority ability that is ready within the GCD).  The use of Manic Grieftorch here was relying on other offGCD entries syncing to the GCD by default, while your trinket would not.  I am now matching that logic BUT keep in mind that if you press Shadowstrike but don't use Manic Grieftorch before the GCD expires, it will fall Shadow Blades and Symbols of Death again.

![image](https://github.com/Hekili/hekili/assets/9438134/86efb1db-7967-4f7e-bb86-c0d898212ede)

(I'm using Bottled Flayedwing Toxin in place of Manic Grieftorch on this alt.)

![image](https://github.com/Hekili/hekili/assets/9438134/7ca6c114-076b-4b2c-87d8-fdd45b3cce59)
![image](https://github.com/Hekili/hekili/assets/9438134/a53483b4-17e2-41c9-8e2c-d139b8fe4d19)
![image](https://github.com/Hekili/hekili/assets/9438134/03a87f04-0c09-416e-8304-918f73667aaf)
![image](https://github.com/Hekili/hekili/assets/9438134/6959f0fb-7a50-4b4c-b571-db9367103844)

You can see that my trinket is lower in priority (cds 25) than Symbols (cds 10) and Shadow Blades (cds 13).  It's only recommended sooner because the trinket is flagged to be used off-GCD while Symbols is not, so the trinket is ready 1s sooner during the GCD.
