### ISSUE TITLE
[REC] Blood DK, cooldown.dancing_rune_weapon.remains not updating within the Standard Tombstone action

### ISSUE THREAD

**Issue by rscotthopson** [Hekili/hekili#2626]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The cooldown.remains is not updating for dancing_rune_weapon within the Standard > Tombstone action. It is remains at 120. This causes Tombstone to be recommended irrespective of DRW cooldown.

### How to Reproduce

1. Enter game as blood dk
2. Select talent sharttering bone
3. Stand in D&D
4. put DRW on cooldown and wait until cooldown is below 25
5. alternatively, you can simply put DRW on cooldown and mouse over the condition list to see that the cooldown.dancing_rune_weapon.remains stays at 120 irrespective of current cooldown.

![image](https://github.com/Hekili/hekili/assets/114375147/37444c2e-2056-4e40-bcec-a54349ca65a8)

### Snapshot (Link)

https://pastebin.com/pAT5pc4p

### Contact Information

Discord "Scott (Tenraiel)#3960"

**Comment by Hekili** [comment]
You'll want to put your snapshot on Pastebin and link it so it remains readable.

This is likely occurring because DRW isn't available to the Primary display (CDs are set to Shown Separately).  Abilities that can't be recommended in the display act as though they're fully on CD, otherwise you can be stuck in an endless loop preparing to push a button you're not going to push.

I'll take a look when there's a more readable snapshot, though.

**Comment by rscotthopson** [comment]
Currently back at work, I'll put it into PB tonight. Sorry about that 

Yeah, I keep the cooldowns separate so I can keep from blowing them at the end of a pack. Glad you added that functionality. I hope you can get it working!

**Comment by rscotthopson** [comment]
> You'll want to put your snapshot on Pastebin and link it so it remains readable.
> 
> This is likely occurring because DRW isn't available to the Primary display (CDs are set to Shown Separately). Abilities that can't be recommended in the display act as though they're fully on CD, otherwise you can be stuck in an endless loop preparing to push a button you're not going to push.
> 
> I'll take a look when there's a more readable snapshot, though.

I updated the snapshot link.

**Comment by rscotthopson** [comment]
> You'll want to put your snapshot on Pastebin and link it so it remains readable.
> 
> This is likely occurring because DRW isn't available to the Primary display (CDs are set to Shown Separately). Abilities that can't be recommended in the display act as though they're fully on CD, otherwise you can be stuck in an endless loop preparing to push a button you're not going to push.
> 
> I'll take a look when there's a more readable snapshot, though.

Based on your feedback regarding showing cooldowns seperately, I selected this box in the Blood Toggles selection and it fixed my issue
![image](https://github.com/Hekili/hekili/assets/114375147/d5f56226-f348-4c57-9a07-6a33b10d1dcd)

**Comment by Hekili** [comment]
Yeah, that's the correct workaround to use for the moment.  It has some subtle drawbacks that aren't worth explaining if it is working for you.

I plan to revise what it means to have cooldowns shown separately.

Currently, you have 2 options:
* Shown Separately ON:  Toggle Controls if Shown in Separate Display
* Shown Separately OFF:  Toggle Controls if Shown in Primary/AOE Display

There are probably scenarios where you might want the toggle to do something else when the separate display is enabled:
* Toggle ON:  Shown in Primary/AOE Display
* Toggle OFF:  Shown in Separate Display

This would make it so that when CDs are off, they're shifted to a separate display; otherwise, they're just part of the regular displays.

Or maybe:
* Toggle ON:  Shown in Primary/AOE _and_ Separate Display
* Toggle OFF:  Shown in Separate Display

This would make it so when CDs are off, they're in a separate display; otherwise, they're visible in both displays.
