### ISSUE TITLE
[REC] Subtlety opener delays Rupture far too long compared to Raidbots sim.

### ISSUE THREAD

**Issue by jankozilla** [Hekili/hekili#2649]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Log into WoW. Started attacking target dummy, Rupture is delayed till way after, not suggesting after flagellation. Also issue suggestion Beacon of the Beyond.

### How to Reproduce

1.Play WoW
2.Play Sub rogue
3.Hit target dummy.

### Snapshot (Link)

https://pastebin.com/3JBhQpgd

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/3v9DxkFCZDgDcfua7EZwXU

### Contact Information

Janko#2971

**Comment by Hekili** [comment]
Ok, I've put a fair amount of analysis into this.  The tl;dr is that there are two major factors.  The first is just a difference between what the addon can forecast/expect and what the sim can log afterward.  The second is probably a combination of an inconsistency between the sim and the addon *and* a likely APL issue that just fortunately works by mistake in the sim.

I have fixes ready that should make the results more closely match the sim.

### 1st Difference

Your opening Shadowstrike procs 5 combo points in your sim.  I'm guessing that's a Weaponmaster proc; I'm not sure we can consistently expect that, so the addon will generate CP more conservatively vs. the example that was selected in the sim.

### 2nd Difference

The usage of Shadow Dance basically short-circuits the use of Rupture; in the sim, using Flagellation applies `flagellation_buff` while the addon applies `flagellation` (which also counts as `flagellation_buff`).  In the snapshot, after using Flagellation:

> 53.  shadow_dance ( stealth_cds - 9 )
> The action (shadow_dance) is usable at (3.00 + 1.00).
> List ( stealth_cds ) called from ( Subtlety:default:12 ) would PASS at 1.00.
>    energy.deficit[55.17] <= variable.stealth_threshold[90.00]
>  - this entry's criteria PASSES: ( ... | **buff.flagellation.up[true]** | ... ) & variable.rotten_threshold[true]

In your sim, Shadow Dance isn't recommended immediately after Flagellation and you can see that the buff applied is `flagellation_buff`:

Time | List | # | Name | Target | Resources | Buffs
-- | -- | -- | -- | -- | -- | --
0:01.005 | cds | K | flagellation | Fluffy_Pillow | 139.3/150: 93% energy 5.0/7: 71% combo_points | bloodlust, slice_and_dice, silent_storm, sophic_writ
0:02.010 | cds | M | shadow_blades | stitchy | 150.0/150: 100% energy 5.0/7: 71% combo_points | bloodlust, slice_and_dice, silent_storm, **flagellation_buff**, sophic_writ

Honestly, I'd almost guarantee that the sim checking for `buff.flagellation.up` is an error that just happened to get the expected result.  As far as I can see, `flagellation_buff` and `flagellation_persist` get applied but never Flagellation.  I think `flagellation` as a buff alone is probably mistaken carryover from the Covenant version.  If the priority is updated to check `buff.flagellation_buff.up` instead, then the sim starts matching the addon.  But that's probably not what we actually want.

In any case, the failure to cast Rupture is caused by the cast of Shadow Dance, which is caused by the addon treating `flagellation` and `flagellation_buff` the same.  I'm modifying the addon not to do that any more.  The Rogue theorycrafters may want to revisit their Shadow Dance criteria to use the `flagellation_buff` aura and also check that Rupture's been applied first.

Current:
> actions.stealth_cds+=/shadow_dance,if=(variable.shd_combo_points&(!talent.shadow_dance&buff.symbols_of_death.remains>=(2.2-talent.flagellation.enabled)|variable.shd_threshold)|talent.shadow_dance&cooldown.secret_technique.remains<=9&(spell_targets.shuriken_storm<=3|talent.danse_macabre)|`buff.flagellation.up`|buff.flagellation_persist.remains>=6|spell_targets.shuriken_storm>=4&cooldown.symbols_of_death.remains>10)&variable.rotten_threshold

Revised:
> actions.stealth_cds+=/shadow_dance,if=(variable.shd_combo_points&(!talent.shadow_dance&buff.symbols_of_death.remains>=(2.2-talent.flagellation.enabled)|variable.shd_threshold)|talent.shadow_dance&cooldown.secret_technique.remains<=9&(spell_targets.shuriken_storm<=3|talent.danse_macabre)|`dot.rupture.ticking&buff.flagellation_buff.up`|buff.flagellation_persist.remains>=6|spell_targets.shuriken_storm>=4&cooldown.symbols_of_death.remains>10)&variable.rotten_threshold

...or there might be other Subtlety APL changes coming that wipe all of this out anyway.

**Comment by jankozilla** [comment]
ohh awesome !! Thank you!

**Comment by jankozilla** [comment]
Just let us know when its up!

And thank you again for your time!

**Comment by Hekili** [comment]
It's in the next release that I'll post in a few minutes.
