### ISSUE TITLE
Havoc DH - Serrated Glaive - not being recommended as opener or before eye beam

### ISSUE THREAD

**Issue by R34P3R89** [Hekili/hekili#2652]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I was trying this "no move" build for Havoc where I don't take the Momentum path. Therefore, I decided to roll with Serrated Glaive as a talent, which buffs the damage of Chaos Strike and Eye Beam by 20% per target hit with Throw Glaive. 
Therefore, my rotation should include throw glaive as spell before I use Eye Beam or Chaos Strikes. Right now, however, I believe that Throw Glaive is merely a filler.
Is there any way to fix this or modify this?

### How to Reproduce

1. Enter game as Demon Hunter
2. Choose Havoc as specialization
3. Talent into Serrated Glaive
4. Start a fight and check the recommendations by Hekili

### Snapshot (Link)

https://pastebin.com/TQ2XR5wZ

**Comment by Hekili** [comment]
Throw Glaive would've been recommended if Blade Dance were on cooldown. 

I'll need a sim of your character for comparison purposes to investigate further.

**Comment by chiraino** [comment]
Blade Dance should not be checked for this, Blade Dance needs to be ready after Eye Beam, and not go on cooldown before.

**Comment by archxlock** [comment]
I noticed the same behavior today, and chiraino is correct.

edit:
Here's a sim of my DH if it helps.
https://www.raidbots.com/simbot/report/had7TqyVPdeAh2MdPXDTPn/simc

**Comment by Starianor** [comment]
This still appears to be happening, not sure if there is a way to fix it, Would be really nice though.

edit: after reading the comment from Hekili, I think just removing "& cooldown.blade_dance.remains" from the Priorities > Havoc > entry 25. Throw Glaive seems to have fixed it for me

**Comment by Hekili** [comment]
That's what this means:

> Throw Glaive would've been recommended if Blade Dance were on cooldown.

From archxlock's sim:
![image](https://github.com/Hekili/hekili/assets/9438134/60dfb43e-af58-435f-8121-3aa8fa35b389)

That usage of Throw Glaive (after Blade Dance is on CD) includes the Blade Dance condition:

![image](https://github.com/Hekili/hekili/assets/9438134/1f7a0470-491f-440e-a4b5-28f70d876e9b)

> Blade Dance needs to be ready after Eye Beam, and not go on cooldown before.

In the sim, Death Sweep was used at `4.710` and the hasted GCD looks like it's at about 0.75s.  Throw Glaive is used at `6.986` (3 GCDs later).  Eye Beam is used next at `7.744` then we get our post-beam Death Sweep at `9.038`.  The time between Death Sweeps is 4.328s, suggesting that the Death Sweep is available despite not completing its full cooldown.  I'd assume that's a reset from Chaotic Transformation due to Eye Beam triggering (extending) Metamorphosis.

Does that not actually occur?  If not, the sim profile needs an update to address it.  If Eye Beam is resetting Death Sweep/Blade Dance CDs, then you certainly don't need DS/BD off-cooldown before using it.

I'll check a couple of details that might be impacting what is seen in-game.  I did make an edit to that sim profile removing the BD check, and it looks like average performance is nearly identical, but without checking for BD cooldown, the top end is higher.  

https://www.raidbots.com/simbot/report/cTe5S7fjHnqVinqagiJQ9F/simc

I may go ahead and incorporate that edit, but it does result in an immediate Throw Glaive into Eye Beam which might raise some significant confusion.

**Comment by Starianor** [comment]
The transformation from eyebeam doesn't reset the cooldown on blade dance, only using actual meta does, so that's maybe where the disconnect is. I tried making my own custom edits and tonight during raid it did feel a lot better. So if an official update could be made, that might be even better because I think my change I made was kind of basic. It gets the job done, but maybe it could be better.

**Comment by Hekili** [comment]
In that sim, I don't think I accounted for the haste from Metamorphosis, so it's possible that the CD would actually reset in that amount of time.

I do have a pending update that will allow Throw Glaive without Blade Dance being on cooldown; it adds a new option to the spec's settings that I've turned on by default.

**Comment by Starianor** [comment]
In the ideal situation, DH can actually get two death sweep during that short time that we are transformed, so we really need it to not be on cooldown or just finishing its cooldown as eyebeam finishes so we can get two in.

**Comment by Hekili** [comment]
Sure, I'm not disagreeing. It just raises the question of why the sim is explicitly written that way.

The assumption may be that, in the opener, the Eye Beam channel provides enough time for the CD to recover and the sim isn't resetting BD/DS with Eye Beam/Demonic. 

It may be worth supplying a ticket to SimC if the sim opener is unrealistic or doesn't match guides and so forth. The option I'm adding resolves it well-enough for the addon for now.

**Comment by Starianor** [comment]
I just wanted to reply to this and let you know that it looks like they updated the APL for DH in the most recent update, so the temporary change you made doesn't really do anything and doesn't need to be there anymore. Anyway, just wanted to let you know and thanks for the quick temp fix regardless.

**Comment by Hekili** [comment]
Yup, I updated the priority; I'll remove the option.  Thanks!
