### ISSUE TITLE
Steady Shot is recommended when Trueshot is active

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#2654]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

If we activate Trueshot, the addon recommends using Steady shot to get a Steady Shot buff. This is a very large loss of damage. When Trueshot is active or its benefit from talent, we should always give preference to Aimed Shot and Kill shot proks. We need to minimize the use of Steady Shot. And they should use Aimed Shot and Kill shot as much as possible (if there are any pros)

### How to Reproduce

1. Select the dummy's ST.
2. Activate Trueshot
3. And follow the rotation. According to the decline of Steady focus, there will be a recommendation to use Steady shot. While Trueshot is active.

### Snapshot (Link)

https://pastebin.com/tMUgxEg0

**Comment by Hekili** [comment]
Link a sim for comparison.

**Comment by Dragonfo** [comment]
https://www.raidbots.com/simbot/report/u9k2mBqxoDtc6KmUSKuTnh

**Comment by Hekili** [comment]
Your snapshot was not taken with Trueshot active, so I cannot make a comparison here.  Please take the snapshot when Steady Shot is recommended during Trueshot (and should not be recommended).

**Comment by Dragonfo** [comment]
https://pastebin.com/fHySCRWS 
So I got the Trueshot proc and at the time of the Trueshot proc, I had a Steady Shot recommendation. And it should not be when Trueshot is active, even when it is of use. This is a loss of damage, since for 2 seconds we will just use the weakest ability at the moment of active Trueshot.

**Comment by Hekili** [comment]
Your sim actually does use Steady Shot during Trueshot if Steady Focus is falling off, depending on what other buttons you had to push in the moment:

![image](https://github.com/Hekili/hekili/assets/9438134/c93a24f2-8a33-45ee-8d1c-f41cb3633362)

The first Steady Shot is the last entry in the action list (meaning nothing else was available):
![image](https://github.com/Hekili/hekili/assets/9438134/9c582488-1d6e-4f30-a880-33c155abd219)

The second Steady Shot is explicitly used if you've already cast your first Steady Shot and Steady Focus is expiring soon.
![image](https://github.com/Hekili/hekili/assets/9438134/06d36fe7-f4aa-4d88-bdb3-df37fe75e8dd)

(The second example may be misleading since it does check that Trueshot isn't up, but that's only when Steady Focus is down -- this high priority entry in the priority isn't used to cause the *first* cast of Steady Shot during Trueshot.)

I do suspect that the Steady Focus count variable may need to be reset more often; I'll make a change to help ensure that you don't see 2 of the `G` Steady Shots in a row during Trueshot.  Those are the `st - 1` entries in the addon.  If you snapshot 2 of the `st - 1` entries in a row recommended during Trueshot, that'd truly be an error.
