### ISSUE TITLE
[REC] Fury Warrior Execute showing priority when not available

### ISSUE THREAD

**Issue by ThatRickGuy** [Hekili/hekili#2658]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Occasionally while playing my Fury Warrior Hekilli will show Execute as the next priority, but on those occasions Execute isn't available. The target's health is too high and the free proc of execute hasn't occurred. After a few GCDs it'll move on to the next priority. 

### How to Reproduce

I don't have a clear indication of the steps to recreate, it usually happens a few times a night in both mythics and raids. And since it's usually in the middle of a fight, it's not easy to get a screenshot of, but if I can catch it next time, I will update this issue. 

### Snapshot (Link)

will grab later

**Comment by Hekili** [comment]
In the future, I'd prefer that you wait until you have a snapshot to open the ticket, as I can't do anything with this information in the meantime.

My best guess here would be that you have target swaps turned on and it's suggesting you swap to a target in the proper health range.  Otherwise, there will likely be more helpful information available in the snapshot when you get it.

**Comment by Hekili** [comment]
Closing for lack of information.  You can add missing details and reopen when you have the snapshot(s).
