### ISSUE TITLE
Devastation Evoker too little priority on Eternity Surge in Dragonrage

### ISSUE THREAD

**Issue by Amortalist** [Hekili/hekili#2660]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Since we're moving out of EOI and now playing Event Horizon (lower cd on Eternity Surge), ES and FB should be an absolute priority cast during dragonrage to maximize dragonrage's duration (up to 42s under Bloodlust). On another topic I think we could benefit of clearer ways to show chaining/clipping disintegrate (clipping should only happen for empowered spell like EB or ES and Shattering Star, or 2 stacks of Burnout anyway)

### How to Reproduce

Play devastation evoker ST build with Event Horizon talented

### Snapshot (Link)

https://pastebin.com/1TA7tRRR

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/wYHsYM6AWq3PhEeT9Ah48V

### Contact Information

Nibana#6011

**Comment by Hekili** [comment]
I'll need you to provide a more specific snapshot.  Were you thinking that ES should've been recommended over FB in this snapshot?  If not, you'd need to provide a snapshot taken when ES was ready but not recommended and you thought it should be the top recommendation.

The snapshots really need to be "I should've seen X at this moment but I saw Y instead."  Then I can investigate in more detail.  If I compare to your sim, and you were expecting ES right here, the difference *may* be that you're no longer in Bloodlust (i.e., where your sim opens with ES instead of FB).  The logic that would take you to use FB appears correct at first glance.

> On another topic I think we could benefit of clearer ways to show chaining/clipping disintegrate (clipping should only happen for empowered spell like EB or ES and Shattering Star, or 2 stacks of Burnout anyway)

If you want to propose a different way of presenting those, you can do that in another ticket.  If you think the addon is recommending clipping (or not) at the wrong time, you'd have to supply snapshots of those recommendations with an explanation.

**Comment by Amortalist** [comment]
Hey sorry, was away for a few days. Basically the snapshot I sent was taken when I should have been advised to cast ES, it was at pull on dummy, and I was in Dragonrage, Hekili advised me to FB, LB and DI before even starting to suggest ES.

**Comment by Amortalist** [comment]
Here is another snapshot at pull, just casted Dragonrage and Hekili advise FB > SS > DI > ES, when it should be ES > FB > SS >  Trinkets > DI : https://pastebin.com/i6zaTwW6
