### ISSUE TITLE
[FEATURE] Implement Timing's for Demonology 2min Tyrant to align with Shadow Priest Power Infusion

### ISSUE THREAD

**Issue by Noodleboy0** [Hekili/hekili#2666]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

If you are receiving a PI from a shadow priest on Demo lock it is optimal to hold your gfg and Tyrant to line up with their Pi. Is it possible for this to be done either as an option, or as a separate profile? The Lock theorycrafters made an APL to represent this that I've linked below if that helps.

https://github.com/simulationcraft/simc/pull/7590

### Contact Information

Discord: Spaghetti#3936

**Comment by Hekili** [comment]
No, the addon cannot reliably trust that you're getting an external PI at the 2 minute mark.  You would need to toggle CDs off with `ALT-SHIFT-R` (or whatever you've changed the binding to) in order to prevent the recommendation until you want to see it, then tap the toggle again to allow CDs to be recommended again.
