### ISSUE TITLE
outlaw rogue reccomending ambush when not possible

### ISSUE THREAD

**Issue by thamjam** [Hekili/hekili#2680]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my outlaw rogue, it keeps recommending "Ambush" when I can only use "dispatch"

### How to Reproduce

it telling me to use "ambush" but I am not stealthed and I only can use "dispatch"

### Snapshot (Link)

https://pastebin.com/szAq7Wxu

**Comment by IIeTpoc** [comment]
Snapshot is not complete. Try to reset the default profile you are using and then posting a snapshot again.

Snapshots are detailed logs of how the addon arrived at the recommendations it made.  They can be automatically generated if the addon was unable to make a recommendation.  Otherwise, they are manually triggered by pausing (default: ALT-SHIFT-P) or snapshotting (default: ALT-SHIFT-[).  Snapshots are generally required when submitting issue tickets.  They provide critical information about what the addon could see when it made its choices.

See https://github.com/Hekili/hekili/wiki/Reviewing-Recommendations#snapshots for more information.
