### ISSUE TITLE
[REC] Not recommending flagellation on sub rogue

### ISSUE THREAD

**Issue by wheatbread** [Hekili/hekili#2689]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When specced into flagellation, Hekili does not seem to ever have flagellate come up in its spell recommendations.   It acts the same as if I were not specced into it. 

If you look at the priority list on wowhead: https://www.wowhead.com/guide/classes/rogue/subtlety/rotation-cooldowns-pve-dps , it is meant to be used early on in the opener, and then after that before finishing move --> shadow dance.

### How to Reproduce

1. Take flagellation on sub rogue.
2. Start dpsing. 

### Snapshot (Link)

https://pastebin.com/EfVGZ0Py

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/3F7oyMtPPoXvRAdnzwwid9

### Additional Information

This happens for both ST and AOE if specced into flagellation.  The above sim is for a single target flag build, on 1 target patchwerk.

Here is a sim for an aoe flag build, on 5 target patchwerk:  https://www.raidbots.com/simbot/report/q88WczAy3RgtWjbF1hicK1

And here is a sim the same aoe flag build, in dungeon slice:  https://www.raidbots.com/simbot/report/3F7oyMtPPoXvRAdnzwwid9

**Comment by Hekili** [comment]
Yes, of course, Flagellation should be recommended.

More likely than not -- I can't tell because your snapshot is not complete -- you have not yet [enabled the Cooldowns toggle](https://github.com/Hekili/hekili/wiki/Getting-Started#toggles--cooldowns-interrupts-potions-and-defensives).

If that's incorrect, see the below instructions for providing a complete snapshot.  Thanks!

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, **press CTRL+A to select all text including hidden text** and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by wheatbread** [comment]
*edit:

Aha!  After I posted that, I realized "minor CDs" are unchecked.  Checking it makes Flag display.  Thank you and sorry for the bother!

-----------------------------------------------

Hi,

Thank you for the reply!  I checked the options to make sure that cooldowns are showing in the main display, and that flag isn't disabled. 

![image](https://github.com/Hekili/hekili/assets/548824/5a61b503-1227-464a-a359-3f2d25a59082)

![image](https://github.com/Hekili/hekili/assets/548824/5f832288-540e-4ec3-912f-b68891b48289)

(I think these are all the options that can stop it from showing?  Unless there are some somewhere I'm missing.)


Sorry, I didn't realize it wasn't complete.  

Here is a new snapshot:  https://pastebin.com/ArDJwFRA

I froze it when I saw it recommending rupture without flag, while flag was available (pretty early on in fight).
