### ISSUE TITLE
Outlaw Rogue: Problem with vanish

### ISSUE THREAD

**Issue by MrWizard516** [Hekili/hekili#269]
When trying to do Visions while fighting Windrunner he uses vanish which in turn resets the fight every time. I don't know how to disable it from suggesting vanish.

**Comment by Hekili** [comment]
Vanish has a built-in requirement for you to be fighting a boss and in a group before it is recommended.

If you are seeing Vanish recommended while soloing a Vision, you should take a snapshot and submit the information along with your ticket.

Otherwise, you can go to /hekili > Abilities > Outlaw > Vanish and disable the ability with the checkbox there.

**Comment by MrWizard516** [comment]
Thanks for the fast response

**Comment by MrWizard516** [comment]
I tried doing what you said and ran into an issue. "/hekili > Abilities > Outlaw > Vanish" isn't there. there are only 2 options in the dropdown 
1. Hyper Organic Light Originator
2. Poisons

**Comment by Hekili** [comment]
Get BugSack/BugGrabber to see if there's an error report.
Make sure you're using the latest version.
/reloadui and check again.
