### ISSUE TITLE
Lava Lash is recommended without Flame shock.

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#2691]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Lava lash is recommended for use without Flame shock. I don't know what condition you have there. But to use Lava lash and after Flame shock. This is nonsense. And if you ao it's a loss of dps. I made a snapshot where the next recommendation was Lava lash and after Flame shock. Make a pre-check for Flame shock, if the target is not there then first use it, and after lava lash. But not vice versa no matter what would be the condition.

### How to Reproduce

Start the fight with 1 target.
Add another goal to the main goal.
There will be a recommendation to switch to the main one and use Lava lash through it.
Take the main target away from the new one, and it will still recommend switching to the main target with Lava lash.

### Snapshot (Link)

https://pastebin.com/UxP6cqpx

**Comment by Hekili** [comment]
Short answer:  The sim profile doesn't seem to expect you to switch to a target that doesn't have Flame Shock if you could've spread with Lava Lash first.  I'll go ahead and just the priority to apply Flame Shock if it's missing, so it won't assume you could swap to another FS'd target and spread from there.

Longer version:

> Lava lash is recommended for use without Flame shock. I don't know what condition you have there. 

The addon priority comes directly from SimulationCraft with minor adjustments related to what is known in-game vs. what is known to the sim.  You can review the priority directly in game, or look at the snapshot.

> Start the fight with 1 target.
> Add another goal to the main goal.

The snapshot has 6 targets, so this isn't the exact scenario you've described so far.

> There will be a recommendation to switch to the main one and use Lava lash through it.

The first recommendation in your snapshot is Windfury Totem.  The second is Lava Lash (entry 12 in the `aoe` action list).  It isn't a recommendation to swap to another target, as far as I can tell.  It's just using Lava Lash because you have Lashing Flames talented and nothing higher in priority had its conditions met:

```
42.  lava_lash ( aoe - 12 )
 - this entry's criteria PASSES: talent.lashing_flames.enabled[true]
Action chosen:  lava_lash at 1.00!
```

The sources of Flame Shock that were ruled out before that were Primordial Wave (still on CD for 8.44 seconds), then Flame Shock if you had no active Flame Shocks at all.

```
35.  flame_shock ( aoe - 5 )
 - this entry's criteria FAILS: ( talent.primordial_wave.enabled[true] | talent.fire_nova.enabled[false] ) & active_dot.flame_shock[2.00] = 0
```

This is where I'll go ahead and edit, because the sim can more safely assume you spread Flame Shock before swapping, but the addon needs to recovery from any weird behavior in-game.  So this should be in the next release.

**Comment by Hekili** [comment]
This will be addressed in the next release.
