### ISSUE TITLE
[REC] Havoc DH: Fel Rush and Vengeful Retreat are recommended even if disabled

### ISSUE THREAD

**Issue by SCP002** [Hekili/hekili#2696]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Fel Rush ("Рывок Скверны" in my localization) and Vengeful Retreat ("Коварное отступление" in my localization) are recommended even if checkboxes "Fel Rush: Filler and Movement" and "Vengeful Retreat: Filler and Movement" are unchecked (turned off) in settings. I expect these two abilities not to appear in the priority list with such settings.
![WoWScrnShot_070323_151555_edited](https://github.com/Hekili/hekili/assets/22541678/c4c87693-db13-4c72-bb1a-d7176a10ba79)

### How to Reproduce

1) Enter the game as havoc demon hunter.
2) Uncheck "Fel Rush: Filler and Movement" and "Vengeful Retreat: Filler and Movement" in settings (left mouse button on the minimap icon).
3) Click on "Vengeful Retreat: Fel Rush and Felblade" and set it to "Disabled (default)" in settings.
3) Attack target dummy with recommended spells until you see Fel Rush and/or Vengeful Retreat as recommended.

### Snapshot (Link)

https://pastebin.com/mgk86zpj

**Comment by Hekili** [comment]
Disabling the Fel Rush / Vengeful Retreat: Filler and Movement options means those abilities aren't used because (1) you have nothing else to push or (2) simply to charge because your target is out of range.  Using those abilities because of your talents is still enabled.

If you go to /hekili > Havoc and review the options:
![image](https://github.com/Hekili/hekili/assets/9438134/81105d35-a706-4e27-ae3d-2f07d3c20225)

![image](https://github.com/Hekili/hekili/assets/9438134/dae531fe-a7e4-492a-b0db-1ee05b4bf36d)

You can check out a "No Movement" build for Havoc if you don't want those to be recommended.  Otherwise, you're wasting talent points.
