### ISSUE TITLE
Can’t get option panel

### ISSUE THREAD

**Issue by chaston7** [Hekili/hekili#272]
The 4 auras are on bottom, but options are not coming up and not showing on interface like last one. Can’t change anything

**Comment by Hekili** [comment]
Gonna need you to get BugSack/BugGrabber and see if you're getting errors.  I can't tell anything about your situation from this ticket.  No addon version, no class/spec info, etc.

**Comment by chaston7** [comment]
Well it’s bm hunter and I just updated it today. The version I have from Jan 17 worked fine

**Comment by Hekili** [comment]
What did BugSack and BugGrabber show?

**Comment by chaston7** [comment]
Don’t have that.Nvm I’ll just stick with old one and find up to date imprints or something

**Comment by Hekili** [comment]
Lol

**Comment by chaston7** [comment]
Don’t find it funny but okk

**Comment by Hekili** [comment]
Why wouldn't you just get BugSack and BugGrabber so that I can know what's happening and fix it?

**Comment by chaston7** [comment]
Well the 4 auras are there for my rotation I just can’t get to options to change anything. The last version I could. I put the old one back. The options are right there on my interface addon and the little toggle on my map to change to auto, aoe, single, etc. I erased and reloaded today’s version 3 times, with same results. Thought maybe someone else had run into this problem

**Comment by Hekili** [comment]
You're the first to report it, but others are likely having the same issue. But I can't reproduce it (yet?) on my end.  So we're back to needing the error info from BugSack/BugGrabber.

**Comment by chaston7** [comment]
ok let look up how to use them and I’ll go download em

**Comment by Hekili** [comment]
So, yeah, downloading BugSack and BugGrabber is pretty straightforward.  They're on Curse/Twitch.

Make sure they're enabled.

Go into the game, type /hekili to open options.

You should have a minimap icon for bugsack that will contain any error messages.  Post the first error message (if there are multiple, click the left arrow until you reach the first).  Or post all of them.

Also, make sure you downloaded v8.3.0-04-04 since that's the latest version.
