### ISSUE TITLE
The Flame Mage cycle is very poor, it should be redone!

### ISSUE THREAD

**Issue by ZHarmy** [Hekili/hekili#2766]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

HEKILI's current 10.15 Flame Mage cycle is based on version 9+! Many items and skills are still the same as before and have not been thoroughly updated like Ice Method, so the cycle performance is very poor.

1. During combustion, Phoenix and Flame Shock resources are not fully consumed, and excessive reading of Burning and Fireball spells is required (Phoenix and Flame Shock should be consumed as much as possible)

2. After combustion is ready, hot combo, no use! Accidental non-stop reading of Burning and Fireball spells (perhaps a bug)

3. The Sun King should not read when resources are not exhausted during combustion

4. This loop currently does not correctly read the level of the Phoenix, does not calculate T30 and Phoenix returns for talents, and does not consume Phoenix reasonably

5. Mutation magic, this skill should be used after resource depletion during combustion, not unused

Overall! The entire cycle should be overturned and redone, it's very real garbage

### How to Reproduce

false

### Snapshot (Link)

false

### Raidbots Sim Report (Link)

false

### Additional Information

false

### Contact Information

494858224@qq.com

**Comment by Hekili** [comment]
Sorry, you'll have to fill out a ticket correctly and provide snapshots if you want to 

> HEKILI's current 10.15 Flame Mage cycle is based on version 9+!

What makes you think this?

> During combustion, Phoenix and Flame Shock resources are not fully consumed, and excessive reading of Burning and Fireball spells is required (Phoenix and Flame Shock should be consumed as much as possible)

You'd need to include a snapshot of "Burning" (?) or Fireball being recommended during Combustion when you think they shouldn't be recommended.

> After combustion is ready, hot combo, no use! Accidental non-stop reading of Burning and Fireball spells (perhaps a bug)

You'd need to provide a snapshot where this is actually happening.

> The Sun King should not read when resources are not exhausted during combustion

I do not understand what you mean.

> This loop currently does not correctly read the level of the Phoenix, does not calculate T30 and Phoenix returns for talents, and does not consume Phoenix reasonably

Snapshot?  What makes you think this is true?  What does "level of the Phoenix" mean?  What makes you think it is not aware of T30?

> Mutation magic, this skill should be used after resource depletion during combustion, not unused

I don't know what you're referring to, here.  Evocation, maybe?  Mana Gem?  You may want to link Wowhead spells instead of translating spells because I can't tell what you mean.

For reference, I'll include the instructions re: snapshots again:

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by ZHarmy** [comment]
1，Frost Mage Cycle Compared to Flame Mage Cycle! There aren't as many 9.+versions of equipment, accessories, and skills available
2，During the combustion, I stared closely at the Phoenix and Flame Impact! At present, both of these skills can be used 3 times, and the combustion and explosion process requires consuming these resources as much as possible, with little need for interspersed reading of Burning and Fireball spells
3，There is no need to read the Sun King during combustion, and it is inappropriate to read the reading bar at this time
4，The combustion is ready， With the 'Hot Strike' BUFF! Occasional reading burn and fireball surgery
5，Phoenix has 3 times now! The 'combination' will be left twice, and the 'combination' will end and be consumed again, which is unreasonable
6，Mutated hallucinogenic energy == ID：382440
These are a series of errors! No evidence is needed. I don't have much time to help with the repair. You can ask others if it's true. Thank you very much for your work

**Comment by hellovvorld1024** [comment]
Fix #2760 is worse than before.
When the combustion buff exists, SKB's Pyroblast will recommend.
and Scorch will recommend maybe Phoenix has ballistic problems during flight.
I know this kind of feedback non help to u. I'll provide some snapshots later.

**Comment by hellovvorld1024** [comment]
1. When the combustion buff on, Scorch will recommend.
https://pastebin.com/h2MiUXWL
![1](https://github.com/Hekili/hekili/assets/132650401/0554aa04-8443-4a01-8d21-580a98cef316)


2. When the combustion buff on, SKB's Pyroblast will recommend.
https://pastebin.com/bycjrEQt
I don't know why the second snapshot didn't take a screenshot.
The actual situation is that just cast combustion, and SKB is on. Immediately recommend casting Pyroblast.

3.  When recommending fireball or burning, Phoenix Flames recommendation priority is still low, and often reserved 2 stacks. The screenshot above can reflect report.

Maybe my snapshots laggy. I should take it when it's recommended instead casting the current spell.

**Comment by ZHarmy** [comment]
Actually, I really want to know who the Flame Mage is maintaining! The recent updates to this loop in several versions of HEKILI do not seem to be in the author's style, which is very negative

**Comment by hellovvorld1024** [comment]
> Actually, I really want to know who the Flame Mage is maintaining! The recent updates to this loop in several versions of HEKILI do not seem to be in the author's style, which is very negative

Please report problems instead of complaining, If you want the problem to be resolved quickly. :)

**Comment by Hekili** [comment]
@hellovvorld1024:

> When the combustion buff on, SKB's Pyroblast will recommend.
> https://pastebin.com/bycjrEQt
> I don't know why the second snapshot didn't take a screenshot.

I limited the addon to take only one screenshot per reload; it's really meant to keep auto-snapshots from going crazy, so I'll change it to only apply to auto-snapshots.

> The actual situation is that just cast combustion, and SKB is on. Immediately recommend casting Pyroblast.

In that snapshot, you're in the process of casting Flamestrike and the next recommendation is Fire Blast.  There's no Pyroblast recommendation shown:

`Fire; Primary - Fire Blast(1.48), Flamestrike(1.48), Fire Blast(1.98), Fire Blast(2.58), Flamestrike(2.64), Phoenix Flames(3.80), Scorch(4.96), Flamestrike(6.12), Scorch(7.28), Shifting Power(8.44)`

> Maybe my snapshots laggy. I should take it when it's recommended instead casting the current spell.

Yes, you should snapshot the recommendation you disagree with as it's displayed.  I know it can be tricky.

> When recommending fireball or burning, Phoenix Flames recommendation priority is still low, and often reserved 2 stacks. The screenshot above can reflect report.

Phoenix Flames was *almost* the first recommendation, but it was waiting for the duration of Charring Embers to fall under 4 GCDs:

```
This entry's criteria FAILS: set_bonus.tier30_2pc[1.00] & ! action.phoenix_flames.in_flight[false] & debuff.charring_embers.remains[4.89] < 4 * gcd.max[1.16] & ! buff.hot_streak.react[0.00]
Recheck #1 ( +0.27 ) MET: set_bonus.tier30_2pc[1.00] & ! action.phoenix_flames.in_flight[false] & debuff.charring_embers.remains[4.63] < 4 * gcd.max[1.16] & ! buff.hot_streak.react[0.00]
Action chosen:  phoenix_flames at 0.27!
```

Instead, Fire Blast is ready immediately and doesn't care about Charring Embers.  Then, other abilities took priority until 3.8 seconds in.

@ZHarmy:  If you don't supply the snapshots, I have nothing to investigate for you.

> 1，Frost Mage Cycle Compared to Flame Mage Cycle! There aren't as many 9.+versions of equipment, accessories, and skills available

This has no impact; leaving old items in is helpful to folks who are leveling and does not impact max level characters at all.  Fire Mage APL has been synced and updated from SimC about a dozen times in Dragonflight.
- https://github.com/Hekili/hekili/commits/dragonflight/Dragonflight/APLs/MageFire.simc

> 2，During the combustion, I stared closely at the Phoenix and Flame Impact! At present, both of these skills can be used 3 times, and the combustion and explosion process requires consuming these resources as much as possible, with little need for interspersed reading of Burning and Fireball spells

I don't know what Burning spell is (Scorch?).  Phoenix Flames can be delayed waiting for Charring Embers duration to drop.

> 3，There is no need to read the Sun King during combustion, and it is inappropriate to read the reading bar at this time

I have no idea what "read the Sun King during combustion" means.

> 4，The combustion is ready， With the 'Hot Strike' BUFF! Occasional reading burn and fireball surgery

What do you see?  What do you think should be different?  Use Wowhead links to spells so that the names match.

> 5，Phoenix has 3 times now! The 'combination' will be left twice, and the 'combination' will end and be consumed again, which is unreasonable

Snapshot during Combustion when you think Phoenix Flames should be recommended but it isn't.

> 6，Mutated hallucinogenic energy == ID：382440

So, Shifting Power.  Assuming your Major and Minor Cooldowns are active, Cooldowns toggle is active, there's no reason I can see why it wouldn't be recommended.  Without your snapshot, I have no way of seeing if you have a configuration issue or are using your toggles.

> No evidence is needed. I don't have much time to help with the repair.

Don't respond without providing the required snapshots/data, otherwise you will be wasting both your time and mine.  Thanks!

**Comment by hellovvorld1024** [comment]
https://pastebin.com/JLmeRmgp
![2](https://github.com/Hekili/hekili/assets/132650401/b1c0df81-e169-4788-b403-ddd1f9289ce3)

Details Streamer reflects the history of spells I've casted in rotation exactly as recommended.
As you can see in the screenshot. Combustion and Heating up buffs are on. and Phoenix Flames having 2 charges.
Scroch recommended 4 times in the queue to get Hot Streak,  Before and More than Phoenix Flames.



And...
![4](https://github.com/Hekili/hekili/assets/132650401/aab15a5c-5cfd-4cbe-af84-14c6a73b1d1f)
A lot of Scroch will be recommended in various situations. Forgive me for not save a snapshot data for this screenshot.

**Comment by hellovvorld1024** [comment]
https://pastebin.com/zjZ3z5UT
![3](https://github.com/Hekili/hekili/assets/132650401/45a3b0b0-d41f-4406-bf98-4c0c09c2f5e4)

When the Combustion Buff still have 6 seconds left, and SKB buff is max and have 27 seconds left.
recommend casting Flamestrike to activate SKB.

**Comment by Hekili** [comment]
@hellovvorld1024 -- Could you run a Patchwerk 5-target sim on Raidbots and provide the link for comparison?

> https://pastebin.com/JLmeRmgp

```
53.  phoenix_flames ( combustion_phase - 7 )
 - this entry's criteria FAILS: set_bonus.tier30_2pc[1.00] & ! action.phoenix_flames.in_flight[false] & debuff.charring_embers.remains[6.98] < 4 * gcd.max[1.05] & ! buff.hot_streak.react[0.00]
Recheck #1 ( +2.89 ) MET: set_bonus.tier30_2pc[1.00] & ! action.phoenix_flames.in_flight[false] & debuff.charring_embers.remains[4.21] < 4 * gcd.max[1.05] & ! buff.hot_streak.react[0.00]
Action chosen:  phoenix_flames at 2.89!
```

This entry for Phoenix Flames would've been used in 2.89 seconds, when Charring Embers remaining duration falls under 4 GCDs.

```
74.  phoenix_flames ( combustion_phase - 24 )
 - this entry's criteria FAILS: set_bonus.tier30_2pc[1.00] & travel_time[0.30] < buff.combustion.remains[8.32] & buff.heating_up.react[1.00] + hot_streak_spells_in_flight[0.00] < 2 & ( debuff.charring_embers.remains[6.98] < 2 * gcd.max[1.05] | buff.flames_fury.up[false] )
```

This entry would've been recommended if Flames Fury were active -or- Charring Embers had fewer than 2 GCDs remaining.

```
76.  phoenix_flames ( combustion_phase - 26 )
 - this entry's criteria FAILS: ! set_bonus.tier30_2pc[1.00] & ! talent.alexstraszas_fury.enabled[true] & travel_time[0.30] < buff.combustion.remains[8.32] & buff.heating_up.react[1.00] + hot_streak_spells_in_flight[0.00] < 2
```

This entry is ruled out because you have Tier 30 2pc.

This seems to match the default sim that's shared on the [SimulationCraft](https://simulationcraft.org/reports/T30_Raid.html) site, which only uses Phoenix Flames 4 times in the first Combustion (30 seconds).  It does look like I can increase DPS a tiny bit in sims if I make it also use Phoenix Flames in `combustion_phase - 24` if it's about to cap on charges.

Default: 
![image](https://github.com/Hekili/hekili/assets/9438134/4c4faa1b-b609-4869-8867-d5b2e5c3703a)

Modified:  
![image](https://github.com/Hekili/hekili/assets/9438134/598cd0c0-4cbe-4ea6-b507-825d3a0388a0)

Scorch is the next entry tested and is ready to go when the GCD is up.

**Comment by Hekili** [comment]
> https://pastebin.com/zjZ3z5UT

```
71.  flamestrike ( combustion_phase - 21 )
 - this entry's criteria PASSES: buff.fury_of_the_sun_king.up[true] & buff.fury_of_the_sun_king.remains[26.66] > cast_time[1.93] & active_enemies[5.00] >= variable.skb_flamestrike[3.00] & buff.fury_of_the_sun_king.expiration_delay_remains[0.00] = 0
```

The entry for Flamestrike that was selected is specifically included in the `combustion_phase` priority and appears rightfully recommended with 3+ targets.

**Comment by hellovvorld1024** [comment]
Thanks for the test. From your analysis I conclude that it's not scroch recommends too much, but phoenix flames recommends less to recommend scroch get the Hot Streak even phoenix flames are available in Combustion buff.

I really didn't do simc analysis, but based on my experience with more than 3 targets in the M+ environment, I think the queue of AOE under active cast Combustion should be like this:
1. phoenix flames
2. meteor
3. scorch
4. combustion in casting scorch
5. fire blast in casting scorch
6. flamestrike
7. flamestrike      (When combustion buff and Heating up are on, casting scroch and then cast fire blast, get Hot Streak in casting. cast Pyroblast/Flamestrike during the remaining time. Explosion, can get two Pyroblast/Flamestrike.)
8. fire blast
9. flamestrike
10. fire blast
11. flamestrike
12. phoenix flames
13. flamestrike
14. fire blast
15. flamestrike
16. phoenix flames
17. flamestrike
18. fire blast
19. flamestrike

In the case of active cast combustion:
1. Priority guarantee not to lose Feel the Burn buff and Tier 30 2pc Buff;
2. Phoenix Flames at Tier 30 4pc Buff replace Fireball / Scorch;
3. Phoenix Flames is about to cap on charges to replace Fireball / Scorch;
4. Phoenix Flames refresh Tier 30 2pc debuff time in target at SKB buff 6 or 7 stacks, if target's Tier 30 2pc debuff time less than Pyroblast/Flamestrike cast time + (8- 6 or 7 + 1) * gcd.max.
5. Phoenix Flames and Scorch to get Hot Streak when Fire Blasts are not available and Combustion buff on ( maybe );





I try to understand snapshot here:
```
76. phoenix_flames ( combustion_phase - 26 )
  - this entry's criteria FAILS: ! set_bonus.tier30_2pc[1.00] & ! talent.alexstraszas_fury.enabled[true] & travel_time[0.30] < buff.combustion.remains[8.32] & buff.heating_up.react[1.00] + hot_streak_spells_ in_flight[0.00 ] < 2
```

and where remarks like this in simc:
```
phoenix_flames,if=!set_bonus.tier30_2pc&!talent.alexstraszas_fury&travel_time<buff.combustion.remains&buff.heating_up.react+hot_streak_spells_in_flight<2
Use Phoenix Flames and Scorch in Combustion to help generate Hot Streaks when Fire Blasts are not available or need to be conserved.
```

FAILS HERE because I‘ve T30_2pc. and I don't know why  `!talent.alexstraszas_fury` here, no matter whether this talent enabled or not, it will always crit when combustion buff on.

THEN 77. scorch ( combustion_phase - 27 )   PASSED.

After deleted the part: `!set_bonus.tier30_2pc&!talent.alexstraszas_fury`
I got roughly what I expected.

The new question is after cast Fire Blasts when Heating up buff on, would immediately recommend Phoenix Flames. Is there any way to prevent this?

I uncommented fire_blast in hot_streak_spells.

Adding ballistic judgment has no effect,
Because Fire Blasts has no gcd, I will recommend the next spell immediately. I judge Fire Blasts before and after in my addon. If I currently have Heating up buff and recommend Phoenix Flames, I will add a delay of 0.6s to Fire Blasts before and after.


I simulated the situation before and after the modification in raidbot. In a 5-minute battle, whether it is aoe or single, there will be about 2% damage attenuation.


But in the case of the actual aoe 5 stakes, the peak damage during my active Combustion period has increased from 220k to 280k, and the SKB is ahead of Mutated

My suggestion is for `phoenix_flames, if=!set_bonus.tier30_2pc&!talent.alexstraszas_fury&travel_time<buff.combustion.remains&buff.heating_up.react+hot_streak_spells_in_flight<2`
Add a config:  `((!set_bonus.tier30_2pc&!talent.alexstraszas_fury) | (active_enemy > 1 & config.phoenix_flames) ) & ...`

**Comment by hellovvorld1024** [comment]
May I ask how to add Scroch before Combustion when Combustion is available and no Heating up and Hot Streak buffs,
and then in casting scorch to cast Combustion trigger subsequent double flamestrike?

Thanks.

**Comment by hellovvorld1024** [comment]
NEW PROBLEM   https://pastebin.com/9zBCaUCE

I remember it seemed to happened before.
Always recommend Fireball and not Pyroblast when Hot Streak Buff on.

**Comment by Hekili** [comment]
> NEW PROBLEM https://pastebin.com/9zBCaUCE

I don't know; it doesn't look like that's the default priority.

```
Fire abc (Custom: MageFire[63]); Primary - fireball(0.00)
```

**Comment by ZHarmy** [comment]
1014 Flame Mage doesn't seem to have any improvement, it's still a lump of shit! During the 'combustion' period, there was still a large amount of reading 'fireball' and 'scorch', 'phoenix' still causes waste. Removing this loop is the correct choice

**Comment by ZHarmy** [comment]
1014 Flame Mage doesn't seem to have any improvement, it's still a lump of shit! During the 'combustion' period, there was still a large amount of reading 'fireball' and 'scorch', 'phoenix' still causes waste.

**Comment by Hekili** [comment]
@ZHarmy Normally, I'd advise you to take a snapshot of the recommendation you disagree with, so that I can review how that recommendation was generated, but I'd rather you not post here any more.
