### ISSUE TITLE
Show next priority spell only until the current spell channel has finished  example: fist of fury

### ISSUE THREAD

**Issue by krispykos** [Hekili/hekili#2776]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

not sure if this is a current feature or something I can input in conditions but the logic I put in doesn't work and here's basically what I would like just simply not to show the next priority until the current spell has finished channeling example Fist of Fury for monk

if not IsCurrentSpell("Fist of Fury") and not IsCasting() then
    if GetTimeToFinishCasting() <= X then
        -- Suggest the next spell (conditional here)
    end
end

**Comment by marekCs** [comment]
I think if Hekili shows you "use another spell now" even while channeling the previous spell, it means just break channeling and do it. How is that possible, why wouldn't you finish channeling? Probably because the algorithm has calculated that finishing the entire channeling is no longer worthwhile if it has charged up another combo or spell that will give a better result in the overall fight.

**Comment by krispykos** [comment]
you are probably right, however, I'd like certain spells to just finish channeling in a scenario, let's say it melee enemies and you're talented into turbo fist for pvp this parries all attacks you wouldn't want to break it

**Comment by Hekili** [comment]
These interrupted channels are specifically written into the Windwalker priority; the solution would be to write a custom priority that doesn't break the channels (and to take the associated DPS loss).
