### ISSUE TITLE
[REC] WOTLK Feral Druid Rotation suggesting Shred when not properly positioned

### ISSUE THREAD

**Issue by bobkat2000** [Hekili/hekili#2778]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The Feral DPS rotation is recommending Shred during while attacking from the front... Shred can only be performed while behind the target which is usually a pre-attack (stealth) move, or while in a group (I'm solo, PVE).  The rotation ends up just filling with Shred, making it unusable.

### How to Reproduce

1. Use regular rotation to attack any regular NPC.
2. I can cast Faerie Fire (Feral), then Mangle (Cat), and then it recommends Shred, which can't be performed.
3. Try other attacks like Rake to see if it changes/updates the rotation, but does not.

### Snapshot (Link)

https://pastebin.com/uJGKvJbR

### Contact Information

Bobkat#1333

**Comment by Supernuss** [comment]
That is not an issue - the apl is designed for optimized damage, playing solo and using mangle is not optimized.
If one would add this "feature" of checking your positioning, hekili would start recommending mangle when a boss turns to you for a second (like jaraxxus when casting his Fel Lightning) - but this is not what you'd want. Just save your energy until he turns back to the tank.

If you want to be suggested mangle while playing solo, you could copy the Prio-List and switch the line for shred with mangle.
Or as most people probably do: just press mangle instead of shred when hekili recommend shred - there's no need to change anything.

**Comment by Hekili** [comment]
Yeah, there's no API that the addon can use to know that you're not in position to Shred, and the standing philosophy here is that telling you the ideal button to push is also telling you to get into position to use it.

> The rotation ends up just filling with Shred, making it unusable.

When it says Shred but you can't, the obvious alternative is to Mangle.

> If you want to be suggested mangle while playing solo, you could copy the Prio-List and switch the line for shred with mangle.

I previously had functionality that would detect a failed Shred and stop recommending Shred from then forward, until you do your own Shred, but it felt too misleading.  I'll think a little bit about this, but maybe there's room to tweak the priority such that, when solo, Shred will only be recommended from Prowl or if your target is Gouged or Stunned.  Maybe.
