### ISSUE TITLE
Rogue always recommending poisons for aoe, also doesn't recommend Secret Technique

### ISSUE THREAD

**Issue by pete543** [Hekili/hekili#2785]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my subtlety rogue, it always recommends "atrophic poison". I have to turn off aoe in spellflash. Also, I have Secret Technique in my talents, but it doesn't recommend that either.

### How to Reproduce

Sub rogue, spellflash, have secret technique and poisons

### Snapshot (Link)

https://pastebin.com/XD6phraf

**Comment by Hekili** [comment]
> For my subtlety rogue, it always recommends "atrophic poison".

Your snapshot doesn't reflect this.  If you have a main poison applied, it'll accept what you provided.  If you're talented for Atrophic, why would you not use it?

> I have to turn off aoe in spellflash.

Why?  Please describe what you see (take screenshots even), rather than how you've tried to work around it.

You don't really need to use Dual display mode (showing AOE) as melee.  The addon will automatically adjust to the number of targets nearby in Auto mode.

> Also, I have Secret Technique in my talents, but it doesn't recommend that either.

Take a snapshot *at the time you think Secret Technique should be recommended, but isn't.*  The snapshot you provided recommended Symbols of Death(0.00), Shadowstrike(0.00), Eviscerate(1.00) in the AOE display.  

Secret Technique, generally speaking, is recommended during Shadow Dance, with 3 stacks of Danse Macabre (since you're talented for it), and with Premeditation down /  or not 2 targets, plus with Cold Blood active / on CD / or untalented.

**Comment by Hekili** [comment]
(You probably want to toggle Cooldowns on as well.)

**Comment by Hekili** [comment]
(Also, update to the latest version.)
