### ISSUE TITLE
Hekili no longer prioritizes Death Coil durring the Gargoyle window for the Unholy DK rotation

### ISSUE THREAD

**Issue by ructus** [Hekili/hekili#2799]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

After the 9/12/2023 update to v10.1.17-1.0.1, game version 10.1.7, Hekili no longer prioritizes Death Coil durring the Gargoyle window in the Unholy DK rotation. 

### How to Reproduce

1. Enter the game as an unholy DK
2. Uee the standard single target raid build https://www.wowhead.com/ptr-2/talent-calc/death-knight/unholy/DAPUVBEBSEVBEFEhqRAOVUhAVAmQFFWEkQBQ
3. Use standard opener: 
 Army/Potion
 Outbreak
 FS
 Death and Decay
 DT+Garg
 DC 
 DC 
 DC 
 UA+ERW + Mirror of Fractured Tomorrows (Assuming mastery)
 Apoc
(Helkili should prioritize Death Coil in the rotation while summon gargoyle is active after this)

### Snapshot (Link)

https://pastebin.com/uFwxykMH

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/j9SM7N74VTUxkXCL22FMwb

### Additional Information

This priority worked correctly prior to the latest update to v10.1.17-1.0.1. 

### Contact Information

anuvik

**Comment by Hekili** [comment]
In the snapshot provided, Dark Transformation's remaining cooldown is 8.69 seconds, so it seems like this is after the Gargoyle has expired.

```
47.  dark_transformation ( cooldowns - 3 )
The action is not ready ( 8.69 ) before our maximum delay window ( 5.22 ) for this query.
```

```
19.  death_coil ( high_priority - 3 )
The action (death_coil) is usable at (0.00 + 0.00) with cost of 30 runic_power (have 37).
...
- this entry's criteria FAILS: ( active_enemies[1.00] <= 3 | ! talent.epidemic.enabled[false] ) & ( pet.gargoyle.active[false] & talent.commander_of_the_dead.enabled[true] & buff.commander_of_the_dead.up[false] & cooldown.apocalypse.remains[12.91] < 5 & buff.commander_of_the_dead.remains[0.00] > 27 | debuff.death_rot.up[true] & debuff.death_rot.remains[6.40] < gcd.max[1.18] )
```

Can you provide a snapshot where your Gargoyle is still active?

**Comment by ructus** [comment]
See if this is better. 

https://pastebin.com/pPfZvEEt

**Comment by Hekili** [comment]
In this snapshot, it's recommending Death Coil.

**Comment by Breadwinka** [comment]
1.https://pastebin.com/9immYNgv
2.https://pastebin.com/CPx8rkjZ
3.https://pastebin.com/ggfRyJdE

**Comment by Tummieqt** [comment]
I will try to get a snapshot of this to assist fault finding, but I came here specifically looking if anybody else was having this issue the last two resets. Guild raid is done for the week so I will try to PUG/LFR as it seems to act as expected when I try to force the behaviour on a target dummy.

However, in raid during Gargoyle windows it isn't prioritising Death Coil. Prior to 12/13 Sep reset it was recommending Death Coil as expected upon a Sudden Death proc, immediately after an ability that would put you over 30 Runic Power (RP) or after hitting 30 RP through damage converted from AMS/AMZ. However during my raid 1930-2230 AEST on 14 and 21 Sep it was constantly pooling to 100 RP or sitting on Sudden Death procs and still insisting on clawing shadows rather than Death Coil to juice up Gargoyle. 

Outside of Gargoyle windows seems to be recommending as expected.

**Comment by Tummieqt** [comment]
https://pastebin.com/qNW7aMyZ

Think I got this one right. If I took this at the right time it was suggesting Clawing Shadows when sitting on 80RP followed by DC DC maybe a DnD in there while Gargoyle still had 15-16 seconds duration remaining. 

I tried this again 3 times on the target dummy and I am getting similar results. It just is no longer prioritising DC during gargoyle window and seems to be looking to cast Clawing Shadows because of runes or wounds available to pop. There were occasions where it suggested 2-3 Clawing Shadows in a row during Gargoyle window, but I was too slow on the pause/snapshot keybinds.
