### ISSUE TITLE
Feral - possible fine-tuning

### ISSUE THREAD

**Issue by PaigePB** [Hekili/hekili#281]
I've noticed when simming with Raidbot or looking at wow analyser that there are some differences between what is suggested and what I'm doing with hekili both for single and multi-target.

1. single - wow analyzer is suggesting that I use thrash more before Brutal slash in order to take more advantage of wild fleshrenderings (azerite trait).

2. multi - raidbot sims seem to indicate that most of my damage in multi-target should be coming from brutal slash, however even with consistently many targets 30% of my damage is coming from rip rather than brutal slash (10%).

So I'm curious about the difference. That said, Hekili is amazing and I greatly appreciate the ability to use it. :D

**Comment by Hekili** [comment]
These are good questions.

For pt. 1, historically it hasn't actually simmed better to stress about that, but doing a quick sim test now, it looks like it's probably worthwhile (well, 0.3% DPS worthwhile).  I'll look at refining that.

For pt. 2, do you have a relevant log?  Which fight type are you using to test multi-target?  Do you get a different result if you change the Brutal Slash charges option in your spec options?

**Comment by PaigePB** [comment]
Thank you. For the second, I was comparing details to a sim but I didn't capture the details. I'll see if next week I can get the actual logs for the fight - it was heroic hivemind.

**Comment by PaigePB** [comment]
Hi, I was not able to get good logs on hivemind this week. I'll try again next week. Also hivemind alternates between waves of adds and single-target/cleave so as I pondered I wondered if that could be the cause of the discrepancy. So I went to the multi-target dummies (three small ones together) in Boralas and followed the multi-target prompts from hekili for 4.5 min. (disclaimer: I stayed focused on the middle target, when hekili gave me a 3 on swipe, I didn't try to switch (I don't have that switch mechanism down yet - however I would think if I did switch it would increase swipe not lessen it?).

![image](https://user-images.githubusercontent.com/30805995/75022300-d62d2600-5463-11ea-92a9-f8bc7fc429c0.png)

This is what details is saying is my damage.

This is RaidBots quick sim for dungeon slice (not sure if you have access to the url but here it is)
https://www.raidbots.com/simbot/report/dDAR2suRN9784n8pjUiwDv

![image](https://user-images.githubusercontent.com/30805995/75022481-286e4700-5464-11ea-83fb-8938b603e927.png)

Thoughts? Is the discrepancy because I didn't switch targets when prompted for Swipe?  If there's another way I can generate more log details, please let me know.

Maybe there's another test that I can do that's closer to dungeon slice?

**Comment by Hekili** [comment]
You're comparing a few things that are different.

You're looking at DPS in Details vs. Damage in RaidBots; you'd expect the damage proportion to be similar but it still muddles the data.  Your sim is a 6 minute fight while your Details is 4.5 minutes.  3 dummies is more equivalent to a 3-boss Patchwerk than a DungeonSlice sim.  DungeonSlice gives you a boss enemy for an average of 2 minutes, 20 seconds, 5 small adds every 45 seconds on average (after the first 140 seconds), and 2 big adds every 30 seconds on average after the first 155 seconds.  

In DungeonSlice, those 5 small adds are going to get you a lot more damage out of Primal Wrath.

The "3" on Swipe is not telling you to swap targets, it's just showing you how many targets were detected.  Recommending target swaps is something you'd have to enable in your spec options, and it's indicated by a circle with a triangle that points to the right, not a number.  And it still wouldn't apply to Swipe, as you don't target swap for Swipe.  You'd potentially target swap for Ferocious Bite (to refresh a low-duration Rip with Sabertooth) or Rip (without Primal Wrath) or Rake (with multiple targets that'd survive long enough to bother).

The instructions in a new ticket explain how to get a snapshot when there's a particular recommendation from the addon that you don't agree with.  I'd really need you to provide that information to investigate further.

To compare to in-game performance, it'd be more useful to post your log to WarcraftLogs and link it.  Maybe use WoW Analyzer or another similar tool to see what it calls out.  I can't think of a fight right now that is comparable to your 3 dummy test, so I can't even use my own raid logs for comparison.

**Comment by Hekili** [comment]
After more digging, if I account for a few differences:

Encounter:  Patchwerk, 3 targets.
Sim Length:  4 minutes.
I removed the target swaps (`target_if`) since you don't do target swaps.

I *didn't* remove Bloodlust or raid buffs, mainly because I didn't remember how to manually do that in RaidBots:Advanced off the top of my head.

https://www.raidbots.com/simbot/report/qEZmScVCegZQmqax86H6kT

![image](https://user-images.githubusercontent.com/9438134/75042740-ea394d80-548c-11ea-9200-0b074221481c.png)

Now, looking at the sample actions from the sim:

![image](https://user-images.githubusercontent.com/9438134/75042837-0d63fd00-548d-11ea-9f31-a951a528ec66.png)

You can see that we're doing the opener Rip in SimC and then overwriting it via Primal Wrath about 5 seconds later.  The addon actually uses Primal Wrath in multi-target during the opener to avoid this.

Anyway, in SimC/RaidBots, it's attributing 1.3 million damage to that single cast of Rip with actual seconds of uptime.  So that's *probably* an error and you can probably go ahead and roll that damage into Primal Wrath instead of Rip.

That takes us from Swipe and Primal Wrath damage being roughly equal in this sim to Primal Wrath accounting for 29.5% of your damage, or 30% more damage than Swipe.

That gets us closer to your test case in Details, which has PW+Rip doing about 20% more than Swipe alone.

The remaining difference could easily come from the raid buffs, Bloodlust, user error, bad luck, and variance.

Here's a comparison of target swaps vs. not target swapping, for reference:

![image](https://user-images.githubusercontent.com/9438134/75043594-59637180-548e-11ea-8679-50b8376ba1b5.png)

You lose 3K DPS overall but have +3K DPS to your priority target (i.e., the real boss) which is more relevant to actual fights in Ny'alotha.  The practical difference of multidotting Rake and trying to use Sabertooth to extend adds' Rips in your build is probably not worth it in most real cases (especially since you took Primal Wrath).

**Comment by PaigePB** [comment]
This is *very* nice. Thank you for the effort and the detail explaining. I appreciate the work.

**Comment by PaigePB** [comment]
And thank you for creating and maintaining such an amazing addon.
