### ISSUE TITLE
Outlaw Rogues. It always recommends Ambush constantly.

### ISSUE THREAD

**Issue by Jarloren** [Hekili/hekili#2815]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

It is constantly recommending ambush even outside of stealth. However if I disable ambush then it won't recommend it while I am in stealth. Its messing with my rotation and is making me try to use Ambush and in reality I'm using dispatch with like 2 combo points, thus wasting resources.

### How to Reproduce

![WoWScrnShot_100323_221024](https://github.com/Hekili/hekili/assets/146903215/e0cf7d94-b51e-4808-a92a-d55650c7ed58)

Use those talents and just start hitting a dummy. Exhaust all of your methods to enter stealth in combat and it will still recommend Ambush. Its causing me to waste Combo points on horrible dispatches.

### Snapshot (Link)

Outlaw; Primary - Ambush(0.00), Pistol Shot(1.00), Dispatch(2.00)

### Contact Information

tristencathcart@gmail.com

**Comment by syrifgit** [comment]
Looks correct to me. Literally line one of the class guide says to use Ambush when its available.

https://www.icy-veins.com/wow/outlaw-rogue-pve-dps-rotation-cooldowns-abilities

Wowhead guide also agrees, it is your best builder: 

https://www.wowhead.com/guide/classes/rogue/outlaw/rotation-cooldowns-pve-dps

Look at this talent which you've taken: https://www.wowhead.com/spell=381845/audacity

Also the snapshot is not correct.

**Comment by chevyn11** [comment]
Yeah, have a read what the talent "Audacity" does in your talent tree, its basically a proc that allows usage of ambush outside of stealth. 

I think your problem stems from you not having Ambush on your non-stealth bar. You'll need it if you're playing with that talent. An audacity proc doesn't count as you being in stealth (so it doesn't switch bars / stance if you're using stance macros).

> and in reality I'm using dispatch with like 2 combo points, thus wasting resources.

Not sure what this has to do with hekili, sounds like it was your decision to dispatch at 2cp instead of building with ss or ps or something :stuck_out_tongue_closed_eyes:

**Comment by Hekili** [comment]
The guidance from other users is correct; you can Ambush outside of Stealth depending on talents/procs and you'll want to arrange your bars such that you can do so.
