### ISSUE TITLE
[FEATURE] Consider extra window for precombat spells

### ISSUE THREAD

**Issue by marekCs** [Hekili/hekili#2837]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Dear Hekili,
I'm reaching out to suggest a feature that could further improve the addon - an additional icon window for precombat scenarios.
Currently, Hekili provides ST and AoE modes (or just Primary), along with a distinct window for interrupts or defensive spells. However, there's no dedicated window for precombat actions. In classes like Arcane Mage, precombat setup is quite intricate. If primary icons don't distinctly highlight precombat actions, it might lead to some confusion.

I believe an extra window solely for precombat icons/spells that appear only at the beginning before the actual combat initiates and then disappear post-engagement, could be a valuable addition. This could help in better planning and executing precombat strategies, enhancing the user experience especially for classes with complex precombat preparations.

Thank you for considering my suggestion. Your continuous effort in improving the Hekili addon is much appreciated. I look forward to any potential updates and am happy to provide further input if needed.

### Contact Information

marek_devop

**Comment by Hekili** [comment]
I've thought about precombat actions and I do not think I would address it with an additional display.

I'm thinking about making the addon aware of pull timers, so if a precombat action is used at 10 seconds prepull that it would recommend at that point. 

The real question is what to do if you miss the timing. If it's supposed to be used 10 seconds prepull and you don't do that, what should show at 6 seconds? Push the button to catch up, or skip it because it's too late?

**Comment by marekCs** [comment]
Hi Hekili,

Thank you for your response, and I understand your reluctance towards adding an additional display for precombat (although I still believe it's the most effective solution). Regarding the precombat timer, I don’t think it's a good idea for these reasons: 1) Pull timers are not always used and aren't a mandatory feature within WoW UI, essentially working only in raids and not always at that. 2) As you mentioned, what happens if a user misses the timer?

Hence, I would like to propose a different solution. Perhaps distinctly highlighting the precombat icons in some way, like a strong yellow border of 2px, for instance. Additionally, it would be helpful to include a large decimal indicating how long the spell takes to cast, aiding users in knowing when to start the precast, especially when there are multiple precombat icons. The only drawback is if a user has the display set for only one or two icons, and there are more precombat spells, it becomes a problem.

Also, could the already implemented notification bar be utilized for this purpose? If not, then highlighting seems like the next best option? Currently, it’s hard to distinguish precombat icons from regular ones.

Thank you immensely for your work, I deeply appreciate it.

**Comment by Hekili** [comment]
> 1) Pull timers are not always used and aren't a mandatory feature within WoW UI, essentially working only in raids and not always at that.

Keep in mind, once you're in combat, you're in combat.  So if what you're *really* looking for is a long opener sequence before switching to in-combat priority, even if you're actually now in combat -- that'd be too weird.

I guess I don't understand the expected behavior.  Let's say you have buttons to push over a 10 second span ahead of combat.  What would you expect to see when your tank facepulls 4 seconds prematurely?  If there is no pull timer, how do you know it's X seconds before pull?

Without a pull timer, how do you know when "6 seconds before pull" is?

> 2) As you mentioned, what happens if a user misses the timer?

I was genuinely asking this question of you.  What, in your mind, does a player see if they're supposed to Prescience X seconds ahead of pull, and they don't?  Skipping to the next action might be wrong.  Pressing Prescience late might be wrong.  How do we know what we should be recommended if you don't respect the timer?  How do we know and prove what is optimal?

> Currently, it’s hard to distinguish precombat icons from regular ones.

You could add captions to the entries in the precombat action lists and have those display, if you really wanted.  As far as the addon is concerned, you're in combat if you're actually in combat, or (in the case of future predictions), you're in-combat after using an ability that triggers combat.

**Comment by marekCs** [comment]
Thank you for the continuous dialogue. Here are my thoughts:
Regarding pre-pull knowledge, in M+ dungeons, I can estimate when the tank is about to engage, giving me roughly 2 seconds to prepare. In raids, pull timers are usually set, making it straightforward. In the open world, it's up to me when to initiate the pull.

If a player misses the pre-pull casts, nothing major happens; the addon switches to fight mode as it currently does.

I wasn’t aware that custom captions could be added to the precombat action lists for display. This could indeed be a viable solution to differentiate precombat actions. I'll explore this feature.

I appreciate your time and effort in addressing my concerns.

Warm regards..
