### ISSUE TITLE
[REC] Rogue, Assasination doing ST rotation after a while addon fails to recommend and takes autosnapshot

### ISSUE THREAD

**Issue by Ktuky** [Hekili/hekili#2884]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

On my assasination rogue, after a burst window basically ends addon fails to recommend next and takes auto snapshot. Can reproduce this every time.

### How to Reproduce

1. Enter a game as Assasination Rogue
2. Start single target rotation
3. After using all cooldows, addon fails to recommend next steps and auto snapshots

### Snapshot (Link)

https://pastebin.com/tsRcnNwf

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/wr6JGWQi5UwxHa82tgmH12

**Comment by Hekili** [comment]
So, there are similar spots in your sim that have a long delay before recommending Envenom:

![image](https://github.com/Hekili/hekili/assets/9438134/8b6cee6f-4784-407a-8553-d2b1614b0b96)

![image](https://github.com/Hekili/hekili/assets/9438134/4fb85280-e205-4949-951b-dd94fb3dd55c)

This one is almost **12 seconds** without using an ability:

![image](https://github.com/Hekili/hekili/assets/9438134/24e569ec-6b97-4d56-bbae-f0aaa9830d58)

So I would expect that SimulationCraft will see changes to help resolve this going forward.  There is also an issue here that your amplifying_poison debuff stacks were not detected, because I named the dot differently than SimulationCraft.  I will fix that element.

I tried adjusting your sim to use Envenom more to avoid these lulls, but it was a DPS loss.  That said, your character waiting 12 seconds represents 240+ energy being generated and inevitable overcapping and waste.  That can't be the right answer.

**Comment by fzarr** [comment]
With T31 4pc, sin rogue wants to aggressively pool to get as many envenoms out while the previous envenom debuff is active as possible. Perhaps the APL isn't playing well with old or no tier equipped.

**Comment by Hekili** [comment]
There was an update from SimC that may address this.  It's in today's release (h).

**Comment by alonewicked** [comment]
> So, there are similar spots in your sim that have a long delay before recommending Envenom:
> 
> ![image](https://user-images.githubusercontent.com/9438134/281785116-8b6cee6f-4784-407a-8553-d2b1614b0b96.png)
> 
> ![image](https://user-images.githubusercontent.com/9438134/281785188-4fb85280-e205-4949-951b-dd94fb3dd55c.png)
> 
> This one is almost **12 seconds** without using an ability:
> 
> ![image](https://user-images.githubusercontent.com/9438134/281785346-24e569ec-6b97-4d56-bbae-f0aaa9830d58.png)
> 
> So I would expect that SimulationCraft will see changes to help resolve this going forward. There is also an issue here that your amplifying_poison debuff stacks were not detected, because I named the dot differently than SimulationCraft. I will fix that element.
> 
> I tried adjusting your sim to use Envenom more to avoid these lulls, but it was a DPS loss. That said, your character waiting 12 seconds represents 240+ energy being generated and inevitable overcapping and waste. That can't be the right answer.

I'm not an expert in add-ons and problem solving, I just had the problem that nothing was suggested to me for AOE/Multitarget. What you read out of the sims, I can't do much with that, I tried to take the snapshot on the training dummies and at first nothing worked (probably my mistake) and then that was the only snapshot that was created. Unfortunately I can't say more about it, but I really appreciate your quick reaction/answer.

**Comment by YomamaNow** [comment]
You are correct. Blizzard's last hotfix does not impair Hekili at the wooden dummies. It impairs it in groups. SimC catering to it would be an unusual theory, because it would have to no longer go by your damage potential and instead maybe cater to this handicap. I'm wondering if Hekili can even overcome what Blizzard has done.

**Comment by Delerp** [comment]
I got 4 piece and have had this happen quite often now in single target, two snapshots:
https://pastebin.com/VfVULbHp
https://pastebin.com/FYBE1fjp

Is this caused by the same issue in this ticket?

**Comment by Hekili** [comment]
>  Blizzard's last hotfix does not impair Hekili at the wooden dummies. It impairs it in groups. SimC catering to it would be an unusual theory, because it would have to no longer go by your damage potential and instead maybe cater to this handicap. I'm wondering if Hekili can even overcome what Blizzard has done.

The API limitation is in combat, but I've worked around that already.

I've made updates to Rogue specifically in 1.0.9 that may resolve this for Assassination.
