### ISSUE TITLE
Blood of the Enemy suggested while out of range

### ISSUE THREAD

**Issue by ghost** [Hekili/hekili#290]
**Describe the Bug/Issue**
Blood of the Enemy is suggested even when you're not within range of your target.

**Expected behavior**
Blood of the Enemy to not be suggested in the rotation unless you're within range of your target.

https://www.wowhead.com/spell=298277/blood-of-the-enemy

**Comment by Hekili** [comment]
There is a slippery slope when filtering out abilities based on range.  I'll be honest, I don't like the "Exclude" option for displays in regard to range-checking.

What folks _should_ do, is when they see Blood of the Enemy recommended, is think "I should get in range to use Blood of the Enemy" rather than "I'm standing 40 yards away but I'll push Blood of the Enemy, I guess."  Seeing BOTE in your queue should prompt you to get in position for it -- just like any other ability.

Filtering out abilities based on range-checking kinda subverts the primary intent of the addon, which is to tell you what would be optimal/consistent with SimC.  Withholding a BOTE recommendation because you're at 14, 20, or 40 yards can have all sorts of consequences depending on your class/spec/priority.  For instance, if the priority is written to sync BOTE with your major cooldown, and you can use your major cooldown at a distance, then you might end up with fewer BOTE recommendations overall than you should have, if you never move into range.

I'll think about it.  I can add a range value to BOTE, so that if you use "Exclude" it'll work, but if there are problems beyond that, I'll probably leave that alone.

What's your class and spec?  Where's the rest of the ticket information?

**Comment by Hekili** [comment]
BOTE will now use an 11 yard range-check (vs. your target) when your display is set up to filter abilities by range.
