### ISSUE TITLE
[REC] Assasination rogue opener issues

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#2986]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Attached snapshot should show both issues.

** Recommending on-use trinket (Irideus Fragemt) after first global instead of syncing with Deathmark**
It might not be relevant any more because Irideus Fragment is a season 2 trinket, but it does still seem to work correctly in a raidbots quicksim and might be indicative of another problem.

If I have Irideus Fragment equipped, its recommending it very early in the opener, thus losing a lot of value as its losing the stat buff in the opener setup when it could be maximised in cooldown window. It also recommends it as soon as its back off of CD instead of syncing with the Deathmark at 4min.

** Incorrect opener sequence **
Sequence should be something like Stealth -> Garrote -> Ambush -> Rupture -> Mutilate -> Slice and Dice -> Mutilate -> Mutilate -> Envenom -> Deathmark -> Shiv -> Shadow Dance -> Kingsbane -> Envenom / Garrote

Instead, pre-combat, addon recommends: Garrote -> Slice and Dice -> Ambush -> Mutilate -> Envenom -> Shiv -> Shadow Dance, not recommending Deathmark at all. 

Note: it does vary a bit when you enter combat with the initial Garrote and is more correct but still not matching simc.

Snapshot after initial Garrotte: https://pastebin.com/UB1ZGAff

### How to Reproduce

1. Enter game as sin rogue, standard ST build (equip Irideus Fragment, or maybe other on-use trinket).
2. See opener recommendation

### Snapshot (Link)

https://pastebin.com/Wp0uAM7h

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/iTdxQn1w93dHgJeDxYz8g4

**Comment by Delerp** [comment]
With version 1.0.5a this still occurs, albeit with some differences:

https://pastebin.com/uKMhRFn9

Hekili suggests: garrote-ambush-envenom-shiv-mutilate-thistletea

Rupture is not applied until later on. I believe this causes issues with other abilities since slice and dice and deathmark both have dot.rupture.ticking as requirements.

compare to sim: https://www.raidbots.com/simbot/report/c9KR46SxvTE1yhGHNSaibx/simc rupture applied very early on

somehow sim works differently. sim does not use the following line when initiating from stealth:
actions.stealthed+=/envenom,if=effective_combo_points>=4&buff.master_assassin_aura.up&!buff.shadow_dance.up&variable.single_target

instead it uses

actions.dot+=/rupture,if=effective_combo_points>=4&(pmultiplier<=1)&refreshable&target.time_to_die-remains>(4+(talent.dashing_scoundrel*5)+(variable.regen_saturated*6))

does it have something to do with combo point prediction? maybe sim does not pass the line effective_combo_points>=4

**Comment by Hekili** [comment]
It's definitely something impacted by talents; in your build, I get the Envenom recommendation before Rupture.  In other talents, I get Rupture first.

**Comment by Delerp** [comment]
New beta fixes the opener, but i'm noticing it recommend garrote twice in a row a few seconds into the fight:
https://pastebin.com/qqrzFN0M

This might not be related to the fix though, probably some apl oddity with it trying to snapshot improved garrote?

Edit: false alarm, APL issue. APL is for some reason using garrote twice in a row, can be seen here: 
 https://www.raidbots.com/simbot/report/c9KR46SxvTE1yhGHNSaibx/simc
sample sequence at time 0:22:102

**Comment by Hekili** [comment]
You can fluff up the snapshot and duration by Garroting multiple times.
