### ISSUE TITLE
[BUG] Assassination rogue snapshots every second

### ISSUE THREAD

**Issue by kolefield** [Hekili/hekili#3021]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I was fighting Laradar on LFR, suddenly there were no recommendations for the Primary set. Afterwards, a snapshot was taken every second until I disabled the addon. I switched to [this](https://www.wowhead.com/talent-calc/rogue/assassination/DANFRVFRRFUVZiRBCRAMVVRUVEYVEUoVBU) set of talents before the fight, so that may have something to do with it. It didn't happen previously.

Pastebin of snapshot: https://pastebin.com/QfXwMSKH

### How to Reproduce

1. Start combat as assassination rogue with the previously mentioned talents
2. Do combat until the chat message pops up "Unable to make recommendation for Primary..."

### Player Information (Link)

https://pastebin.com/EbVV5S5x

### Error Messages (Link)

No lua errors

**Comment by Hekili** [comment]
Can you try this macro and tell me the result?

`/run local s = Hekili.State; for k,v in pairs(s.set_bonus) do if type(v) ~= "number" then print( k, v ) end end`

If it doesn't print any text, that's great.  Otherwise, it might show something like:

`some_name table:00003818339`

**Comment by kolefield** [comment]
That script didn't print anything

**Comment by Hekili** [comment]
So the reason that Assassination snapshotted is because occasionally, the priority is having you wait for longer than the addon really allows for.

The reason it snapshotted *a lot* is because there was something in that set_bonus table that wasn't a number.  I can't find anything in my code that would account for it.

If you have the same thing happen again, please use the macro again before reloading your UI.  Other than that, the Assassination issue in general already has an open ticket number.  Thanks for reporting.
