### ISSUE TITLE
[REC] [Havoc DH] Incorrect Check for Unbound Chaos Buff Affecting Fel Rush/Immo/Inertia Interaction

### ISSUE THREAD

**Issue by Elehiggle** [Hekili/hekili#3030]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I have opened the same issue on SIMC, but not sure they care: https://github.com/simulationcraft/simc/issues/8455

APL will check if Unbound Chaos buff is up to determine if Fel Rush will trigger Inertia, but the Inertia talent only requires that you have HAD Unbound Chaos, it does not matter if you had the buff 1 minute ago, it will still trigger Inertia. Poorly formulated talent maybe. This also changes behaviour of Immolation Aura usage.

### How to Reproduce

Proc Unbound Chaos by using Immolation Aura, wait eg. 13 seconds for Unbound Chaos buff to fall. APL will recommend using Immo Aura again to trigger Unbound Chaos for a Fel Rush to trigger Inertia. Instead, it should consider that I already used Unbound Chaos in the past and had not yet triggered Inertia.

### Snapshot (Link)

https://pastebin.com/EnAxhZrg

**Comment by legacy3** [comment]
I can confirm this behavior.

**Comment by yolanthecampanella** [comment]
Interesting, I was just about to open a ticket about this myself.

**Comment by N30Exca** [comment]
Not only this issue is present in H DH APL also opener is wrong

After Immolation Aura is popped if A Fire Inside did not proc Felblade should be suggested but it only rarely suggested, after that Eye Beam should be suggested and then The Hunt into a fel rush.

What is suggested instead is Immolaton Aura>Sigil of Flame>Fel Rush>Immolaton Aura>Eye beam

How to Reproduce
1-Enter the game
2-pop Immolation aura

Snapshot (Link)
https://pastebin.pl/view/804d0ea3

Raidbots Sim Report (Link)
https://www.raidbots.com/simbot/report/6XYs63gJdNjGQrikBXoDd6

**Comment by Hekili** [comment]
1.0.16-beta1 will have a test fix for Unbound Chaos.

**Comment by Hekili** [comment]
This should be resolved; Unbound Chaos is now forced on if you've used Immo Aura more recently than you've used Fel Rush.
