### ISSUE TITLE
BM Opener is incorrect with AoE talents

### ISSUE THREAD

**Issue by syrifgit** [Hekili/hekili#3034]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

ST talent opener recommends barb-barb-call
AoE opener recommends Call

They ought to be the same as per the class guides, this is new behaviour since I played last night.

### How to Reproduce

Take AoE talents and pull a single target encounter (M+ boss, raid boss, dummy, etc).

### Snapshot (Link)

https://pastebin.com/CbuPzYHT

### Raidbots Sim Report (Link)

https://www.icy-veins.com/wow/beast-mastery-hunter-pve-dps-rotation-cooldowns-abilities?area=area_3

### Additional Information

Here is the correct single target snapshot for reference: https://pastebin.com/bftiPpG4

### Contact Information

Syrif

**Comment by syrifgit** [comment]
Actually I am seeing on the sim that apparently it has changed, but I don't see any mention of it in the guides or hunter discord, weird.

https://www.raidbots.com/simbot/report/kS4ECnigSPEQgpybPxUbBf

Looks like

ST Talents: Double barb
AoE Talents in AoE situation: Double barb
AoE Talents in ST situation: No barb on opener, but ONLY on the sim, not the class guides, and this is new.

So uh .. I guess I am not sure if this needs to be changed or not? I opened a thread on the hunter discord to see if Azor comments.

**Comment by Williamn88** [comment]
The APL does not do openers so it might differ a tiny bit from guides.
You currently only see the double barb if you have a point in scent of blood (m+ build got that, raid AOE build does not). You can modify the APL to do the barbs before cotw without a point in scent of blood but it's within margin of error. So does not really matter too much 

Also should not be something new. The APL have not been changed since 10.2.
But I have a feeling you most likely have played the m+ build in raid AOE with scent of blood as they are almost identical before. My addon have not been updated for a while and it's the same as you experience.

**Comment by syrifgit** [comment]
Yeah I'll just swap the talent point back, annoying to have the opener change after like a year lol.
