### ISSUE TITLE
Step mode

### ISSUE THREAD

**Issue by petesmisc** [Hekili/hekili#308]
Dear developer, I have been using your mod for some time and I would love to see a feature that allows me to "step" thru the rotation in a none Combat mode. 
This way I can see the rotation icons being used in a static state, the Step mode could be advanced by pressing the currently displayed icon so forth and so on.

Again, this is a none combat mode, only used for viewing.

If its currently possible to do this now, please let me know how.

Thanks for reading,
Pete

**Comment by Hekili** [comment]
There's not really a step mode, nor could there be a "real" step mode because a great number of mechanics are based on %chance procs.  The addon only forecasts things that are certain (resource gains, buffs gained from using an ability, etc.) so there'd always be factors to consider that the addon reacts to instead of predicts.

The best you can really do in the addon is to go into /hekili > Displays > Primary and set Icons Shown to 10.  Then you can hit Pause.  Now you can see the next 10 recommendations.  If you mouseover the icons, you can see why the recommended actions were recommended (sometimes it's complex and takes some interpretin).

For more detail, after pausing you can retrieve the snapshot from /hekili > Snapshots and see why other actions weren't recommended.

**Comment by Hekili** [comment]
(But keep in mind the bit about the addon not predicting unpredictable things.)

**Comment by petesmisc** [comment]
Thank you for the suggestion.
I just got back in the game after about a 24month hiatus, I currently have 2 windows, Primary +1,
The second window is smaller than the Primary and I don't remember how I did that and now I cant find where I can adjust that second window, I only see the size adjustments for the Primary.

Thanks,
Pete

**Comment by Hekili** [comment]
/hekili > Displays > AOE

Number of icons and size of icons is all there.

**Comment by petesmisc** [comment]
I'm sorry I must be dense but I see the w/h controls and it does make the
adjustment but once I get out of the configuration, the main window is the
size I set it to but the second window is still the smaller, some how they
are not linked. Dont know why the second window is not staying the same
size as the Primary.

Thanks
