### ISSUE TITLE
[REC] Outlaw Rogue leveling recommendations awful

### ISSUE THREAD

**Issue by Chippel** [Hekili/hekili#3097]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Man I love this addon when playing my Hunter but this is not useful when playing a Rogue.

I'm currently level 68 and the recommendations are awful. For instance, Hekili recommends me to open with Sinister Strike out of stealth. It even sometimes recommends Pistol Shot out of stealth. It _never_ recommends to open with Ambush, I mean, never. It also barely recommends BTE. 

I attached my Snapshot. If you need anything else, I'm happy to give it to you to improve it for Rogues.

### How to Reproduce

Well, just playing an level 68 Rogue. No settings were changed. Even reset the profile.

### Snapshot (Link)

https://pastebin.com/hYRLsEsJ

**Comment by syrifgit** [comment]
Make sure to read your class guides/resources about the rotation.

You do not have the "hidden opportunity" talent, and straight from the rogue discord: **_builds without HO do not press Ambush because it does not proc Fan the Hammer, and Sinister Strike was changed to proc Count the Odds so SS is always a better global._** The Wowhead guide rotation also assumes you have Hidden Opportunity, as explained by the guide right above the rotation, but you can find rotation info for the "Keep it rolling" build in the rogue discord which seems to be closest to what you're running (you aren't following either of the current builds).

As a side note, you are also not max level, and you should have seen a warning on your screen that Hekili is designed for max level characters. You have neither every talent point nor any tier set.

All that to say it's correct that you are not being recommended Ambush.

**Comment by Chippel** [comment]
Im sorry for not paying attention then. I used the in-game recommended talent tree by Blizzard. I guess I'll change to a build which is on WowHead then. You can close this.
