### ISSUE TITLE
[REC] Mage/Frost, Conditions for Shifting Power seem wrong.

### ISSUE THREAD

**Issue by CR82** [Hekili/hekili#3098]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Shifting Power is recommended although all cooldowns are ready.

### How to Reproduce

1. Enter the game as a Frost Mage
2. Shifting Power is recommended 

### Snapshot (Link)

https://pastebin.com/H3gAkyDk

**Comment by syrifgit** [comment]
From the class guide:
[Shifting Power](https://www.wowhead.com/spell=382440) when Ray of Frost,  [Comet Storm](https://www.wowhead.com/spell=153595), and Frozen Orb are on cooldown for at least 10 seconds longer.

From your snapshot:
 27.  ray_of_frost ( st - 4 ) - ability disabled 
  29.  frozen_orb ( st - 6 ) - ability disabled
  
  You have 2 of the abilities disabled, Possibly because of the separate CD bar?
  
  Try
  1) Making sure the individual abilities are enabled (under abilities section dropdown list)
  2) Put your CDs back into the main display instead of separate

**Comment by CR82** [comment]
I think the problem is in the part of the condition that was added latest by Hekili:

cooldown.icy_veins.true_remains<20|boss&fight_remains<20

If I delete this part, the recommendation works as I expected it to, but maybe I don't see the intetion.

**Comment by Hekili** [comment]
The best fix for this is to put Shifting Power on the Cooldowns toggle as well, so it follows the same rules as your other major cooldowns which are on the Cooldowns toggle (and are shown separately).

**Comment by Hekili** [comment]
> If I delete this part, the recommendation works as I expected it to, but maybe I don't see the intetion.

I'm genuinely uncertain of why the sim is written to burn Shifting Power regardless of other CDs if Icy Veins is coming off cooldown, but that's what your sim is set to do.

**Comment by CR82** [comment]
Icy Veins is not the problem I think, because even at the start of a fight when all cooldowns are available (including Icy Veins), it recommends to burn Shifting Power immediately.

Maybe it's worth it just for the damage? But then it should check if an enemy is in range.

**Comment by Hekili** [comment]
Looking at the sim conditions, it still looks like this is intentional.  The reason that conditions are met is that Icy Veins' cooldown is less than 20.  The logic would be "use SP when FO/CS/RoF CDs are over 10 seconds OR Icy Veins comes off CD within 20 seconds."  It's likely seeking to reduce those cooldowns assuming you wouldn't have held them but maybe they fell below 10 seconds.

You should probably put Shifting Power on the same toggle as your Ray of Frost and Frozen Orb, that way it's recommended over there out of the way.  Running into this recommendation for SP is a warning that you're not using FO/CS/RoF enough, which is the danger of holding CDs overly long.
