### ISSUE TITLE
[REC] Demonology Warlock Recommendations not matching sim

### ISSUE THREAD

**Issue by Jacii1121** [Hekili/hekili#3114]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Recommendations don't match Sims.  Especially Fireblood usage.

### How to Reproduce

Dark Iron Warlock - Talent Spec - BoQAj5LiEN4VXhSin5RcWeAUgggkEJJQKKQaJJhUCAAAAAIBSikSEhkIpolkkQAAAAAAQiA

Fireblood is recommended within the first 3 recommendations.  Whereas in the sim, 13s into the fight.  Demonbolt also suggested unlike Shadowbolt in the sim.  

Willing to do any extra testing, you need. Thank you for everything you do.

### Snapshot (Link)

https://pastebin.com/iCz43Pne

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/3NH4TdQWzuS2Lc1XeboVmp

### Contact Information

jacii_

**Comment by Hekili** [comment]
Demonbolt in the opener is intentional (and meant to work with Power Siphon).  I'm not convinced the sim is more optimal in that regard.

Fireblood would probably be fine if the condition were updated to be `gcd.remains = 0`.  The sim completes the precombat list once (like a sequence) and then ignores it, but the addon tries to find a precombat recommendation while your GCD is active, and continues to the in-combat list until it finds something that can be used now (Fireblood, which is off-GCD).
