### ISSUE TITLE
[REC] Outlaw sometimes recommending Dispatch in crackshot windows instead of BtE

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#3134]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

This only happens sometimes, feels quite random, but sometimes the addon will recommend dispatch even though bte is off cd and youre in a crackshot window with stealth/subterfuge/UHUH active.

### How to Reproduce

Smack the dummies for a bit doing rotation, sometimes you will see dispatch being recommended in stealth windows when bte is off cooldown.

Using KiR build, not sure if it happens with HO.

### Snapshot (Link)

https://pastebin.com/2pZ7f8p3

**Comment by Hekili** [comment]
It's happening because you've spent Energy down so low that Dispatch is available sooner than Between the Eyes.  This is likely to occur in sims as well, assuming the sim ever spends down below the energy cost of Dispatch.

**Comment by fzarr** [comment]
Would it be possible to add a 'always use bte while stealthed' with crackshot talented to prevent dispatch being recommended? Sometimes I've seen it swap rapidly between bte and dispatch and it can be quite confusing.

**Comment by Stonewalljay** [comment]
I agree with fzarr, when using hekili on the target dummy, something isnt right.  My sim on 5 targets for 3 min is 470k, but I only achieve 370k.  Thats a big difference and my buff uptimes are not what raidbots tells me, so Between the Eyes is not being used enough to bring the cooldown of Adrenaline Rush fast enough.  I'm not an expert of this class which is why I rely on Hekili, but I do see that my buff uptimes do not reflect the sims buff uptime from raid bots.  AR is only up about 66% of the time and it should be close to 100%.  The only way this is happening is because I'm not using the correct abilities to bring the cooldown fast enough to use it again.  Thank you!

And honestly, I could be wrong...I really dont know, but I use Hekili with other classes and it works amazing.

**Comment by stantsz** [comment]
@Stonewalljay most likely a l2p issue. Here's AR uptime after 4 mins on a the aoe dummies for me:

![image](https://github.com/Hekili/hekili/assets/159400614/a69d6a3b-f895-4e3a-a02f-aa67da3ae587)

According to sim, I'm supposed to be at 92% uptime:
![image](https://github.com/Hekili/hekili/assets/159400614/c19bc053-0c94-4737-91ef-38e98ad7970f)


I simmed at 529k dps and achieved 516k.

**Comment by fzarr** [comment]
Hekili is correct and this particular issue is related to energy. Whether builder/spenders are being recommended incorrectly to cause energy issues should be addressed elsewhere but i do think its mostly from pressing the wrong abilities or getting very bad rng (or in a real world scenario, from dying or badly timed extended downtime).

I saw the situation I posted about in a sim. It occurs when low on energy and you have enough stacks (typically 4-5) of Summarily Dispatched to lower the cost of Dispatch to as low as 9 energy. On extremely low energy and low energy regen, this then becomes more efficient to use than BtE even in a crackshot window. This typically only happens in lower target counts or without deft manoeuvrers when blade flurry can't be used as an efficient builder. 

I think this can be closed.
