### ISSUE TITLE
[REC] Affliction Warlock ST CD usage is broken

### ISSUE THREAD

**Issue by MatteoLombardi** [Hekili/hekili#3140]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For affliction warlock, Darkglare and Soul Rot are never suggested unless forced by previously casting Vile Taint as the addon would suggest in AoE

### How to Reproduce

1. Play Affliction
2. Follow ST rotation while in automatic switching between ST and AoE mode
3. Cast Vile Taint
4. Suddenly Soul Rot and Darkglare show up

### Snapshot (Link)

https://pastebin.com/TLzuPBzb

### Contact Information

@nidhogg94 on discord

**Comment by syrifgit** [comment]
It appears that you are using these abilities in a separate display bar which is causing them to act as disabled in your primary bar. As noted in the tooltip when you select that option, it may not work well for all specs.

There are 2 things you can try
1) Don't put your cooldowns separate
2) Try the "(GLOBAL) When Cooldowns Show Separately, Use Actual Cooldowns" checkbox on the ability page.

Since you have those abilities assigned to the "cooldowns" display, you would need to select that snapshot inside the addon when you take it, not primary, if you still encounter issues after trying those.

**Comment by Hekili** [comment]
Another option than what Syrif recommended would be to put Vile Taint on the Cooldowns toggle.  That would make it appear with your Cooldowns and they would all be aware of each other's actual CD.
