### ISSUE TITLE
[REC] Sub Rogue Rotation not properly recommending Secret Technique

### ISSUE THREAD

**Issue by xXSFORTUNEXx** [Hekili/hekili#3167]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The rotation for sub rogue seems to be wrong after an update the week prior. It begins to recommend Secret Technique but never actually does resulting in lower DPS since its a pretty heavy CD. It may have been when the rupture timer was added. I'm not sure but after raiding following that update I was doing low dps until I implemented the CD myself.

### How to Reproduce

1. Enter game as Sub Rogue
2. Find target dummy
3. Begin fighting target dummy
4. You'll notice that it begins to move Secret Technique up in the queue but keeps pushing it back and then eventually out of queue

### Snapshot (Link)

https://controlc.com/b679e3e2

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/75AGwpD2bE1jCg2sUFf5qt

### Additional Information

In the sim above you'll notice Secret Technique is used early in rotation (about 5 seconds)  and recommend (via wowhead rotation guide) to be used when you have 3 or more stacks of Danse Macabre.

Ive noticed when you hit 3 stacks of  Danse Macabre, Secret Tech moves up in the queue but once it passes 3 it gets further and further until its gone but the CD is up.

**Comment by Hekili** [comment]
In your snapshot, you have 2 Combo Points and 6 banked in Shadow Techniques.  The addon is expecting that you will cap combo points by using Shadowstrike, then recommends Secret Technique.  Is that incorrect?

**Comment by xXSFORTUNEXx** [comment]
It may be the the Shadow Technique issue. But once I use Shadowstrike it will then recommend a different finisher (usually evis) and push Secret Tech back.

**Comment by fzarr** [comment]
Not sure if its related, but I've noticed (edit: in aoe) sims recommend using sectech on the first gcd after shuriken tornado, but the addon recommends black powder until tornado is pressed and then switches to a shadowstrike->sechtech, then into sectech.

Raidbots quicksim: https://www.raidbots.com/simbot/report/7n6bmwQq3SMVcVSR33z3mS
Snapshot of opener before tornado is pressed (all actions followed until that point are the same as the above sim): https://gist.github.com/fzarr/d237ad332c9fc25fc18b0d46a38b7cef

After tornado is pressed (but before it does anything), this will turn into a recommendation of shadowstrike->sechtech, and when the first shuriken storm from the tornato hits and generates cps, it will remove the shadowstrike and recommend sechtech as the first gcd correctly. However this switches so fast its pretty difficult to react in time unless you already know its going to happen.

Bonus snapshot of the shadowstrike post-tornado state: https://gist.github.com/fzarr/6da39d2e0ee571a8d7645c3e7dfc5ea1
Another snapshot of it recommending storms instead of sectech after tornado pressed (swaps rapidly from this state): https://gist.github.com/fzarr/70411f77e9bb28cc5584463a1c8d976d

**Comment by IIeTpoc** [comment]
It should not be related to the situation above, but the cooldown function of Secret Technique in RogueSubtelty is outdated.
Line 1072 is 
`cooldown = function () return 45 - min( talent.deeper_stratagem.enabled and 6 or 5, combo_points.current ) end,`

But it should be just `cooldown = 60`, as you have already implemented cooldown reduction of Secret Technique earlier.

https://www.wowhead.com/spell=280719/secret-technique

**Comment by Hekili** [comment]
The CD piece has been addressed (but doesn't cause this kind of issue).

I've made it so Shuriken Tornado will immediately generate CP in its model for the sake of smoothing out recommendations.
