### ISSUE TITLE
Keybindings wrong when using Bartender 4 as a Druid and transformed

### ISSUE THREAD

**Issue by Vortilion** [Hekili/hekili#327]
BEFORE SUBMITTING AN ISSUE:

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.
- check

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.
- check

Describe the Bug/Issue
the keybindings are not displayed or rather they are wrong when playing as druid and being in e.g. cat form. I am using bartender 4 for the action bars. Bar 1 is used for the normal Humanoid Form and switches to Page 7 when in another form. Keybindings are still visible, but from wrong page (the Humanoid form one).

Expected behavior
Keybindings of corresponding page are being used, not only page 1.

WHEN SUBMITTING AN ISSUE:
https://pastebin.com/Fnk64icB

**Comment by Hekili** [comment]
The BT4 keybind detection was user-submitted and doesn't appear overly concerned with the paging options of Bartender4.

I do plan on overhauling keybind detection in the future (but there is a lot of future, so that's Blizzard Soon(tm) at best).

In the meantime, you can manually set any keybinds that aren't detected properly via /hekili > Abilities > Override Keybind Text (or something along those lines).
