### ISSUE TITLE
Shred Recommended When Rake = 0 and TF/SA = 1/1

### ISSUE THREAD

**Issue by Necrochrist** [Hekili/hekili#3322]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Feral Druid - Shred is being recommended over Rake when Rake doesn't exist (or is =>4.6 seconds) on target and Tiger's Fury/Sudden Ambush is active.  Shred is also being recommended when the opportunity to upgrade Rake exists.  For example, a Tiger's Fury-only Rake exists on target, but when Sudden Ambush procs while Tiger's Fury is still active, Shred will be recommended rather than casting Rake to use Sudden Ambush to upgrade the current Tiger's Fury-only Rake.  

### How to Reproduce

1. Enter game as Feral Druid. 
2. Regarding Shred/Rake:  Take Dire Fixation Talent. (Current M+ Archon Loadout for Feral Druid: BcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAASk0STCSSSSJtDgWSkIJAAAAAAKAkkEAQSSSIJSJoFJAAAAAAIBAA
3. Talent selection does not seem to matter.  Whether using Dire Fixation or Rampant Ferocity, the issue persists.
4. Attack Single Target Dummy (Animated Duelist) in Gladiator's Refuge in Valdrakken.
5. Follow Hekili's recommendations.

### Snapshot (Link)

https://pastebin.com/tgFYn4zZ

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/hmeU2HeNj6VFJ8CFBw5iaZ

### Contact Information

angelsoftheseventhdawn@outlook.com

**Comment by syrifgit** [comment]
Looks like you have some sort of issue going on making it not recognize sudden ambush maybe? Your addon isn't recognizing prowl as a valid spell.

```4.   prowl ( precombat - 4 ) - ability unknown```

I just logged onto my feral and loaded up your talents, it spends the proc on rake pretty much every time. Maybe a fresh install or something? Or try resetting the priority pack just in case: https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions#rotation--performance

**Comment by Necrochrist** [comment]
Reinstalled, issue still persists.  I'd post a video, but the file is too large.  Here's a couple of screenshots showing Shred being recommended when Rake is about to fall off, SA/TF both active.  The second screenshot is Rake completely fallen off and Shred still being recommended.  I've used TellMeWhen long before Hekili in the same manner.  That Rake icon you see with the roman numeral 2 shows a Rake buffed with Tiger's Fury is applied to target.
![Shred2](https://github.com/Hekili/hekili/assets/76629068/11eae6bc-0128-442a-8193-eaacbe292901)
![Shred1](https://github.com/Hekili/hekili/assets/76629068/2da0e87c-8aa2-4d00-83db-4fc71abea491)

**Comment by Necrochrist** [comment]
I also periodically run into instances where Ferocious Bite (non-APC) is recommended although Rip is about to fall off.  Once Rip falls off, Ferocious Bite will remain as the recommendation for a few seconds before finally switching to Rip.

**Comment by Hekili** [comment]
Rake wasn't recommended because you weren't prowling/stealthed, and Shred is higher priority than Rake when Clearcasting is active.

| Pass/Fail | Action
| --- | ---
| Fail | actions+=/rake,cycle_targets=1,if=(down\|persistent_multiplier>dot.rake.pmultiplier)**&(buff.prowl.up\|buff.shadowmeld.up)**
| ... | ...
| Pass | actions.builder+=/shred,if=(**buff.clearcasting.react**\|(talent.dire_fixation.enabled&!debuff.dire_fixation.up))&!(variable.need_bt&buff.bt_shred.up)

After consuming Clearcasting with Shred, the next recommendation would likely be Rake:

| Pass/Fail | Action
| --- | ---
| Pass | actions.builder+=/rake,if=(**refreshable**\|buff.sudden_ambush.up&persistent_multiplier>dot.rake.pmultiplier)&!(variable.need_bt&buff.bt_rake.up)

**Comment by Necrochrist** [comment]
> Rake wasn't recommended because you weren't prowling/stealthed, and Shred is higher priority than Rake when Clearcasting is active.
> 
> Pass/Fail	Action
> Fail	actions+=/rake,cycle_targets=1,if=(down|persistent_multiplier>dot.rake.pmultiplier)**&(buff.prowl.up|buff.shadowmeld.up)**
> ...	...
> Pass	actions.builder+=/shred,if=(**buff.clearcasting.react**|(talent.dire_fixation.enabled&!debuff.dire_fixation.up))&!(variable.need_bt&buff.bt_shred.up)
> After consuming Clearcasting with Shred, the next recommendation would likely be Rake:
> 
> Pass/Fail	Action
> Pass	actions.builder+=/rake,if=(**refreshable**|buff.sudden_ambush.up&persistent_multiplier>dot.rake.pmultiplier)&!(variable.need_bt&buff.bt_rake.up)

I believe there is a bit of a misunderstanding.  Prowl is not the problem.  It's Rake not being prioritized over Shred when Sudden Ambush is active and Rake (tier 4 or less) is <=4.6 sec on target.  This causes Shred to consume most of the SA procs even if Rake needs to be upgraded or is missing from the target entirely.

**Comment by Hekili** [comment]
Using Rake over Shred when Rake is falling off or Sudden Ambush procs only occurs in the sim profile during Berserk/Incarnation:

![image](https://github.com/Hekili/hekili/assets/9438134/da15b33b-cccf-4628-be71-91639bc9b2f8)

Otherwise, Shred is used during Clearcasting at a higher priority than Rake (based on the order they are listed, below):

![image](https://github.com/Hekili/hekili/assets/9438134/b012dcd0-c202-405d-a717-308fb6ad0530)

> I believe there is a bit of a misunderstanding. Prowl is not the problem.

I was explaining the SimC action list as written, which the addon matches.  There is a high priority Rake entry (ahead of both the `berserk` and `builder` lists) that only fires if Prowling or Shadowmelded.  As you can see in the screenshots, the `builders` list does not have an entry placing Rake ahead of Shred.  

Here's an example from your sim showing Shred used while Sudden Ambush is active:

![image](https://github.com/Hekili/hekili/assets/9438134/d2e7727a-7e2e-43c8-aea4-e6f5b19f4962)

We would need a modified sim showing a higher DPS result to justify changing the addon's behavior here.

**Comment by Necrochrist** [comment]
I really appreciate the explanation.  Thanks!
