### ISSUE TITLE
[BUG] Shadow Priest profiles not loading

### ISSUE THREAD

**Issue by FatherChunk** [Hekili/hekili#3348]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Title. No profiles are available to load for shadow priest. Addon works fine (typing /hekili brings up the options menu) and other classes load their profiles and work as intended. Notification pop up on login states "Priest does not have any Hekili modules loaded (yet). Watch for updates.

### How to Reproduce

1. Enter the game as a shadow priest.

### Player Information (Link)

n/a

### Error Messages (Link)

n/a

**Comment by syrifgit** [comment]
That's because it hasn't been completed yet. Do what the addon says and "watch for updates"

The following specs are currently supported in the initial The War Within release of the addon:

Blood, Frost, Unholy DK
Havoc, Vengeance DH
Balance, Feral, Guardian Druid
Augmentation, Devastation Evoker
Beast Mastery, Marksmanship, Survival Hunter
Protection, Retribution Paladin
Elemental, Enhancement Shaman
Arms, Fury, Protection Warrior
Affliction, Demonology, Destruction Warlock (currently using DF priorities)

**Comment by FatherChunk** [comment]
Fair enough, figured that was the case but couldn't find any specific mention of spec's not being ready yet. 
Cheers for the swift response.
