### ISSUE TITLE
(Feral) Primal Wrath recommended while already up on all enemies

### ISSUE THREAD

**Issue by BuurmanDeBuurman** [Hekili/hekili#335]
Primal Wrath does damage and applies Rip to all targets in range. It's a talent. 

I think the problem here (if not a coding issue) is that the debuff it applies is not called Primal Wrath but Rip, perhaps a good place to start checking?

1.  https://pastebin.com/0Q30t3Ht

2.  https://pastebin.com/6MWu50Ed

**Comment by Hekili** [comment]
What makes you think that's incorrect?  What led you to the conclusion about the debuff name?

**Why Primal Wrath?**

At 5 Combo Points, Primal Wrath is 30% of AP per target + 12 seconds of Rip (or extension of Rip), for 20 Energy.  Let's say Rip is already up on all targets and the duration was maxed out at least application.  Let's say you get the full pandemic refresh, so 30% of a 12-second Rip is 30% of 100% AP.  Another 30% AP per target.

So hitting Primal Wrath gets you 60% of AP per target if Primal Wrath was your last finisher.  Potentially more.  It takes 3 targets to be very close to a 5 CP 50 Energy Ferocious Bite (180% AP vs. 196.56% AP).  At 4 targets, Primal Wrath is always better.

**Funneling**

Sure, there are scenarios where you might just want to Primal Wrath to get Rips on additional targets and then funnel damage into your primary target, but that's not what the priority is designed to do (because it's so situational) and not what you'd see from your sims.  That's a tactical decision that requires some judgment (and may not be optimal overall DPS, but may help you kill a particular boss faster).

I've occasionally tweaked my own priority to handle this (i.e., Orgozoa), but not as part of the general release (as I'd have to support it and explain the difference a lot).

The good news is, you can edit your priority to do the same thing.  Make a copy and give it a shot.

I think my edits were:
1.  Disable the 5th entry in the finishers list.
2.  Change the conditions for the 7th entry in the finishers list to:  `spell_targets.primal_wrath >= 2 & ( dot.rip.remains < 4 | active_dot.rip < spell_targets.primal_wrath )`

That makes it so you'll Primal Wrath after Rip falls off your current target or a new target comes into range, etc., but otherwise you should end up with a Ferocious Bite recommendation.  If I'm not forgetting something.

**Comment by BuurmanDeBuurman** [comment]
I actually don't have in depth knowledge of Feral but it seemed counter-intuitive based on what I know from Assassination rogue. That explains the reasoning, thanks for the deep dive.
