### ISSUE TITLE
Aug - Not recommending Upheaval

### ISSUE THREAD

**Issue by Wow157985** [Hekili/hekili#3410]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Ran M+ and never recommended upheaval. 
Tried it on dummies, same thing.

### How to Reproduce

Attack Dummies and you can see it

### Snapshot (Link)

https://pastebin.com/EWSSKTj1

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/65KLruvxLbw4GLBsbgaBDt

### Additional Information

SimC does recommend it 2x during 1 min which seems correct. Not happening in-game though.

### Contact Information

Wow157985

**Comment by bySenom** [comment]
Since the rotation update, I can agree. Firebreath is only recommended at the beginning and Upheaval is not recommended at all. Additionally, the rotation broke at the start.

Edit:

I also need to mention that Prescience is recommended only once at the start instead of twice, and it's not recommended often enough in the normal rotation. Sometimes the buff has already expired and isn't refreshed. In the opener after Ebon Might, Upheaval and Firebreath are skipped, and the core rotation is continued instead. The Rotation was very good before the 0.9.1a. update, downgrade to 0.9.1.

snapshot
https://pastebin.com/FtQyhvVe

**Comment by Hekili** [comment]
There is a missing Upheaval entry in the APL.  This will be resolved today.

> Firebreath is only recommended at the beginning and Upheaval is not recommended at all. Additionally, the rotation broke at the start.

Snapshot when Fire Breath should be recommended but isn't.

> Additionally, the rotation broke at the start.

What does this mean?

> I also need to mention that Prescience is recommended only once at the start instead of twice, and it's not recommended often enough in the normal rotation.

You're solo in the snapshot you provided.  Is there value to casting Prescience twice when solo?  I'll revert this change, but I'm curious.

> Sometimes the buff has already expired and isn't refreshed.

In the snapshot you provided, as far as the addon can tell, your Prescience is applied to two random people around you.  There could be an issue with tracking the aura falling off in the test dummy area, but I'm not certain.

> In the opener after Ebon Might, Upheaval and Firebreath are skipped, and the core rotation is continued instead.

The opener looks like this after my planned changes:

![image](https://github.com/user-attachments/assets/ace832bf-3039-4577-8684-9741a3ee886e)

These changes will be posted in 0.9.1b in a little bit.

**Comment by MatteoLombardi** [comment]
> You're solo in the snapshot you provided. Is there value to casting Prescience twice when solo? I'll revert this change, but I'm curious.

There isn't, no need to revert. I noticed the single prescience as well while using dummies, but I forgot I was solo. In key it went as intended. Addon would break and snapshot after Fire Breath (would pop up Tip the Scales as CD to use but no Upheaval follow up -> Casting Upheaval caused error).

Will test again with 0.9.1b

**Comment by bySenom** [comment]
> You're solo in the snapshot you provided. Is there value to casting Prescience twice when solo? I'll revert this change, but I'm curious.
> 

There isn't any value in casting Prescience twice when solo, so there's no need to revert that change. I thought it was a bug because, in the last update, you had to cast it twice, but it seems to track the group members now. Sorry for the confusion.

> Snapshot when Fire Breath should be recommended but isn't.

https://pastebin.com/hzNAeMLn

Fire Breath was available throughout the entire fight but was only recommended at the opener. After using Ebon Might, it got skipped in favor of casting Eruption.

> What does this mean?

While casting Eruption, the recommendations disappeared. Initially, there were three icons, then it reduced to two, and finally to one. After that, no icons were displayed. About a second later, Eruption reappeared as the recommended ability, but there was a 2-3 second downtime without any recommendations. This issue occurred in the snapshot I provided above.

**Comment by Hekili** [comment]
> [pastebin.com/hzNAeMLn](https://pastebin.com/hzNAeMLn)

Sorry, I meant after updating.

**Comment by Wow157985** [comment]
I tried it and it does recommend "upheaval" now. But it recommends "tip the scales" before "upheaval" instead of "fire breath". Previous versions of Hekili, SimC, and on-line guides recommend it before "fire breath".

**Comment by Hekili** [comment]
> I tried it and it does recommend "upheaval" now. But it recommends "tip the scales" before "upheaval" instead of "fire breath". Previous versions of Hekili, SimC, and on-line guides recommend it before "fire breath".

Post a snapshot?

**Comment by Fyurie** [comment]
The guides are a little outdated but this behavior is technically correct, it's because you don't want to max rank fire breath to get more value from Molten Embers.

There's info about this in the Aug channels on Wyrmrest Temple.
