### ISSUE TITLE
Crimson Tempest Not Recommended 

### ISSUE THREAD

**Issue by Romdiaz123** [Hekili/hekili#3416]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Crimson Tempest when speced is not being recommended in rotation 

### How to Reproduce

Play Rogue 
5-Target Dummies
Follow rotation 

### Snapshot (Link)

https://pastebin.com/b2mpi1xx

**Comment by Romdiaz123** [comment]
Looking into it, seems this was set to "0" default and not being able to recommend. Set to "1" and now recommended. 
![Screenshot 2024-07-28 141732](https://github.com/user-attachments/assets/0ccffb17-539b-4ab3-9bb8-8d051d203596)

**Comment by Hekili** [comment]
Per your snapshot:

```
        50.  crimson_tempest ( dot - 3 )
        The action (crimson_tempest) is usable at (0.00 + 1.00) with cost of 30 energy (have 282).
         - the action is ready before the current recommendation (at +1.00 vs. +10.00).
        List ( dot ) called from ( Assassination:default:10 ) would PASS at 1.00.
        NONE
         - this entry's criteria FAILS: spell_targets.any[5.00] >= 3 & refreshable[true] & pmultiplier[0.00] <= 1 & effective_combo_points[1.00] >= variable.effective_spend_cp[5.00] & energy.regen_combined[19.34] > 25 & ! cooldown.deathmark.ready[false] & target.time_to_die[1.00] - remains[0.00] > 6
```

Crimson Tempest would've been recommended if you had 5+ Combo Points, your Energy regeneration were greater than 25, **and** your target was expected to live at least 6 additional seconds (the dummies are sitting at low health when you took your snapshot).

The biggest barrier, under normal combat circumstances, would be the `energy.regen_combined > 25` since you're sitting at 19.34 (based on base regen, plus Garrote, Rupture, Nothing Personal effects).

I'll remove the Energy requirement pending review of whether the value should be higher than it is.
