### ISSUE TITLE
Custom display

### ISSUE THREAD

**Issue by knorki1306** [Hekili/hekili#343]
Hello,

it would be great to have a custom display which can be placed on the interface. I do not want to have my cooldowns in the primary display. Placing them in Defensives or Interrupts helps, but it's not the best solution.

Stefan

**Comment by Hekili** [comment]
I'd strongly recommend using WeakAuras for extra HUD elements like this.  While I may eventually add more of a HUD to this addon, the behavior would be wildly different between classes/specializations.  Some specializations use their cooldown abilities as soon as they are ready, others are trying to line up multiple CDs.  Another display for CDs might be misleading since it's not just "when will X be ready?" but "when will X be ready and when will circumstances be right to use it?"  Those criteria might only pass in a narrow window after using another ability, for example.  That would cause the cooldown ability to appear/disappear repeatedly, which isn't ideal for a HUD element.
