### ISSUE TITLE
[REC] Rogue Outlaw - Between the Eyes being recommended outside of stealth with Crackshot Talent

### ISSUE THREAD

**Issue by Mongrul** [Hekili/hekili#3446]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I think there used to be an option to disable Between the Eyes outside of Stealth+Subterfuge, I am not seeing that checkbox anymore. I do see the Stealth Padding slider but even maxxed out I am still being recommended Between the Eyes outside of Stealth+Subterfuge.

### How to Reproduce

 Enter game as Combat Rogue. Take Talents Subterfuge and Crackshot. Enter Stealth and go through rotation on test dummy, when Subterfuge ends (Stealth effect goes away and Stealth Bar flips to regular bar) Between the Eyes is still being recommended. If Between the Eyes is used outside of Stealth with Crackshot Talent, it goes on a 45 second cooldown!

### Snapshot (Link)

https://pastebin.com/iRi17WwN

**Comment by Zanetsuken** [comment]
https://www.wowhead.com/guide/classes/rogue/outlaw/rotation-cooldowns-pve-dps

Current priority has BTE as use on CD at 6 CP or 5 during subterfuge

**Comment by Mongrul** [comment]
I better get with the times then! I'll run with the new priority, sorry about the false alarm.

**Comment by fzarr** [comment]
The Wowhead guide still has a condition on bte: 'Hold if Vanish or Adrenaline Rush have 45 seconds or less on its cooldown if not already active.' . 

Wasn't the option in question added to make sure you didn't use bte outside of stealth so it was always off cd by the time vanish came back? Otherwise, its possible to use bte outside of stealth, and incorrectly perform the rotation such that its not off cd when vanish is available. 

A very niche option for sure, but I think the reason it was added still exists?

**Comment by Hekili** [comment]
You have CDs toggled off, which disables Vanish and sets its CD to max (120 seconds).

```
52.  between_the_eyes ( finish - 2 )
The action (between_the_eyes) is usable at (0.00 + 0.44) with cost of 25 energy (have 164).
- the action is ready before the current recommendation (at +0.44 vs. +10.00).
List ( finish ) called from ( Outlaw:default:14 ) would PASS at 0.44.
  variable.finish_condition[true]
- this entry's criteria PASSES: talent.crackshot.enabled[true] & cooldown.vanish.remains[120.00] > 45 & ( raid_event.adds.remains[0.00] > 8 | raid_event.adds['in'][3600.00] < raid_event.adds.remains[0.00] | ! raid_event.adds.up[false] )
```

This makes it so that the criteria for Between the Eyes is met.  If CDs were enabled, this entry would've passed.

I will *probably* change the `cooldown.vanish.remains` to `cooldown.vanish.true_remains` which bypasses the CD-fudging associated with toggles.  You can do the same in the meantime, if you'd like.

**Comment by Mongrul** [comment]
I appreciate you looking into this. I indeed had my CD's off doing world content when I noticed this. I also have the Solo Vanish checkbox checked so I am not dropping combat when solo. (Rogue has been on ice since prepatch)
