### ISSUE TITLE
Hunter BM don't recommend dire beast before Bloodshed

### ISSUE THREAD

**Issue by esergiosantos** [Hekili/hekili#3461]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Dire Beast does not recommend before Bloodshed, Cooldown ON, and is not in a separate display.

### How to Reproduce

1. Enter game as a Hunter BM.
2. Take ST Talents Bloodshed
3. Start Attack Dummy
4. See recomendations.

### Snapshot (Link)

https://pastebin.com/DH04C6r2

### Raidbots Sim Report (Link)

https://mimiron.raidbots.com/simbot/report/48f7XnRhsgMaKhjN6PH4cY

### Additional Information

example of rotation to be used in Opener
https://www.icy-veins.com/wow/beast-mastery-hunter-pve-dps-rotation-cooldowns-abilities?area=area_2

### Contact Information

sergiovegas1

**Comment by Hekili** [comment]
As you can see in your Raidbots sim, the priority as written differs from what the Icy Veins guide recommends:

![image](https://github.com/user-attachments/assets/f725989d-9de2-478d-82f6-a1c25fee8524)

You could write a custom priority, if you were so inclined.  The addon will sync up with updates in SimulationCraft as they become available.

**Comment by esergiosantos** [comment]
Hekili is not recommending dire beast before Bloodshed, as in this print, however if I turn off the cd, it recommends correctly as in raidbots and icyveins
![image](https://github.com/user-attachments/assets/755787e7-3210-4596-857e-60aa596b0ce9)

CD off 
![image](https://github.com/user-attachments/assets/30fdd67a-59e2-4127-aa72-385cba7ace5d)

**Comment by Hekili** [comment]
The difference is that the sim is using Dire Beast with Beast Within up because of this logic:

Dire Beast:  `talent.huntmasters_call & ( ! buff.bestial_wrath.up & talent.killer_cobra | cooldown.call_of_the_wild.ready )`

This means that with Huntermaster's Call talented:
* use Dire Beast when Bestial Wrath is NOT active and Killer Cobra is talented, OR
* use Dire Beast when Call of the Wild is ready

There was earlier feedback that Dire Beast shouldn't be used here when you don't actually have Call of the Wild talented, so the addon was updated to also do a talent check:

Dire Beast:  `talent.huntmasters_call & ( ! buff.bestial_wrath.up & talent.killer_cobra | talent.call_of_the_wild & cooldown.call_of_the_wild.ready )`

You could remove the `talent.call_of_the_wild &` part from this entry (Beast Mastery > Action Lists > st > 4) if you want it to match the sim in that regard, but the sim will probably get changed as well.

**Comment by esergiosantos** [comment]
call of the wild talent is not being used in 99% of the logs in the pre patch, maybe it will be changed in the launch of TWW with the hero talents I haven't checked what the rotation there would be like yet,  hekili already configured for the new beta rotations?

**Comment by esergiosantos** [comment]
removing the part, talents.call_of_the_wild &  seems to have resolved it with the CD ON
![image](https://github.com/user-attachments/assets/f94a2a61-95f2-47cd-95b3-606c24e6ce44)
