### ISSUE TITLE
Unholy DK - Army of the Dead v2

### ISSUE THREAD

**Issue by Nazeth** [Hekili/hekili#349]
**Describe the Bug/Issue**
On rotation army_of_the_dead trigger works with summoned minions called Army of the Dead. That minion can be summoned via VoP Major, Apocalypse and Army of the Dead spells. It provides incorrect results and rotation malfunctions.

**To Reproduce and Expected behavior**
Every time, when Army of the Dead minions will be summoned via spells VoP Major, Apocalypse and Army of the Dead it will trigger army_of_the_dead scripts and interacts with that scripts from rotation.

**How it should works**
army_of_the_dead should works only with spell called Army of the Dead instead of minions called Army of the Dead.

**Screenshots**
No screenshots. It's script issue.

**PUT ISSUE REPORT LINK HERE:**

No raport, No needed. It's script issue.
 
**PUT SNAPSHOT LINK HERE:**

No raport, No needed. It's script issue.

**PUT ERROR MESSAGE(S) HERE:**

No error message

Better?

**Comment by Hekili** [comment]
No, you absolutely need to provide the issue report and ideally, a snapshot, of this problem that you describe actually happening.

I don't know which version of the addon you are using.  I don't know your talents.  I don't know your azerite or your essences.

What you are saying about scripting doesn't actually make sense in regard to scripts.  The cooldown of Army of the Dead is not dependent on there being any summoned ghouls nor where they procced from.  You might be misled by the cooldown of Army of the Dead looking like it is at the maximum time if Army of the Dead is on the cooldowns toggle and your cooldowns are toggled off.  But I can't see your settings to determine if that's related.

> Every time, when Army of the Dead minions will be summoned via spells VoP Major, Apocalypse and Army of the Dead it will trigger army_of_the_dead scripts and interacts with that scripts from rotation.

I have no idea what this means.

> army_of_the_dead should works only with spell called Army of the Dead instead of minions called Army of the Dead.

I don't know what you mean.  Because I don't know what you think is different, and I can't do any testing at all because I don't know the information from Issue Reporting and/or Snapshot that might give me useful context.

If you want me to spend any more time on this, actually provide the required information.

**Comment by Nazeth** [comment]
It will be the same on all talents what i can use, because i analyzed simc and hekili rotation.
Hekili-v8.3.0-04-22.03

You have "Army of the Dead" spell. That spell summon 8 minions called "Army of the Dead" and eventually "Magus of the Dead"
The same minions can be summoned by Apocalypse and VoP Major essence.

Because rotation care only about "Army of the Dead" spell cooldown, but cooldown.army_of_the_dead.remains works with minions from that 3 spells, then it create a lot of malfunctions.

**Comment by Hekili** [comment]
You are making assumptions about how the addon internally handles things, and you are not correct.  `cooldown.army_of_the_dead.remains` is not impact at all by when/how minions were spawned.  There's literally nothing in the code for checking the cooldown that works that way.

Instead of telling me what you are assuming is happening:

1.  Provide the information from your Issue Reporting tab.
2.  Describe what you are seeing, not why you think you are seeing it.

**Comment by Nazeth** [comment]
i tried to do rotation myself and optimize a bit resource management. I tried to prevent use spells that use runes by use &!cooldown.army_of_the_dead.remains, when Army of the Dead spell is ready, but that thing works always, when i have summoned Army of the Dead minion on field.

**Comment by Hekili** [comment]
Okay, I'm sorry, but you are refusing to follow simple instructions so I will not be able to help you.  Good luck.

**Comment by Nazeth** [comment]
Describe what you are seeing, not why you think you are seeing it.

I did that what you ask

**Comment by Nazeth** [comment]
I should you paste screen how rotation bar with your rotation disappears completely from time to time and appears again after pressing a random skill after 10 sec? during that time it will suggest me to use Outbreak or Death Coil only?

**Comment by Hekili** [comment]
No, you should stop submitting issues because you will not provide the required information and you will not cooperate when asked.

If you wrote a custom priority and you end up with no abilities recommended, you've probably made a mistake in your priority that results in no abilities being available.

I would have no way to help you explore that without the Issue Reporting tab information in /hekili, a snapshot (per the instructions here) when you are experiencing the problem etc.  But I am not going to make the mistake of asking you for information that you are not going to provide.

You're on your own.  Good luck.

**Comment by Nazeth** [comment]
This also applies to your rotation. I noticed that during making my rotation.

**Comment by Hekili** [comment]
There was a recent issue related to forecasting runes, that impacted Unholy Frenzy and Summon Gargoyle builds.  It was fixed, because people provided bug reports, issue reporting information, and snapshots.

Despite how ridiculously frustrating it is to interact with you, I'd still be happy to help you sort this out if you provide the information I've asked for.  It enables me to actually tell what's happening in your case.  But what you've provided thus far doesn't actually make sense.  I get that it's what you *think* is happening, but it's really not.

What is it that prevents you from going to /hekili > Issue Reporting and copying that information to paste here?  What prevents you from hitting the Pause or Snapshot binding and copying and pasting that to Pastebin per the instructions here?

**Comment by Nazeth** [comment]
build: v8.3.0-04-22.03
level: 120 (120)
class: DEATHKNIGHT
spec: unholy

talents: bursting_sores

    death_pact
    grip_of_the_dead
    infected_claws
    pestilence
    pestilent_pustules
    unholy_frenzy

azerite: azerite_empowered = 3
    festermight = 3
    heart_of_darkness = 2
    heed_my_call = 1
    impassive_visage = 1
    magus_of_the_dead = 1
    overwhelming_power = 1
    resounding_protection = 2
    unstable_flames = 1

essences: [vision_of_perfection] = 2, breath_of_the_dying = 1, memory_of_lucid_dreams = 1, purification_protocol = 1

sets/legendaries/artifacts: none

gear: ancient_tuskarr_sea_charm = 1
    artisan_officers_shirt = 1
    ashjrakamas_shroud_of_resolve = 1
    corrupted_gladiators_decapitator = 1
    heart_of_azeroth = 1
    malignant_leviathans_armguards = 1
    malignant_leviathans_clasp = 1
    malignant_leviathans_hauberk = 1
    mirageweavers_gauntlets = 1
    realitydefying_greaves = 1
    renowned_guild_tabard = 1
    ring_of_collective_consciousness = 1
    second_sight_helm = 1
    torment_in_a_jar = 1
    warboots_of_rezans_bladeguard = 1
    writhing_spaulders_of_madness = 1
    zandalari_band = 1

corruptions: void_ritual = 1

itemIDs: 157927, 158075, 158151, 165661, 169223, 172777, 173821, 173837, 173943, 174163, 174165, 174175, 174178, 174530, 174956, 69210, 89195

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Unholy
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    festermight_cycle = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = false

**Comment by Nazeth** [comment]
build: v8.3.0-04-22.03
level: 120 (120)
class: DEATHKNIGHT
spec: unholy

talents: all_will_serve
    death_pact
    ebon_fever
    epidemic
    grip_of_the_dead
    soul_reaper
    unholy_frenzy

azerite: azerite_empowered = 3
    festermight = 3
    heart_of_darkness = 2
    heed_my_call = 1
    impassive_visage = 1
    magus_of_the_dead = 1
    overwhelming_power = 1
    resounding_protection = 2
    unstable_flames = 1

essences: [vision_of_perfection] = 2, breath_of_the_dying = 1, memory_of_lucid_dreams = 1, purification_protocol = 1

sets/legendaries/artifacts: none

gear: ancient_tuskarr_sea_charm = 1
    artisan_officers_shirt = 1
    ashjrakamas_shroud_of_resolve = 1
    corrupted_gladiators_decapitator = 1
    heart_of_azeroth = 1
    malignant_leviathans_armguards = 1
    malignant_leviathans_clasp = 1
    malignant_leviathans_hauberk = 1
    mirageweavers_gauntlets = 1
    realitydefying_greaves = 1
    renowned_guild_tabard = 1
    ring_of_collective_consciousness = 1
    second_sight_helm = 1
    torment_in_a_jar = 1
    warboots_of_rezans_bladeguard = 1
    writhing_spaulders_of_madness = 1
    zandalari_band = 1

corruptions: void_ritual = 1

itemIDs: 157927, 158075, 158151, 165661, 169223, 172777, 173821, 173837, 173943, 174163, 174165, 174175, 174178, 174530, 174956, 69210, 89195

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Unholy
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    festermight_cycle = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = false

**Comment by Nazeth** [comment]
2 different builds

**Comment by Hekili** [comment]
Great, that's a start.  Now I need the snapshot when you're not getting a recommendation or you think AOTD's cooldown has been impacted by a spawned ghoul.

**Comment by Hekili** [comment]
FYI, using your first talent build, I've identified a bug with rune regen timing that I'm testing a fix for.  My fix seems to eliminate any blank or incomplete recommendation queues (even showing up to 10 icons at a time).

Still can't know if that's what was impacting you, but it may improve things for you regardless.
