### ISSUE TITLE
Lightsmith holy armaments not being recommended, integral to personal dps on protection and holy on Lightsmith.

### ISSUE THREAD

**Issue by nthnprsnlkid** [Hekili/hekili#3601]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Addon not recommending Holy Bulwark or Sacred weapon.

### How to Reproduce

If possible, pandemic would be great. 

### Snapshot (Link)

https://pastebin.com/99aM1jqU

**Comment by chevyn11** [comment]
so I think its to do with this: 
```next_armament[sacred_weapon] = sacred_weapon[true]```
`next_armament` is a variable that evaluates to the word `sacred_weapon`
`sacred_weapon` is a variable that evaluates as `true`

which looks like its comparing the word "sacred_weapon" to true, which is false ("sacred_weapon" !== true).
 
Could try using just `sacred_weapon` instead of next_armament=sacred_weapon
Or otherwise try to quote it (not sure if this works in hekili) `next_armament="sacred_weapon"`

the same for holy_bulwark: 
```next_armament[sacred_weapon] = holy_bulwark[false]```

removing this and the next line might work too, so theyre not vars?
https://github.com/Hekili/hekili/blob/thewarwithin/TheWarWithin/PaladinProtection.lua#L922

**Comment by chevyn11** [comment]
Or reverting it back to this: 
![image](https://github.com/user-attachments/assets/0e06fb02-8e1d-455a-be99-187595e81b9c)

**Comment by syrifgit** [comment]
Closing as this issue is many, many addon versions ago. If the issue still exists, please open a new ticket with new snapshots and sims.
