### ISSUE TITLE
[REC] Destruction Warlock never recommends wither

### ISSUE THREAD

**Issue by EricMiukyQin** [Hekili/hekili#3607]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Destruction Warlock never recommends wither even if I have talent internal_combustion enabled.

### How to Reproduce

No response

### Snapshot (Link)

https://pastebin.com/tuBBCE11

**Comment by syrifgit** [comment]
Might be because there are 2 different spellIDs, maybe they need to be flipped? Says talent missing. Unfortunately don't have a level 71+ lock atm.

In addon under talent reg: https://www.wowhead.com/spell=445465/wither
in addon under ability reg: https://www.wowhead.com/spell=445468/wither

ID used in wowhead talent calc: https://www.wowhead.com/spell=445468/wither

@Hekili

**Comment by EricMiukyQin** [comment]
Wither replaced immolate for destruction warlock.

**Comment by Hekili** [comment]
Should be fixed in 1.0.7
