### ISSUE TITLE
[REC] Outlaw rogue recommending BtE outside of subterfuge windows

### ISSUE THREAD

**Issue by BeemMN** [Hekili/hekili#3637]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Outlaw seems to be recommending naked BtE without vanish while charges are off cooldown during normal rotation leading to missed burst and wasted vanish charges

### How to Reproduce

Load in as outlaw rogue
Use wowhead outlaw rogue M+ talent build without killing spree
Hit single target/cleave training dummies for about a minute

### Snapshot (Link)

https://pastebin.com/bVULbNLq

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/c6GLv2yFaDute2fdHra4MH

### Contact Information

Discord: beam_mn

**Comment by chevyn11** [comment]
this is correct because the APL wont use vanish if adrenaline rush is not up. Your adrenaline rush is still on cooldown for >45 seconds (the same cooldown as BTE). This means you can safely use BTE and once adrenaline rush is up for vanish BTE will be back up again. 

Of course it cant predict restealths between packs so you have to use some brain power to not use BTE then.

I'm not sure how you got into a situation where you have 2 vanish stacks and AR is on cooldown for a long time though - and perhaps the apl should account for that and just send vanish on 2 stacks anyway to get CDR rolling. But probably something for the rogue discord.
