### ISSUE TITLE
Sunfury Arcane Single Target Rotation

### ISSUE THREAD

**Issue by GitBearded** [Hekili/hekili#3655]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

This snapshot is taken after the opener is complete and youre rolling into the standard rotation, its recommending barrage and shifting power far too early and barrage too many times. Just check Raidbot link.

### How to Reproduce

Do the rotation.

### Snapshot (Link)

https://pastebin.com/w4R4FPw9

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/nw4D21ixQRH9WYS7KHMXaH

### Contact Information

COLOSSAL

**Comment by syrifgit** [comment]
WIP on overhaul: https://github.com/syrifgit/hekili/tree/arcane-overhaul

Todo: 

Add handlers
- Spheres
- Burden
- Glorious

**Comment by davidmann4** [comment]
need any help? I would be happy to test it or help otherwise!

looking at your branch - did you saw the update on the simc apl?

https://github.com/simulationcraft/simc/blob/thewarwithin/ActionPriorityLists/mage_arcane.simc

it was 3 days ago. maybe interesting. 

looks like a lot of the buffs where tracked incorrectly. good catch!
