### ISSUE TITLE
Retribution profile fails finishers while levelling

### ISSUE THREAD

**Issue by jaw1976** [Hekili/hekili#367]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
While levelling a Retri Paladin Hekeli does not give any finisher moves. Eventually you end up without any recommendations. After tinkering a bit it seems the scripts assume that everyone has avenging wrath which only becomes available at level 80.

I think I fixed the issue by changing the finisher - wings_pool variable to start with "level < 80 | " before the previous evaluation, thus always returning true if character does not yet have avenging wrath.

**To Reproduce**
Fight anything with a retri pally below level 80.

**Expected behavior**
Hekeli should give finisher recommendations.

**Screenshots**
N/A
**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/2jD6S7ar

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/UdT946rX

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
Low levels are explicitly not supported, but looking at the information:

The priority is written with the expectation that you have Avenging Wrath or Crusade, and has logic to get you to avoid burning your Holy Power before it's time to hit AW or Crusade.

However, since you don't get Avenging Wrath until level 80, that logic is always ruling out DS and TV.

```List ( finishers ) called from ( Retribution:generators:2 ) would PASS at 0.00.
holy_power.current[5.00] >= 5 | buff.memory_of_lucid_dreams.up[false] | buff.seething_rage.up[false] | talent.inquisition.enabled[false] & buff.inquisition.down[true] & holy_power.current[5.00] >= 3
- this entry's criteria FAILS: variable.wings_pool[false] & ( ! talent.execution_sentence.enabled[false] | cooldown.execution_sentence.remains[0.00] > gcd.execute[1.38] * 2 | cooldown.avenging_wrath.remains[0.00] > gcd.execute[1.38] * 3 & cooldown.avenging_wrath.remains[0.00] < 10 | cooldown.crusade.remains[0.00] > gcd.execute[1.38] * 3 & cooldown.crusade.remains[0.00] < 10 | buff.crusade.up[false] & buff.crusade.stack[0.00] < 10 )
```

You could customize your priority here to remove the conditions from Retribution - finishers - 6 that are causing blockage:

`! talent.execution_sentence.enabled[false] | cooldown.execution_sentence.remains[0.00] > gcd.execute[1.38] * 2
`

And you'd want to do the same for Divine Storm in Retribution - finishers - 5.

`variable.ds_castable & ( ! talent.execution_sentence.enabled | ( spell_targets.divine_storm>=2 | cooldown.execution_sentence.remains > gcd * 2 ) )
`

Provided as-is, no warranty.  I won't be changing the base addon to support lower levels at all for BfA.  But hope that helps.

**Comment by jaw1976** [comment]
Thank you for the quick response. I did do a quick look around before posting the issue, but I couldn't find any reference to not supporting low levels. Apparently I did not look hard enough. It does make sense to only optimize for max level, but I find Hekili so good at learning the rotations for new classes while levelling them also.

Anyway, thank you for a great add on!
