### ISSUE TITLE
Unholy DK stops suggesting after a few abilities. Scourge Strike missing a lot

### ISSUE THREAD

**Issue by Naruske** [Hekili/hekili#368]
I don't know why it stops suggesting anything. Usually faster on single target than aoe

https://pastebin.com/awc29DRf

**Comment by Hekili** [comment]
Please use Pastebin for snapshots; GitHub formatting is terrible.

Your DK is level 81; the Unholy priority has logic built around AOTD which you don't have.  There may be other issues for lower levels.

The addon isn't intended to support levels below 110, because most priorities are written with the expectation that you have access to all your abilities and talents.

**Comment by Naruske** [comment]
Hi! It worked okay prior to me installing azerite UI. Something messed up the ability for your addon to see that the abilities were on my action bars so I removed azerite UI and now it's functioning again! Sorry for the trouble
