### ISSUE TITLE
[Destruction Warlock] Shadowburn being constantly recommended in interrupt window regardless of enemy HP percentage.

### ISSUE THREAD

**Issue by BalefireBombshell** [Hekili/hekili#3702]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Shadowburn is being recommended in the interrupt section of the rotation icons, at all times, regardless of whether the target health has dropped below 30%.  Shadowburn itself is designed to be optimally used as a pseudo-execute, as it gains a 100% chance to critically strike when used on enemies below 30% HP, and will refund its soul shard cost if it kills an enemy.  Having the ability be essentially recommended to be kept on cooldown seems counterintuitive to the design of the ability itself.

### How to Reproduce

1. Enter game as Destruction Warlock
2. Talent into Shadowburn
3. Click on a target with health above 30%
4. See Shadowburn flashing on your hotbar, and displayed in the Interrupt window of Hekili

### Snapshot (Link)

https://pastebin.com/UHdsdYuq

### Contact Information

scherzo1701 (Discord)

**Comment by Hekili** [comment]
Shadowburn would be appearing in the Interrupts window because you have added it to the Interrupts toggle.

It is not being shown "conditionlessly" but rather:

```
        53.  shadowburn ( default - 12 )
        The action (shadowburn) is usable at (0.00 + 0.00) with cost of 1 soul_shards (have 3).
         - the action is ready before the current recommendation (at +0.00 vs. +10.00).
         - this entry's criteria PASSES: ( cooldown.shadowburn.full_recharge_time[0.00] <= gcd.max[1.24] * 3 | debuff.eradication.remains[0.00] <= gcd.max[1.24] & talent.eradication.enabled[true] & ! action.chaos_bolt.in_flight[false] & ! talent.diabolic_ritual.enabled[false] ) & ( talent.conflagration_of_chaos.enabled[false] | talent.blistering_atrophy.enabled[true] ) | fight_remains[30.00] <= 8
```

The conditions met here are:
1. MET: You've capped on Shadowburn charges, so you might as well spend one and let it regenerate.
2. MET: Eradication is not active and you don't have a Chaos Bolt in flight and you're not a Diabolist.
3. NOT MET: You've taken Conflagration of Chaos.
4. MET: You've taken Blistering Atrophy.
5. NOT MET: The fight is almost over.

Shadowburn is recommended when either 1 or 2 and 3 or 4 are met, or if 5 alone is met.  In your case, it looks like hitting Shadowburn here would get your charges recharging, proc Eradication, and with +20% damage from Blistering Atrophy.

You could customize your priority to also require a target with health under 30% or slated to die within 5 seconds by updating its conditions to:

`( target.health_pct < 30 & target.time_to_die < 5 ) & ( `*all existing conditions here*` )`

**Comment by BalefireBombshell** [comment]
Precisely the behavior I was wanting, yes.  Thank you!
