### ISSUE TITLE
Hekili crush my fps

### ISSUE THREAD

**Issue by rogal223** [Hekili/hekili#373]
Hello. I have a problem with hekili before it was not changed the computer I have equipment now.
ryzen 5 3600
rtx 2070 super
16GB ddr4 3200
A problem such as that I have the fps addon enabled can sleep up to 0 when generating ~ 160fps on an instance.
as off the addon there is no problem with the stability of the game. can you help it somehow? I can't imagine playing without this add-on

**Comment by Hekili** [comment]
You'd have to submit a proper ticket so I'd know what version you're using, your character information, etc. 

I don't know what "can sleep up to 0" means.

**Comment by rogal223** [comment]
I'm using version 8.3.0-06. The game can go down to 0 fps. When people kill everything, fps returns. I am currently playing warrior prot

**Comment by Hekili** [comment]
Fill out the complete ticket and I'll look into it.

**Comment by rogal223** [comment]
where i found it?

**Comment by Hekili** [comment]
You deleted it when you made your initial submission.

**Comment by rogal223** [comment]
build: v8.3.0-06
level: 120 (120)
class: WARRIOR
spec: protection

talents: anger_management
    bolster
    booming_voice
    crackling_thunder
    into_the_fray
    rumbling_earth
    unstoppable_force

azerite: azerite_empowered = 3
    bastion_of_might = 2
    blood_rite = 1
    brace_for_impact = 1
    gutripper = 1
    heart_of_darkness = 1
    heed_my_call = 1
    impassive_visage = 2
    iron_fortress = 1
    moment_of_glory = 1
    overwhelming_power = 1

essences: [conflict_and_strife] = 3, aegis_of_the_deep = 3, strength_of_the_warden = 2, vision_of_perfection = 3

sets/legendaries/artifacts: none

gear: ashjrakamas_shroud_of_resolve = 1
    bonefetished_faceguard = 1
    boots_of_hallucinatory_reality = 1
    carapace_of_pulsing_vita = 1
    deathguards_vambraces = 1
    fusion_hacker = 1
    gauntlets_of_absolute_authority = 1
    heart_of_azeroth = 1
    humming_black_dragonscale = 1
    improvised_riot_shield = 1
    legplates_of_profane_sacrifice = 1
    malignant_leviathans_clasp = 1
    ring_of_cosmic_potential = 1
    sigil_of_warding = 1
    thornwoven_band = 1
    writhing_spaulders_of_madness = 1

corruptions: infinite_stars = 1
    twilight_devastation = 2

itemIDs: 157897, 158075, 159443, 159666, 162548, 165496, 168963, 168980, 169223, 173821, 173940, 174044, 174165, 174168, 174173, 174533

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Protection Warrior
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    free_revenge = true

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
So, first try the new beta and see if it makes a difference (it probably won't, but it makes it easier for me to test if I know that).

Second, if you're getting a performance hit like that, the instructions explain to get BugSack/BugGrabber and see if there are error messages that would point me toward a solution.  Get those addons and see if there are any logged errors.

With the information you provided so far, I can test a Protection Warrior that has your talents and some of your traits.

If there's more information about when you're seeing a slowdown (i.e., in big packs of enemies, in specific boss fights), that kind of information helps me investigate.

In the future, please keep the instructions in the ticket and fill in the blanks where it directs.  It makes it so we don't have to go back and forth like this before I can start looking at the potential problem.

**Comment by rogal223** [comment]
the most noticeable drops are on raid. on cleaning trash more mobs but also, for example, I have the image cut when I move the camera while doing rotation on the fire mage on training dummy in zuldazar. I noticed that where there is a hanging combination of skills, such things happen. I have already replaced the graphics card on rx 5700 xt, I checked the processor and memory for errors. there is nothing. I am surprised because with such equipment there should not be even a small cut

**Comment by Hekili** [comment]
So you posted issue reporting information for a Protection Warrior, but the problem you're experiencing is happening for you for a Fire Mage?  Both?  Neither?  Something else.

I'm going to close this ticket, and if you want to revisit it, submit a single complete ticket following the instructions provided, with information from when you're actually experiencing this issue.

If you're running into trouble with Fire Mage specifically, Fire will always use more CPU than other priorities, because if you have a Fire Blast available, it has to check to see if you can Fire Blast during a cast or before an impact before it checks other options.

You can try to reduce CPU usage a few different ways:

Each displayed icon costs more CPU to predict. You can show fewer icons via /hekili > Displays > Primary > Icons Shown.

You can throttle the number of allowed updates per second in /hekili > Fire > Performance.

You can cap the amount of CPU time it can use to make recommendations (same location as #2). If you throttle the time allowed for predictions, then if the addon crosses that threshold on the first or second recommendation, it will stop and won't calculate the second or third.

Otherwise, don't use it if it doesn't work well for you.
