### ISSUE TITLE
Arcane Sunfury AoE Opener Recommendation

### ISSUE THREAD

**Issue by Westside24ch** [Hekili/hekili#3780]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Mage - Arcane

### Describe the Issue

On Sunfury Arcane, during the AoE rotation it recommends Arcane Orb as my 2nd press after Evocation. I assume this is because High Voltage is talented, but from what I'm finding there doesn't appear to be a moment where Arcane Orb should be pressed before missiles in this opener.

### How to Reproduce

Enter as Arcane Mage with Sunfury and AoE talents. Make sure high voltage is talented. When standing in front of the target dummies, the addon will recommend Evocation, then Arcane Orb, and then Arcane Missiles. Arcane Missiles should be the 2nd recommendation in this situation, and Arcane Orb third when High Voltage is talented.

### Snapshot (Link)

https://pastebin.com/1L476ZcK

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/bGXqZ6r6iN3yBS9nnh5LSp

**Comment by Hekili** [comment]
This will require a regular (or quick) sim, not a top gear sim.

The `cd_opener` list includes using Arcane Orb at a high priority when you have fewer than four Arcane Charges.

**Comment by Westside24ch** [comment]
Gotcha. Obviously I'm just going off guides, and I don't see that as a condition anywhere, but obviously if it's in the APL somewhere, it'll get recommended.

https://www.raidbots.com/simbot/report/hhVPYP9UcePHdPSzD9cbLQ 

Here is a Quick AoE sim with optimal raid buffs. 

Also it may be worth noting, that when it comes to the opener, I'm not sure if it's possible to enter with more than the 1 charge you get from Evocation. Maybe it's something that you can replicate and see for yourself. I would assume guides would mention to Orb to get to 4 but for some reason none of them do.

**Comment by Hekili** [comment]
> Also it may be worth noting, that when it comes to the opener, I'm not sure if it's possible to enter with more than the 1 charge you get from Evocation. Maybe it's something that you can replicate and see for yourself. I would assume guides would mention to Orb to get to 4 but for some reason none of them do.

You're correct about having 1 charge from Evocation; here's what happened in the first several lines of your sim (you'll have to scroll sideways to see your `arcane_charge` buff/stacks to the right):

Time | # | Name [List] | Target | Resources | Buffs
-- | -- | -- | -- | -- | --
Pre | 0 | flask[precombat] | Candelario | 3330442.9/3330443 100% mana | spellfire_sphere(3), incanters_flow
Pre | 1 | food[precombat] | Candelario | 3318057.1/3318057 100% mana | spellfire_sphere(3), incanters_flow
Pre | 2 | augmentation[precombat] | Candelario | 3318057.1/3318057 100% mana | spellfire_sphere(3), incanters_flow
Pre | 3 | arcane_intellect[precombat] | Fluffy_Pillow | 3318057.1/3318057 100% mana | spellfire_sphere(3), incanters_flow
Pre | 4 | aoe_target_count[precombat] | Candelario | 3649862.9/3649863 100% mana | spellfire_sphere(3), incanters_flow
Pre | 6 | opener[precombat] | Candelario | 3649862.9/3649863 100% mana | spellfire_sphere(3), incanters_flow
Pre | 7 | sunfury_aoe_list[precombat] | Candelario | 3649862.9/3649863 100% mana | spellfire_sphere(3), incanters_flow
Pre | 8 | steroid_trinket_equipped[precombat] | Candelario | 3649862.9/3649863 100% mana | spellfire_sphere(3), incanters_flow
Pre | A | mirror_image[precombat] | Fluffy_Pillow | 3649862.9/3649863 100% mana | spellfire_sphere(3), incanters_flow
Pre | C | evocation[precombat] | Fluffy_Pillow | 3649862.9/3649863 100% mana | spellfire_sphere(3), incanters_flow
0:00.000 | D | potion[default] | Fluffy_Pillow | 3649862.9/3649863 100% mana | **arcane_charge**, big_brained, clearcasting, siphon_storm(7), spellfire_sphere(3), incanters_flow
0:00.000 | E | use_items[default] | Fluffy_Pillow | 3773235.7/3773236 100% mana | bloodlust, **arcane_charge**, big_brained, clearcasting, siphon_storm(7), spellfire_sphere(3), incanters_flow, tempered_potion
0:00.000 | M | arcane_orb[cd_opener] | Fluffy_Pillow | 3773235.7/3773236 100% mana | bloodlust, **arcane_charge**, big_brained, clearcasting,  siphon_storm(7), spellfire_sphere(3), incanters_flow, quickwicks_quick_trick_wick_walk, tempered_potion
0:00.871 | O | arcane_missiles[cd_opener] | Fluffy_Pillow | 3773235.7/3773236 100% mana | bloodlust, **arcane_charge(4)**, big_brained, clearcasting,  siphon_storm(7), spellfire_sphere(3), incanters_flow,  quickwicks_quick_trick_wick_walk, tempered_potion
0:01.744 | P | arcane_surge[cd_opener] | Fluffy_Pillow | 3773235.7/3773236 100% mana | bloodlust, aether_attunement_counter, **arcane_charge(4)**,  arcane_harmony(5), big_brained, high_voltage, nether_precision(2),  siphon_storm(7), spellfire_sphere(3), incanters_flow(2), quickwicks_quick_trick_wick_walk, tempered_potion

You can see here that, as written, Evocation leads to one Arcane Charge.  Potion, generic Use Items (looks like Quickwick's trinket), and Arcane Orb all at 0:00.000, after which Arcane Charges stack to 4.  Then Arcane Missiles is cast, then Arcane Surge.

The next Arcane Surge into Touch of the Magi is a little over a minute into the fight.  There's no usage of Arcane Orb to gain Arcane Charges because your sim was already sitting at 4 stacks:

Time | # | Name [List] | Target | Resources | Buffs
-- | -- | -- | -- | -- | --
1:18.509 | R | arcane_barrage[sunfury] | Fluffy_Pillow | 3079823.1/3649863 84% mana | aether_attunement_counter(2), arcane_charge(4), arcane_harmony(6),  arcane_tempo(5), enlightened_damage, high_voltage, nether_precision,  glorious_incandescence, mana_cascade(6), spellfire_sphere(5),  spellfire_spheres(2), incanters_flow(2), overflowing_energy, time_warp,  egg_sac(3), flask_of_alchemical_chaos_crit
1:19.363 | N | evocation[cd_opener] | Fluffy_Pillow | 3355487.3/3649863 92% mana | aether_attunement_counter(2), arcane_charge(4), arcane_tempo(5),  enlightened_damage, high_voltage, mana_cascade(6), spellfire_sphere(5),  spellfire_spheres(3), incanters_flow, time_warp, egg_sac(2),  flask_of_alchemical_chaos_crit
1:21.449 | P | arcane_surge[cd_opener] | Fluffy_Pillow | 3649862.9/3649863 100% mana | aether_attunement_counter(2), arcane_charge(4), arcane_tempo(5),  big_brained, clearcasting, enlightened_damage, high_voltage,  siphon_storm(7), mana_cascade(6), spellfire_sphere(5),  spellfire_spheres(3), incanters_flow(2), time_warp, egg_sac(2),  flask_of_alchemical_chaos_crit
1:22.870 | T | arcane_barrage[sunfury] | Fluffy_Pillow | 751534.2/3649863 21% mana | aether_attunement_counter(2), arcane_charge(4), arcane_surge,  arcane_tempo(5), big_brained, clearcasting(2), enlightened_mana,  high_voltage, siphon_storm(7), mana_cascade(5), spellfire_sphere(5),  spellfire_spheres(3), incanters_flow(3), egg_sac(2),  flask_of_alchemical_chaos_crit
1:22.870 | L | touch_of_the_magi[cd_opener] | Fluffy_Pillow | 970525.9/3649863 27% mana | aether_attunement_counter(2), arcane_surge, arcane_tempo(5),  big_brained, clearcasting(2), enlightened_mana, high_voltage,  siphon_storm(7), mana_cascade(7), spellfire_sphere(5),  spellfire_spheres(4), incanters_flow(3), egg_sac(2),  flask_of_alchemical_chaos_crit

If/when there are sim updates to alter this behavior, I'll incorporate into the addon, but it appears to be a very-intentional inclusion as written.  Often, guides are simplified a bit vs. the sim profile, and the addon's design philosophy is to be as consistent with sim profiles as possible.

**Comment by syrifgit** [comment]
It's really easy to just look at the class guide. Free, even.

![image](https://github.com/user-attachments/assets/15914304-037c-47b5-ab43-c8cca64e0e94)

**Comment by Westside24ch** [comment]
Lol, of the guides I watched and read, figures Icyveins has it right there in the rotation. Shoulda checked there, my fault. Thanks both for your clarification!

**Comment by GitBearded** [comment]
![IMG_8052](https://github.com/user-attachments/assets/c12eebca-490e-40a9-aeaf-69fcf23e8cee)

It’s even in the wowhead guide.
