### ISSUE TITLE
[REC] elemental blast has 2 charges and only gets recommended when you have 2 charges 

### ISSUE THREAD

**Issue by nalby1992** [Hekili/hekili#3781]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

addon recommends lightning bolt to insta cast instead of elemental blast when i have only 1 charge of the ability available always recommends properly when im at 2 charges 
[New Text Document.txt](https://github.com/user-attachments/files/17004330/New.Text.Document.txt)

### How to Reproduce

single target build with elemental blast picked in talents as enha shammy, do the rotation normally with cooldowns on, keep doing rotation until u have elemental wolves active and it recommeds you to do lightining bolt instead of elemental blast while still having 1 charge of elemental blast available

### Snapshot (Link)

https://pastebin.com/3yjuQWLn

**Comment by Hekili** [comment]
There is a higher priority entry for Elemental Blast:
` - this entry's criteria FAILS: buff.tempest.stack[0.00] < buff.tempest.max_stack[10.00] & buff.maelstrom_weapon.stack[8.00] >= 5 & talent.elemental_spirits.enabled[true] & feral_spirit.active[2.00] >= 2 & feral_spirit.remains[6.53] <= 2 * gcd.max[1.18]`

In this case, it's waiting for Feral Spirit to be near expiration, likely to prioritize Lightning Bolt with the lightning dog buff. Otherwise, the Elemental Blast entry to avoid overcapping charges will come into play.

**Comment by Hekili** [comment]
The 1.0.14 release will include an updated SimC priority that it looks like will use Elemental Blast more aggressive.
