### ISSUE TITLE
Symbols of Death recommended too early in opener

### ISSUE THREAD

**Issue by dlogan1990** [Hekili/hekili#3815]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - subtlety

### Describe the Issue

Very early in the sub rogue opener, the addon telling me to press symbols of death right before the cooldown window starts. All theory crafter guides recommend pressing it in the same global as shadow dance, AFTER Flagellation + Finisher . I believe this will lead to Symbols of Death being misaligned in your opener and result in a damage loss. I have included a screenshot of the recommended opener on wowhead.

![sub SOD](https://github.com/user-attachments/assets/9d3f1c17-cc57-4ce1-a8b9-4980ac1f1e65)

### How to Reproduce

1. Enter game as subtlety rogue.
2. On a target dummy, Steath then cast Shadowstrike, Slice and Dice Shadowstrike , Shadowstrike.
3. Will See the addon recommend pressing Flagellation, Symbols of death, then rupture. Symbols of death should be pressed AFTER the rupture with Shadow Blades and Shadow Dance.

### Snapshot (Link)

https://pastebin.com/4RYnbWAN

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/uW55rYfWVwd4qMCM8dsqj8

### Contact Information

devinnthedude - Discord

**Comment by syrifgit** [comment]
Your sim disagrees with that image. The sims and the addon agree that symbols is before rupture. If you think this is incorrect, you should bring it up with the rogue theorycrafters so that the sims can be changed and the addon will follow suit. Otherwise you can do some custom simming to prove that using symbols afterwards is a DPS gain, and the addon could be changed despite the sims.

![image](https://github.com/user-attachments/assets/63cb8187-4652-488b-b06f-58372ab19df6)
