### ISSUE TITLE
Immolation aura didnt show on havoc

### ISSUE THREAD

**Issue by JGBG78** [Hekili/hekili#3816]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DH - Havoc

### Describe the Issue

Its seems there is a bug with immolation aura, its like it was uncheck for the rotation (little red star between name in the list) but the spell is do

### How to Reproduce

https://cdn.discordapp.com/attachments/307520968895627264/1286410233878548590/image.png?ex=66ee7724&is=66ed25a4&hm=7a8a5836834280b6302fbe94624b092481cbbc9d0369d72ac1f39be801a32cc5&

### Snapshot (Link)

https://pastebin.com/JNh5Ws1W

**Comment by syrifgit** [comment]
The screenshot link doesn't work and the the snapshot you posted is only 1 icon and it is out of combat, so I cannot actually get any information from it because it ends so quickly.

That being said, sounds to me like you accidentally disabled the ability. Go to the Abilities page, find it in the list, and enable it. If that doesn't work, you may re-open this ticket with a new snapshot, in combat and showing multiple icons ideally. 

If you require support in French I can also respond in French.
