### ISSUE TITLE
[REC] Ret Pala in multi target situations judgement nearly never gets recommend 

### ISSUE THREAD

**Issue by scythelow** [Hekili/hekili#3881]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Paladin - Retribution

### Describe the Issue

in AoE situation 5+ targets my Blade of Justice resets very often and the addon always priotize it over judgement even if all target have expurgation on them and / or dont have greater judgement debuff. wowhead rotation guides say you prioritize Blade of Justice in AoE Situation but only to spread Expurgation debuff on more targets. my sim also uses Judgement more freaquently in AoE fights.

### How to Reproduce

find 3+ targets and just start attacking

### Snapshot (Link)

https://pastebin.com/DxTFv45X

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/wtPURPzK8YdyYv9Zx5eSP2

### Contact Information

mindlessself

**Comment by syrifgit** [comment]
Your sim is casting 3x as many blade of justice as judgment.

The class guide also lists blade ad higher priority than judgment regardless of this expurgation. I'm not seeing this thing you're referring to about only using it to spread a debuff. Can you provide a direct source?

Seems you are misunderstanding the class rotation to me?

**Comment by scythelow** [comment]
The AoE priority is very similar to single target, with the most important change being the swap to Divine Storm as your primary Holy Power spender, and an increase in priority of[ Blade of Justice](https://www.wowhead.com/spell=184575/blade-of-justice) due to the power of cleaving[ Expurgation](https://www.wowhead.com/spell=383344/expurgation) debuffs. You will want to swap to the AoE priority at 2 or more targets.

**Comment by scythelow** [comment]
thats what it says on wowhead and also if i get divine purpose procc it still recommends to use wake of ashes even if it waste a divine purpose buff there

**Comment by scythelow** [comment]
i was just asking if you should rather still use judgement more often in aoe situations since if i get a lot of art of war procs it never recommends judgements then anymore. you might be right that i dont understand it if so im sorry.

**Comment by syrifgit** [comment]
Can you screenshot or reference exactly where it says to only use blade of justice to spread that debuff? I couldn't find anything

**Comment by scythelow** [comment]
no i doesnt im not sure either i can try to ask in paladin class discord

**Comment by scythelow** [comment]
even if its not correct to not use judgement ever in AoE situations, the divine purpose thing you did not even answer to?

**Comment by Hekili** [comment]
The first Blade of Justice entry is ruled out because Expurgation is ticking:

```
25.  blade_of_justice ( generators - 4 )
The action (blade_of_justice) is usable at (0.00 + 0.00).
 - this entry's criteria FAILS: ! dot.expurgation.ticking[true] & talent.holy_flames.enabled[false]
```

The next Blade of Justice is selected because its criteria are met, specifically that you have 3 or fewer Holy Power / Holy Blade is not talented and there are 2+ targets with Blade of Vengeance talented.  Basically every condition for its use are met.

```
30.  blade_of_justice ( generators - 9 )
The action (blade_of_justice) is usable at (0.00 + 0.00).
- this entry's criteria PASSES: ( holy_power.current[1.00] <= 3 | ! talent.holy_blade.enabled[false] ) & ( spell_targets.divine_storm[3.00] >= 2 & talent.blade_of_vengeance.enabled[true] )
```

The first entry for Judgment is 3 entries later, so it is not even tested, but would've been met if Blade of Justice's conditions weren't met or if it were still on CD:  `( holy_power.current[1] <= 3 | ! talent.boundless_judgment.enabled[true] )`

The Wowhead guide by Bolas shows this as well, except with more lenient requirements for using Blade of Justice over Judgment:

![image](https://github.com/user-attachments/assets/66791f6c-24f4-4ab4-b1ae-dbcd28487e95)

I made a quick, revised comparison sim where the second Blade of Justice ( generators - 9 ) also checks for a Judgment debuff up or that Judgment is on cooldown.  It is a (small) DPS loss; though maybe it could be refined further.

![image](https://github.com/user-attachments/assets/fdc790c7-4b52-459b-adc0-f1e68179f31c)

https://www.raidbots.com/simbot/report/fW9afVN9vAewisztYjREGe/simc
