### ISSUE TITLE
[REC] Explosive shot not being recommended for MM in Single target

### ISSUE THREAD

**Issue by Stoufs** [Hekili/hekili#3893]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Hunter - Marksmanship

### Describe the Issue

Explosive shot is not being recommended for Single target recommendations.

### How to Reproduce

Target dummy

### Snapshot (Link)

https://pastebin.com/qN3vqPAh

**Comment by syrifgit** [comment]
Unable to reproduce, it is being recommended just fine in ST.

https://pastebin.com/9ncQdcLX

`Marksmanship; Primary - Explosive Shot(0.03), Steady Shot(1.32), Aimed Shot(2.79)`

https://www.raidbots.com/simbot/report/gKAr49wQRUy51M3XYYzwJD

If you stand at a dummy for over 2 minutes, it never recommends it even a single time? Because it's not very high priority, the sim doesn't even use it until 45 seconds into combat, it's like the 17th priority in Single Target.

**Comment by Hekili** [comment]
Illustrating Syrif's answer:

![image](https://github.com/user-attachments/assets/6f828c74-78c5-43d6-9607-93bc52a1bd1c)

The higher priority Explosive Shot (highlighted at top) actually requires multiple targets, even on the single target action list.

The lower priority one doesn't require multiple targets, but is only recommended when all of the higher priority actions/conditions are not met first.
