### ISSUE TITLE
Blood DK's Heart Strike shows incorrectly

### ISSUE THREAD

**Issue by Dajova** [Hekili/hekili#393]
**Describe the Bug/Issue**
Rune cooldown does not match on Heart Strike what's actually shown.

**To Reproduce**
- Play Blood DK (have not tested other specs yet)
- Do your usual rotation
- Addon suggests that the ability/rune is on cooldown while it is not.

**Expected behavior**
Heart Strike shows as avaiable and usable.

**Screenshots**
![image](https://i.imgur.com/AMAxWe2.png)

**Issue Reporting**

[https://pastebin.com/ptwj7FLf](https://pastebin.com/ptwj7FLf)

**Snapshot**
 
No reported snapshot.

**Error**

No error, just showing incorrectly.

**Comment by Hekili** [comment]
Can you make use of the "pause" feature and mouseover the Heart Strike icon when this happens.

I suspect it's not about rune availability and that it's about waiting for other conditions to be met.

**Comment by Dajova** [comment]
Hmm, this is odd. After hitting 60, i've been unable to re-create the issue. I'll report back if it happens again.

**Comment by Dajova** [comment]
Alright, got it to happen again. This is what it said:
![https://i.imgur.com/s76ikgA.png](https://i.imgur.com/s76ikgA.png)
![https://i.imgur.com/7jMkyzo.png](https://i.imgur.com/7jMkyzo.png)

**Comment by Hekili** [comment]
The `rune.time_to_3` and `rune.time_to_4` conditions impact *when* the action is recommended.  That's consistent with the priority as written.

Usually, it doesn't matter a whole lot if you go ahead and spend down your runes, but the priority is conservative with spending runes so that you'll be able to Marrowrend if you need to do so.

Most of the time, it's safe to ignore it and go ahead and Heart Strike, but if you're taking hits and Heart Strike while you're low on runes, you can put yourself in a situation where your Bone Shield stacks get low and now you're waiting.
