### ISSUE TITLE
[REC] Guardian druid removing Rage of the Sleeper from recommendation after using Incarnation

### ISSUE THREAD

**Issue by aaronlilla** [Hekili/hekili#3933]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Druid - Guardian

### Describe the Issue

Rage of the sleeper will be correctly recommended to be used after incarnation, pairing them together- until you actually use Incarnation and then Rage of the Sleeper will be totally removed from the recommendations until some later time. Sometimes it will constantly flash in the rotation for a second before disappearing again.

### How to Reproduce

Enter game as Guardian Druid
Get into combat with 5 dummies pack
Note how it will recommend Thrash -> incarn -> rage of the sleeper etc..
Hit Incarnation, note how Rage of the sleeper is now removed from recommendations

### Snapshot (Link)

https://pastebin.com/sttH7jqc

### Additional Information

Before using Incarnation:
https://pastebin.com/sttH7jqc

After using Incarnation:
https://pastebin.com/Lz4E6h85

**Comment by syrifgit** [comment]
The addon thinks the thrash spam is more important and doesn't make it down to the rage entry. Not idea if that's correct. but that's what is happening

**Comment by Hekili** [comment]
Syrif's description is correct; the reason the recommendations change suddenly is that *initially, Thrash is on CD but Incarnation takes away its CD*.  That implies:
1. The CD reset/elimination from Incarnation is probably not modeled correctly.
2. As written, Rage of the Sleeper won't get used unless you have fully-stacked Thrash bleeds.

Possible solutions:
1. Possible `line_cd` for Thrash so that it won't Thrash repeatedly, but that may backfire at other times (i.e., you don't have anything but Thrash to push anyway).
2. Move Rage of the Sleeper up in priority above Thrash, but most of its conditions want you to have > 40 Rage, presumably to be able to Maul/Raze and make use of the Leech bonus.  That means you could theoretically still Rage starve yourself enough to stay under 40 Rage and still keep Thrashing away, but it'd probably be harder.
3. Could probably flag Rage of the Sleeper to `use_off_gcd` which would then allow it to weave in during a Thrash GCD, assuming its other requirements are still met.

Option 3 is probably the way that I'll go, but not 100% certain.

*edit: Correction about why Thrash wasn't initially recommended.*

**Comment by syrifgit** [comment]
Guardian Druid modelling was significantly improved in November, this shouldn't be happening anymore. The CD of thrash was way off in the model, so the addon "reacting" was it realizing thrash was in fact available, when it didn't think it would be (due to outdated model).
