### ISSUE TITLE
Unholy DK recommendations stop when cooldown toggle enabled

### ISSUE THREAD

**Issue by xaqbr** [Hekili/hekili#395]
**BEFORE SUBMITTING AN ISSUE:**

**Describe the Bug/Issue**
Randomly in the middle of the battle, the add-on will stop showing recommendations even though most of my other skills are ready and available to use.

**To Reproduce**
- Playing as Unholy DK
- Enable "Show Cooldowns" in Toggles
- Attack any enemy

**Expected behavior**
Recommendations should continue, not disappear completely. I understand no recommendation is not technically an error, but shouldn't it at least suggest _something_ in this case?

**Screenshots**
I have a video available here: https://i.imgur.com/kaOJsdu.mp4

**PUT ISSUE REPORT LINK HERE:**

https://pastebin.com/XzaFwAjz
 
**PUT SNAPSHOT LINK HERE:**

https://pastebin.com/DgdW9q0U

**Comment by Hekili** [comment]
The issue here is that the priority is written to Scourge Strike / Clawing Shadows at >4 Festering Wounds, and Festering Strike at <4 Festering Wounds.

When you're sitting at 4 Festering Wounds and nothing higher priority is ready, you have nothing to do.  The addon is basically waiting for a wound to be applied or for circumstances to change otherwise.

I've run sims that reflect it is DPS neutral or even DPS positive to allow SS/CS at >=4 Festering Wounds, so I will probably go ahead and make that modification.

**Comment by xaqbr** [comment]
Here is a better video: https://i.imgur.com/jOahsTz.mp4
Issue report: https://pastebin.com/yw7AgxxU
Snapshot link: https://pastebin.com/qZACZiqX

**Comment by Hekili** [comment]
The new release includes a tweaked priority that should avoid the 4 FW issue.
