### ISSUE TITLE
[REC] The problem is the shaman's AoE

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#3954]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

Problem with the implementation of Conductive Energy talent in AOE through the use of Pwave. The recommendations that are offered, they are not correct. He suggests to use after Pwave ->Lava Lash -> Chain Lighting when we have 6 targets under Flame Shock buff. And should be done like this Pwave -> Lava Lash -> Lightning Bolt (Tempest) to trigger the talent Conductive Energy and hang on the target Lightning Rod, which will later strengthen Chain Lighting. And now he uses Chain Lighting without Lightning Rod when only 1 target will be with this buff and the other 5 without, and at the end of Pwave he will use Lightning Bolt(Tempest). And in AOE he uses Tempest very little, even under Ascendance he keeps his stacks to 10 max. The logic of rotation is not clear in AOE and his recommendations. 

### How to Reproduce

Approach the training dummies in the city.
And follow the recommendations of the addon. 
As will be ready for the second time Pwave to look at the sequence of actions in the recommendations of the addon.

### Snapshot (Link)

https://pastebin.com/5n9XT56E

**Comment by syrifgit** [comment]
Please provide an AoE sim for your character.

https://www.raidbots.com/simbot/quick

**Comment by geraint425** [comment]
https://www.raidbots.com/simbot/report/tFNW76rSAbXELDaDXJcJQn

**Comment by syrifgit** [comment]
Seems to be a non-issue. I am unable to replicate it in the opener, it picks lightning bolt the first time.

There are other times in the rotation that it does chain lightning after, but so does your sim. It is building up to tempest, which will apply lightning rod just like lightning bolt. So this is expected. Additionally, it is also because you need to spend your arc discharge stacks before getting tempest, and lightning bolt will not consume these.

![image](https://github.com/user-attachments/assets/f5d578f8-13be-4d66-9ec4-d01c65c228b6)

I am also unable to replicate "not using tempest often". It's using it consistently, and almost immediately every time. The logic is pretty clear, it follows the sims as far as I can tell.
