### ISSUE TITLE
[REC] Do not recommend Bloodthirst/Bloodbath while Ravager is active with Unhinged (Fury Warrior)

### ISSUE THREAD

**Issue by dubudevs** [Hekili/hekili#3969]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warrior - Fury

### Describe the Issue

While Ravager is active with Unhinged talented it will automatically trigger Bloodthirst and Bloodbath (practically) off cooldown. This causes jumpy recommendations because it goes on cooldown unexpectedly. Critcake describes this during his opener in his video on the "new" thane m+ build here: https://youtu.be/d6gN1lOSLPw?t=239

### How to Reproduce

Play Fury
Play Ravager and Unhinged
Observe that during Ravager Bloodbath will often be in the 2nd or 3rd recommendation slot and disappear because its low on the priorities and will never be available when you would get to that action on the list it due to automatically triggering.

### Snapshot (Link)

https://pastebin.com/x4R0GYH3

**Comment by syrifgit** [comment]
Probably set ravager / BS to queue that event on every 2nd tick, but need to figure out the tickspeed for bladestorm.

**Comment by johnnylam88** [comment]
Bladestorm ticks every second. Ravager ticks every 2 seconds. I believe that these tick intervals are unaffected by haste.

**Comment by Hekili** [comment]
I'm tempted to "simplify" this because queued events are computationally expensive -- the addon has to test the APL before an event, then if it doesn't find something it can use, test between the first event and the next, and repeat until something can be recommended.

By simplify, I mean calculate the 'functional' CD of BT/BB during Ravager/Bladestorm and just apply it during the reset or the cast of R/BS.

**Comment by dubudevs** [comment]
The expected behaviour would be the same assuming you press recklessness and ravager at the same time, you never want to manually press BT/BB manually even though it is pressable. 

The exact behaviour is weird, I misexplained it slightly in op. It doesnt entirely put it on cd, it just consumes the rampage BB buff, meaning if you do manually press it then you are pressing it for BT which is very low priority. This is why the recommendations flash, you get a BB proc after pressing rampage which is 2-3 gcds down the prio but it is very quickly consumed by ravage so the recommendation disappears because you dont want to press BT. Even if the buff wasnt consumed on this rampage "cycle" you still do not want to press it because you will have rage to press rampage again by the time you get to that point which is higher prio.

The actual 1st position recommendations are not affected by this at all as the APL correctly doesnt ever get to recommend it because the buff is consumed, only the jumpiness of the 2-3rd future recommendation.

**Comment by johnnylam88** [comment]
I don't think it's worth changing anything in the addon to accommodate this. It's easier to just adjust the APL to not suggest Bloodthirst during Bladestorm with that talent, and as a practical matter this only helps clean up the recommendation queue -- the actual first recommendation will always be correct.

**Comment by syrifgit** [comment]
could add a BT/BB restriction to avoid deviating the APL.

`nobuff = function () return talent.unhinged.enabled and "bladestorm" or nil`, not sure about ravager, does it have a trackable buff?

(also I think that might be redundant since you're channeling bladestorm anyways? idk haven't played warrior in a minute lol)

**Comment by Hekili** [comment]
The issue is that there's a difference between disallowing BT/BB during Bladestorm from a forecasting perspective.  If BT/BB are triggered on the last tick of BS/BB, it's on cooldown and won't be the next recommendation after Bladestorm.  If they aren't, they could conceivably be the next button pushed after Bladestorm.  Unless I'm still missing something.

**Comment by dubudevs** [comment]
Unhinged doesnt put the button on CD its used for triggering Rampage empowered BB procs, in the current builds you do not want to manually press BT/BB at all because you would only ever press it during this window if you could press it as BB because BT does so little damage. 

HOWEVER Fury is recieving relevant changes with the next reset that may change this, so you could hold of on making any changes for now.
