### ISSUE TITLE
QOL Requests

### ISSUE THREAD

**Issue by mspykerez** [Hekili/hekili#397]
Hi! This is sorta of a QOL request. Can you plz make it so the addon on 'Abilities' and 'Gear and Trinkets' tabs marks the abilities or items that are manually disabled or set to show on 'boss encounter only' as grey/red respectively (like it already happens on the action lists).

Also would be great if we could manually enter new/old items that are not present on the 'Gear and Trinkets' list.

ps. I'm taking this opportunity to ask if an ability such as bloodlust for the horde that has a different name for the alliance (heroism) is automatically converted to the corresponding faction name in the priorities/action lists that have the ability ?

**Comment by Hekili** [comment]
The first part makes sense and can be done in a clean way with Shadowlands (nesting color codes in strings is improved in 9.0).

Being able to add gear/trinkets is a bit complicated.  It can work *most* of the time but the problem is that a fair number of items require more than the basic "has itemID, has cooldown, applies X buff or debuff" logic.

I genuinely don't recall if Bloodlust and Heroism automatically convert at this point in time.  I don't recommend having (regular) Bloodlust in a DPS priority because when to use Bloodlust is a raid leader decision.

**Comment by Hekili** [comment]
Disabled abilities/gear/trinkets will now (in -alpha42 and higher) be shown in red in the dropdown on their respective options tabs.

This has an additional side-effect -- disabled entries will be moved to the bottom of the dropdown.
