### ISSUE TITLE
[REC] No Shadow Embrace recommendation in MT rotation.

### ISSUE THREAD

**Issue by Jumimaru** [Hekili/hekili#3980]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warlock - Affliction

### Describe the Issue

Hitting drain soul for SE stacks before soul rot -> summon darkglare then rapture spam is essential in the aff rotation.

This is not the case now when you follow the MT opener.

### How to Reproduce

Spec into Aff and talent drain soul and SE. Then follow the MT opener.

### Snapshot (Link)

https://pastebin.com/Zr2cPG6W

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/fyvXiKj7mLXjtnLaHhKMgc

### Additional Information

Spec into Aff and talent drain soul and SE. Then follow the MT opener.

**Comment by Hekili** [comment]
Your snapshot needs to be taken at the time the issue occurs; not out of combat pre-pull.  It sounds like this would be if/when the addon recommends Soul Rot without using Drain Soul for Shadow Embrace stacks.

Also -- it's worth noting that the sim you provided opens with the following:

![image](https://github.com/user-attachments/assets/b745d913-2adc-440c-bd6f-5ef3707d22ff)

That is, Soul Rot followed by Drain Soul followed by Summon Darkglare.  The Drain Soul entry that was used requires that there are 4 or fewer targets, so that condition would not be met with 5 target dummies.  Your snapshot was taken with 5 targets (the cleave dummies), so I re-ran your sim with 5 targets.  When I do so, Drain Soul does not get recommended at that point.

![image](https://github.com/user-attachments/assets/4f72157f-0a02-4d39-9db5-f9ac0e0f3c83)

I also ran a comparison sim where I increased that target count, to see if it's a DPS gain to Drain Soul for Shadow Embrace at 5 targets.

![image](https://github.com/user-attachments/assets/7c0e1127-9b34-4fb5-8f95-a2b9180b3227)

That's *almost* effectively no difference, though it's a higher bottom-end and higher top-end damage with 5 targets:

![image](https://github.com/user-attachments/assets/cfcf2c6f-2670-4ae1-872b-f3d0f2af903f)

The top-end and bottom-end shifts back and forth as you add more targets (my edit will Drain Soul at up to 10 targets).  I tried Hectic Add Cleave as well, but that's generally going to have SE stacks up since you start that sort of fight with a single-target before adds come out.

I think the logic here is probably that if you're fighting a pack of enemies, it's *probably* an add wave and none of them will *probably* survive long enough to be worth delaying your CDs (i.e., you Drain Soul, apply the SE stacks, target dies, switch targets, need to apply the SE stacks again, target dies, ad infinitum).

If this issue occurs with fewer than 5 targets, please add an updated snapshot and reopen the ticket.  Thanks!
