### ISSUE TITLE
[REC] Darkglare getting recommended before Drain Soul in opener

### ISSUE THREAD

**Issue by Reshuffling** [Hekili/hekili#3988]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warlock - Affliction

### Describe the Issue

Affliction lock, in single target opener Hekili recommends Darkglare before Drain Soul which is wrong compared to the APL.

### How to Reproduce

Play Affli
Play Shadow Embrace

### Snapshot (Link)

https://pastebin.com/LR9H7HK0

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/dPc1PukVjJnj5vtHnanPNf

### Contact Information

Hardan in Discord

**Comment by Hekili** [comment]
There is a pending update which addresses this issue (checking for Shadow Embrace to be maxed before Summon Darkglare) in single-target.

Drain Soul was otherwise ruled out in your snapshot based on being Soul Shard capped, but this should've reached another Drain Soul entry that would've fired instead.  Fix should be available later today.
