### ISSUE TITLE
[REC] Recommending manual VT redot when Shadowcrash is available in aoe (no unfurling) - Shadow Priest

### ISSUE THREAD

**Issue by dubudevs** [Hekili/hekili#3991]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Priest - Shadow

### Describe the Issue

Noticed that occasionally the addon will recommend to manually redot targets in aoe when shadowcrash should be used, and is correctly recommended elsewhere. I wasn't able to track down the cause :(

This happens in real content too.

### How to Reproduce

Play Shadowcrash
Hit dummies
Wait

### Snapshot (Link)

https://pastebin.com/mSzMZ8Ey

**Comment by dubudevs** [comment]
https://pastebin.com/EPtu2WBQ Here's a new snapshot on the live 11.0.5-1.0.2 showing the same issue

**Comment by syrifgit** [comment]
For some reason, when shadow crash checks if the dot is refreshable at `+2.47`, it thinks the answer is no.

When Vamp Touch checks if the dot is refreshable at the same point in time, `+2.47`, the answer is yes.

Will look more later.

**Comment by Hekili** [comment]
I'm making a few adjustments that may help to resolve this issue.

1. Shadow Crash will use target cycling based on Vampiric Touch if Whispering Shadows it talented.
2. buff/debuff/dot.X.refreshable will be subject to recheck timings.
3. Vampiric Touch, if Misery is talented, will target cycle based on SWP/VT (whichever has less time remaining).
4. `raid_event` related conditions removed from the priority.
5. Vampiric Touch's `max_targets` value set to `1`, so `spell_targets.vampiric_touch` will always equal 1 (until/unless there's a mechanic that makes it hit multiple targets; lmk if overlooked something).

This means:

> 24.  shadow_crash ( aoe - 3 )
> - `no aura identified for target-cycling and no aura matching shadow_crash found in ability / spec module; target cycling disabled.`

Addressed by item 1.

> The action (shadow_crash) is usable at (0.00 + 0.00).
> - the action is ready before the current recommendation (at +0.00 vs. +10.00).
> List ( aoe ) called from ( Shadow:default:4 ) would PASS at 0.00.
> - active_enemies[5.00] > 2
>  - this entry's criteria FAILS: ! variable.holding_crash[false] & ( `dot.vampiric_touch.refreshable[false]` | dot.vampiric_touch.remains[11.56] <= target.time_to_die[47.00] & ! buff.voidform.up[false] & ( raid_event.adds['in'][3600.00] - dot.vampiric_touch.remains[11.56] ) < 15 )

Addressed by item 2; since VT has 11.56 seconds, the addon will check if it should use Shadow Crash in ~5.26 seconds (when VT is at 30% of its 21s apply duration).

Item 5 should alter some VT entries' by impacting `max_vts`:

> max_vts 1 [Shadow:precombat:5]; conditions = PASS: NONE
> - value = 12: NONE
> max_vts 2 [Shadow:aoe_variables:1]; conditions = PASS: NONE
> - value = 5: spell_targets.vampiric_touch[5.00] >? 12

`max_vts` would equal 1 here instead of 5.

**Comment by Oxyhydrogen455** [comment]
https://pastebin.com/u8YiGUzE

new snapshot on the live showing the same issue
at some Point i just spamm VT

**Comment by Hekili** [comment]
@Oxyhydrogen455 Your snapshot recommends Void Torrent. I can see that you did cast Vampiric Touch 4x before the snapshot, but the snapshot needs to be taken when Vampiric Touch is shown.

It looks like the last Vampiric Touch was used to proc Unfurling Darkness, which will happen even if Vampiric Touch is already up. I'll need a snapshot of each recommendation to identify the defect.

**Comment by Hekili** [comment]
Should be resolved in 1.0.7 (probably).
