### ISSUE TITLE
SIN Rogue: Disappearing Addon again :D

### ISSUE THREAD

**Issue by DrWren** [Hekili/hekili#4059]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Started on H Queen, pulled boss, did opener, and addon disappeared,  autosnappshoted.  Waited till the maintenance this morning to see if it happened again after maintaince, did it 3 times, so I took did the copy pasta and decided to report.

### How to Reproduce

Pull boss, do opener, not sure if energy is the issue or not, but at the start with BL i should have plenty of energy to hit everything to do opener for SIN Rogue.

### Player Information (Link)

https://pastebin.com/iPAvQbRJ

### Error Messages (Link)

https://pastebin.com/iPAvQbRJ

### Additional Information

More than happy to continue to keep testing files.

### Contact Information

Wren1740

**Comment by Yuuseki** [comment]
Came here to report the same issue. This is what it looks like:
![YoloMouse_S4XDgC58NQ](https://github.com/user-attachments/assets/d07da589-4a95-4391-bad5-354d850142c2)
Reproducible with these talents (Ovinax build): CMQAA0tw2gAD7pPTLoW5IGZDeMjZmZmZmhHYAAAAAAYWglZAAAAAAottZmhZmxYmZWmlZGjBGmZmxMbWGzAsZWGYALBLDTghFA
I myself encountered it on M Ovinax, Hekili v11.0.5-1.0.2 on 25th Oct.
I did some digging and I found the offender in the new Assa APL. To give some comfort, the rotation is actually correct according to the SimC APL, it's just that it looks buggy because the addon displays disappear. If it worked properly, the addon would show you to wait/pool energy (red number on primary display counting down). The buggy behaviour is related to the new not_pooling line:
`actions+=/variable,name=not_pooling,value=variable.in_cooldowns|!variable.cd_soon&variable.avoid_tea&buff.darkest_night.up|!variable.cd_soon&variable.avoid_tea&variable.clip_envenom|variable.upper_limit_energy|fight_remains<=20`
Specifically the `upper_limit_energy` variable, which is set like this:
`actions+=/variable,name=upper_limit_energy,value=energy.pct>=(70-30*talent.sanguine_blades-10*talent.vicious_venoms.rank)`
If you are not specced into Sanguine Blades and Vicious Venoms, then the threshold is 70% energy because it's pooling before sending CDs.
Hope the pooling display will get fixed soon <3

**Comment by DrWren** [comment]
Ah ok, that works for me then. If that’s what’s going on sweet. But Im concerned as to why the addon took an automatic snapshot? lol

**Comment by Hekili** [comment]
> why the addon took an automatic snapshot?

So you can provide it here.  The addon is supposed to do its best to come up with a recommendation, and make a snapshot if it can't.

I *think* this issue should be resolved since I made changes to variable.upper_limit_energy and how it is used, but if not, please open a ticket with a new snapshot (1.0.4 or later).

**Comment by DrWren** [comment]
Oh no, I know that sir, I just didn't know why it to the snapshot if it was doing what I was supposed to be doing. Looks like it been working as of last night in m+, I will test in Raids later if needed, but so far so good!!! Good works sirs!!!
