### ISSUE TITLE
Melee Targets Excluded by range 

### ISSUE THREAD

**Issue by TonyF4a** [Hekili/hekili#4074]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Hunter - Survival

### Describe the Issue

with the display set to automatic, it does not switch to the aoe rotation and sticks to the st rotation when multiple targets are in melee range. also happens with reactive dual display, the secondary aoe display never pops up. using nameplate detection and damaged enemies. targets near pet is disabled. ive also experienced this on other melee specs as well (dk)

### How to Reproduce

Not sure how to reproduce. sometimes happens when i log in. other times it happens after starting a key. as well as after switching talents, swapping characters, etc... super random. but a reload always fixes it. just awkward to do it mid dungeon if it happens there

### Snapshot (Link)

https://pastebin.com/TAdPerek

**Comment by syrifgit** [comment]
In this snapshot, your enemies are all 38 yards away and you have your detection set to 10 yards.

```
targets:  Nameplates are enabled.
 - Checking nameplate list for nameplate12 [ Creature-0-3023-2552-11451-225982-00009BA88D ] Cleave Training Dummy.
    - Excluded by range (38 > 10).
 - Checking nameplate list for nameplate5 [ Creature-0-3023-2552-11451-225982-00011BA88C ] Cleave Training Dummy.
    - Excluded by range (50 > 10).
 - Checking nameplate list for nameplate1 [ Creature-0-3023-2552-11451-225982-00011BA88D ] Cleave Training Dummy.
    - Excluded by range (38 > 10).
 - Checking nameplate list for nameplate13 [ Creature-0-3023-2552-11451-225982-00019BA88C ] Cleave Training Dummy.
    - Excluded by range (38 > 10).
 - Checking nameplate list for nameplate4 [ Creature-0-3023-2552-11451-225982-00001BA88D ] Cleave Training Dummy.
    - Excluded by range (38 > 10).
 - Checking nameplate list for nameplate8 [ Creature-0-3023-2552-11451-225982-00001BA88C ] Cleave Training Dummy.
    nameplate8   - -1 - Creature-0-3023-2552-11451-225982-00001BA88C - 126.00 - 10 - Cleave Training Dummy 
 
 - Checking nameplate list for nameplate6 [ Creature-0-3023-2552-11451-225982-00001BA88E ] Cleave Training Dummy.
    - Excluded by range (45 > 10).
 
 ```
 
 Regardless as a survival or BM hunter, I recommend using pet-based detection.

**Comment by TonyF4a** [comment]
yes they are showing here as 38 yards away, yet i was standing right on top of them. looking at that chunk of the snapshot, it seems as tho only one of them registered as in range or i could be misunderstanding? but when this does happen, i most certainly am standing in the middle of a group of enemies.

**Comment by syrifgit** [comment]
Does it happen with things that arent target dummies? Can you provide the screenshot too? When you make a snapshot, once per login/reload, the addon saves a screenshot at the same time in your wow folder.

**Comment by TonyF4a** [comment]
it has happened with things that aren't target dummies yes, i notice it inside keys typically. ill send a screenshot next time it happens (had disabled that in the settings at some point and now i wish i hadn't) but it hasn't happened again tonight thankfully. worth noting, i was originally using elvui stock nameplates. when i switched to plater it seemed to happen much less frequently... no idea if that has an impact on it or not tho... just something i noticed. i also dont have friendly nameplates enabled, just enemy nameplates. lastly i disabled damaged based detection and having been only using nameplate detection.

**Comment by Hekili** [comment]
What do these commands show in your chat?

`/dump GetCVar( "nameplateShowAll" )`
`/dump GetCVar( "nameplateShowEnemies" )`

Does your client show multiple nameplates at once, or only your targeted enemy?

**Comment by TonyF4a** [comment]
both commands say =1 and yes i see all enemy nameplates, not just my target

**Comment by Hekili** [comment]
> Can you provide the screenshot too? When you make a snapshot, once per login/reload, the addon saves a screenshot at the same time in your wow folder.

**Comment by XtremeBaumer** [comment]
I don't have a snapshot with this, though I experience the same issue pretty often. The addon does not seem to recognize enemies. This is a screenshot with the auto-display. I am exactly at the green cross and usually Hekili show the number of targets close by in the bottom right corner of the spell icon.
![image](https://github.com/user-attachments/assets/c90e95ff-6726-44da-ae20-f01b723469f6)

Same pull, rejoining the fight after a death, the enemy count now goes up:
![image](https://github.com/user-attachments/assets/cf3df8b5-4bc7-4189-83ad-7a8403ccfb6e)

**Comment by Hekili** [comment]
It takes both a snapshot and a screenshot (from the same time) to investigate.

**Comment by andr-a** [comment]
Hi,
I believe the issue is LibRangeCheck. It sometimes stops working correctly. I tested this with a WeakAura which checks the number of nameplates in range using the Range Check condition.
A reload is a good way to fix this, but does not always work. I noticed if I reload while a nameplate is in my field of view it works most times.

**Comment by TonyF4a** [comment]
i have been trying my best to reproduce the problem so i can snag a screenshot with the snapshot... but it seems to happen much less frequently or just not happen at all (this a good thing tho!) which has been the case the past few nights. i do recall at one point when i was looking into it myself, my bug catcher did catch something with LibRangeCheck? could be misremembering tho...

**Comment by TonyF4a** [comment]
got it to happen! still unsure what causes it but here ya go! snapshot and screenshot. can see im in range and hitting everything, but the automatic display is not registering that the other targets are in range https://pastebin.com/bschPBZP
![WoWScrnShot_102724_200517](https://github.com/user-attachments/assets/377fb973-d03a-46ff-8a13-ae02ead457fe)

**Comment by masterkain** [comment]
perhaps https://github.com/WeakAuras/WeakAuras2/issues/4836

**Comment by Hekili** [comment]
@TonyF4a Getting the error message from your bug catcher might help.  It does seem to be an issue with LibRangeCheck, though it could be a caching issue.  I'm curious whether, when this happens:
* Does turning nameplates off and on fix it?  (I think you tap `V` twice to do this.)
* Does rotating your camera so the nameplates disappear and come back fix it?

Those questions + any LibRangeCheck error messages might help sort out the root cause.

**Comment by TonyF4a** [comment]
ok, happened again as soon as i started a key. tried disabling nameplates, moving camera ect but no luck. switched the display to dual in the middle of the chaos as i didnt want to risk losing the snapshot when i did a reload

https://pastebin.com/EeLgw8F6 snapshot

https://pastebin.com/cZ9ixWU0 the bug that was caught

some strange things happened when i tried to open up the settings tho. it sorta got stuck open in combat

![WoWScrnShot_103024_193108](https://github.com/user-attachments/assets/390c6e11-d6a0-4953-98ed-87df46099b4e)

**Comment by XtremeBaumer** [comment]
Found something new. With nameplates turned on, its bugged, but with nameplates turned off, it works. 

![WoWScrnShot_103124_130608](https://github.com/user-attachments/assets/2b1c359f-066e-4e7f-b1e7-d4e7dc7459da)
![WoWScrnShot_103124_130605](https://github.com/user-attachments/assets/c37d59ad-b156-495d-8b46-8053f101660b)

I am using Plater for refence

**Comment by Hekili** [comment]
That's helpful information.  That suggests that the range filtering for nameplates is what gets "stuck" -- when nameplates are off, it falls back to damage-based target detection.

**Comment by XtremeBaumer** [comment]
After the fix, the issue still persists:
![WoWScrnShot_111024_113058](https://github.com/user-attachments/assets/745b88e1-df4c-49cb-9883-58da2aceaf3e)

Will provide a snapshot as soon as possible (the keybind doesn't work on german keyboards btw. because there is no "[" key)

It consistently happens with void emissary:

![WoWScrnShot_111024_120517](https://github.com/user-attachments/assets/ec10eafe-6fd3-436e-bd5c-6fa9ff723bdc)

https://pastebin.com/QVrE95VE

And a few more snapshots. Partly because now other issues arise with target count.
The issues are now:
- Too few targets counted
- Too many targets counted, even if there is only 1 nameplate

1. https://pastebin.com/Z4MuRZhb
![WoWScrnShot_111024_130911](https://github.com/user-attachments/assets/73b153f8-05ef-4541-9820-27d324f22bba)

2. https://pastebin.com/Aw9WZLuq
![WoWScrnShot_111024_130921](https://github.com/user-attachments/assets/45ef0a76-5064-4abb-a010-652dab18ad4a)


3. https://pastebin.com/1wn1eENW
![WoWScrnShot_111024_132446](https://github.com/user-attachments/assets/de4829aa-b275-4a46-90b8-71fe096618c8)

4. https://pastebin.com/TuMJBfjC
![WoWScrnShot_111024_133423](https://github.com/user-attachments/assets/62156571-774a-4d33-8ed8-61c25686742c)

5. https://pastebin.com/96jnTfud
![WoWScrnShot_111024_133541](https://github.com/user-attachments/assets/799738b3-3c42-4509-9784-fd2dac149792)


And for good measure a video showing the target count in action: https://youtu.be/8n5prehhbXY

**Comment by TonyF4a** [comment]
just adding on to above post, still experiencing this issue as well. no bugs caught in game tho, and a reload sorted it out as usual.

https://pastebin.com/Kerpy16y
![WoWScrnShot_111324_161543](https://github.com/user-attachments/assets/5712d596-4616-4823-b041-66244facec44)
