### ISSUE TITLE
[REC] As BM hunter in single target rotation, multi-shot keeps getting recommended

### ISSUE THREAD

**Issue by RussellAnas** [Hekili/hekili#4101]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Hunter - Beast Mastery

### Describe the Issue

Multi-shot is recommended in single target rotation. Tried this with both 'auto' (where spells adjust per count of mobs) and 'single target only' options in the addon 

### How to Reproduce

1. Enter game as BM hunter
2. Try rotation on single target
3. Multi shot gets recommended instead of cobra shot

### Snapshot (Link)

https://pastebin.com/sBKf0Zgk

**Comment by syrifgit** [comment]
This is currently part of the single target rotation due to a bug. I imagine it may get changed though, but as of right now on the newest SIMC apl it is correct.

Straight from SIMC repository:
`actions.st+=/multishot,if=buff.beast_cleave.remains<gcd*1.25&talent.bleak_powder&(buff.deathblow.up|(cooldown.black_arrow.remains<gcd&(target.health.pct<20|target.health.pct>81)))`
