### ISSUE TITLE
Vampiric Touch recommend even though Unfurling Darkness is on cooldown

### ISSUE THREAD

**Issue by Bobisadrummer** [Hekili/hekili#4117]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Priest - Shadow

### Describe the Issue

With Unfurling Darkness talented, Vampiric Touch is usually recommended twice or once then again following the next recommendation when the Unfurling Darkness debuff is not present and higher priority spells are not available. At the moment Vampiric Touch ends up getting recommended even though Unfurling Darkness debuff is present.

### How to Reproduce

1) Shadow Spec
2) Talent Unfurling Darkness
3) Cast Vampiric Touch on a hostile target.

### Snapshot (Link)

 https://pastebin.com/MKBytAMQ

### Additional Information

A different snapshot showing 3 VT recommendations following the first cast of VT at the start of combat. https://pastebin.com/Kp7J5a9s

**Comment by Hekili** [comment]
Should be resolved in 1.0.7.

**Comment by Bobisadrummer** [comment]
11/1/24's build 1.0.8. seems to have VT being recommended repeatedly when adds spawn in a fight. https://pastebin.com/fM8TCEws

**Comment by Hekili** [comment]
I can't tell for the previous casts, but the current VT is recommended in order to proc Unfurling Darkness (which would be followed by another VT to consume Unfurling Darkness).  You don't have the CD debuff applied to your character, so that seems accurate.

What I guess has happened here is that there was a natural Vampiric Touch refresh recommendation because it was low/falling off, followed by a VT recommendation to proc Unfurling Darkness except the cast finished *slightly* faster than the Unfurling Darkness cooldown, which lead to another VT recommendation -- the present one -- to proc Unfurling Darkness again.

I am going to adjust the Unfurling Darkness logic to pad for latency a bit and see if this is minimized.  There also may be room for a priority optimization where VT would *not* be used for a routine refresh if UfD is talented and will be off CD within *`x`* seconds.  (It requires simming to see what value `x` should be.)

**Comment by Bobisadrummer** [comment]
I think I figured out what I was seeing. It seems that VT is being suggested instead of MF as a filler when all the other rotational abilities (DP, MB MF:I, VoiT) are on CD. https://pastebin.com/5T5rTCE6
