### ISSUE TITLE
[REC] Error with the Shaman opener

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#4119]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

![image](https://github.com/user-attachments/assets/7f1061b5-6c3b-41cd-847d-bd653277f586)
![image](https://github.com/user-attachments/assets/7a33c887-5506-4a7c-bdf6-45112bd05d80)
![image](https://github.com/user-attachments/assets/e72a3a0a-fdcb-461d-bced-5c64e47d4a10)
The sequence in 1 goal is incorrect. I have attached a screenshot of what it looks like for me. And then a screenshot of what it looks like at Raidbots.  Icyveins also has an opener on it. It happened with the last release. If anything here are my talents CcQAYp+JUk5Lea12OyacsLNThMzMDMjZmtZmZGmlZmllxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwGAbmxwGZBmRDNYBAzykZwswwYMmZGzYZmZyCLjlxMDAgxA

### How to Reproduce

Take my talent set
Approach the single target. 

### Snapshot (Link)

https://pastebin.com/KqvWA6Vc

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/koLSkbvVMB7wFAQe4QvhZJ

**Comment by Hekili** [comment]
1. Guide openers are only minimally relevant vs. what the sim actually does.
2. The addon priority is modified to use Doom Winds sooner (which sims as a DPS gain) because once you pop Ascendance, you'll delay Doom Winds for the whole duration and waste a lot of cooldown recovery time.
3. The official SimC update for 11.0.5 will be out soon; I'll integrate its changes when it's available, but I'm not going to change anything before then (to avoid throwing away work).
