### ISSUE TITLE
[REC] Can't track talent.invoke_yulon.enabled any more

### ISSUE THREAD

**Issue by oversoe** [Hekili/hekili#4125]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Monk - Mistweaver

### Describe the Issue

When talented into invoke chiji, you can track the talent with talent.invoke_chiji.enabled, but talent.invoke_yulon.enabled doesn't turn true.

### How to Reproduce

1. Spec into yulon
2. Check APL
3. talent.invoke_yulon.enabled is false.

### Snapshot (Link)

https://pastebin.com/8x8Ja5Xn

**Comment by syrifgit** [comment]
It is now called `invoke_yulon_the_jade_serpent`, so try `talent.invoke_yulon_the_jade_serpent.enabled`


    invoke_chiji_the_red_crane    = { 101129, 325197, 1 }, -- Summon an effigy of Chi-Ji for 12 sec that kicks up a Gust of Mist when you Blackout Kick, Rising Sun Kick, or Spinning Crane Kick, healing up to 2 allies for 13,380, and reducing the cost and cast time of your next Enveloping Mist by 33%, stacking. Chi-Ji's presence makes you immune to movement impairing effects.
    invoke_yulon_the_jade_serpent = { 101129, 322118, 1 }, -- Summons an effigy of Yu'lon, the Jade Serpent for 12 sec. Yu'lon will heal injured allies with Soothing Breath, healing the target and up to 2 allies for 16,784 over 7.4 sec. Enveloping Mist costs 50% less mana while Yu'lon is active.
 
 
`talent.invoke_chiji.enabled` also does not work, as expected. Not sure what you mean there. `talent.invoke_chiji.enabled` will **always** return false because you cannot have it talented, the addon doesn't think that talent exists because it's spelled wrong, so therefore it is not enabled.

![image](https://github.com/user-attachments/assets/3f84164c-9d6d-4aed-9b16-ddd986c68713)

![image](https://github.com/user-attachments/assets/1f365db5-c65c-4c33-8640-179d283e60b8)

**Comment by syrifgit** [comment]
And FYI your custom pack is throwing a lot of errors, you may want to review the `MonkMistweaver.lua` file to see what things are actually called.

**Comment by oversoe** [comment]
Thanks man - how do I see the errors it's outputting?

**Comment by syrifgit** [comment]
They're in the snapshot you attached

**Comment by oversoe** [comment]
I'm going through it now, there's a lot of fidgetting I did in dragonflight and never really got to cleaning up - thanks for pointing me in the right direction :-)
