### ISSUE TITLE
Summon Demonic Tyrant not being recommended at all

### ISSUE THREAD

**Issue by mjolnir-debug** [Hekili/hekili#4151]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warlock - Demonology

### Describe the Issue

Demo warlock here. I have not need Tyrant recommended in awhile (maybe since anniversary?). This is usually part of your opening right after charhound/dreadstalkers/gfg are summoned

### How to Reproduce

1. Power Siphon
2. Demon Bolt
3. Summon Charhound
4. Shadowbolt
5. Summon Dreadhounds

Then it recommends Demonic Strength and I don't see any icon for recommending Tyrant before this

### Snapshot (Link)

https://pastebin.com/ZC0h3jRc

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/9fRkiDP2rUDj5nZhTs9KCa

**Comment by syrifgit** [comment]
Your tyrant is selected to be summon in about 3 seconds.

`Action chosen:  summon_demonic_tyrant at 3.07!`

It's hard to tell anything else because you have your cooldowns split up between 2 different displays, and demo lock has a very specific sequence to go through so that can mess with it because your 2 displays have no idea which button you will hit when trying to recommend future things. So your main display doesn't actually know that you'll press tyrant because it's separated.

I highly recommend putting tyrant back in the main display and simply toggling cooldowns on and off if you don't want to cast it.

That sim link also doesn't help because you ran an advanced sim, submit a regular quick sim next time.

**Comment by mjolnir-debug** [comment]
Thank you. I am not sure how that happened. I may have changed things on an alt and not saved a separate profile. I restored the default profile and it is resolved. Noted to quick sim for next time!
