### ISSUE TITLE
[REC] Enhancement not spreading Flame Shock in AOE if Thorim's Invocation is already set to Chain Lightning

### ISSUE THREAD

**Issue by jakeparshall** [Hekili/hekili#4164]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

The SIMC for enh has an entire priority before going into ascendance, that hekili does not do. It makes sure to spread FS after pwave and make sure crash lightening is rolling etc. But when i go up to dummies and start by pressing pwave, it goes right into ascendance without applying any of those conditions that SIMC and wowhead/icyveins says also.

### How to Reproduce

Do normal rotation, Pwave, chain lighteing then it goes straight into ascendance etc

### Snapshot (Link)

https://pastebin.com/YfXNNm6S

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/jT4Bem5mLiXFUHf2szKgNC

**Comment by Hekili** [comment]
You have to keep in mind that you're not starting from the same "fresh" state here that the sim does.  You already triggered `ti_chain_lightning` and don't need to retrigger it before using Ascendance, so that Ascendance recommendation supercedes the Lava Lash and Chain Lightning casts.

I could force the Lava Lash to be used for spreading Flame Shock, but if Thorim's invocation is already set to Chain Lightning there's no reason to cast those Chain Lightnings before popping Ascendance.

**Comment by jakeparshall** [comment]
What im saying ist hat i cant even get it to spread flame shocks or use pwave before tempest ever after the opener. It only happens once. If i go and do a rotation, and then let all my cds come back up, it wont tell me to cast pwave or FS before ascendance, and thats a good thing because of pwave and tempest interaction right?
