### ISSUE TITLE
[REC] Guardian of Ancient Kings is being recommended even though it is on CD in Prot Paladin.

### ISSUE THREAD

**Issue by esergiosantos** [Hekili/hekili#4257]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Paladin - Protection

### Describe the Issue

Guardian of Ancient Kings is being recommended even though it is on CD in Prot Paladin.

### How to Reproduce

1. Enter Game as Prot Paladin 
2. do your normal rotation on an M+ 
3. Addon is recommending Guardian after having already used it and still having 3 minutes left to return the CD.

### Snapshot (Link)

https://pastebin.com/DH04C6r

### Raidbots Sim Report (Link)

https://mimiron.raidbots.com/simbot/report/48f7XnRhsgMaKhjN6PH4cY

### Contact Information

sergiovegas1

**Comment by billyplus** [comment]
Guardian of Ancient Kings (skill id 86659) is replaced by Guardian of the Forgotten Queen (skill id 228049).

IsSpellKnownOrOverridesKnown( 228049 ) always return true.

![屏幕截图 2024-12-22 130228](https://github.com/user-attachments/assets/2c6ac659-e969-4e89-a49a-f7a57a061c75)

**Comment by billyplus** [comment]
PVP skills are empty.
![屏幕截图 2024-12-22 130957](https://github.com/user-attachments/assets/58aa4d8f-a0e2-4787-aab3-efeccefde45a)

**Comment by syrifgit** [comment]
Unable to see your pastebin

**Comment by billyplus** [comment]
@esergiosantos 
try this solution before somebody fix this bug.
Find the line: "IsSpellKnownOrOverridesKnown( 228049 ) and 228049"
replace with: "IsSpellKnownOrOverridesKnown( 228049 ) and 86659"

**Comment by billyplus** [comment]
> Unable to see your pastebin

@syrifgit 
I can reproduce by changing the  trigger percent of "Guardian of Ancient Kings" in options to 3%， then go to fight with "Dungeoneer's Training Dummy Tanking".

**Comment by tjyhgb** [comment]
Same issue. I won't open a new issue but describe it here.

Subject: Bug Report: Incorrect Skill Display in Hekili Plugin

Description:
I’ve identified an issue in the Hekili plugin where the skill list incorrectly displays "Guardian of the Forgotten Queen" instead of the base skill "Guardian of Ancient Kings", even when the PvP talent "Guardian of the Forgotten Queen" is not selected.

Impact:
This causes the plugin to repeatedly suggest "Guardian of the Forgotten Queen" during critical moments (e.g., low health or high incoming damage), which disrupts the proper skill rotation and affects survivability.

Steps to Reproduce:

Ensure that the PvP talent "Guardian of the Forgotten Queen" is not selected.
Trigger a scenario where "Guardian of Ancient Kings" should be used (e.g., low health).
Observe that the plugin incorrectly displays "Guardian of the Forgotten Queen" in the rotation.
Expected Behavior:
The plugin should display "Guardian of Ancient Kings" as the correct skill when the PvP talent is not selected.

Additional Information:

Plugin Version: Hekili v 11.0.7 - 1.0.0
WoW Client Version: 11.0.7


It works if I roll back the plug version to 11.0.5-1.0.17

**Comment by tjyhgb** [comment]
> @esergiosantos try this solution before somebody fix this bug. Find the line: "IsSpellKnownOrOverridesKnown( 228049 ) and 228049" replace with: "IsSpellKnownOrOverridesKnown( 228049 ) and 86659"

Which file I need to change?

**Comment by tjyhgb** [comment]
> @esergiosantos try this solution before somebody fix this bug. Find the line: "IsSpellKnownOrOverridesKnown( 228049 ) and 228049" replace with: "IsSpellKnownOrOverridesKnown( 228049 ) and 86659"

I tried your solution, now it shown as "Guardian of Ancient Kings" but still got stuck after all protect spells’ cooldowns are not ready. Hekili will still sugest Guardian of Ancient Kings even its cooldown is not ready. It seems even shown as Guardian of Ancient Kings but still cannot figure out the cooldown of Guardian of Ancient Kings. I will just rollback to version 11.0.5-1.0.17. That still works.

**Comment by Spike2D** [comment]
`id = function () return IsSpellKnownOrOverridesKnown( 212641 ) and 212641 or 228049 or 86659 end,`
This should fix it.

**Comment by syrifgit** [comment]
> 212641

Not sure how that would fix it with a spellID that's no longer in the current version game (might still be able to access it in Legion content?) . This will make the ID always equal to the PVP version, logically.

I will look into it, though I am unable to actually replicate it myself. Works completely fine for me as-is.

**Comment by Spike2D** [comment]
> > 212641
> 
> Not sure how that would fix it with a spellID that's no longer in the current version game (might still be able to access it in Legion content?) . This will make the ID always equal to the PVP version, logically.
> 
> I will look into it, though I am unable to actually replicate it myself. Works completely fine for me as-is.

Did you took into account Glyphs?
