### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by nyteghost** [Hekili/hekili#435]
Just a quick question, when playing a destro lock, i notice it puts a arrow at bottom right of the icon in queue, does that mean i cast the icon and then switch target, or do i switch target and then cast?

**Comment by Hekili** [comment]
It means to cast it on a different target.  I.e., put Havoc on something else so your Chaos Bolts hit your current target + the other.  Or put Immolates on other targets.

I'm not a fan of telling people to switch targets altogether, because you're probably targeting what you're targeting for a good reason.

**Comment by nyteghost** [comment]
Okay thank you! That’s what I thought
