### ISSUE TITLE
Affliction Lock Malefic Rapture  doesnt proc (lower level)

### ISSUE THREAD

**Issue by seathasky** [Hekili/hekili#480]
**Describe the Bug/Issue**
 Malefic Rapture doesnt proc on addon after all requirements met.

**To Reproduce**
Casting all dots on target.

**Expected behavior**
 Malefic Rapture proccing after all dots put on target. Some other user in another ticket said you need an azerite 

**Screenshots**
https://www.youtube.com/watch?v=XCAWO1rfLTc

**Issue Reporting tab:**

https://pastebin.com/DrVs7Re6

**Snapshots :**
 
https://pastebin.com/YxGmBMJ3

**Comment by Hekili** [comment]
That snapshot was not taken at the time you thought Malefic Rapture should've been recommended. You're not in combat.

**Comment by seathasky** [comment]
You can see in the youtube video clearly shows the issue but heres another snap https://pastebin.com/iW8Hk89s i'm not sure why that one says i was out of combat

**Comment by seathasky** [comment]
Another https://pastebin.com/W8Tt2xH2

**Comment by Hekili** [comment]
You are not in combat in that snapshot.

**Comment by seathasky** [comment]
https://pastebin.com/GujnPxhS

**Comment by Hekili** [comment]
That one works. But yes, the short answer is that because the addon and priority is designed for 50+, the priority is written assuming you have a talent you don't yet have. 

You would need to write a custom priority or just level until you have more talents before the issue will resolve. Thanks!

**Comment by seathasky** [comment]
I know it has nothing to do with spells I do not have. 
![Screen Shot 2020-10-18 at 6 25 26 PM](https://user-images.githubusercontent.com/17598024/96387353-5fba0280-116f-11eb-98fd-1fe47173dde0.png)

Basically the addon is all builders atm no spenders.  EVEN at low levels, I tested on my wifes warlock which has seed of corruption  spender and it still throws back the same Shadow Bolt bs. It shouldnt be doing this. But if you've given up thats up to you.
![Screen Shot 2020-10-18 at 6 29 26 PM (2)](https://user-images.githubusercontent.com/17598024/96387496-6bf28f80-1170-11eb-8419-1ec80a182814.png)

**Comment by Lipstopica** [comment]
Well seed of corruption will only be used on +2 targets, and if it isn't well then report that as bug with the snapshots and stuff. 

The video you linked shows it suggesting the dots including UA. The only spender you have is Rapture... which isn't meeting the requirements of the APL. If you don't have Vile Taint talent, it's not going to suggest Rapture. It's the way the APL/Addon work.
It's using Shadow Bolt as a filler because you don't have the talent for Drain Soul so it suggests Shadow Bolt.

Hekili already said it won't work correctly at low levels because of the requirements on certain APLs.

**Comment by seathasky** [comment]
Doesnt change the fact that it's still the incorrect rotation but I digress, it's not for low levels. Just annoying since he knew i was low level from the get go and had me do snapshots to then come back and tell me i'm low level and to fuck off. So yea i'll do that now.

**Comment by Lipstopica** [comment]
Well if you message me on discord (Snappi#2212), I can try and help you set up a custom priority until you get the talent.

**Comment by Hekili** [comment]
I told you that if you provided the snapshot, I could tell you why.  I answered, perfectly amicably, that because the addon and priority is designed for 50+, the priority is written assuming you have a talent you don't yet have.

Lipstopica's explanation is mostly right, though I'd clarify that Malefic Rapture doesn't rely entirely on Vile Taint specifically.

![image](https://user-images.githubusercontent.com/9438134/96387845-1b306600-1173-11eb-9e1e-56549e4d0492.png)

There are 3 entries for Malefic Rapture in the priority, and they each correspond to the talent row above.

```
37.  malefic_rapture ( default - 16 )
The action (malefic_rapture) is usable at (0.00 + 0.00) with cost of 1 soul_shards.
    - the action is ready before the current recommendation (at +0.00 vs. +6.71).
    - this entry's criteria FAILS: ( ! azerite.cascading_calamity.enabled[false] | dot.unstable_affliction.down[false] | soul_shard[4.00] > 1 ) & dot.vile_taint.ticking[false]
```

This one relies on having Vile Taint ticking.

```
38.  malefic_rapture ( default - 17 )
The action (malefic_rapture) is usable at (0.00 + 0.00) with cost of 1 soul_shards.
    - the action is ready before the current recommendation (at +0.00 vs. +6.71).
    - this entry's criteria FAILS: ( ! azerite.cascading_calamity.enabled[false] | dot.unstable_affliction.down[false] | soul_shard[4.00] > 1 ) & talent.phantom_singularity.enabled[false] & ( dot.phantom_singularity.ticking[false] | cooldown.phantom_singularity.remains[0.00] > 12 | soul_shard[4.00] > 3 )
```

This one relies on having the Phantom Singularity talent.

```
39.  malefic_rapture ( default - 18 )
The action (malefic_rapture) is usable at (0.00 + 0.00) with cost of 1 soul_shards.
    - the action is ready before the current recommendation (at +0.00 vs. +6.71).
    - this entry's criteria FAILS: ( ! azerite.cascading_calamity.enabled[false] | dot.unstable_affliction.down[false] | soul_shard[4.00] > 1 ) & talent.sow_the_seeds.enabled[false]
```

This one relies on Sow the Seeds.

While yes, it is not optimal to never cast Malefic Rapture, a properly talented character that is level 35 or higher would meet these requirements without issue.

If you edit one of these entries (I'd recommend default - 18), you can make it so it works without the talent from that row.  Default 18 would be:  `( ! azerite.cascading_calamity.enabled | dot.unstable_affliction.down | soul_shard > 1 ) & ( talent.sow_the_seeds.enabled | level < 35 )`

Have a wonderful day.

**Comment by seathasky** [comment]
Well, maybe I read you wrong Hek, just seemed like that from my angle. Thanks for the help.

**Comment by seathasky** [comment]
![Screen Shot 2020-10-20 at 7 43 23 AM (2)](https://user-images.githubusercontent.com/17598024/96581880-7dd74e00-12a8-11eb-8561-cfaaec037913.png)

Thanks for the update, works good at lower levels!
