### ISSUE TITLE
Elemental Shaman - Echoing Shock then Flame Shock?

### ISSUE THREAD

**Issue by Snichy** [Hekili/hekili#483]
Not sure if this is intended, a bug or my understanding of the rotation is way off.

Quite often, after it recommends I use Echoing Shock (which duplicates the next ability), the next recommendation in the queue is to cast Flame Shock (DoT).  I would have thought this was a waste of the proc as it simply re-applies the DoT and we gain no more benefit than a couple of seconds on the DoT, whereas after clicking Echoing Shock the next ability should be a heavy hitting ability like Lava Burst or Earth Shock so it is duplicated and the damage is more substantial.

Snapshot: https://pastebin.pl/view/2016c986
Character Data: https://pastebin.pl/view/7dc5e85a

**Comment by Hekili** [comment]
Elemental Shaman will definitely see some revision in the near future.  You're welcome to toy with the priority (see /hekili > Priorities > Elemental), but otherwise we'll both need to wait for the spec's theorycrafters to update SimulationCraft.

(If it takes much longer, I'll look at porting SE&L or Icy-Veins priorities.)
