### ISSUE TITLE
[Incomplete Ticket] Significant frame drop while in combat

### ISSUE THREAD

**Issue by Starcallerreign** [Hekili/hekili#590]
For the last couple of days I've noticed significant frame drops while in combat. I tried reinstalling/updating the addon but nothing changed. Frames go back to normal when addon is disabled. Hekili also sends a lot of snapshot reports while the frame drop is  happening. 

https://pastebin.com/3849A9Fx - Snapshot
![Screenshot_2](https://user-images.githubusercontent.com/75174254/100519851-c6810180-319a-11eb-80b8-8c3c5c70fceb.png)
![Screenshot_3](https://user-images.githubusercontent.com/75174254/100519853-c97bf200-319a-11eb-9b16-597e505a4e6a.png)

**Comment by Hekili** [comment]
You have to submit the requested ticket information.

**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
If the addon is generating snapshots, you can provide those snapshots here so I have the relevant information.

**Comment by Starcallerreign** [comment]
Here it is, sorry for the trouble.
https://pastebin.com/3849A9Fx - Link version
[Hekili snapshot - FPS.txt](https://github.com/Hekili/hekili/files/5610904/Hekili.snapshot.-.FPS.txt)

**Comment by Hekili** [comment]
That's not an autogenerated snapshot, it has recommendations for 6 slots.

Also, 6 recommendations is a lot, and each recommendation costs a bit more CPU, so you might not want that many to begin with. 

Beyond 3 or 4, there's such a high amount of entropy -- anything could proc that might revise those recommendations -- making the time spent generating them effectively wasted.

**Comment by Hekili** [comment]
I adjusted the Affliction priority to avoid some redundant checking, so that should result in some reduced CPU usage.
