### ISSUE TITLE
Affliction - Extreme FPS drops when Drain Soul is being cast.

### ISSUE THREAD

**Issue by tdevine21** [Hekili/hekili#591]
Something with the addon is triggering FPS drops when Drain Soul is cast. Also, love the addon!

:)

**Comment by Hekili** [comment]
Submit all the required ticket info.

**Comment by tdevine21** [comment]
> Submit all the required ticket info.

First time posting a ticket. How do I post the required ticket info?

**Comment by tdevine21** [comment]
build: v9.0.2-1.0.10
level: 60 (60)
class: WARLOCK
spec: affliction

talents: absolute_corruption
    burning_rush
    drain_soul
    haunt
    mortal_coil
    soul_conduit
    vile_taint

pvptalents: none

covenant: kyrian

azerite: none

essences: [none], none

sets/legendaries/artifacts: none

gear: darkmoon_deck_putrescence = 1
    evernight_drape = 1
    faemoss_bindings = 1
    glowing_endmire_stinger = 1
    masterful_phaedrum_necklace = 1
    masterful_phaedrum_ring = 1
    muehzalas_hexthread_sarong = 1
    quick_oxxein_ring = 1
    selfless_watchers_gauntlets = 1
    shadowlace_cowl = 1
    shadowlace_mantle = 1
    shadowlace_tunic = 1
    slippers_of_leavened_station = 1
    spiritmenders_cord = 1
    whizblast_walking_stick = 1

legendaries: none

itemIDs: 173069, 173132, 173133, 173145, 173214, 173218, 173220, 178156, 178831, 179339, 179351, 179927, 181426, 181430, 181575

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Affliction
    petbased = false
    potion = unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**Comment by tdevine21** [comment]
Frames drop from a solid 120 to around 75.

**Comment by Hekili** [comment]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by tdevine21** [comment]
Sorry, brotha. To busy with family to post all this information. Pretty simple issue to describe though. Consistent FPS whole fight until Drain Soul becomes my next talent to cast. Once Drain Soul starts channeling my FPS tanks about 30FPS. Once it's done, FPS goes right back to normal. 

Something is up with Drain Soul in the latest version. Have a good one man and look forward to the next update!

**Comment by Vaniolock** [comment]
i also have this problem only on warlock affliction , also i can say boss encounters do trigger alot of performance issue until u pause it

**Comment by Hekili** [comment]
Still has to be properly reported.  Update and provide the missing info.

**Comment by Hekili** [comment]
I have two changes in that should reduce CPU usage.

1.  I revised the APL to avoid rechecking the darkglare_prep list multiple times each time the recommendations are iterated upon.  This is in 1.0.12.

2.  In 1.0.13-beta1, I've added a "Manage Drain Soul Ticks" checkbox for Affliction, defaulting to false.  If checked, the addon models the application of Shadow Embrace with each tick of Drain Soul.  That is the other CPU intensive piece that isn't particularly beneficial when generating recommendations.  **If checked, the addon will use more CPU to try to time channel breakage along with Drain Soul ticks.**  If left unchecked, the addon only has to check if it has a recommendation before Drain Soul ends or after Drain Soul ends.
