### ISSUE TITLE
Enhancement Shaman Doom Winds Legendary

### ISSUE THREAD

**Issue by Abraxion** [Hekili/hekili#605]
1) Addon is fully up to date in support of 9.0.2.

2) When using the enhancement shaman Doom Winds Legendary, the priority list changes from your regular priority to only dropping Windfury Totem.  Under normal circumstances, Hekili will recommend dropping Windfury Totem around the end of its natural duration.  However, with Doom Winds legendary equipped, upon dropping Windfury Totem, the priority list tells you to only drop Windfury Totem.

Expected Behavior:
When Windfury Totem is dropped, the priority list should continue with the normal Enhancement Shaman priority, not continually dropping Doom Winds.

Talent and Gear Information:
<script src="https://pastebin.com/embed_js/5PCt8iRh"></script>

Snapshot of Issue:

WIP

**Comment by Hekili** [comment]
Were the instructions missing when you came to make this bug report?

**Comment by Hekili** [comment]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
@Abraxion Can you confirm if you'll be providing the missing info (especially the snapshot)?

**Comment by Abraxion** [comment]
> @Abraxion Can you confirm if you'll be providing the missing info (especially the snapshot)?

Are the screenshots not appearing? I added two of them, let me go back and see what the issue on my end is.

**Comment by Hekili** [comment]
Please read the ticket instructions I provided.  Snapshots are not screenshots.

**Comment by Hekili** [comment]
Never mind, testing a solution in beta right now.
