### ISSUE TITLE
separate cooldowns

### ISSUE THREAD

**Issue by mspykerez** [Hekili/hekili#61]
Can you make it so cooldowns are shown on their own separate display frame ?

**Comment by Hekili** [comment]
Nope.  Use WeakAuras for something like that.  That's not what the addon is designed to do.

Separating cooldowns into a different frame makes them unpredictable, for instance:

Let's say Ascendance is only recommended if/when Flame Shock is applied and will be up for 15 seconds.

`actions.cooldowns+=/ascendance,if=debuff.flame_shock.remains>=15`

If I make a frame that only shows DPS cooldowns, it's going to stay blank until you've cast Flame Shock, then suddenly show Ascendance afterward.  Separate displays don't know/care what the others are up to.  If you hit Ascendance then, the Primary display will suddenly shift because Ascendance wasn't recommended within that display.

Track cooldowns with WeakAuras.  Predict recommendations with Hekili.  :)

**Comment by mspykerez** [comment]
Humm I'm no coder but can't you just adopt how hero-rotation addon does it?

**Comment by Hekili** [comment]
I _could_ do it differently, but no, the explanation above is still accurate. If you just want something to show cooldowns, make a WeakAura or use a different addon. That's not a _priority recommendation_.
