### ISSUE TITLE
major cooldown like "army of the dead" to be removed

### ISSUE THREAD

**Issue by hekiliuser** [Hekili/hekili#616]
army of the dead to be taken off  the cooldown list of dk's. it gets in the way during non boss fight and messes up rotation of the addon

**Comment by ilu4ko** [comment]
I'd rather vote for making an option to all classes to either not show damage cooldowns everywhere except for bosses or just to clone primary line without any CDs.

In both ways, players will manage their CDs. Because sometimes the queue is fully loaded with cooldown abilities and not showing any others (can make more than 5 slots, but it's inconvenient)

**Comment by ShmooDude** [comment]
You can already set individual abilities to "Boss Encounter Only" in the abilities pane or disable them entirely.

However, it might be more convenient for some classes with a lot of cooldowns if there was a global option in the Toggles pane that would flag it for all of them.

**Comment by Hekili** [comment]
Taking Army of the Dead off the Cooldowns toggle doesn't disable Army -- it makes it always enabled regardless of the toggle.

I don't think any specs have enough cooldowns that manually setting the Boss Encounter Only check is asking too much.  (Half the CDs for any spec are racials, and you really only have one of them on any character.)

Historically, I've left Army of the Dead disabled in the default priority but didn't in Shadowlands.  That's really just because it's such a long CD that you're going to use it once per fight and you'll probably want to time it for something specific.

Not sure if I'll change anything at the moment.  The addon already gives you the tools to disable AOTD rather easily.  /hekili > Abilities > Army of the Dead, then disable it.

**Comment by ilu4ko** [comment]
Guys, you are the best. I just set the required rules and it's amazing. Thank you a lot!
