### ISSUE TITLE
Retribution Paladin:  Fails to provide recommendations (needs Issue Reporting / Snapshot information)

### ISSUE THREAD

**Issue by Brdrker** [Hekili/hekili#656]
Initial engagement starts off proper enough but reduces down to one displayed indicator, basically indicating spamming Consecration.

**Comment by Brdrker** [comment]
This shows upon login:

Message: Interface\AddOns\Hekili\Options.lua:3943: attempt to concatenate local 'k' (a nil value)
Time: Wed Dec  9 03:44:03 2020
Count: 1
Stack: Interface\AddOns\Hekili\Options.lua:3943: attempt to concatenate local 'k' (a nil value)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\Hekili\Options.lua"]:3943: in function `EmbedItemOption'
[string "@Interface\AddOns\Hekili\Classes.lua"]:544: in function `func'
[string "@Interface\AddOns\Hekili\Events.lua"]:218: in function `handler'
[string "@Interface\AddOns\Hekili\Events.lua"]:56: in function <Interface\AddOns\Hekili\Events.lua:50>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by Brdrker** [comment]
Movie of flow

https://www.dropbox.com/sh/dhmqp28gq44d9gn/AAAtar-0w8buPxqhB9vwlCm_a?dl=0

**Comment by Irornbound** [comment]
I have exactly the same problem. Starts off fine then reduces to spamming consecration. I'm reverting back to the previous version untill the author finds the time to fix this.

**Comment by Hekili** [comment]
Follow the instructions for submitting a ticket and provide the required information.

**Comment by Hekili** [comment]
(Here are those instructions...)

**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
The error info you provided *shouldn't* be related but maybe it is.  I added some code to generate a warning (the "Warnings" section will appear in /hekili if that happens) to provide me some more information.

I can't replicate the issue you're having, so you'll have to provide the snapshot information if you want me to solve.

Make sure to pick up 1.0.19 before testing.  Thanks.
