### ISSUE TITLE
Problem with evaluating cooldown.trueshot.remains

### ISSUE THREAD

**Issue by Bl4ckread** [Hekili/hekili#66]
I was fiddling around with the action lists trying to tweak them a bit to suit my playstyle better, and stumbled on the following problem:

cooldown.trueshot.remains seems to return the full duration of 120 seconds regardless of the state the game is in, instead of the current remaining time on the cooldown. I used the following criteria for casting arcane shot:
actions.st+=/arcane_shot,if=focus>75|(buff.precise_shots.up|focus>45&cooldown.trueshot.remains>20&(target.time_to_die<25|talent.calling_the_shots.enabled))&buff.trueshot.down|target.time_to_die<5

What the cooldown.trueshot.remains>20 is supposed to do is to trigger the lower focus threshold of 45 instead of 75 for casting arcane shot whenever Trueshot is on cooldown, and then stop casting when the trueshot cooldown is nearing its end. I ran a sim on raidbots with this APL and checked the sample sequence and there it was working just as I intended it to work. This would lead me to suspect that the addon isn't reading the game state correctly, or there is something else weird going on. Are you aware of any problems regarding this?

The same syntax seems to work for other spells like rapid_fire, the trigger for double tap:
actions.cds+=/double_tap,if=cooldown.rapid_fire.remains<gcd.max|target.time_to_die<20
works exactly as one would expect.

**Comment by Hekili** [comment]
cooldown.trueshot.remains will return the full duration while you have cooldowns toggled off.

**Comment by Hekili** [comment]
`cooldown.trueshot.true_remains` should bypass this filtering and provide you the actual remaining time.

**Comment by Bl4ckread** [comment]
Ah wasn't aware of this, thanks a lot!

**Comment by Hekili** [comment]
Just keep in mind, there's a reason for the default behavior.  If your APL has any logic that runs in preparation for Trueshot coming off cooldown, but Trueshot is toggled off and is not going to be recommended, you are potentially setting yourself up to repeat that behavior over and over.

An example from Elemental Shaman would be refreshing Flame Shock early before using Ascendance, since you don't want to refresh it during Ascendance.  Without this behavior, the addon would tell you to refresh Flame Shock over and over again, anticipating that you'll cast Ascendance even though you're holding it for something else.

**Comment by Bl4ckread** [comment]
Thanks! This shouldn't be a problem with my case, as holding on to trueshot would just revert to the default APL fuctionality pretty much. But I'll keep this in mind for the future!
