### ISSUE TITLE
WW AND BM Monk Tweak please

### ISSUE THREAD

**Issue by ltbutterman** [Hekili/hekili#683]
Amazing rotations so far for both specs but can support be added for WW profile if using "Memory of the Last Emperor" lego? To cast Jade Lightning when at 20 stacks and ONLY at 20 stacks?

For Brewmaster can we add support for "Scalding Brew" conduit. If socketed to prioritize Breath of Fire over Keg Smash?

**Comment by Hekili** [comment]
The Windwalker priority includes conditions for Crackling Jade Lightning at 20 stacks; if you're not seeing that, submit a proper ticket, following the instructions, including a snapshot when you're at 20 stacks and CJL is not recommended.

For Brewmaster, you'd need to do some sims to show that's actually optimal.  For Scalding Brew to work, it appears that you need to have hit Breath of Fire after Keg Smash, or else the Breath of Fire DOT is not applied.  So the default behavior appears correct.  (Unless, again, you have done sims to demonstrate otherwise.)
