### ISSUE TITLE
WW Monk rotation freezes when some spells on CD

### ISSUE THREAD

**Issue by vicwac** [Hekili/hekili#690]
Rotation stops making recommendations sometimes when Rising Sun Kick, Whirling Dragon Punch and Fists of Fury are on cooldown. This happens randomly, I haven't found a pattern to it, as sometimes Hekili recommends filler skills like Tiger Palm when the main ones are on CD, and sometimes it just gets stuck on a skill (even when there's enough energy to recommend Tiger Palm) until it comes off CD. Let me know if additional snapshots are required.

Snapshot:
https://pastebin.com/83WB9a0j

**Comment by Hekili** [comment]
What is the snapshot meant to illustrate?  It provides recommendations in all slots.  What did you think should be recommended?  What does "stuck on a skill" mean?

**Comment by vicwac** [comment]
I believe it should recommend a filler skill like Tiger Palm when all others are on cd, sometimes I have enough energy for TP to be recommended but it is not. If this is by design to pool energy then I'm fine with it, I'm just not completely familiar with the logic you programmed so I assume it was an error. No offense intended.

**Comment by Hekili** [comment]
I still need you to provide a snapshot that actually shows the problem you're describing.

If there are times where the addon offers no recommendations, get a snapshot at that time and submit it here, per the instructions.

**Comment by Smudgiee** [comment]
Not sure if he means this, not sure but it was hanging on sun kick when it was like 4 seconds left. But this is when I had toggles disabled for other abilities which might be the cause but only had this issue on monk myself when toggling certain abilities

https://pastebin.com/bcu1zm1i

**Comment by Hekili** [comment]
I don't have any idea what "hanging on sun kick" means.  What are you talking about?  What is the specific, actual problem?

**Comment by Smudgiee** [comment]
I dont know... I am trying to see what he sees and it basically stays on sun kick for like 4 seconds? I have no idea myself but he seems its an issue so I gave a report because I think that is what he is talking about. I dont feel like it should be sitting on sunkick for 4 seconds when it could be doing another combo or ability?

**Comment by Smudgiee** [comment]
suggesting sunkick for 4 seconds when its not usable*

**Comment by Hekili** [comment]
The OP's description says "stops making recommendations" so that needs a snapshot showing missing recommendations to investigate.

Your snapshot shows Rising Sun Kick in 3.11 seconds.  It doesn't recommend Tiger Palm because that would overcap Chi.  It doesn't recommend Blackout Kick because that would break your combo.  What were you thinking should've been recommended in your snapshot, @Smudgiee?

**Comment by Smudgiee** [comment]
My bad then. I thought that is what he meant by rotation freezes. English isn't my first language. I thought he meant frozen as in stops recommending "stuck on a skill". I was just trying to help him out as he didnt give a log, and I could get one. My bad. And I Im not sure I am learning but my guess it was like that because I toggled certain abilities off which should've been recommended (wdp, fists,chi burst etc) so thats what I think it should be suggesting but obviously I had them toggled off. I dont think it's wrong just that it feels odd, but thats because my issue of toggling stuff.

**Comment by Hekili** [comment]
I appreciate that you're helping and your English is very good.  I am just trying to identify precise issues; the instructions and tools (snapshotting!) are intended to make it easy for me to understand what is happening, but it's incredibly challenging and time-consuming to pry information out of people.  If people follow the ticket instructions, I can help them.

**Comment by Smudgiee** [comment]
I understand. But as you say its recommending sun kick in 3 seconds because it would overcap chi or break the combo. If that's how the apl is then it must be right. Just feels odd to play like that but I guess thats how it should be saved instead of overcapping on chi which mighht "feel" better but not be suggested/worth.

**Comment by Hekili** [comment]
I just ran a quick sim comparison, overcapping is actually okay, though the Tiger Palm overcap should be pretty rare.  I'll keep an eye on it and potentially make changes.

**Comment by Smudgiee** [comment]
Thank you for doing what we're too silly and misunderstanding to do ^^ sorry.

**Comment by Hekili** [comment]
Will put in a change in an upcoming build.
