### ISSUE TITLE
Crash out to login.   Only error is Hekili per bugsack/bugrabber

### ISSUE THREAD

**Issue by rcumby** [Hekili/hekili#731]
1x Hekili\Events.lua:1759: attempt to perform arithmetic on local 'finish' (a nil value)
[string "@Hekili\Events.lua"]:1759: in function <Hekili\Events.lua:1630>
[string "@Hekili\Events.lua"]:1937: in function `handler'
[string "@Hekili\Events.lua"]:56: in function <Hekili\Events.lua:50>

Locals:
event = "COMBAT_LOG_EVENT_UNFILTERED"
_ = 1608682860.064000
subtype = "SPELL_CAST_START"
_ = false
sourceGUID = "Player-96-002672E7"
sourceName = "Indexes"
_ = 1297
_ = 0
destGUID = nil
destName = nil
destFlags = -2147483648
_ = -2147483648
spellID = 5176
spellName = "Wrath"
school = 8
amount = nil
interrupt = nil
a = nil
b = nil
c = nil
d = nil
offhand = nil
multistrike = nil
time = 639042.147000
amSource = true
amTarget = false
hostile = true
minion = false
ability = <table> {
 gcd = "spell"
 velocity = 20
 handler = <function> defined @Hekili\Classes\DruidBalance.lua:2348
 copy = <table> {
 }
 key = "wrath"
 texture = 535045
 charges = 1
 recharge = 0
 id = 190984
 isProjectile = true
 impact = <function> defined @Hekili\Classes\DruidBalance.lua:2346
 funcs = <table> {
 }
 realUnit = "Creature-0-4227-2222-8161-170157-0000628D3B"
 spendType = "astral_power"
 desc = "Hurl a ball of energy at the target, dealing 1,062 Nature damage."
 name = "Wrath"
 realCast = 639042.147000
 cooldown = 0
 startsCombat = true
}
_ = nil
_ = nil
_ = nil
start = nil
finish = nil
travel = 0.050000
(*temporary) = <function> defined @Hekili\State.lua:4975
(*temporary) = <table> {
 spend = <function> defined @Hekili\State.lua:1344
 putTrinketsOnCD = <function> defined @Hekili\State.lua:4927
 role = <table> {
 }
 IsKnown = <function> defined @Hekili\State.lua:6091
 forecastResources = <function> defined @Hekili\State.lua:1158
 purge = <table> {
 }
 stat = <table> {
 }
 safenum = <function> defined @Hekili\State.lua:501
 floor = <function> defined =[C]:-1
 essence = <table> {
 }
 queue = <table> {
 }
 SetWhitelist = <function> defined @Hekili\State.lua:5809
 holds = <table> {
 }
 prev_off_gcd = <table> {
 }
 active_dot = <table> {
 }
 mainhand_speed = 3.079000
 channelSpell = <function> defined @Hekili\State.lua:1046
 equipped = <table> {
 }
 gain = <function> defined @Hekili\State.lua:1331
 TimeToReady = <function> defined @Hekili\State.lua:6404
 setStance = <function> defined @Hekili\State.lua:964
 history = <table> {
 }
 varPaths = <table> {
 }
 args = <table> {
 }
 AddToHistory = <function> defined @Hekili\Events.lua:1213
 SetupCycle = <function> defined @Hekili\State.lua:650
 print = <function> defined @FrameXML\RestrictedInfrastructure.lua:116
 remove = <function> defined =[C]:-1
 ClashOffset = <function> defined @Hekili\State.lua:6581
 azerite = <table> {
 }
 shift = <function> defined @Hekili\Classes\DruidBalance.lua:587
 offset = 0
 QueuedCastRemains = <function> defined @Hekili\State.lua:5315
 ApplyCastingAuraFromQueue = <function> defined @Hekili\State.lua:5337
 TargetBuffUp = <function> defined @Hekili\State.lua:4916
 pvptalent = <table> {
 }
 rawGain = <function> defined @Hekili\State.lua:1338
 GetItemGem = <function> defined =[C]:-1
 UnitIsFriend = <function> defined =[C]:-1
 combat = 639019.012000
 addStack = <function> defined @Hekili\State.lua:841
 HasRequiredResources = <function> defined @Hekili\State.lua:6395
 TargetDebuffUp = <function> defined @Hekili\State.lua:4921
 UnitCanAttack = <function> defined =[C]:-1
 rawSpend = <function> defined @Hekili\State.lua:1351
 script = <table> {
 }
 IsUsable = <function> defined @Hekili\State.lua:6253
 GetPlayerAuraBySpellID = <function> defined =[C]:-1
 movement = <table> {
 }
 active_enemies = 1
 IsFiltered = <function> defined @Hekili\State.lua:6221
 cooldown = <table> {
 }
 stance = <table> {
 }
 gcd = <table> {
 }
 proc_bloodtalons = <function> defined @Hekili\Classes\DruidFeral.lua:888
 varDB = <table> {
 }
 ResetQueues = <function> defined @Hekili\State.lua:5133
 auras = <table> {
 }
 Ge

**Comment by Hekili** [comment]
Got the rest of the info?

**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
I genuinely don't think I can cause a crash to the login screen, but that error will be prevented in the next release.
