### ISSUE TITLE
WW whirling dragon punch

### ISSUE THREAD

**Issue by deedz1** [Hekili/hekili#738]
Please describe your idea or feature and when it would be useful.
hi,

currently there is an unlimited range consideration for WW's Whirling dragon punch

can you please add a 8 yard check to the simc apl - I do not now what the proper code is

thanks

**Comment by Hekili** [comment]
No, I won't put this in the APL, but I may make a related user option.

**Comment by deedz1** [comment]
you've been nothing but unhelpful

you could have just told me I could add  target.distance<=8  to anywhere
WDP is

The last time I post on your github ever. Zero help to people

**Comment by Hekili** [comment]
Ok?

**Comment by Hekili** [comment]
I guess, since I've been baited here, I'll just note:

1. A user preference for this has been created (similar to Fury Warriors' Whirlwind class option).
2. You didn't ask how to do it yourself; you asked if I would add it to the priority for all users and I answered that question.  I generally don't do this sort of rule-out because ruling out an ability based on position is probably the wrong choice -- the right choice is to get in position so you can use your optimal ability.  You might find yourself in a scenario where you're left with a really bad alternative, since you might not have another Hit Combo/Combo Strikes friendly ability available when you rule out WDP.
3. I generally don't help people write custom priorities, even if asked, because it generally means that I am just writing custom priorities for people.  If folks don't have experience customizing SimulationCraft APLs, they are probably not going to understand the matching syntax/expressions for this addon.

Anyway, have a great day.
