### ISSUE TITLE
Avenging Wrath checks for Paladins in Torghast

### ISSUE THREAD

**Issue by Aelmott** [Hekili/hekili#826]
Since Torghast tend to give you many Anima powers, I've got an irritation from Avenging Wrath.

Many of the Torghast powers will give you free Avenging Wrath at points. Generally when you enter
a new floor. Or with the right combo of other powers the ability to almost extend it indefinitely and 
have the cooldown reset before its gone.  This creates the situation of Hekili recommending the use
of Avenging Wrath when its already up and thats just a waste. I've ran into this with both Ret and Prot.

Any chance you could place a check to see if you already have Avenging Wrath up before it tries to
suggest you use it? This has never been an issue before, but Torghast has created some unusual
combinations of things and the ways abilities interact.

Thanks...
Ael

**Comment by Hekili** [comment]
If this is an issue, then the Avenging Wrath buff in Torghast must already have a different ID than your own Avenging Wrath buff -- otherwise, this is already prevented.

I'd need you to provide a snapshot (see ticket instructions) when you have Avenging Wrath up and the addon is recommending Avenging Wrath, along with the spell ID of the Avenging Wrath buff that you have on yourself.

**Comment by Hekili** [comment]
Please confirm if you'll be adding information to this ticket or if it should be closed.  Thanks.

**Comment by Aelmott** [comment]
Haven't been back into Torghast in the last couple of days so no chance to collect data/snapshot. By all means go ahead and close it, when/if I get more information I'll go forward from there. I'll do my best to see if the AW granted by Torghast has a different ID number since its is an anima power and not necessarily a player action.
