### ISSUE TITLE
Echoin Reprimand + Slice n Dice. [ROGUE]

### ISSUE THREAD

**Issue by endisnear1010** [Hekili/hekili#829]
Hekili sometimes tries to spend the Animacharged combopoint produced by echoing reprimand on Slice n dice. The animacharged combopoint only works for damaging finishers.

**Comment by ghost** [comment]
I can +1 this. Hekili tries to spend the Animacharged combo point on SnD to get a 7 combo point finisher, but it only works on damaging finishers. Not the biggest issue, but would be a great QoL fix regardless :)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/59188217/104444615-b2556000-55a0-11eb-9f93-53de7d1cc839.png)

Adding a screenshot for reference.

**Comment by Hekili** [comment]
Will need a snapshot for this, per ticket instructions.

**Comment by ghost** [comment]
I'll see what I can do about generating a snapshot, since this bug appears at random times, during random encounters which makes it pretty hard to replicate. I'll have to raid and run some dungeons to do further testing.

**Comment by Hekili** [comment]
Nothing happens at random times.  You'd likely be able to replicate this issue on a target dummy.

**Comment by ghost** [comment]
https://pastebin.com/Mms28WDA

**Comment by ghost** [comment]
In this particular situation - it suggests to apply SnD on the 2nd animacharged combo point, but after using sinister strike, it goes back to the default behavior of suggesting SnD on 6 combo points,

**Comment by Hekili** [comment]
I need a snapshot where Slice and Dice is recommended when you have the animacharged # of combo points.  The snapshot provided does not do that.

**Comment by endisnear1010** [comment]
well his first screenshot certainly does

**Comment by whoaisjustin** [comment]
Screenshot != snapshot

**Comment by endisnear1010** [comment]
here's another one tho 
![69833abb348b03dbf6747df3729d7114](https://user-images.githubusercontent.com/77386952/104624199-941c5c80-5693-11eb-950c-501a369776e7.png)

**Comment by SpatenLa** [comment]
a screenshot is missing many many many informations that are NEEDED to find the issue. That means a screenshot is completely worthless. you need to post a SNAPSHOT when the issue happens so it can be looked after.

**Comment by endisnear1010** [comment]
Sorry am new here dont really know the difference between a snapshot and a screenshot. will check it out

**Comment by Hekili** [comment]
It's in the ticket instructions, as noted in my first response.

**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by endisnear1010** [comment]
i hope this is right  https://pastebin.com/CvHExRP8

**Comment by MrSmurfy** [comment]
I was looking into this from a code point of view and after discussing with Hekili we concluded that if the Slice n Dice logic is to be changed then it would actually end up in DPS loss.

Sims ran by Hekili;

HecticAddCleave
![HecticAddCleave](https://user-images.githubusercontent.com/11522121/104708877-8a8c0680-571e-11eb-8177-f53235a0992c.png)

DungeonSlice
![DungeonSlice](https://user-images.githubusercontent.com/11522121/104708990-adb6b600-571e-11eb-8d24-8c2675f5d326.png)

Patchwerk
![Patchwerk](https://user-images.githubusercontent.com/11522121/104709001-b0191000-571e-11eb-9515-571a0a80336d.png)

Although it might feel strange to cast a non damage finisher when animacharged it follows the simulationcraft APL and results in the best DPS possible.

**Comment by endisnear1010** [comment]
I'm not sure that I understand that. Because the animacharged point doesn't
do anything for snd. After using snd on a anima charged Combopoint you
still have that animacharged Combopoint and snd for 12 sec or whatever this
is on 2 cp. So are you saying that it's right to click snd when having 2cp.
Or are you saying you can't change it for some reason?

MrSmurfy <notifications@github.com> schrieb am Fr., 15. Jan. 2021, 10:48:

**Comment by MrSmurfy** [comment]
It should only be changed if it actually increases our DPS, which it doesn't as the sims show.

**Comment by ghost** [comment]
That was honestly unexpected. :P

**Comment by aquos757** [comment]
listen im not trying to be rude or anything, but either i totally dont understand what you simmed there or you guys dont understand ( its prolly me i know) but hekili would never recommend using snd on 2cp, it only does that when its animacharged which doesnt change anything so please help me understand

**Comment by MrSmurfy** [comment]
@aquos757 I noticed your last post you deleted and can understand that it may be confusing somewhat.

We simmed using the simulationcraft APL, (the one the addon uses), and a version with Slice n Dice not being used whilst animacharged. 

The sim shows that it doesn't matter that you don't get the 7 CP duration, you'll still end up with better DPS in all cases. Hope that explains it better.

**Comment by endisnear1010** [comment]
alright, thanks for clearing this up then :)
