### ISSUE TITLE
Using shaman Flame Shock too late?

### ISSUE THREAD

**Issue by LucianDK** [Hekili/hekili#846]
One thing Ive noticed is that the addon doesnt seem to prioritize flame shock enough. A rare few times getting one called at super low duration on one, or even letting it lapse before it shows up.

**Comment by Hekili** [comment]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by istari0n** [comment]
I've changed this part: "( ! ticking | dot.flame_shock.remains <= gcd |"
and made it like this: "( remains <= gcd |"
and it seems to start working fine.
correct me if I did smth wrong...

**Comment by Hekili** [comment]
@LucianDK I have to have all the ticket information to do a comparison.

@istari0n It's probably confirmation bias, your edit doesn't really change anything that would impact the outcome.  (If Flame Shock isn't ticking, its remaining time is less than a GCD, so the existing logic is a bit redundant.)

This is a scenario where it's probably best to also compare sims.  I don't even know which specialization we're talking about right now.

**Comment by LucianDK** [comment]
It was elemental specialization.  And the reason for why im asking is that the refresh is comming too close to expiry then you risk it falling off, when you can take advantage of the pandemic refresh period to ensure a 'safety buffer' if you dont react fast enough.  Especially since Flame Shock uptime is absolutely critical and the top in all priority lists.

Flame Shock benefits from Pandemic, meaning that you can refresh it any time that it has less than 30% of its original maximum duration remaining and the remaining duration will be added to the new debuff. Therefore you are be able to refresh Flame Shocks without wasting any duration when it has 5 seconds or less remaining, and it will be extended by 18 seconds. For example, if your Flame Shock has 5 seconds left and you refresh it your new Flame Shock would last 23 seconds.

Using Fire Elemental makes it even more complex as it doubles the duration of newly cast flame shocks while its up, meaning the pandemic refresh period moves. Which can be beneficial if the fire elemental is about to expire and wanting one more long dot.

Ive had to make a tracker for the flame shock dot in tellmewhen as hekili asks for refresh far too late.

**Comment by Hekili** [comment]
I know the mechanics.  You still have to submit the required ticket information.
