### ISSUE TITLE
Monk Windwalker, Spinning Crane Kick 4 secs wait before using suggested

### ISSUE THREAD

**Issue by Zriel88** [Hekili/hekili#860]
**BEFORE SUBMITTING AN ISSUE:**

 Using stable, let me know if you want me to use alpha release.

**Describe the Bug/Issue**
Using the AOE priorities of WindWalker monk, sometimes the addon asks to wait before using the SPK, for about 4 seconds.

**To Reproduce**
- Fight 3 or more dummys. Use RSK + FOF + WDP, continue the rotation. At some point addon will start to suggest to wait a bit before casting next SPK

**Expected behavior**
As far as I know, I would understand to wait for using chi generators beause of energy exhaustion, but I don't think we should wait for using chi expenders as they deal most of our damage.

**Screenshots**
Hekili is shown on the center of the screen, You can see the 3.9 secs of wait suggestion.
![image](https://user-images.githubusercontent.com/8926895/105349082-7b5afc00-5be9-11eb-8b2a-ab73192f72a8.png)

1. Character data
https://pastebin.com/1HgDnzxb

2. Snapshot
https://pastebin.com/iC2YZTn0

**Comment by Hekili** [comment]
Thanks for the description and snapshot.  Here are the relevant lines for this Spinning Crane Kick recommendation:

Here are the relevant conditions for Spinning Crane Kick in aoe - 7, which is the SCK entry that was recommended.

![image](https://user-images.githubusercontent.com/9438134/105363396-f8767900-5bc9-11eb-9781-aa2a333c4b6b.png)

The first requirement is that SCK won't break Combo Strikes / Hit Combo.  That is true.

The next requirement is split; Bonedust Brew would need to be on CD for 2+ seconds for the next bundle of conditions to be met.  It's not, so everything that's connected to it with an & (and) can be ignored.  After the Bonedust-related conditions, the next condition is that Energy will cap in 3 seconds or fewer.  That condition is not met immediately, so we don't recommend SCK immediately.

The addon looks again at a couple of slices of time.  In 1.61 seconds:

![image](https://user-images.githubusercontent.com/9438134/105363572-307dbc00-5bca-11eb-8f08-583733094047.png)

The other conditions generally hold true.  Energy will cap in 3 seconds, so overall, conditions are met and SCK is recommended at the 1.61 seconds mark.

(Noting here:  The snapshot and your screenshot are not taken at the same moment.  But you can see that your energy is pretty low in the screenshot and your time to energy cap is also probably pretty high.)

So, as written -- and consistent with the SimulationCraft priority -- the addon's logic is working as expected.  Not a bug.

*However*, this does seem like a pretty odd reason to delay, and a lot of time to potentially delay.  This suggests some additional simming is in order to determine if that timeframe is reasonable.

I can do some of that simming, with your character in mind, if you will go to Raidbots and sim yourself on 3+ Patchwerk targets.  Send me the link, and I'll tinker with this entry to see if it should be less restrictive (i.e., if the Energy requirement should be relaxed or even inverted).

**Comment by Zriel88** [comment]
You are correct, seems the SIMC APL does the same. Which I don't get XD
https://www.raidbots.com/simbot/report/tCG72r6wErmxGej417qFh9

![image](https://user-images.githubusercontent.com/8926895/105366284-730dbb80-5bff-11eb-9442-ed981c2b8aed.png)

If you want, I can ask for this on the Peak of Serenity discord.

**Comment by Hekili** [comment]
They may or may not make revisions themselves.  But yeah, I did my own simming:

![image](https://user-images.githubusercontent.com/9438134/105366496-683a3300-5bcd-11eb-9475-9978089e2028.png)

Here's an example where I've made a couple of tweaks, that quickly shows a DPS increase on a few targets:

https://www.raidbots.com/simbot/report/gg6ZPTgo8AsPMmgm6VkdMv

**Comment by Hekili** [comment]
I'm putting my own changes to address this in the next release, but I'll watch for simc changes as well.

**Comment by Zriel88** [comment]
Scurch is going to take a look into this
yeah I was going to say to you that I wouldn't care if you were going to wait for SIMC APL to be updated, as I understand is less work just copying their APLs wihtout needing to track your own changes.
Whatever you prefer is good for me.

**Comment by Hekili** [comment]
You're welcome to share any of the tweaks that I tried with him.

3 Target Kyrian, rev 2:
https://www.raidbots.com/simbot/report/qbjNkK447cR9iCeyThUWfG

4 Target Night Fae, rev 2:
https://www.raidbots.com/simbot/report/m5ffChqdFDr36K3EsKNigX

2 Target Night Fae:
https://www.raidbots.com/simbot/report/kPZFpEMXQuKLo3uo6aRdL3
(This one shows a DPS loss with the Calculated Strikes logic ported directly from guide to SimC.  It probably needs energy cap related logic.)

4 Target Night Fae:
https://www.raidbots.com/simbot/report/gg6ZPTgo8AsPMmgm6VkdMv

**Comment by Hekili** [comment]
(Another quick test for the 2 target scenario:  Either checking for combo_strike or checking for Energy cap ends up being a minor DPS gain.  Checking for both is still a DPS loss.)

https://www.raidbots.com/simbot/report/q6KUHRWeNB3Qcs33UWDNNg

https://www.raidbots.com/simbot/report/q6KUHRWeNB3Qcs33UWDNNg

https://www.raidbots.com/simbot/report/2SHi8JSAAiN2oVXWxkVqPt
