### ISSUE TITLE
Beta Retribution Priority Not Suggesting Spenders (at max Holy Power) when Execution Sentence and Final Reckoning Desynchronize

### ISSUE THREAD

**Issue by lloydBl** [Hekili/hekili#868]
**Describe the Bug/Issue**
Sorry for the barrage of issue reports from  me, I really do appreciate your add on and your continued work on it. 

This issue has to do with the new retribution priority list in the beta build.  When using Execution Sentence and Final Reckoning talents, if Execution Sentence put on cool-down (used) before Final Reckoning is used*, the default priority list recommends only recommends builder abilities even when you are at maximum Holy Power.  It gets stuck only recommending Crusader Strike, Consecration, and Judgement (and HoW if usable) until either Final Reckoning is used or Execution Sentence has under ~10 seconds left on its cool down.  This occurs in both AoE and single target.

This issue occurs with and without being talented into Seraphim, however if talented in Seraphim, spender recommendations return when that ability is used.  Seraphim however is not recommended when the action list gets stuck on recommending builders only

*The current recommendation priority does not to my knowledge ever recommend Execution Sentence before Final Reckoning.  This was discovered by misclicking Execution Sentence first.

**To Reproduce**
-Spec into Execution Sentence and Final Reckoning
-Cast Execution sentence on the Target with 3 Holy Power
-Priority recommendation should exhibit the above behavior 

**Expected behavior**
Either Final Reckoning should be recommended or a Holy Power spender. Builders should not be recommended when Holy Power is capped.

**PUT ISSUE REPORT LINK HERE:**
https://pastebin.com/TkGWydUU
 
**PUT SNAPSHOT LINK HERE:**
Occurring in AoE (5 targets): https://pastebin.com/ZaEwysFD
Occurring in Single Target: https://pastebin.com/UP1N9ux3

**PUT ERROR MESSAGE(S) HERE:**
N/A

**Comment by Hekili** [comment]
Your analysis here is pretty solid, except the "stuck on builders only" part.  It's not that it's stuck on builders, it's that finishers end up ruled out because of how ExS, FR (and Seraphim) all relate.

In your ST snapshot, Seraphim wasn't recommended because it's timed to line up with Execution Sentence and you'd hit ExS first.  TV wasn't recommended because FR wasn't on CD.  FR wasn't recommended because Seraphim wasn't up.

A quick sim reflects no damage loss if I relax the Seraphim conditions to allow Seraphim when ExS is on CD for > 45 seconds.  I'll give that a shot.

**Comment by Hekili** [comment]
These changes are in the latest release; please let me know if you still have the issue with the 1.0.36 release.
