### ISSUE TITLE
Balance druid double on-use trinket problem

### ISSUE THREAD

**Issue by Olanid57** [Hekili/hekili#878]
Hello,

I'm a boomkin playing with double-use trinket (empyrean ordonance).
The main reason is to use it 20second before poppin CDs to have intelligence buff sur CA/Convoke/other trinket.
Unfortunately for me it recommends to use it just before CDs and the other trinket 20 seconds later.

**Screenshots**

![Capture](https://user-images.githubusercontent.com/59389933/106180754-06656480-619d-11eb-8c26-fa2c25f17033.PNG)

Thanks 

Describe the Bug/Issue

The main reason is to use it 20second before poppin CDs to have intelligence buff sur CA/Convoke/other trinket.
Unfortunately for me it recommends to use it just before CDs and the other trinket 20 seconds later.

To Reproduce : I tried the rotation on target dummies
A clear and concise description of what you expected to happen : I expected Empyrean Ordonance to be used 20s before CDs and the other trinket to be used with CDs

PUT ISSUE REPORT LINK HERE : https://pastebin.com/KFsYVExe

PUT SNAPSHOT LINK HERE: https://pastebin.com/4Dbx1JFu

PUT ERROR MESSAGE(S) HERE : No errors

**Comment by Hekili** [comment]
Please follow the ticket instructions when submitting a ticket.

**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Olanid57** [comment]
sorry, i thought it was enough. I edited. 5sorry for my english)

**Comment by Hekili** [comment]
There's no problem with your English, just needed the additional required information.

You're correct about wanting to use Empyrean well in advance so you have the buffs when you go into CDs.  The way it's written into the Balance profile is a bit complicated and I haven't cleaned it up yet.  It's on my radar, though.

**Comment by Olanid57** [comment]
Ok so if i understood right, this is not a "bug". It's a work-in-progress ?

Thanks for your job.

**Comment by Hekili** [comment]
I'd be interested in an update, in terms of whether this is resolved for you or not after 1.0.40.  (It might not be.)

**Comment by Olanid57** [comment]
No, it's not.
Do you want a full report with all pastebin links again ?

**Comment by Hekili** [comment]
Yes, current snapshots would help.  Thanks for responding so quickly.

**Comment by Olanid57** [comment]
https://pastebin.com/Zy42RW3r

You're welcome

**Comment by Smudgiee** [comment]
This may not be helpful but for me it's working the way it should. Have you messed with any of the settings inside of Hekili Rotation?

**Comment by Olanid57** [comment]
I dont think so except "skins" stuff.

**Comment by Hekili** [comment]
Please report/reopen if this is still an issue in 9.0.5.

**Comment by Olanid57** [comment]
Still not working in 9.0.5, i'll make a snap if required

**Comment by Hekili** [comment]
Snapshots are always good.

**Comment by Olanid57** [comment]
https://pastebin.com/JcL24zDj
