### ISSUE TITLE
Unholy DK - Apocalypse and Army of the Death

### ISSUE THREAD

**Issue by Nazeth** [Hekili/hekili#911]
Commonly Apocalypse and AotD is used everytime if its possibe, but often it's a waste of preparations and cooldown against trash that will die too fast to unleash potential. Instead of that we could use that Festering wounds to cast few scource strikes and kill them faster.

Suggestion:

- Optimize Apocalypse to avoid of use it, if mobs around will die soon. The same with Raise Abomination.
- AotD is commonly wasted cooldown on trash or Elites on raids and dungs. What about optimize it around mini-boss Elites and Bosses?

**Comment by Hekili** [comment]
This is what the "toggles" feature is for.  Use it to turn off your damage CD abilities when you don't want to use them.

**Comment by Nazeth** [comment]
Apocalyple isn't a cooldown. Its a default Ability. Anyway SimC scripts aren't optimized and they will be build and reserve Festering Wounds for it even if will move it to "cooldown" group.

**Comment by Nazeth** [comment]
Also i want for example use Raise Abomination normally, when AotD only on bosses, but i can't split that. You merged that two abilities together.

**Comment by whoaisjustin** [comment]
> Apocalyple isn't a cooldown. Its a default Ability. Anyway SimC scripts aren't optimized and they will be build and reserve Festering Wounds for it even if will move it to "cooldown" group.

Add it to the cooldowns toggle if you want it to be toggled on/off with your other cooldowns.

**Comment by Hekili** [comment]
If you want different behavior, but don't have a sim-tested priority to prove an actual benefit, you're on your own in terms of building your own custom priority.

By default Apocalypse is on the Cooldowns toggle, unless you have Army of the Damned.  (Holding Apocalypse w/ AOTD talented is likely to waste a good amount of CDR.)  You can still manually put it on the Cooldowns toggle, as @whoaisjustin noted.

Elaborate more on AOTD vs. Raise Abomination.  They do swap in the addon (because they swap in-game, as well).  You'd still be able to differentiate the conditions for the two.  When your PvP talents are active and you took Raise Abomination, `pvptalent.raise_abomination.enabled` will be `true` (otherwise, `false`).

**Comment by Nazeth** [comment]
But i want to use it. i just dont want to build Festering wounds and use Apocalypse on thrash that will die before i will cast Apocalypse. Its a waste of runes.

Imagine to cast 2 Festering Strikes on each trash, because scripts require it to build wounds for Apocaypse, but next 10 targets will die before you will cast Apocalypse. In that reason i wasted multiple festering wounds and runes.

I want something rather to avoid build festering wounds for Apocalypse, if my target will die too fast before i will be able cast Apocalypse and my minions dealt any damage to that target and next, nearby targets in range.

**Comment by Hekili** [comment]
> If you want different behavior, but don't have a sim-tested priority to prove an actual benefit, you're on your own in terms of building your own custom priority.

**Comment by Nazeth** [comment]
SimC rotation is build around perfect conditions, but real fight never is perferct for that scripts. Even by logic wasting 4 runes to cast 2 Festering Strikes for mob that will die before i will cast Apocalypse is a waste of 4 runes. Intead of that i could cast Festering Strike and 2-3 Scourge strikes to kill it faster and save my Apocalypse cooldown and runes.

**Comment by Hekili** [comment]
You can absolutely make time-to-die and add-wave-duration based decisions in a SimC priority.  That is what you'll need to do, if you want to demonstrate this value and prove out your logic.

It's not that I'm disagreeing with you, but you have to do the work to *prove* your thinking, if you want something changed in the base addon.  And I don't generally write custom priorities for people otherwise.

**Comment by Nazeth** [comment]
Im mostly doing later my own rotation, because your addon is a good base for programist. Sadly SimC rotation isn't perfect. It isn't even good, because it does not take into account many circumstances, such as targets dying too quickly. SimC focuses mainly on fighting bosses that can be hit much longer.

Sometimes im scared, when i see hundreads of scripts in my rotation and it looks more like a bot than rotation helper xD

**Comment by Nazeth** [comment]
If I were to publish it, a discussion about closing this type of addons would surely arise.

**Comment by Hekili** [comment]
That's cool, if you find yourself crossing the line into automation, go break the rules elsewhere.  Take care.
