### ISSUE TITLE
Brewmaster not showing up as off-spec

### ISSUE THREAD

**Issue by mrgianlu** [Hekili/hekili#916]
Hi.

I'm mostly used to use Hekili as Windwalker.

I recently started trying out the tank spec, and I'd like to have Hekili helping me out with the rotation.

However for some reasons, even though hekili works like a charm on WW spec, once I switch my spec to BM the addon:

1) recognise the spec (quick action menu shows the Brewmaster option to maximize the celestial brew shield)

2) but it just doesn't trigger any suggestion

3) has the boxes are correctly placed and without transparency, in fact once in the option menu I can see the skeleton of them sadly empty.

4) is of course enabled

5) the problem persist after restarting the game with the correct spec (without the spec switch in the same session)

Any suggestion on how to proceed to have it shown? anybody with a similar issue?

Thanks.

EDIT:
Issue reporting text:
https://pastebin.com/rFr449tB

**Comment by Hekili** [comment]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by mrgianlu** [comment]
updated the original post with pastebin link.

honestly I don't know what else could I add to better describe the issue.

**Comment by Hekili** [comment]
All of the required info would be a fantastic start.  I'm not able to replicate your issue with a fresh profile.  Both Brewmaster and Windwalker are listed.

**Comment by Hekili** [comment]
Looking at a fresh profile, in Brewmaster spec, open /hekili and check the following:

![image](https://user-images.githubusercontent.com/9438134/108232921-4327da00-7111-11eb-9751-42c6a7d69c51.png)

1. In Brewmaster, Core, Enabled is checked.
2. Under Priorities (left), Brewmaster is listed.
3. In Brewmaster, Core, for Priority, Brewmaster is selected.

If those are set and it's not showing anything, press Pause (ALT-SHIFT-P) by default, then go to Snapshots and get Display = Primary, # = 1 and paste to Pastebin and provide a link.

Alternately, check the Profiles section and ensure that either Enable spec profiles is unchecked or that you have the correct profile selected for Brewmaster.

**Comment by mrgianlu** [comment]
trying out your steps

in the meanwhile this gif is what is happening, the boxes are there but not filled with info:
https://giphy.com/gifs/nLSe46xK9FkaNmZGqB/fullscreen

coming back in few minutes.




OK thanks, you can close this, CORE was unchecked.

Thanks for the support dude and sorry for taking your time with this noob question. I'm subscribing to your patreon right now :)

**Comment by Hekili** [comment]
No worries.  Not sure how it would've come unchecked, but glad it's covered now.  Thanks for the support.  Take care!
