### ISSUE TITLE
Fire Mage Auto Snapshot

### ISSUE THREAD

**Issue by Smudgiee** [Hekili/hekili#920]
The latest version of Hekili is being used.

I keep getting a auto snapshot from Hekili. No idea why it's doing it but it's when I do /Hekili to open the interface it snaps for some reason no idea why. But it says AoE. Apart from that I have no idea what else to give for information as its appears during /hekili interface. 

https://pastebin.com/hiDRSuhY - Snapshot
https://pastebin.com/8FL7ng2j - Issue report

**Comment by Smudgiee** [comment]
I guess I can close, no idea but it's stopped now. Maybe I accidently changed something without noticing to cause the snapshot.

**Comment by Hekili** [comment]
I'll look at the snaps.  There are a few edge-case scenarios where the addon can't come up with a recommendation, so I'm not surprised this came up with Fire Mage (the most complicated APL of them all).  I can cause an occasional autosnapshot with Shadow Priest hot-swapping between AOE and ST, but I haven't prioritized that issue because nobody else has reported it.  :)  I do appreciate that you brought the snapshot when you saw that it was creating snapshots.
