### ISSUE TITLE
Balance druid AOE/M+ Suggestion BoAT Lego Starfall vs Starsurge 

### ISSUE THREAD

**Issue by mati3464** [Hekili/hekili#933]
Hello

On dreamgrove discord we was talking a bit about aoe prio for balance druid with Balance of All Things lego. 
At this moment using hekili profile, hekili on 2+ targets with this lego, allways prio 1-2 Starsurge  in first 1-2 sec after entering eclipse and if you miss it because you to slow, it will change for starfall. This profile have one problem, because if you use those 1-2 starsurge's you will always lose starfall uptime on 2+ targets, and having 100% uptime on SF on 2+ targets allways is prio ( if time to die is more than SF duration ) in m+ scenario this starsurge dumping is loss around 10-15% dps in overall. 

Sec thing for enhancement is that, if you are in 3+ scenario and you are in lunar eclipse you never use moonfire's on 3+ targets, time when you refreshing moonfire dot is always in 3+ scenario solar eclipse. At 1-2 scenario, you want uptime moonfire/sunfire dots on any eclipse. 

On ST hekili recommendation is almost 95% accurate , AP predictions are great and its working fine with Balance of all thing lego, but on AOE and m+ scenario, this tweak that always prio uptime starfall 100% on 2+ targets than use starsurge after entering eclipse will be nice dmg boost for those who using hekilii as rotation helper on m+ 

Sunfire dots refresh working great, because its prio for refreshing on any eclipse and any number of targets scenario.

**Comment by Hekili** [comment]
If you want changes to recommendations, you need to post sims of the different behavior.

**Comment by mati3464** [comment]
> If you want changes to recommendations, you need to post sims of the different behavior.

its hard to get accurate sims for m+ scenario, recommendations that i posted above are after using and watching hekili over month on ST and AoE Scenarios and discussion with others bala druid's.

As bala druid with over 2k Rio i will add this tweek as great enhancement for m+ scenarios and recommendations.

**Comment by Hekili** [comment]
You'd still need to provide the edits you've described and show how they sim.

**Comment by SpencerMalone** [comment]
I am also seeing this, and I think I tracked down the APL cause. When I encountered it on a training dummy, I had no CDs up and paused to see what was up. Here was the state of the pause:

![idkwhy](https://user-images.githubusercontent.com/8786752/110251692-86b67c80-7f36-11eb-89be-a84332c9b86b.png)

So, the issue is, look at the simc APL: https://github.com/simulationcraft/simc/blob/shadowlands/engine/class_modules/sc_druid.cpp#L8464
` aoe->add_action( "starsurge,if=variable.dream_will_fall_off&variable.starfall_wont_fall_off&!variable.ignore_starsurge|(buff.balance_of_all_things_nature.stack>3|buff.balance_of_all_things_arcane.stack>3)&spell_targets.starfall<4&variable.starfall_wont_fall_off","Use Starsurge with Dreambinder to keep up the buff without losing Starfall uptime and use Starsurge on 4+ BoAT stacks until 4 targets" );`

That last `&variable.starfall_wont_fall_off` is absent for hekili's APL, and without that we will use starsurge before we have starfall up incorrectly

**Comment by SpencerMalone** [comment]
Ah, was added in https://github.com/simulationcraft/simc/commit/d7221031202ba2571c3cb177361a7c33093bbc0f

**Comment by Hekili** [comment]
Good catch and great research.  The revised APLs are in a big pile of pending commits.

![image](https://user-images.githubusercontent.com/9438134/110259198-7c1ad800-7f74-11eb-94a7-07fb54327fa3.png)

I would've accidentally resolved this with the next release, but it's good to have confirmation.  I hope to get these changes out tonight or tomorrow.  They require more checking than usual because of some recent syntax additions in SimC that I spotted and have to make sure are modeled correctly.

**Comment by Hekili** [comment]
These fixes are in the new beta.
