### ISSUE TITLE
Display freezing due to glow show/hide error.

### ISSUE THREAD

**Issue by Twissle** [Hekili/hekili#94]
On the latest 8.1.5-04 release, elemental seems to be misbehaving. The previous version that worked correctly for me was beta2. I initially thought it was just a problem with recommending Flame Shock when already applied and skill on cooldown, but I also saw issues with not recommending Lava Burst at all, and even once recommending recasting Stormkeeper just after it had already been cast.

Relevent talents chosen are Echo, Master of the Elements, Icefury, Stormkeeper.

This screenshot will show one of the issues I had with recommending an on-CD and already applied FS:
![ele_broken](https://user-images.githubusercontent.com/49195503/55401497-40d62a00-5551-11e9-90b9-8012eefe53ac.png)

Here is a link to a snapshot with a problem (not sure which one I captured here.. there were many issues):
https://textuploader.com/15yl0

**Comment by Hekili** [comment]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Twissle** [comment]
Here is another snapshot. The addon was recommending an already-applied and on cooldown Flame Shock (like in the screenshot above) whereas it probably should have recommended spending a lava surge proc. I have had issues with the addon at times recommending Totem Mastery when they are already down, and both Stormkeeper and Icefury when they have already been cast.

https://textuploader.com/15ylj

**Comment by Hekili** [comment]
BugSack?  BugGrabber?

**Comment by Twissle** [comment]
Installed buggrabber/bugsack and found this. I think it will probably help you:

![hekili_bugsack](https://user-images.githubusercontent.com/49195503/55402777-93651580-5554-11e9-9f3f-b61dd0444dd1.png)

That '466x' number was rising rapidly. Addon was stuck recommending Frost Shock this time after an Icefury and after all charges had been used.

**Comment by Twissle** [comment]
One final thing I've just noticed in the screenshot I posted at the start of the thread, are that the icons don't correspond correctly with my keybindings. The first Flame Shock is correctly labelled as 1, but the second flame shock labelled '3' is Lightning Bolt for me, the = is Icefury and the 2 would be Lava Burst.

**Comment by Hekili** [comment]
Please try the latest alpha and let me know if this is resolved.  https://github.com/Hekili/hekili/releases/tag/v8.1.5-05-alpha1

**Comment by Twissle** [comment]
05 alpha1 has fixed the rotational problems, but I'm still getting occasional errors that look the same as before. Far far less of them though.
![bugsack_report2](https://user-images.githubusercontent.com/49195503/55407068-a29c9100-555d-11e9-8be2-2c04f3c6ca4e.png)

**Comment by Hekili** [comment]
alpha2 is going up which may address the remaining errors.

**Comment by Twissle** [comment]
I'll try it, but now that I've actually set some glow options for my Primary display (previously the option was blank), I'm no longer getting LUA errors on alpha1.

**Comment by Twissle** [comment]
No problems on alpha2 also now. Thanks for your assistance and hard work!

**Comment by Hekili** [comment]
Fixed and posted as 8.1.5-05.
