### ISSUE TITLE
Variable Intensity Gigavolt Oscillating Reactor How to make it use on 6 stacks?

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#96]
Hello. I noticed such a thing as the Variable Intensity Gigavolt Oscillating Reactor, it is suggested to use the addon when it wants, but can it be done so that it only suggests using it when there are 6 stacks, and only in this case? or please tell me where I can personally indicate this or correct it for myself so as not to disturb you further on such issues. Just addon is not taking into account these nuances in trinkets, and there is an incident, in rotation.

**Comment by beanlord7** [comment]
Hm, I don't really use cooldowns frame, but I have the trinket, so I dug around a bit inside the .lua files and found this comment:
>all:RegisterAura( "vigor_engaged", {
>    id = 287916,
>    duration = 3600,
>    max_stack = 6
>    -- May need to emulate the stacking portion.    

so I tried it out and turns out you don't need to emulate the stacking, as the aura stack count works perfectly fine by itself. ^^

now, idk which class and spec you play, but for my windwalker monk this is what I did to make it work:
- toggled cooldown display on. (obviously)
- went to edit windwalker priority list.
- in default action list:
  - edited the entry "[call action list] - cd" (this is the trigger for the cooldown usage rotation, might be called differently for other specs)
  - added condition "buff.vigor_engaged.stack = 6"
  - added the same condition to the entries "[use items]" and "[potion]" (since we only want to be using our stuff at 6 stacks.
- after that, in "cd" action list:
  - added a new entry (position 1) 
  - set action as the trinket

I hope you can make it work, and if not, I'll try to explain better. :D also, do not forget to export a backup string for your priority, as it will reset to the old one whenever the addon gets updated.

EDIT: so I changed the conditions from just 
>"buff.vigor_engaged.stack = 6" 
to
>"(buff.vigor_engaged.stack = 6 & equipped.variable_intensity_gigavolt_oscillating_reactor = true) | equipped.variable_intensity_gigavolt_oscillating_reactor = false
this way the priority list stays universal and doesn't interfere with people who do not use the trinket.

I will try to suggest this change in SimC github page, maybe they'll implement it.

**Comment by Hekili** [comment]
The comment on emulating the stacking portion has more to do with forecasting ahead of time whether we're at max stacks or not.

You shouldn't need:

```(buff.vigor_engaged.stack = 6 & equipped.variable_intensity_gigavolt_oscillating_reactor = true) | equipped.variable_intensity_gigavolt_oscillating_reactor = false```

...the check to see if it is equipped is built in.

**Comment by Hekili** [comment]
The addon will only recommend the trinket at 6 stacks w/o adding any additional conditions.
